### ISSUE TITLE
Gun disappears when character is caught in an explosion

### ISSUE THREAD

**Issue by Yumorii** [cmss13-devs/cmss13#1022]
## Description

Has happened twice to me, once with a mag harness and the other without. I was caught in an explosion as a marine wielding a shotgun both times (first occasion without any attachments, and the other with a mag harness and a mini flamer) after which my gun just disappeared after I woke up from being knocked unconscious. 

## Difference between expected and actual behavior

Gun should still be present especially since I am sure no one took my weapon.

## Steps to reproduce

Note that this is how it happened to me -
1. Be marine (medic, not sure if that affects anything)
2. Be wielding a shotgun (both hands) (first time I'm not sure if I was wielding it or if it was just in suit storage)
3. Get caught in explosion (was knocked out by a grenade both times)
4. Gun disappears completely (first occasion nobody took my shotgun and I was sure of it, second time I had a mag harness so there was no way anyone took it)

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
intended
