### ISSUE TITLE
Unable to set different liquid transfer amounts

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#1027]
## Description

As per title.

## Difference between expected and actual behavior

I should be able to set the transfer amount for whatever liquid container.

Unfortunately it doesn't work.

## Steps to reproduce

Get a liquid container that allows for the setting of liquid transfer amounts
Try to set it to a different amount like 60 units.
It defaults to 10 units.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
could not reproduce

**Comment by Sargeantmuffinman** [comment]
I'll try to reproduce this bug.
