### ISSUE TITLE
Screen is black

### ISSUE THREAD

**Issue by aceroyuno** [cmss13-devs/cmss13#1029]
## Description
The whole viewport screen is black

## Difference between expected and actual behavior
I should be able to see anything from the game's display, I can see ui overlay still. Further testing, I can see properly through security camera's.

## Steps to reproduce
I literally could not tell you, all I did was download the cache and none of the elements loaded properly, when unchecking hardware display I got to see some assets, but others were still black squares and the ui disapears.

## Issue bingo (not required to be all checked)

- [ x] Issue could be reproduced at least once
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
Do not update to BYOND 514.1586 as it contains certain visual gamebreaking issues

Link to 514.1585 if you need it back: https://secure.byond.com/download/build/514/514.1585_byond.exe

Or if you need to find a specific version you can use and go from here:
 https://secure.byond.com/download/build/

EDIT: IN GENERAL IT'S BETTER TO STAY ON A STABLE VERSION OF BYOND UNTIL IT:
A) STOPS WORKING.
B) THE SERVER STOPS SUPPORTING THAT BYOND VERSION.

**Comment by Segrain** [comment]
Should be fixed by now.
