### ISSUE TITLE
BTR-120

### ISSUE THREAD

**Issue by cnaper-dodo** [cmss13-devs/cmss13#1048]
Description
Adding a new type of equipment.First, VC USCM, and then as the lor experts decide.

A more detailed description.
*No one knows exactly where this miracle of engineering came from.Where the emergency storage warehouses were opened, where this museum exhibit was removed.But now you see him in front of you.*

BTR-120, one of the best infantry support vehicles.Equipped with an autocannon on the head, 2 m56 and a good battering ram armor, she saved the infantry more than once.
But besides the pros, it also has cons.1-Due to its extremely low mass and high suspension, it is not capable of simply hitting damage.To do this, he must demolish the enemy with a battering ram.It's also big enough to be the number 1 target.
But from the pros:Good auxiliary weapons, good cross-country ability in difficult terrain (including swamps and sands).Well, it has a lot of seats for infantry.
*No one knows exactly where this miracle of engineering came from.Where the emergency storage warehouses were opened, where this museum exhibit was removed.But now you see him in front of you.*

https://drive.google.com/file/d/1nvHVUr-c1yIEleEads26NCs1bXDX5-EJ/view?usp=sharing

**Comment by NuggetsOnToast** [comment]
This is a joke right?

The last thing CM needs is more vehicles when they to this day have not found a suitable place in the current gameplay loop for the existing vehicles we have already.

Also why would the UCSM use this over their own model of APC transport.

**Comment by morrowwolf** [comment]
This is the correct place to handle design docs: https://github.com/cmss13-devs/cmss13-design-docs
