### ISSUE TITLE
Tape Recorder dont seem to record if started and place on a table.

### ISSUE THREAD

**Issue by Chocollateral** [cmss13-devs/cmss13#1050]
## Description
Tape Recorder when started and place on a surface like a table dont seem to record anything but silence of said time. Print out of recording also only show start of recording and ending. Playback only show this- https://gyazo.com/56178dde580471ce32bb44937f27f369

## Difference between expected and actual behavior
after being turned on and place on surface, should record what is actually said in both playback and a print out transcript.

## Steps to reproduce
Found this issue happened on the ship in the brig interrogation room, the room top left of bring used for interviews. I was a SEA was asked to inspect a few MPs after a few misshaps in the round, had the time so i did it. called in one MP shut the shutters started the recorder and put it on the table. I as asked my questions and such and the whole thing went on for  422 seconds, just over 7 minutes. I only found this issue after making copies of the transcript one to give to the CO and one for brig records. It was then found out it just recorded 7 minutes worth of silence.

## Issue bingo (not required to be all checked)
-[X]Issue could be reproduced at least once
-[X]Issue happened in a recent (less than 7 days ago) round
-[X]Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by SexmasterWasTaken** [comment]
You need to add an x in the square brackets as well as removing the space. Currently not sure which parts of issue bingo are meant to be checked.

**Comment by Chocollateral** [comment]
> You need to add an x in the square brackets as well as removing the space. Currently not sure which parts of issue bingo are meant to be checked.
last I checked its still a recurring issue, all parts need a check that are involved.

**Comment by MidwayAtom** [comment]
Resolved with a recent Merge.
