### ISSUE TITLE
Horizontal Bat

### ISSUE THREAD

**Issue by TropicalFlak** [cmss13-devs/cmss13#1051]
## Description
Horizontal Bat

## Steps to reproduce
1. Find a bat (living)
2. Nest it
3. Free it

![Horizontal bat](https://user-images.githubusercontent.com/108848001/190193553-6ff70ae6-9aea-415b-9935-b41aa575b484.png)

## Issue bingo (not required to be all checked)
- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@ItsVyzo you can no longer nest non-host creatures.
![image](https://user-images.githubusercontent.com/117036822/236616250-a6f0aa8c-7d02-4f6e-973e-43042045eb35.png)
you can close this issue thanks

**Comment by ItsVyzo** [comment]
Thank you @Huffie56
