### ISSUE TITLE
Hi-Cap Blowtorch fillable with nonwelding fuel liquids

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#1052]
Didn't test any of the other torches.

## Description
1. 0/80 welding fuel
2. saw the unga juice reagent tank: I said huh I wonder, hit the torch on it, refill sound. 0/80 fuel. No indication of medicine leaving the the tank, no indication of anything in the hi cap torch.
3. Saw a nearby Incinerator 3 tank fuel back pack, said hmmm, whacked it with the torch, refill sound. 0/80 fuel(forgot to check if it removed incinerator fuel from the backpack)
4. FOB was under siege, tossed my hi cap to engie, he kindly filled with his back pack- went to repair flank cades, 0/80
5. Personally tried welder fuel tank and welder fuel backpack. Seemed unfillable afaik it was stuck full of useless and imaginary liquid.

## Difference between expected and actual behavior
I think ya get it.

## Steps to reproduce
1-5 above

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
Issue identified, lack of a strict typecheck, wasn't an issue in the past due to a lack of custom tanks

**Comment by PhantomEpicness** [comment]
Fixed in #1064
