### ISSUE TITLE
Climbing into window frame isn't cancelled when you move away

### ISSUE THREAD

**Issue by Youbar** [cmss13-devs/cmss13#1058]
## Description
When you climb a window frame, you can move away and as long as you return before the timer expires, you'll be able to continue as normal

## Difference between expected and actual behavior
Movement when climbing window frame should cancel with other input

## Steps to reproduce
1. Be Xeno
2. Climb into empty window frame
3. Move away
4. Come back just a little before circle disappears
5. Success!

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
Alright, so I dug deep into this one. The interrupt flags responsible for interrupting when moving only check for loc/turf changes. It technically works once you loc has changed,but you can still move as long as you dont finish moving to another turf.

**Comment by Huffie56** [comment]
from what i understand this is intented.
