### ISSUE TITLE
Predator Skinning Synths

### ISSUE THREAD

**Issue by FrogZeke** [cmss13-devs/cmss13#106]
## Description
Predator skinning does not have a issynth check.  This allows predators to skin synthetics, producing meat and a skin.

## Difference between expected and actual behavior
It has been stated by the Pred Council that synthetics are nothing more than semi-sentient forklifts.  The purpose of skinning is taking meat and a trophy.  Preds cannot skin the APC.  The actual behavior is pred removing synth fillets and creating a skin from a dead synth.

## Steps to reproduce
Use pred tools to butcher a dead synth.

## Issue bingo (not required to be all checked)
- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
what if you could skin tham and get Synth meat instead ?

**Comment by FrogZeke** [comment]
Synthmeat is part of SS13, a combination of blood and coagulants.  In Alienverse lore, food was recycled on ships, so it would be possible to exist.  The issue is that synthetics themselves are not of made of synthmeat or blood.  Skinning a synthetic would not actually kill them, outside of many deep cuts that drained the white cooling fluid.  Aside from the technical aspects of synth construction, Yautja do not skin sentry turrets for meat or trophies. The Yautja Council has determined that synthetics are the equivalent of semi-sentient forklifts, equipment to be ignored or simply destroyed if it interferes with the hunt.  It is not something to take as a trophy regardless.

**Comment by FrogZeke** [comment]
![image](https://user-images.githubusercontent.com/22293891/165671966-25b0392a-6962-418e-a67b-d179db17e6d7.png)
To quote the Synth Senator as this is a WL change.

**Comment by FrogZeke** [comment]
> Seems to be working fine. Have you seen a synth being flayed in game?

Yes, Nathan (Discord name: InsaneRed) was the one flayed, you can confirm with him.  We have multiple species of synthetics.  In the case I saw he was a synthvivor.
