### ISSUE TITLE
Predator: Beheaded bodies that are hung up and skinned regrow their head sprite.

### ISSUE THREAD

**Issue by usnpeepoo** [cmss13-devs/cmss13#107]
## Description

When you as a predator behead a killed human and then hang up their bodies, they’re in a normal state (sprite wise). However, if you start flaying them and finish it completely, they magically regrow their head with the flayed sprite as a replacement head.

## Difference between expected and actual behavior

What it does: Grow a head after flaying
What it should do: Flayed body sprite, No head sprite.

## Steps to reproduce

1: Behead a body 
2: Hang it up with strange rope
3: Use ceremonial knife and flay it
4: Observe as the flayed skin magically recreates a head sprite

## Issue bingo (not required to be all checked)

- [x ] Issue could be reproduced at least once
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
this bug is still active
![image](https://user-images.githubusercontent.com/117036822/236012426-aa0e42b5-ed60-4e7d-a8e2-222f3bd39ab8.png)

**Comment by Huffie56** [comment]
@ItsVyzo can you link this PR https://github.com/cmss13-devs/cmss13/pull/3227 to this issue?
