### ISSUE TITLE
Auto Clean Up Process Removes Recyclables

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#1076]
## Description
Iono if it's qdel or what, I assume it's a newer process from within the last 1-2 years, something autodeletes shards/rods which can be used for different things, Rods recycle up to metal sheets, shards can be used as an audio cue that something, ie a lurker, is walking across them if you wanted to do that, but also are recyclable up to glass sheets which are usable in different constructions, like finishing a Crew Monitor, windows/reinf windows which are good for creating small medbays for medical staff that prevent marines from bumping into them while wasting half the space that would be used up by creating girders, and as a bonus doesn't waste metals.

It also I presume removes blood stains which is honestly pretty bad. . . if I get dragged off and am living, I leave a fresh blood trail that can be followed. Presumably this is deleted along with everything else in one sudden mass delete. Kind of a fucked if you do, fucked if you don't issue though since this touches on server performance and lag.

https://user-images.githubusercontent.com/6540760/190774281-70c4a37e-455d-4051-9bdb-80cb5f7fec6d.mp4

## Difference between expected and actual behavior
It shouldn't remove usable mats from the game. In this video, it deletes 60 rods which equals 15 steel sheets, which I had just stacked, so it doesn't seem to discriminate much in what it deletes as long as it's in the deletable category.

## Steps to reproduce
I'm not really a coder, so I'm not 100% sure outside of I assume either waiting, or the game checks periodically and when it hits a limit it removes all relevant things.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
Some food for thought for solutions, 

make glass shards stackable like rods
make rods auto-stack. iirc, deconstructing a reinforced wall leads to two rods being produced, so boom, it'd be one rod, stack of two

**Comment by MidwayAtom** [comment]
This is intended from the looks of it, since rods are made all over the planet usually when destruction and explosions and sorts. Best bringing it up in Idea Forum on discord.
