### ISSUE TITLE
Motion Detector Working in Satchel

### ISSUE THREAD

**Issue by IMEI21** [cmss13-devs/cmss13#1078]
## Description
MD works in satchel

## Difference between expected and actual behavior
MD should turn off when placed in satchel, confirmed this with ahelp.

## Steps to reproduce
Open satchel.
Place MD in your hand.
Turn on MD.
Place MD inside satchel.
Leave satchel open.
MD still works.

## Issue bingo (not required to be all checked)

- [ X] Issue could be reproduced at least once
- [X ] Issue happened in a recent (less than 7 days ago) round
- [ X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by silencer-pl** [comment]
If memory serves, while it does still work, it will not display the directional blips on the game screen, will only beep and indicate the amount of contacts, which I always thought was intended?

**Comment by IMEI21** [comment]
I was still seeing blips and numbers on the MD when I stuck it in my
satchel.

**Comment by lajolico** [comment]
I cannot reproduce this bug for the life of me.

**Comment by lajolico** [comment]
@memesky117 Were you able to?

**Comment by ThePiachu** [comment]
I think it works as intended. You turn on the MD, put it in the satchel, it beeps and tells you the number, but doesn't show the blips. Useful early warning system, not completely OP.

Remember guys - it used to be that you could yeet the MD on the floor and it would still work, so it's still reasonable.

**Comment by IMEI21** [comment]
Ok, that seems to make sense. I just didn't want to be using it in an
unfair way when I discovered it.

Thank you so much everyone for looking into it for me.

**Comment by MidwayAtom** [comment]
Intended to still work but not see locations. Unable to replicate. Reopen if it occurrs again.
