### ISSUE TITLE
LV 624's Yggdrassil completely hides corpses

### ISSUE THREAD

**Issue by Somniworld** [cmss13-devs/cmss13#1080]
## Description
LV's Yggdrassil tree has a few spots where corpses, wether from marines or xenos, can be *completely hidden*, and are only visible by right clicking the tile. This can notably cause marines to go perma-dead, in front of two medics, 2 meters away.

## Difference between expected and actual behavior
While I was told that the tree hiding marine corpses is intended behaviour, I do believe that, at the very least, medics should be able to see the body's status with their HUDs. Since you're basically just next to a tree, instead of being hidden in a bush, or  whatever.

## Steps to reproduce
Get on LV-624
Go to the Yggrassil tree area.
Stand at the designated location on my extremely well made picture
Die
Go perma in front of 3 medics, get eventually found by a worried teammate, after more than five minutes have elapsed.

![I went perma over this gnarg](https://user-images.githubusercontent.com/43934154/190867818-2b165fb9-b7a7-4ef6-9a75-d97f7ca291bf.PNG)

## Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
Seem more like an layer issue maybe the defib icon should be above the tree sprite?
