### ISSUE TITLE
Inconsistencies with toggling lights while inside other things

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#1083]
## Description

Messages do not take into account current light status, have inconsistent formatting, and do not apply to all lights. Rail lights also fail to create light when turned on from inside things.

## Difference between expected and actual behavior

You get the message `You cannot turn the light on while in the [...]` (whatever you're in is on the end of the message). However, you get the same message if the light is already on; in that case, it should tell you that you cannot turn the light off. The affected code is in `flashlight.dm`, `hardhat.dm`, `misc_special.dm`, and `marine_armor.dm`.

Note that the message only has `SPAN_WARNING` for armor, and not for anything else (inconsistency).

Also, rail lights on guns can still freely be toggled while inside things and has inconsistent behavior with lighting. For example, going inside something with the rail light on usually maintains light around you, but if you switch it off and back on, the light around you doesn't come back on.

## Steps to reproduce

* Turn on flashlight, get in closet, toggle flashlight, notice message saying you can't turn it on.
* Turn on rail light on gun, get in closet, turn rail light off and back on, notice that light around closet is now gone (i.e. you're now in darkness)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
bug still active.

**Comment by Huffie56** [comment]
Will work on fixing that.

**Comment by Huffie56** [comment]
@ItsVyzo can you link this PR https://github.com/cmss13-devs/cmss13/pull/3248 to this issue? 
thanks
