### ISSUE TITLE
C4s get deleted when their attached item is disassembled/picked up

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#1084]
## Description

C4s get deleted when picking up or disassembling the "attached" item.

## Difference between expected and actual behavior

C4s shouldn't just vanish out of existence.

## Steps to reproduce

* C4 a deployed roller bed and pick up the bed (C4 is now gone).
* C4 a vent and then disassemble the vent before C4 explodes (C4 is now also gone).

Note: There are likely several other things that can be C4'd and then deconstructed/undeployed. The roller bed and vent were just some of the first things I thought to test.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
this happens because the item is qdelled

**Comment by Diegoflores31** [comment]
also partially intended since acording to "rule clarification" you should not be able to pick up C4 Items nor store them
