### ISSUE TITLE
turrets on the map fiorina science annex are bugged to shit

### ISSUE THREAD

**Issue by Chrismmar** [cmss13-devs/cmss13#1090]
## Description

the gauss turrets cant be hacked, have to be destroyed, the tesla turret can be hacked, but wont turn on and cant be picked up.

## Difference between expected and actual behavior

what should happen: i can hack and or dismantle the turrets in the crashed ship on the left side of the station. or the tesla turret shouldnt be hackable.

what actually happens: the 2 gauss turrets cant get hacked. and the tesla turret can be hacked, but it wont turn on and you cant pick it up

## Steps to reproduce

just go to the little ship on the left side of the map. and try to hack the turrets, or try to pickup the tesla turret.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
intended other than the tesla

**Comment by Chrismmar** [comment]
then fix it being fixable, otherwise people like me are gonna get confused and get stuck trying to fix the turret not turning on causing them to be ambushed. (like exactly what happened to me)

**Comment by lajolico** [comment]
I'll take a look at this.

**Comment by Huffie56** [comment]
so from what i gather only the tesla is consider a bug...

**Comment by Huffie56** [comment]
going to add that to pile of stuff i will fix...

**Comment by Huffie56** [comment]
The only thing to fix is the tesla tower that is totally bugged out.
