### ISSUE TITLE
Map PMC berets are glitched.

### ISSUE THREAD

**Issue by Firecharge123** [cmss13-devs/cmss13#1091]
## Description

Putting on any PMC berets FROM MAPS (not ERT) breaks the hat. Noticed this every time I've played survivor attempting to put on a beret. Never fails to break. Specifically the maps LV-624 and Solaris Ridge. Using equip hotkey E to equip, not clicking on it. Using left-click and middle-click to attempt opening the inventory, and click-dragging to take it off will not work. Will work stripping the hat off of other people. Will send any item inside the hat to be sent to the void permanently and will allow more than 2 items to be shoved into the hat, unable to retrieve them from the hat ever again.

## Difference between expected and actual behavior

Normal PMC beret allows being able to open its inventory for small items and take off the hat. It currently is bugged and you cannot remove the hat, put items in it and attempting to put more items in it sends them to the void.

## Steps to reproduce

Putting on any PMC berets FROM MAPS (not ERT) breaks the hat. Using equip hotkey E to equip, not clicking on it. Using left-click and middle-click to attempt opening the inventory, and click-dragging to take it off will not work. Will work stripping the hat off of other people.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
Hello i am interested to take this task as my first but i am very new into coding.
i see two way of fixing this issue 
1-fix the specific code that broke for the dead spawned corpse.
2-Make the dead spawned corpse wear ERT caps.
I think i will look into using 2 to solve this seem easier.

**Comment by Huffie56** [comment]
i finally found where the corresponding code was hiding
https://github.com/cmss13-devs/cmss13/blob/master/code/modules/gear_presets/corpses.dm
i assume the corpse named "Corpse - Weyland-Yutani Corporate Security Guard" or "Corpse - Burst Weyland-Yutani PMC (Standard)" is the one you took the cap that are causing issue. i have compare it to the one preset for ERT https://github.com/cmss13-devs/cmss13/blob/master/code/modules/gear_presets/pmc.dm and they are using the same. will keep looking maybe the maps are using the wrong corpses?

**Comment by Huffie56** [comment]
So the simple solution i can propose at my current level is to simply remove the (H).
should work fine right? 
https://github.com/cmss13-devs/cmss13/compare/master...Huffie56:cmss13:patch-1

**Comment by Huffie56** [comment]
i am going to test this unsure if it's still there....

**Comment by Huffie56** [comment]
can't really find where are the beret that cause problem last time i worked on it
