### ISSUE TITLE
APC issues and duplication

### ISSUE THREAD

**Issue by morrowwolf** [cmss13-devs/cmss13#1100]
## Testmerges:

https://github.com/cmss13-devs/cmss13/pull/973 currently TM'd but happened earlier today when 973 was not TM'd.

## Description

APC spawned in, crewman started repairing, APC had missing strip of turfs inside and then duplicated itself.

https://cdn.discordapp.com/attachments/571821929850470411/1021659516229660683/unknown.png
https://cdn.discordapp.com/attachments/571821929850470411/1021659616540622898/unknown.png

The following runtimes are likely relevant: 
https://cdn.discordapp.com/attachments/571821929850470411/1021659490195615744/unknown.png

## Difference between expected and actual behavior

The APC should be usable and not duplicate itself

## Steps to reproduce

Uncertain at this time. Conversation regarding how it happened: https://cdn.discordapp.com/attachments/571821929850470411/1021662515475787916/unknown.png

## Issue bingo (not required to be all checked)
- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Brewstone** [comment]
Issue is easy to replicate and seems to only effect the transport APC. If Transport APC is selected, it spawns 2, 1 unusable and the other with the strip missing.

Additionally, the doors are inverted (red leads to blue, blue to red, & to enter back of APC click on the front)
