### ISSUE TITLE
Defibrillator Sprite Disappearance

### ISSUE THREAD

**Issue by Lagomorphica** [cmss13-devs/cmss13#1104]
## Testmerges:

Don't believe any, except audio update.

## Description
Defibrillators will turn invisible once their sprite is updated - e.g, going from green charge line to yellow charge line.

## Difference between expected and actual behavior
Should not turn invisible.

## Steps to reproduce
1. Take a standard defibrillator.
2. Use it until it has 7 charges or less, or whenever the line will turn yellow.
3. Defibrillator will turn invisible and lose its sprite.

I also have a video of it occurring if needed.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nauticall** [comment]
Confirmed. See PR above for fix ^.^
