### ISSUE TITLE
Stairs are on turf layer which causes built walls to be below stairs

### ISSUE THREAD

**Issue by morrowwolf** [cmss13-devs/cmss13#1106]
## Testmerges:

N/A

## Description

Building walls on stairs creates the walls below the stairs making them invisible. Probably needs to be an open turf layer, stair layer, and closed turf layer.

## Difference between expected and actual behavior

Closed turfs should be above stairs, not underneath them.

## Steps to reproduce

Build a wall or reinforced wall on top of perspective stairs.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
This appears to be fixed now.
