### ISSUE TITLE
You get tail swiped when trying to pull stunned xeno

### ISSUE THREAD

**Issue by DylonBR** [cmss13-devs/cmss13#1108]
## Testmerges:

N/A

## Description
You can be tail swiped by a stunned xeno as marine when trying to pull them

## Difference between expected and actual behavior
Expected behaviour: be able to pull the xeno until they get back up on their feet again
Actual behaviour: you get stunned when trying to pull the stunned xeno

## Steps to reproduce
Shoot AP rocket into tanky xeno, try to pull xeno, get stunned by tail swipe

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
This is not a bug my friend. This is pure balance. If you want to know how they can do it while stunned, I would imagine they get the same energy to react that COs, MPs, SEAs etc get when on harm intent and someone tries to inject them, prompting them to ninja move knock down their 'assailant'. Even when stunned. Imagine if you could take a xeno that was stunned by an HEDP, click and drag them to the human's side of a barricade and close the exit. That is the type of sweat you would introduce by removing this mechanic.

**Comment by Mirvra** [comment]
Marines being unable to drag xenos is a feature, not a bug.

It would be pure cancer if they could... As Superwelder said, grab a stunned xeno, drag them into cades and close them... instantly securing a kill.
