### ISSUE TITLE
Humans Not Receiving Acid Spray Damage Before Death

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#1117]
## Description

Humans, when taking a combined 200 damage, are supposed to die. This allows for overkill damage from say, a bullet hitting a human at 199 brute damage causing the person to reach 230+ damage and die. However, as the picture attached shows, acid spray(possibly other acid damage?) is not being applied on the killing hit which leads to people dying with LESS than 200 damage total. This strongly suggests there is an order conflict between acid spray damage and the death process involved.
![Acid Spray Kill Bug](https://user-images.githubusercontent.com/105765670/192050081-4d9653b7-e820-4d4a-8f61-8365f7a43f37.png)
Survivor killed by acid spray with <200 damage

## Difference between expected and actual behavior

Acid spray SHOULD be applied to the human mob as they die. Death at ~150 damage or less is frankly just a joke to fix as a medic. I have started noticing a lot of these corpses recently that should not be dead with the damage observed. There may be more order conflicts involved with other damage types but this is one I got a screen cap of clearly demonstrating the problem. The spitter acid spray damage on a dotted target is substantial so the body not receiving the damage from the spray and still dying is jarring.

## Steps to reproduce

1.   Have a damaged human mob within the lethal range of an acid spray.
2.   Use an acid spray ability on the mob.
3.   Scan the health of the mob and add the damage up.
4.   Notice the mob did not reach 200 damage and should not be dead with said damage.
5.   Thank your kindergarten teacher for teaching you basic addition.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
probably related to #885

**Comment by Huffie56** [comment]
i tested three time and never managed to kill a an human bellow 200 damage with acid spray as above.
@ItsVyzo so i assume this bug as been fixed and can be closed. thanks

**Comment by ItsVyzo** [comment]
> i tested three time and never managed to kill a an human bellow 200 damage with acid spray as above. @ItsVyzo so i assume this bug as been fixed and can be closed. thanks

Perfect, thank you @Huffie56 

Closed, assumed fixed.
