### ISSUE TITLE
scout and m2c bugs

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#113]
## Description

guys in tarps can use m2cs

## Difference between expected and actual behavior

they should not be able to do this

## Steps to reproduce

obvious

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by hotimep** [comment]
no i think its balanced
