### ISSUE TITLE
New Health Analyzer window won't update upon Re-scanning a Patient.

### ISSUE THREAD

**Issue by Mirvra** [cmss13-devs/cmss13#1130]
## Description
The new Analyzer added by #979 won't update if you re-scan someone while the window is open.
It will also open a brand new window for every single entity you scan, rather than update the original window to show the new Entity.

## Difference between expected and actual behavior
If you scan a marine, do some work on them, then scan them again it should update to show what you've done since last scan.
Instead you have to manually close the pop-up window every single time to get the new stats.

## Steps to reproduce
Grab a Health Analyzer, find a wounded marine, scan them, then give them pills and close wounds and scan again.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Mollwu** [comment]
Holy hell, yes, this would be god's work.
