### ISSUE TITLE
'Hearing' marines join the game while still in lobby

### ISSUE THREAD

**Issue by FrankTheMagicPotato** [cmss13-devs/cmss13#1142]
## Description

While sitting in lobby, you see the text from actions performed by people in the game. I've been getting the text of people joining the game as marines and putting flavor items in their satchels. This is with Ckey, not their character name. For example:
[Persons Ckey] puts the a playing card into the USCM satchel.
[Persons Ckey] puts the bronze service medal into the USCM satchel.

## Difference between expected and actual behavior

You shouldn't get any info from the game while in lobby. 

## Steps to reproduce

Join before round starts, don't Ready Up. Wait until round starts, You get a bunch of messages, specifically of marines joining and having flavor items put in their bags.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Already wrote what is hopefully a fix. Time will tell whether it works.
