### ISSUE TITLE
Unable to high throw on resin

### ISSUE THREAD

**Issue by MemesLauncher** [cmss13-devs/cmss13#1149]
## Description
As the title implies, you are able to high throw as usual, but not when you are clicking on resin.

## Difference between expected and actual behavior
High throw a item (in my cases, a signal flare for cas/a nade) past that horde of marine.
Expectation : It high throws as usual.
Actual behavior : Cannot high throw toward the resin, you can still do a regular throw but that'll hit your marine's aching back (and pray it's not a primed nade).

## Steps to reproduce
1. Take item in hand.
2. Activate High throw (done through ctrl+R+Left click for me) on a tile who has resin on it.
3. Unable to throw (you don't get the red circle above you telling about you readying up for said action.
4. Throw without high throw on to see if you can throw at all, yes you can.

## Issue bingo (not required to be all checked)
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
When you say 'resin' do you mean sticky resin, resin walls, resin membranes... There are many 'resin' objects. Or do you mean all of them?

**Comment by MemesLauncher** [comment]
By resin I don't mean structures, I mean the resin that is spread on the ground, both resin nodes and the resin itself, and the resin structures to an extend (except stuff that are ENCASED in resin, such as window frames, I can target them for high throw atleast as long as I click the sprite of the window frame)

**Comment by Superwelder** [comment]
I could not replicate this in multiple rounds. Every time I high tossed a knife or flare at the weeds or sticky resin or resin walls, the high toss worked as expected.
