### ISSUE TITLE
Click + Drag mechanics Forcing A Click On The Object Being Dragged

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#1159]
## Description

Click + Drag as you would to knock a table over or clicking and dragging on a ladder to yourself to look up said ladder now clicks on the object you are dragging whereas before(within a week of this issue's creation) it did not. This unintentional clicking forces many awkward situations with using some objects in the game which I will list below.

## Difference between expected and actual behavior

Click+Drag mechanics should not cause you to click on the object in question. It should only perform the function of click+dragging. Some examples of why this is a problem: 

- In order to nest a captured creature as xeno, you must click and drag their body to the nest but with this issue, if you are on harm intent, you slash the cap while performing the nest action. 
- In order to look up a ladder, you must click the ladder and drag it to yourself however, doing so with this issue forces you to begin climbing the ladder with no way to look up said ladder. 
- Medics often need to remove armor to defib a dead person, to do so they must click on the person and drag them to themselves to open the remove armor menu however, if you are on harm intent and you do this, you punch/stab/shoot your patient. 
- To knock over a table you must click on the table and drag it off in the direction you want to knock the table over however, if you do this with something in your hand as a human with this issue, you place your object on the table and then flip the table, causing whatever was in your hand to go flying, as xeno you slash before you flip the table. 

I am sure there are more examples but hopefully you can start to see why this issue is quite annoying.

## Steps to reproduce

As I listed above, there are many different ways this issue presents itself so I will stick with the nest example as it is the easiest and most obviously annoying one.
1.  As xeno, have a have a person you are trying to nest on the nest.
2.  While on harm intent, click and drag the person to the nest as you normally would to nest them.
3.  Notice that your character slashes the capture and then starts the nesting process.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Accidentally hit enter when making the issue before it was done so I closed it and reopened it to address the closing.

**Comment by Segrain** [comment]
At a risk of sounding stupid: do you have the preference for combat clickdrag override enabled? Every so often I forget that I have it on (or, more often, forget that I am for once not on help intent) and spend a second or two very surprised at my drags turning into clicks before remembering that _I deliberately enabled a thing whose sole purpose is to turn drags into clicks_.

**Comment by Superwelder** [comment]
> At a risk of sounding stupid: do you have the preference for combat clickdrag override enabled? Every so often I forget that I have it on (or, more often, forget that I am for once not on help intent) and spend a second or two very surprised at my drags turning into clicks before remembering that _I deliberately enabled a thing whose sole purpose is to turn drags into clicks_.

Wow you hit the nail on the head. I had asked multiple people and they all said they had the same problem. Also, I had never changed the click drag override myself. I am not sure how the setting was altered. Many thanks. Closing the issue now though I do believe it is significant enough of an issue with click-drag override to warrant a look at.
