### ISSUE TITLE
Mortar Camera not working!

### ISSUE THREAD

**Issue by Piipoh1** [cmss13-devs/cmss13#1163]
## Description
The M402 Mortar's View Camera function is not working in any form or function. Clickin on the button results in no windows prompt, with or without flare shells fired.

## Difference between expected and actual behavior
When clicked, the View Camera function is meant to pull up a separate, security camera like window that will show any current flare camera shells on the ground, giving a view for the mortar operator in order to optimize shooting in areas that will require long term fire support. Currently, the button will do absolutely nothing, in both WO and standard map rotations and game modes.  Font also seems to be off, may not be apart of the bug.

## Steps to reproduce
1. Acquire a M402 Mortar within the current merge branch.
2. Set up previously mentioned mortar.
3. Click on the view camera function.
4. Fire a flare shell in desperation. 
5. Click on the view camera function once more to have nothing happen.
6. Reconnect.
7. Click on view camera to once again have nothing happen.

## Issue bingo (not required to be all checked)

- [ x ] Issue could be reproduced at least once
- [ x ] Issue happened in a recent (less than 7 days ago) round
- [ x ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Piipoh1** [comment]
Further testing has shown certain maps will function for some players, currently the list is as such.
-Fiornia Annex
I will edit the list as more pop up!

**Comment by Superwelder** [comment]
Just a heads up, you have to delete the spaces within the brackets [] in the "Issue Bingo" section to make the checklist work properly. As for the issue itself, I have been able to use the camera shells on LV-624 and Big Red but not tested other maps. Perhaps your version of Byond is to blame?

**Comment by SexmasterWasTaken** [comment]
Is this repeatable on current master branch?

**Comment by Segrain** [comment]
This one is actually complicated. There is a certain issue preventing it working as intended in WO, it _might_ also be responsible for occasional mishaps in other maps, but it also _might_ be the case that some those issues on other maps are actually user errors with perfectly intended results if you are using the mortar wrong. Will need a bit of digging.

**Comment by amberisepic** [comment]
I was touching around with this, and I believe the issue might have something to do with _power_. When there is no power in an area, the camera menu doesn't open at all. However, when there is power in the area, the menu works again.

**Comment by NoKohi** [comment]
I figured this out with the help of Amber during a Trijent Dam round about 2 weeks ago, if the area the mortar is in isn't powered, then the mortar camera console will not work. If you try using the mortar camera console on any of the LZs on Trijent Dam, it won't work, but carry it to one of the outdoor areas that are powered (e.g. static comms area), then it will work just fine.
