### ISSUE TITLE
health analyzer not working on xenos

### ISSUE THREAD

**Issue by pedr69** [cmss13-devs/cmss13#1166]
t-thanks tgui

## Description
health analyzer gives me a fancy error screen when used on xenos
humanoids work fine

## Difference between expected and actual behavior
expected: health
got: TypeError: Unable to get property 'length' of undefined or null reference
   at t.HealthScan (http://127.0.0.1:21038/tmp8180/tgui.bundle.js:1:414217)

## Steps to reproduce
be dead
rightclick xeno
press analyze health

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by mullenpaul** [comment]
I have replicated this locally and got a fix: https://github.com/cmss13-devs/cmss13/pull/1168

**Comment by mullenpaul** [comment]
This should be resolved now @pedr69
