### ISSUE TITLE
Cluster OB range increase doesn't respect the OB warning/hive core protection

### ISSUE THREAD

**Issue by calvindoyl** [cmss13-devs/cmss13#1178]
## Description

Cluster OB's balances were not updated properly after last range increase. Those standing on the outskirts, in the range that was probably most recently added, do not receive the OB warning/directional warning properly. This additional range is also capable of hitting and destroying hive core/hive proper.

## Difference between expected and actual behavior

Should respect the hive core's OB protection, should warn those standing in it that it's falling to the NE/NW ect.

## Steps to reproduce

Stand under the far edge of a cluster OB and wait.
Put a hive core under the far edge of a cluster ob and wait.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Cluster first rolls the list of turfs to impact then shoot em, if you place the hive core after its start it won't respect the newly placed resin roofing

**Comment by Huffie56** [comment]
i don't see any recent complaint about OB related bug so i am assume it's been fixed putting clean flag on it.

**Comment by morrowwolf** [comment]
Fixed in a PR I'm too lazy to dig up.
