### ISSUE TITLE
APC Ram Medevac or Fulton BUG

### ISSUE THREAD

**Issue by JackThompson322** [cmss13-devs/cmss13#1181]
## Description
APC ram medevac or fulton, press "NO" interfate stuck won't close, press "Yes" didn't do anything the interfate move to somewhere else. Try to ram againt no new interfate show up the old interfate stuck forever on screen and can't press the "submit bug" or other.

## Difference between expected and actual behavior
Press "NO" should make the interfate close not stuck on screen forever.

## Steps to reproduce
Use APC ram a Fulton or Medevac on DS when the interfate show up press "NO", enjoy the bug. 

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
`APC ram medevac or fulton, press "NO" interfate stuck won't close, press "Yes" didn't do anything the interfate move to somewhere else. Try to ram againt no new interfate show up the old interfate stuck forever on screen and can't press the "submit bug" or other.`

can you please reword this in coherent English?

**Comment by memesky117** [comment]
Feel free to reopen once the issue description fits stan's criteria.
