### ISSUE TITLE
Improperly placed unbreakable window in Kutjevo Refinery

### ISSUE THREAD

**Issue by Youbar** [cmss13-devs/cmss13#1200]
## Description

The reinforced window in the pictured room at Medical Stormlocks of Kutjevo Refinery cannot be broken.

## Difference between expected and actual behavior

The window should be capable of being broken. Impenetrable windows are used strictly for turbines or easter eggs which this room does not enclose.

Room location:
https://i.imgur.com/fboWxeZ.png
https://i.imgur.com/Sn6fAYA.png

## Steps to reproduce

Simply go to the Medical Stormlocks on the Kutjevo Refinery map and you will find this room with an unbreakable window.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by 4hands44** [comment]
Will see about fixing it

**Comment by Youbar** [comment]
As an addendum, the stools in the bar are items and not furniture (e.g. beds) so cannot be broken how you might expect as a Xeno.

Picture here : https://i.imgur.com/wdb9Cj8.png
The elevated stools are items, the stools closer to the ground are the furniture.

I can make a separate bug report if needed but it seems excessive given the scope of the problem.

**Comment by 4hands44** [comment]
PR up
