### ISSUE TITLE
Xenomorph health in HUD missing and Corrupted Queen wrong sprite

### ISSUE THREAD

**Issue by Unknownity** [cmss13-devs/cmss13#1214]
## Description
Ghosts are unable to see the health of xenomorphs.
Corrupted Queen isn't green

![unknown (1)](https://user-images.githubusercontent.com/83834638/194752202-e7280464-80e9-4dc7-9bcb-d2c10f4ab51e.png)
![unknown](https://user-images.githubusercontent.com/83834638/194752204-40199f42-ef0f-4a7c-808c-29a96bf5852d.png)

## Difference between expected and actual behavior
you should see health of other xenos as ghost
corrupted queen should be green

## Steps to reproduce
unknown

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
pretty weird . were you able to repeat this bug ?
