### ISSUE TITLE
Cannot make more than one highlighted words section

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#122]
## Description

Goon chat's word highlighter is currently broken as it only allows one highlighted colour type to be shown.

## Difference between expected and actual behavior

It should allow for multiple words to be highlighted with a multitude of different colours.
Currently it only allows one.

## Steps to reproduce

Open up Goon chat's settings in game and see that only one text box is allowed to be used rather than multiple.
![image](https://user-images.githubusercontent.com/104228030/164786575-1836207e-01b0-4dfd-b7a9-180584401a1e.png)

There should be an option to add more than one text box but currently as shown above, there is no option.
## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
This isn't a bug so much as an oversight. Transition backported the chat system and did not include the changes made to it to allow multiple lines.

**Comment by IngloriouslyBad** [comment]
I'd love for this to make a comeback. I had a color for Help, Fall back, infected, medic, Retreat. 
Squad colors, as well as CIC colors.
A color for when people are trying to get ahold me me specifically (((which was helpful during the RP changes for SL beeing OOC tied to following orders or risk a ban. This is now currentlybthe only cor i have left sadly)))
And then a 3rd color for certain call outs people would make like lurkers warriors and queens, Flanked, FOB under attack, etc.
