### ISSUE TITLE
Xeno Acid Blood hurts dead Marines

### ISSUE THREAD

**Issue by Kiara-Miller** [cmss13-devs/cmss13#1231]
## Description

Acid blood hurts dead marines if the xeno is standing ontop of them.

Partial relation to https://github.com/cmss13-devs/cmss13/issues/358 but cause seems to be different form either issue reported there.

## Difference between expected and actual behavior

Dead marines should not be hurt by xeno abilities.

## Steps to reproduce

Have a Xeno with acid blood sit on top of a marine and shoot at it a bunch.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Kiara-Miller** [comment]
Tested on server just now too.

**Comment by usnpeepoo** [comment]
Pretty sure this is intended, i'll ask

**Comment by Kiara-Miller** [comment]
Closing as feature due to Carlar's advice.
