### ISSUE TITLE
Handheld scanner not indicating IB present sometimes

### ISSUE THREAD

**Issue by Wlodek11** [cmss13-devs/cmss13#1266]
## Description
self-explanatory

## Difference between expected and actual behavior
It always showed IB's.

## Steps to reproduce
It would be rather hard.

## Issue bingo (not required to be all checked)

- [ X ] Issue could be reproduced at least once
- [ X ] Issue happened in a recent (less than 7 days ago) round
- [ X ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
how am i suppose to even try to reproduce this?

**Comment by Huffie56** [comment]
no reason to think this is still happening it's been almost a year without a single comment on it....
