### ISSUE TITLE
OT claymores have the shrapnel and explosion fly in a random direction

### ISSUE THREAD

**Issue by DylonBR** [cmss13-devs/cmss13#1279]
## Description
OT claymores will have shrapnel and explosion go off in a random direction

## Difference between expected and actual behavior
both shrapnel and explosion should be directed to where the claymore is facing when it is activated

## Steps to reproduce
make OT claymore with shrapnel and explosive, plant it whichever way you want it, switch ckey to xeno and go on the tile directly infront of the claymore. The explosion and shrapnel may or may not go in your direction.

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
you need to use the correct assembly for this kind of behaviour

**Comment by DylonBR** [comment]
I did use igniter-igniter assembly, yet this bug still happens

**Comment by harryob** [comment]
> I did use igniter-igniter assembly, yet this bug still happens

👍

**Comment by lajolico** [comment]
Working on it now. I found the issue, and hope to get a PR tonight.
