### ISSUE TITLE
Accessories spawn on IO tanker jacket rather than uniform

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#1302]
## Description
When spawning as IO, your rank boards and service medal (playtime medal), both spawn attached to the new tanker jacket, rather than your uniform.

This probably happens with other roles as well.

## Difference between expected and actual behavior
Expected: The rank boards and medal spawn attached to the uniform rather than the jacket
Actual: The rank boards and medal spawn attached to the new tanker jacket accessory

## Steps to reproduce
1. Spawn as IO
2. Check for rank boards and service medal

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Intended.
Do IOs even spawn with a tanker jacket, though? And if so, _why_?

**Comment by Diegoflores31** [comment]
tanker jacket is ugly af it looks like a 2019 sprite with no shading

**Comment by Wintermote** [comment]
This is really annoying behaviour; what's the reason for it being intended? Every round I have to pull my rank board and medal off my tanker jacket and put them on my uniform where I'm expecting them to be in the first place.

So what's the reasoning behind this?

**Comment by Huffie56** [comment]
Simple fix remove the tanker jacket their is no reason to be there?
https://github.com/cmss13-devs/cmss13/pull/1550

**Comment by ItsVyzo** [comment]
not a bug
