### ISSUE TITLE
Can't man M56D after zooming in with Binocs

### ISSUE THREAD

**Issue by aceroyuno** [cmss13-devs/cmss13#1314]
## Testmerges:
n/a

## Description

After using the zoom feature on any of the binoculars and then zooming out, you cannot use an M56D without switching hands.

## Difference between expected and actual behavior

After zooming in and zooming out, I should be able to use the M56D

## Steps to reproduce

-take any binocs and use them
-use them a second time to zoom out
-drag the M56D on to you to use it. It says you cannot man it.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Fixed via #1318. Didn't auto close.
