### ISSUE TITLE
Splints

### ISSUE THREAD

**Issue by RedIBat** [cmss13-devs/cmss13#1315]
## Description

You can apply splint to yourself, while it is in your first aid kit pouch or dropped on the ground.

## Difference between expected and actual behavior

Applying splint process should stop immediately if you put it in your pouch, drop it on the ground.

## Steps to reproduce

Pick up splint, click on your sprite to apply it. Drop it or press E to put it in your pouch. Splints still being applied, if your char does not move.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
One of many, many manifestations of a well known thing. I will get to fixing it, one day...
