### ISSUE TITLE
Resin nodes hidden by structures and objects

### ISSUE THREAD

**Issue by Doom-external** [cmss13-devs/cmss13#1330]
## Description
Resin nodes are hidden by resin walls of all kinds, along with most objects.

## Difference between expected and actual behavior
They should be visible over almost everything bar resin holes I think it was?

## Steps to reproduce
Place resin node, build wall on top of resin node. Place resin node on tile with objects.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
The last to work on it is Segrain atleast it's what i found looking in change log 20 octobre.
Weeds are once again properly layered over the floor (meaning, for example, that vents and pipes are visible over them where appropriate.....
Couldn't find is test merge....

**Comment by LoJoFan** [comment]
BUMP! This also applies to stair tiles, which makes them especially annoying as you have to alt-click the tile.

![image](https://user-images.githubusercontent.com/112346996/201599226-bd33ce4e-0233-48cb-938c-aed68dbcb850.png)

**Comment by blackcrystall** [comment]
Still no one fixed that? Cringe... Okay, I port my fix later.

**Comment by blackcrystall** [comment]
This is issue already fixed? No?
