### ISSUE TITLE
Controllable Hugger issue with GL helmets

### ISSUE THREAD

**Issue by Siefer21** [cmss13-devs/cmss13#1332]
## Testmerges:

Vampire Lurker Merge but likely irrelevant

## Description

Tried facehugging a GL that was being captured as a hugger, in which it killed me off and put the sprite on top of GL and soon died off, failing the hug.

## Difference between expected and actual behavior

Expected I imagine is you don't just... die for trying and failing.

## Steps to reproduce

I assume fail hugging a GL helmet as a hugger again

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Shad0vvs** [comment]
GL helmet has some hugger protection, theres a low chance to get the hug off.

**Comment by Diegoflores31** [comment]
Huggers die on failed hugs when the user is hugger resistant . This is intended for npcs and should likely stay or hugger will be able to just spam hug to bypass protections
