### ISSUE TITLE
Double shotgun delay bug

### ISSUE THREAD

**Issue by LoJoFan** [cmss13-devs/cmss13#1343]
## Description
The double shotgun fire delay applies to single shotguns, making it frustrating for rifle-shotgun weapon combos or quickly holstering and unholstering one shotgun.

## Difference between expected and actual behavior
The double shotgun fire delay should apply only to two or more shotguns. It applies to single shotguns, too. 

## Steps to reproduce
1. unholster shotgun
2. fire
3. holster
4. unholster same shotgun rapidly
5. try to fire
6. :////

Normal shotgun ROF

https://user-images.githubusercontent.com/112346996/198255400-ae8129cc-97b3-4b59-9055-829224139c21.mp4

Reported bug

https://user-images.githubusercontent.com/112346996/198255295-444447d1-532e-41e4-9361-9a13c6c36c3e.mp4

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
I'm not sure to understand why this is an issue, the delay is on grabbing the gun, not firing

**Comment by LoJoFan** [comment]
> I'm not sure to understand why this is an issue, the delay is on grabbing the gun, not firing

Try this in local as per "steps to reproduce", there's a delay on firing. In the second video, I spam left mouse button.

**Comment by LoJoFan** [comment]
> Yes because of your performing steps 3 & 4.
> 
> Use attachments that decrease wield delay if your want to counteract the intended effect.

I don't think we're understanding each other. The M37A2 shotgun in the video has the lowest possible wield delay. It has an angled grip, and no other attachments increase its wield delay. I holster, unholster and quickly wield the shotgun in the video. There is no wield delay problem.

Much like above, I recommend you try to replicate this in local. Follow the steps!

**Comment by Dueu** [comment]
I think its intended to prevent double/triple or maybe quad chungusing. Basically there is a big firing cooldown to ALL shotguns if you rapidly holster and unholster https://github.com/cmss13-devs/cmss13/pull/521#issue-1276120600

**Comment by LoJoFan** [comment]
> I think its intended to prevent double/triple or maybe quad chungusing. Basically there is a big firing cooldown to ALL shotguns if you rapidly holster and unholster [#521 (comment)](https://github.com/cmss13-devs/cmss13/pull/521#issue-1276120600)

Yes, I know. Check "difference between expected behavior and actual behavior".

**Comment by Huffie56** [comment]
1-It seem there is a decrease in your firing rate on the second video and i don't think it's link to a "wielding problem".
2-Your right it seem that firing delay is increase when you holster and wield your gun. that's not intended.
3-https://github.com/cmss13-devs/cmss13/pull/521/files
var/delay_left = (last_fired + fire_delay + additional_fire_group_delay) - world.time
4- seem weird that var "delay_left" is calculate by "adding fire_delay" to "additional_fire_group_delay"
feel to me like it's increasing delay time without checking if your using same gun or a different gun??
If i am wrong forgive me i am bald.

**Comment by LoJoFan** [comment]
> 1-It seem there is a decrease in your firing rate on the second video and i don't think it's link to a "wielding problem". 2-Your right it seem that firing delay is increase when you holster and wield your gun. that's not intended. 3-https://github.com/cmss13-devs/cmss13/pull/521/files var/delay_left = (last_fired + fire_delay + additional_fire_group_delay) - world.time 4- seem weird that var "delay_left" is calculate by "adding fire_delay" to "additional_fire_group_delay" feel to me like it's increasing delay time without checking if your using same gun or a different gun?? If i am wrong forgive me i am bald.

While I don't know what it is in code that's causing it, I think weapon groups is the reason. Everything you said is right.

**Comment by Huffie56** [comment]
> > 1-It seem there is a decrease in your firing rate on the second video and i don't think it's link to a "wielding problem". 2-Your right it seem that firing delay is increase when you holster and wield your gun. that's not intended. 3-https://github.com/cmss13-devs/cmss13/pull/521/files var/delay_left = (last_fired + fire_delay + additional_fire_group_delay) - world.time 4- seem weird that var "delay_left" is calculate by "adding fire_delay" to "additional_fire_group_delay" feel to me like it's increasing delay time without checking if your using same gun or a different gun?? If i am wrong forgive me i am bald.
> 
> While I don't know what it is in code that's causing it, I think weapon groups is the reason. Everything you said is right.

I would sugest to go on discord and try to launch conversation or even ahelp it when a coder is online. that way you can show them directly or make them test it...

**Comment by LoJoFan** [comment]
> > > 1-It seem there is a decrease in your firing rate on the second video and i don't think it's link to a "wielding problem". 2-Your right it seem that firing delay is increase when you holster and wield your gun. that's not intended. 3-https://github.com/cmss13-devs/cmss13/pull/521/files var/delay_left = (last_fired + fire_delay + additional_fire_group_delay) - world.time 4- seem weird that var "delay_left" is calculate by "adding fire_delay" to "additional_fire_group_delay" feel to me like it's increasing delay time without checking if your using same gun or a different gun?? If i am wrong forgive me i am bald.
> > 
> > 
> > While I don't know what it is in code that's causing it, I think weapon groups is the reason. Everything you said is right.
> 
> I would sugest to go on discord and try to launch conversation or even ahelp it when a coder is online. that way you can show them directly or make them test it...

I contacted the coder of the double shotgun delay and was met negatively, which is why I'm making an issue here.

**Comment by Huffie56** [comment]
> I contacted the coder of the double shotgun delay and was met negatively, which is why I'm making an issue here.
I am trying to catch attention from other coder maybe they will confirm what i saw and take a look at it.
I don't think it will be long to fix but just need some coder to pay attention at your video and look at the code.

**Comment by Huffie56** [comment]
@LoJoFan would this https://github.com/cmss13-devs/cmss13/pull/2309 fix your problem?

**Comment by LoJoFan** [comment]
> @LoJoFan would this #2309 fix your problem?

Don't know, doubt it. Will have to see.

**Comment by ItsVyzo** [comment]
At this point in time, this is intended. Not a bug. Refer to #2309 comments by Morrow

**Comment by Huffie56** [comment]
closed didn't even read the messages i bet.
the bug was that holstering would reset the delay to shoot.
and we both tested it while taking into account the draw of the weapon delay.
