### ISSUE TITLE
Roundstart CL spawning in wrong area and without proper access

### ISSUE THREAD

**Issue by khalifjordan** [cmss13-devs/cmss13#1352]
## Description
I have played two rounds as roundstart CL and both times spawned in the general cryopod area and not in my office. I have also spawned with no access to CIC or Research and seem to have no ability to open stairwell shutters either.

## Difference between expected and actual behavior
No access to CIC, Research or ability to open stairwell shutters; these are all things CL's should have access too

## Steps to reproduce
Unsure how to reproduce other than setting CL roll to High?

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by khalifjordan** [comment]
I finally found someone cooperative enough to let me look at the ID in CIC while playing as CL - the ID has 0 access other than USCM IFF selected as on. Not sure if that helps.

**Comment by hotimep** [comment]
feature

**Comment by ThePiachu** [comment]
Started looking into it - for some reason Nightmare variant of CL is loading, hence the messed up spawn and access.
