### ISSUE TITLE
Freeing From Hive Doesn't Set You Back Into Body

### ISSUE THREAD

**Issue by Misttyy** [cmss13-devs/cmss13#1375]
## Description
Simple bug. Destroying the resin nest instead of doing the proper anim for it doesn't let someone who's ghosted back into their body.

## Difference between expected and actual behavior
It should let you back into your body after the nest is broken. Instead, if you break it with your knife instead of using a welder or etc to cut someone loose it keeps them ghosted.

## Steps to reproduce
- Get Capped
- Ghost
- Get freed via someone breaking the nest

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by lajolico** [comment]
I'll take a gander at this

**Comment by Huffie56** [comment]
Should we even be able to bypass the new mechanic and break the nest directly?

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/issues/1375
similar or connected issue could be both tackle in a PR.
