### ISSUE TITLE
UI bug when revived from crit as Xeno

### ISSUE THREAD

**Issue by Kenju22** [cmss13-devs/cmss13#1376]
![2022-10-29](https://user-images.githubusercontent.com/112263479/198857647-43e263b7-525b-43a8-8d2c-e2e42855a2a8.png)

So, was nearly killed but dragged onto weeds and got back up, but when I did quite a few of my buttons were missing icons, and it was a struggle to get anything working again, especially trying to get the constructable menu back up. I've never had this happen before, but I realize there have been a number of TM's lately so it is possible that was somehow related?

Clicking the empty/void buttons got them working *USUALLU* but the menu for what I was building went down every time I made something, and I had to get it back up when I wanted to make something other than what I had just made.

**Comment by Huffie56** [comment]
> ![2022-10-29](https://user-images.githubusercontent.com/112263479/198857647-43e263b7-525b-43a8-8d2c-e2e42855a2a8.png)
> 
> So, was nearly killed but dragged onto weeds and got back up, but when I did quite a few of my buttons were missing icons, and it was a struggle to get anything working again, especially trying to get the constructable menu back up. I've never had this happen before, but I realize there have been a number of TM's lately so it is possible that was somehow related?
> 
> Clicking the empty/void buttons got them working _USUALLU_ but the menu for what I was building went down every time I made something, and I had to get it back up when I wanted to make something other than what I had just made.

we are going to need more info if we want to reproduce that.
did it happen to you a second time?
if yes feel free to post a new issue using this format...
https://github.com/cmss13-devs/cmss13/issues/new/choose

**Comment by Huffie56** [comment]
@ItsVyzo i think you can close this one.
1-this doesn't have the correct format so it extremely hard to find out how to reproduce...
2-and nobody reproduced it or confirmed it's an issue

**Comment by ItsVyzo** [comment]
Unclear how to reproduce/lacks instructions

thanks @Huffie56
