### ISSUE TITLE
Barricades do not produce sound when they get hit.

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#139]
## Description

When wooden, sand, metal and plasteel barricades get hit they do not produce a sound. 

## Difference between expected and actual behavior

Well, they should emit a sound.

## Steps to reproduce

Hit a barricade that is wooden, sand, metal or plasteel.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Can confirm that all but glass makes no noise upon being hit.
