### ISSUE TITLE
Rain can be heard in space

### ISSUE THREAD

**Issue by silencer-pl** [cmss13-devs/cmss13#1424]
## Description
You can currently hear rain in space if you're standing on the tile as a ghost. Related to the recent Weather system merge I'm assuming.

## Difference between expected and actual behavior
In space, no one (is supposed to be able to) can hear you scream.

## Steps to reproduce
Wait for a map like LV that uses the rain ambience effect.
Walk out into space as a ghost. 
Should work for non ghost mobs too!

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i found the Pull request about it that was merge 8 days ago.https://github.com/cmss13-devs/cmss13/pull/1289 Will look into and  tag geeves if i don't find why.

**Comment by Huffie56** [comment]
I Also heard the Weather sound in space in the admin/thunder dome level i am pretty sure.

**Comment by Huffie56** [comment]
this PR should fix it
https://github.com/cmss13-devs/cmss13/pull/3145

**Comment by Huffie56** [comment]
@ItsVyzo my PR got merge it fix this issue.
https://github.com/cmss13-devs/cmss13/pull/3145
