### ISSUE TITLE
Pens no longer clicky and CL briefcase no longer has sfx

### ISSUE THREAD

**Issue by AnuvKH** [cmss13-devs/cmss13#1429]
## Description
CL pens (WY branded, and possibly all pens had sfx) no longer make a clicky sound when used in hand. They used to make a very distinct and audible (for everyone in range) click sound, and it was real cool. Also the CL briefcase used to make a fax printing sound when an item was being made from it. It also no longer does so. **I am FAIRLY confident the sounds were fine until the recent CL cryobay spawning bug that started a week or two ago, which is now fixed. If that helps nail down the problem.

## Difference between expected and actual behavior
No sounds for pens being used nor the liaison WY Automated Storage briefcase printing. Pens should click and briefcase should make sounds.

## Steps to reproduce
Simply using either item.

## Issue bingo
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ThePiachu** [comment]
Wow, I'll have to investigate that! I specifically gave the CL the power of the clicky pen exclusively so it would be cool but not abused too much! :D

**Comment by ThePiachu** [comment]
No, I checked it locally and the briefcase makes sounds and the pens both in the CL's office and ones created by the briefcase are clicky.

**Comment by fira** [comment]
This is probably a server issue. There's an unaddressed problem with the TGS setup which prevents playing dynamic sounds in the `sound/` directory. I need to remember to fix it...

**Comment by AnuvKH** [comment]
> No, I checked it locally and the briefcase makes sounds and the pens both in the CL's office and ones created by the briefcase are clicky.

That's dang weird. I know for sure it's not working on the server right now, but it was about two weeks ago.

**Comment by Huffie56** [comment]
going to test that.

**Comment by Huffie56** [comment]
@ItsVyzo so i tested it and it work as intended could hear the pen click and the CL briefcase make noises.
you can close it thanks.

**Comment by AnuvKH** [comment]
I noticed this recently, thanks. Glad it was fixed.

**Comment by harryob** [comment]
(i fixed it btw)

**Comment by ItsVyzo** [comment]
> (i fixed it btw)

thanks harry <3
