### ISSUE TITLE
SU6, Flare gun, and flares don't fit in shoulder holster

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#143]
SU6 just wont first off

Flare gun wont either, and of course neither will two unlit flares- old shoulder holster allowed it

**Comment by MidwayAtom** [comment]
@nuklearcellphoneg Please make sure to use the issue bug format given when opening a new issue. Thank you.

**Comment by nuklearcellphoneg** [comment]
> @nuklearcellphoneg Please make sure to use the issue bug format given when opening a new issue. Thank you.

I have a deep seated autism for efficiency, dementia, and schizophrenia, this will be a difficult task

## Description
SU6, Flare gun, and flares don't fit in shoulder holster
## Difference between expected and actual behavior
SU6, Flare gun, and flares don't fit in shoulder holster- they should.
## Steps to reproduce
Try to fit SU6, Flare gun, and flares in shoulder holster
## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)
