### ISSUE TITLE
Objectives should be created after Nightmare inserts are done overwriting / deleting things

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1437]
## Description

Nightmare inserts seem to have caused some issues with Objectives (being fixed with some PRs). We ought to make sure Objectives and Clues spawn properly only after Nightmare inserts are done loading.

Check the conversation https://github.com/cmss13-devs/cmss13/pull/1422 .

Fira said the Nightmare inserts shouldn't be doing that, but from the bugs we've seen, they still do. Either the Objectives are linked before the Nightmare inserts are added, or the Objectives Controller connects to deleted Computers / Folders / etc. and gives them Clues still. We should double check (although https://github.com/cmss13-devs/cmss13/pull/1422 and https://github.com/cmss13-devs/cmss13/pull/1413 will be addressing the null bugs so it might be harder to notice).

## Difference between expected and actual behavior

Objectives should not link to items that were overwritten with Nightmare inserts, but they do.

## Steps to reproduce

Run LV with Nightmare inserts in medical dome or crashed ship and check the Computer Objectives for the deleted computers - they will still be listed.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
This is the second, yet-not-fixed cause behind the #832. Still needs proper fixing. (Yes, I have seen #1413. Not quite what I had in mind, but my solution requires actual mapping, and that requires effort and time. One day.)

**Comment by fira** [comment]
I reiterate belief that provided proper deletions in #1422 of objectives, there should be nothing left in SSobjectives after Nightmare map changes are done and the objectives get connected. This only happens on roundstart.

That or there's another loose end...

**Comment by ThePiachu** [comment]
After talking with Fira, I think the issue might lie from Objectives not being deleted and thus persisting in the Objective Controller. Then they would get linked after the Ngihtmare Inserts were put in. With the two PRs merged that address Objectives deleting themselves properly I don't think we'll see this bug again.

If we do, we can revisit this issue. At least we have mostly honed in on what could be the cause of those various objectives not being linked.

**Comment by Segrain** [comment]
> what could be the cause of those various objectives not being linked.

That much is already known. It is simply a matter of sitting down and doing some mapping to make terminals work like the rest of the system.
