### ISSUE TITLE
Object Narrate, that is the admin command to make objects say/emote stuff does not show up

### ISSUE THREAD

**Issue by silencer-pl** [cmss13-devs/cmss13#1440]
## Description
What the title says. Normally in admin mode right clicking an object should have a option to force it to say/emote stuff with langchat emotes. That is currently missing.

On a sidenote, this verb came back for like 2 rounds seemingly at random, but I didn't see any testmerge changes so I cant say which one may have caused it.

## Difference between expected and actual behavior
I expect to have that verb available from my right click menu. I do not have it available.

## Steps to reproduce
Be with Senior Admin perms (the most of what I could check)
Right click on something
Try to make it say/emote something with the verb. You can't because it's not there.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
it seems the verb will be sometimes missing when connecting, but if you Hide & Re-Show admin verbs, it'll be there
