### ISSUE TITLE
Consistency Issue //Small quality of life improvement with equipement vendor in squad prep

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#1449]
## Pull request:
https://github.com/cmss13-devs/cmss13/pull/1453

## Description
1-Equipment vendor should display their content in a constant way between the different vendors.
   Standard equipment =>Armor =>backpack =>Belt =>pouches=>Mask(standard private vendor order).
   Should be replicate into the ColMarTech Surplus Uniform Vendor and in ColMarTech Automated Armaments Squad Vendor.
2-Also i think ColMarTech Automated Armaments Squad Vendor equipment should be compare with ColMarTech Surplus   Uniform Vendor and remove every item that is already in ColMarTech Surplus Uniform Vendor. As it only increase the cluster around ColMarTech Automated Armaments Squad Vendor.
3-Maybe move munition below the corresponding gun in the ColMarTech Automated Weapons Rack.
4- 

## How that would improve Consistency of the game.
If vendors distributing similar equipment it would more easy for player to navigate and found what they need.
If ColMarTech Automated Armaments Squad Vendor and ColMarTech Surplus Uniform Vendor have more specific roles would be more easy to equip and will disperse marine in the prep while they equip.

**Comment by Huffie56** [comment]
I may look into it to propose a test merge but i prefer launching an issue before to have feedback on it.

**Comment by Huffie56** [comment]
I am currently looking into the code and make a pull request. waiting for feedback in general.

**Comment by Huffie56** [comment]
Any idea why the standard Private vendor is squad lock and why access isn't at least share between alpha bravo and between charlie and delta vendors and doors?

**Comment by Segrain** [comment]
Why would it not be? Each squad goes into its own room. No need to have PFCs from both squads crowding together.

**Comment by Huffie56** [comment]
> Why would it not be? Each squad goes into its own room. No need to have PFCs from both squads crowding together.

it's out of the topic on this issue but i was thinking about proposing to merge the two squad prep for private to gain space and make something less clustered.... anyway it's out of topic....

**Comment by Huffie56** [comment]
found some Consistency issue while looking the code the vendors doesn't use the same name for same object (not sure if it's local)between ColMarTech Surplus Uniform Vendor and ColMarTech Automated Marine Equipment Rack.
Not going to change that name unless someone can confirm it's just local.

**Comment by mullenpaul** [comment]
Be aware that I've just reworked a bunch of the vendor code and will be rewriting the gear one as well to make it work with TGUI. By default, in TGUI, the items in a category are sorted into alphabetical order. There should be a way to override this.

**Comment by Huffie56** [comment]
> Be aware that I've just reworked a bunch of the vendor code and will be rewriting the gear one as well to make it work with TGUI. By default, in TGUI, the items in a category are sorted into alphabetical order. There should be a way to override this.

Thanks for the head up i made a test merge draft but vending machine code is such a mess and disperse. don't you think it would go faster to redo how the code work and instead of having multiple different s Vendors. maybe having one type for each faction that check ID job and import the list that they are allow to take/buy?

**Comment by mullenpaul** [comment]
I was thinking of rewriting the back end code once I've got them all to tgui. The way they could be made simpler is to unify the input data types to a common format. Half the logic between them is duplicated with a different data set. With the UI done I would be able to determine a nice intermediary format

**Comment by Huffie56** [comment]
> I was thinking of rewriting the back end code once I've got them all to tgui. The way they could be made simpler is to unify the input data types to a common format. Half the logic between them is duplicated with a different data set. With the UI done I would be able to determine a nice intermediary format

I am working on a draft about this i start by analyzing how current vendor system is working to separate the different vendor into Types with proper function and see what part of codes they can have in common.
Will help to do plan a rework of how vendors work in the entire CM code hopefully....
Hope to see you there and maybe you will find it useful in the future.
https://github.com/cmss13-devs/cmss13/pull/1460
