### ISSUE TITLE
You can fill ammobelts weapon slot if using a dump method

### ISSUE THREAD

**Issue by fira** [cmss13-devs/cmss13#1450]
## Difference between expected and actual behavior

Dumping should honor the weapon slot restriction.

## Steps to reproduce

The Flaregun belt has 16 slots for flares and one for a flaregun.
If you dump fill it from flareboxes, it will fill it with 17 flares. 
Upon taking a flare out, you can't put it back in.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
that PR fixed a similar issue?
https://github.com/cmss13-devs/cmss13/pull/580
