### ISSUE TITLE
Some TGUIs sometimes randomly close themselves

### ISSUE THREAD

**Issue by Lizurt** [cmss13-devs/cmss13#1451]
## Testmerges:

Don't know where to check them sadly. Round was on ~17:00-19:00 (5-7 PM) UTC, 06/11/22

## Description
Hive Status, Evolve Menu and maybe some other menus sometimes randomly close itself.

## Difference between expected and actual behavior
These menus should remain open as long as the close button remains untouched. But they close themselves after some time.

## Steps to reproduce
Haven't found a way to surely reproduce it, but it happens often enough to notice. Some players noticed the bug too.

1. Open Hive Status or Evolve Menu
2. Wait 5-30 seconds

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
I had the same issue this round with vendors in prep and other window with TGUI. It seem random to me never saw anything like that since TGUI is in place.

**Comment by Herotitan772** [comment]
Yeah same. I’ve had some TGUI interfaces come up and freeze for a few seconds then close but then when you reopen it, it works as expected (mainly the OT demo simulator, reagent tank amount window and one of the prep vendors(cant remember which))

**Comment by Lizurt** [comment]
Cannot longer reproduce, it seems to be fixed by https://github.com/cmss13-devs/cmss13/pull/1454
