### ISSUE TITLE
broken buttons on dropships

### ISSUE THREAD

**Issue by Chrismmar** [cmss13-devs/cmss13#1469]
## Description

the buttons for lockdown on the Alamo and Normandy both do not work, no matter how many times i press them, they flash green but the doors don't lock down

## Difference between expected and actual behavior

what it should do: lock all doors 
what it does: nothing but flashes green
## Steps to reproduce

just press the buttons, I've done it many rounds in a row as a PO and every time the buttons just don't do shit

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Works for me, the only catch is that you can't use the button while of the Almayer for some reason. This appears to be intended, but I don't know why

**Comment by Chrismmar** [comment]
if thats intended thats retarded. just saying

**Comment by MidwayAtom** [comment]
As intended, closing.
