### ISSUE TITLE
synths take organ damage and can't repair it

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#148]
## Description

title

## Difference between expected and actual behavior

they shouldn't be able to take organ damage or should be able to repair it

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Fixed with #260
