### ISSUE TITLE
GRAMMAR CONSISTENCY ERROR IN TECHWEB (GAME BREAKING)

### ISSUE THREAD

**Issue by hotimep** [cmss13-devs/cmss13#1487]
INCEND OB'S DESCRIPTION IS MISSING A PERIOD AT THE END OF IT'S SENTENCE!!!! MY EYES!!!

![5a7891c2e231bd9bc78618b5a5ae0cba](https://user-images.githubusercontent.com/59359762/201015058-3e66cd57-0a20-4629-b630-768afd01c4b2.png)

FOR REFERENCE HERE'S HE AND CLUSTER
![0d16d422e1ff7612e48de49f77422641](https://user-images.githubusercontent.com/59359762/201015144-2bb52a1d-66ef-493c-ba1d-25febbfb3432.png)

**Comment by fira** [comment]
Well, sounds simple enough, just PR it

**Comment by hotimep** [comment]
do i look like a coder to you
