### ISSUE TITLE
Overt Marine Raider gear presets do not get Raider Armor, get generic M3 armor instead

### ISSUE THREAD

**Issue by silencer-pl** [cmss13-devs/cmss13#1493]
## Description
Most likely caused by https://github.com/cmss13-devs/cmss13/pull/1384 - either the armor picking system utilized there is not utilized properly or the underlying system has some issue that causes this.

## Difference between expected and actual behavior
What I and 8 players who rolled a Raider ERT got:
![image](https://user-images.githubusercontent.com/103842328/201139618-a7b1edb4-20e9-415e-84af-d7ace8d50492.png)
What we expected: 
![image](https://user-images.githubusercontent.com/103842328/201140908-a609931b-14aa-44ff-bbd3-ffd7ff75614e.png)

## Steps to reproduce
Create a human with any MARSOC (without the Covert part) gear peset or call the Raider ERT, everyone gets this.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/blob/master/code/modules/gear_presets/uscm.dm line 741

**Comment by Huffie56** [comment]
FIXED!!! i did it  didn't crash anything and spawn the raider ERT with MARSOC M3 Pattern Armor
