### ISSUE TITLE
Funny Tiles

### ISSUE THREAD

**Issue by TropicalFlak** [cmss13-devs/cmss13#1505]
## Description
They sometimes change color when you move them. Seems random to me.

![image](https://user-images.githubusercontent.com/108848001/201311861-0e1cb7f9-d41d-4f08-aeea-9b078c8e8611.png)
![image](https://user-images.githubusercontent.com/108848001/201311872-6214889c-9bb2-4e1f-8799-9b930ed447dd.png)
![image](https://user-images.githubusercontent.com/108848001/201311881-0dd0be58-8732-4fa0-b817-dda78eb2000e.png)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Not enough details to understand how the "bug" works...

**Comment by ItsVyzo** [comment]
see above comment for closing reason
