### ISSUE TITLE
Shrunken UI

### ISSUE THREAD

**Issue by TropicalFlak** [cmss13-devs/cmss13#1508]
## Testmerges:
Im no coder but I have a feeling the Research terminal tgui #1398 PR has something to do with it

## Description
Ever so slightly too small

![image](https://user-images.githubusercontent.com/108848001/201362965-9563e9f1-1dbc-4464-bab8-15b9493ed82e.png)
![image](https://user-images.githubusercontent.com/108848001/201362975-775f4841-5bb5-4b95-98ab-169b186e002c.png)

## Steps to reproduce
Boot up the game and see for yourself

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
issue with a testmerge, resolved since
