### ISSUE TITLE
HF2 Health Analyzer Not Wiping SSD and Soulless Data For Successive Scans

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#1511]
## Testmerges:
Almost certainly related to the scanner's move to tgui. Unsure which patch to tgui scanners that this popped up in but it has existed for some time now.

## Description

Scanning SSD or soulless people reports as much in the health scan at the top. All scans shortly after scanning an SSD or soulless person then retain the SSD or soulless tag. Even when the target is obviously not SSD or soulless. The scanner then 'fixes' itself in a minute or two and will report the correct info assuming you have not scanned anyone that is SSD or soulless in that time. Below are pictures of me scanning myself(obviously not SSD as I am doing the scanning), then some SSD MT I found in a hallway, then scanning myself to illustrate the issue. The exact same thing happens for soulless people as well.
Myself:
![Scanner non-SSD](https://user-images.githubusercontent.com/105765670/201415213-5613aeb3-61d0-4a97-a9e7-46c70e56b686.png)

The SSD MT:
![Scanner SSD](https://user-images.githubusercontent.com/105765670/201415272-3d3d69bf-2525-4c81-9593-934dcf2742ea.png)

Scanning myself after the SSD MT:
![Scanner SSD Report Error](https://user-images.githubusercontent.com/105765670/201415312-d468218c-2244-4a53-aed1-73ea808d4038.png)

## Difference between expected and actual behavior

Self-explanatory.  The scanner should report accurate data. In particular, a medic/synth that is scanning many people may mistake someone that is in pain crit or other impairment as an SSD or soulless person and move on to others. I would not be surprised if the body scanner shared the same problem but I did not test that particular device.

## Steps to reproduce

1. Scan yourself to ensure you are not SSD or soulless.
2. Scan an SSD or soulless person.
3. Scan yourself soon after.
4. Notice the inaccurate information.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
Could be https://github.com/cmss13-devs/cmss13/pull/1145 oct 6
or https://github.com/cmss13-devs/cmss13/pull/1138 sept 28
or https://github.com/cmss13-devs/cmss13/pull/979 sept 26
none of those are made by the same dev so ....
