### ISSUE TITLE
XM88 Attachments dissappearing

### ISSUE THREAD

**Issue by TropicalFlak** [cmss13-devs/cmss13#1523]
## Description
After getting flung by a crusher my attachments were gone after I picked them back up, but when I examined it was still there. When I dropped and picked it up again, there were there.

![image](https://user-images.githubusercontent.com/108848001/201488662-ae8ba03a-4561-48ca-af18-2a7e5b624a69.png)
![image](https://user-images.githubusercontent.com/108848001/201488665-0670ff50-9d3d-414d-8574-858595c842f5.png)

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Looks like an issue with sprites alone.

**Comment by Huffie56** [comment]
@ItsVyzo and @usnpeepoo could you tag this with need reproducing please

**Comment by Huffie56** [comment]
this isn't a good issue post going to look for more info and make a new one.

**Comment by ItsVyzo** [comment]
This seems to have been fixed since
