### ISSUE TITLE
LV-624 Nexus Lockdown

### ISSUE THREAD

**Issue by Googles-Hands** [cmss13-devs/cmss13#1549]
## Description

This has been an issue for as long as I have played, the Nexus building has a button called "Nexus Lockdown" in the admin office, which doesn't actually do anything since there are no shutters.

## Difference between expected and actual behavior

A button which has no shutters to activate. The Nexus needs shutters (CL Office variant, not Research Dome blast doors) placed at all the areas I marked in red.
![LV-new](https://user-images.githubusercontent.com/59937074/201679096-8fa66819-7a79-4c5c-9327-cf9677b4aa6b.png)

Celebrate a new era of CM with me, with Hookers, Blackjack and shutters to keep the rabble out.

## Steps to reproduce

1. Play LV
2. Power the Nexus
3. Hit the "Nexus Lockdown" button

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
in earlier version nexus add a working button to lock down all nexus.
Don't remember why it was remove but their was a reason.
It's more a suggestion for a mapper you will have an easier time finding them on discord...
here it will probably go in the drain.
having the shutter just closing sec office could be another option...

**Comment by MidwayAtom** [comment]
This could be in line with a balance change, best to try and get support via discord in the Idea Forum channel.
