### ISSUE TITLE
Ghosting as infected is counter-intuitive

### ISSUE THREAD

**Issue by fira** [cmss13-devs/cmss13#1552]
When you are infected and nested, you are given the opportunity to ghost. 

This uses a specific combination of `can_reenter_corpse` to avoid metagaming: the relation between ghost and body is preserved, but it is flagged as non-reenterable until freed. Otherwise a captured human could ghost/reenter at will to give out information on radio, for example.

This logic is handled by the nest. The logic for `Ghost` verb is separate and does not allow this. This means if a player says no to the popup then tries to ghost on their own later, they lose the ghost-body relationship for good.

Ahelps in past year have shown a recurrent tendency for this to happen.

Observed problems can likely be explained by:
 * The player doesn't get the nest ghosting alert() or closes it by accident
 * The player does not decide to ghost when getting alert, and assume they can later
 * The player did ghost via the popup, and tries to reenter but doesn't understand why they're unable

## Proposed resolution

Ideally, ghosting in nests should be refactored to also take into account self ghosting.

Additionally, Reenter-Corpse could provide a more specific message about it.

**Comment by Huffie56** [comment]
At least we should put a warning on the pop to warn them and explain better...

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/issues/1375
similar or connected issue could be both tackle in a PR.
