### ISSUE TITLE
Cigarette boxes can't be inspected

### ISSUE THREAD

**Issue by nauticall** [cmss13-devs/cmss13#1577]
## Description

Cigarette boxes (e.g. a box of Lucky Strikes) return nothing when inspected (either with shift+click or with the verb).

## Difference between expected and actual behavior
The boxes should show their item description as does every other object in the game.

## Steps to reproduce

Just shift+click on a cigarette box. Can be any brand and variant - includes the ones in MREs.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Shows up on STUI runtimes all the time. Should be simple to fix.
