### ISSUE TITLE
Retrieve objective null reference error

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1583]
## Testmerges:

- #965

## Description

Recently while doing some light IO work I noticed this time the Retrieve tab had a null reference error:

![image](https://user-images.githubusercontent.com/964559/202182765-3faf7d83-4272-4558-970a-3ac66d8697bf.png)

## Difference between expected and actual behavior

Not to have a null error there.

## Steps to reproduce

1) Do intel
2) Periodically check Retrieve tab
3) ???
4) Null error

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
_Retrieve_ tab? I thought that we had all those fixed. \*sigh.

**Comment by Huffie56** [comment]
the differents related issues that where close on it
https://github.com/cmss13-devs/cmss13/issues/1222

**Comment by Huffie56** [comment]
the difference's PR that where merge i could found
https://github.com/cmss13-devs/cmss13/pull/1413
https://github.com/cmss13-devs/cmss13/pull/1422
https://github.com/cmss13-devs/cmss13/issues/1437

**Comment by ThePiachu** [comment]
Viewing the logs provided by Nanu, I think this narrows it down - it's fultons this time:

runtime error: Cannot read null.name
proc name: get tgui data (/datum/cm_objective/retrieve_item/fulton/get_tgui_data)
  source file: retrieve_items.dm,91
  usr: Gaius Caelus (/mob/living/carbon/human)
  src: Recover a lost fulton (/datum/cm_objective/retrieve_item/fulton)
  usr.loc: the floor (195,150,4) (/turf/open/floor/almayer)
  call stack:
Recover a lost fulton (/datum/cm_objective/retrieve_item/fulton): get tgui data()
/datum/objective_memory_interf... (/datum/objective_memory_interface): get clues(Gaius Caelus (/mob/living/carbon/human))
/datum/objective_memory_interf... (/datum/objective_memory_interface): ui data(Gaius Caelus (/mob/living/carbon/human))
/datum/tgui (/datum/tgui): get payload(null, 1, 1)
/datum/tgui (/datum/tgui): open()
/datum/objective_memory_interf... (/datum/objective_memory_interface): tgui interact(Gaius Caelus (/mob/living/carbon/human), /datum/tgui (/datum/tgui))
Gaius Caelus (/datum/mind): view objective memories(Intel Database Computer (/obj/structure/machinery/computer/view_objectives))
Intel Database Computer (/obj/structure/machinery/computer/view_objectives): attack hand(Gaius Caelus (/mob/living/carbon/human), /list (/list))
Gaius Caelus (/mob/living/carbon/human): UnarmedAttack(Intel Database Computer (/obj/structure/machinery/computer/view_objectives), 1, /list (/list))
Gaius Caelus (/mob/living/carbon/human): click adjacent(Intel Database Computer (/obj/structure/machinery/computer/view_objectives), null, /list (/list))
Gaius Caelus (/mob/living/carbon/human): do click(Intel Database Computer (/obj/structure/machinery/computer/view_objectives), the floor (195,151,4) (/turf/open/floor/almayer), "icon-x=10;icon-y=20;left=1;but...")
ThePiachu (/client): Click(Intel Database Computer (/obj/structure/machinery/computer/view_objectives), the floor (195,151,4) (/turf/open/floor/almayer), "mapwindow.map", "icon-x=10;icon-y=20;left=1;but...")
