### ISSUE TITLE
Loading OBs

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#159]
## Description
Make the process of choosing and loading OBs automated from within CIC. Even if you optimize the OB loading process, there's a timer that stops you from reloading. There's no depth to it gameplay wise(for an MT anyway), in comparison to i.e. PO, where pre loading and pre placing Powerloaders can help you to accomplish more in less time to do more missions.
a. As MT do nothing all shift except diligently wait until told to load another OB or 
b. As MT, do anything else, where you will be told to stop doing that, and come load the OB, disrupting your work
c. If you don't, CIC has to go load it. which disrupts the CIC's work and causes unnecessary friction between players/departments.
## Difference between expected and actual behavior
Loading OBs really **bugs** me.
I'd rather it not.
## Steps to reproduce
Spend a shift as MT solely waiting to load the OB and consider everything else you could be doing.
## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
#ideasguys or code it yourself
