### ISSUE TITLE
suit_jacket/really_black is honked (and can be found on Sorokyne)

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1594]
## Description

`/obj/item/clothing/under/suit_jacket/really_black` can be found in `/obj/structure/closet/wardrobe/suit`, which can be found on Sorokyne in Personal Storage area:

![image](https://user-images.githubusercontent.com/964559/202418193-15c9b6b8-c300-4649-bce3-6175897b385f.png)

## Difference between expected and actual behavior

Have proper sprite, or the item removed / changed.

## Steps to reproduce

Go to the location, open locker.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i put it up on discord in sprites section

**Comment by ThePiachu** [comment]
I did a bit of digging , and the old leaked version of CM had the original suit, not sure if it's better:

[Old Uniforms.zip](https://github.com/cmss13-devs/cmss13/files/10036883/Old.Uniforms.zip)

![image](https://user-images.githubusercontent.com/964559/202594227-6a73575b-b1b8-4e39-9781-aabb23152147.png)

I'll leave that up to the spriters.
