### ISSUE TITLE
Brig Perma Cells Lockdown button can trap you really well

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1595]
## Description

One round I was messing around with every button in the Brig and I found a way for a dumb MP to lock themselves in really well:

![image](https://user-images.githubusercontent.com/964559/202432219-472db3ff-04b4-4508-9b43-5748c9dc74d4.png)

You can press the lockdown button and get into a part of the map where you won't be able to unlock yourself from. Better yet - if there is nobody in perma they will need to bust down a wall to get you unstuck and unfuck the perma, because there is no way to enter the area otherwise:

![image](https://user-images.githubusercontent.com/964559/202432696-c8c26381-0c45-485c-a08c-68fb169219c0.png)

So a small mapping request would be to move the button somewhere else, maybe put a small wall pillar in the middle of the perma room with the button, or maybe add some release button / overwrite in the CMP's room or something.

## Difference between expected and actual behavior

You shouldn't be able to lock yourself out so well the ship would need to be deconstructed to get you out, yet here we are.

## Steps to reproduce

1) Make sure nobody is in Perma.
2) Press this button:
![image](https://user-images.githubusercontent.com/964559/202433023-0690ef7f-942b-43f0-a2c7-a31af9ec0c38.png)
3) Move north one tile as the shutters close.
4) Ask for a Synth to bring the sledgehammer to get you out.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i assume you didn't put this on discord so i will put the issue in mapper chanel.
