### ISSUE TITLE
Intel Safe LV-624

### ISSUE THREAD

**Issue by Googles-Hands** [cmss13-devs/cmss13#1609]
## Description
It gives you the objective to open a safe that doesn't exist, as far as I know there are only two safe's on LV, one in the corporate dome and one in secure storage, none in the nexus.
Either a mapping issue because of a missing safe or a code issue because it gives you the objective to open a safe that doesn't exist.

## Difference between expected and actual behavior
It gives you the objective to open a safe that doesn't exist, as far as I know there are only two safe's on LV, one in the corporate dome and one in secure storage, none in the nexus.

## Steps to reproduce
Do enough Intel-Work to get the objective "Crack open the safe, combination lock is **#|#**"
There is no such safe
Have your OCD be triggered by an unfinished intel list

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ThePiachu** [comment]
You mean the one in Command's Quarters? There is a safe there, but it's uniquely hidden, under the floorboards! ;)

**Comment by Huffie56** [comment]
> You mean the one in Command's Quarters? There is a safe there, but it's uniquely hidden, under the floorboards! ;)

didn't even know this was possible to do for mappers.... nice touch

**Comment by Googles-Hands** [comment]
Alright, nevermind then
