### ISSUE TITLE
Fiora / OBing the hive - wrong error message?

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1647]
## Testmerges:

#1556 , #1456 , #1373

## Description

Recently we played on Fiora (server time 2022-11-21 00:16:50). We got OB coordinates for the Hive at 38, 129. However, when we tried firing on the corrindates, we got the error message of "The target zone appears to be out of bounds. Please check coordinates". I got Shad0vvs to check the coordinates, and they apparently were around the Hive core, which as we understand should've given a different error message. So something is up with the OB stuff there...

We tried multiple different coordinates around that area that were given by people and nothing worked, so I don't think it was user error on the side of the people lazing it.

## Difference between expected and actual behavior

The error message should be proper if it's the Hive Core protecting Xenos than if the coordinates are in space.

## Steps to reproduce

1) Target Hive core with an OB
2) Try firing
3) Get a wrong error message?

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Do you have any other reference coords for the round ?
I'm afraid otherwise we don't log the obfuscated x/y so these are useless :\

**Comment by ThePiachu** [comment]
Lets see, the round was around Server Time 2022-11-21 00:30, and the various coordinates we tried were:

- 77, 531
- 38, 129
- -37, 129
- 38, 135
- 35, 123
- 43, 140

Shad0vvs teleported to 38, 129 I think around server time 1:11 if that helps.

I also have a recording of the round as an SO if you'd like, but I don't think I have a clear view of anyone lazing coordinates to cross-reference...

Do we log where the OBs were attempted to be fired? If not it might be good to track that, along with the initial coordinate obfuscation at roundstart...

**Comment by fira** [comment]
No the logs are only for the effective firing, post-targeting and post deobfuscation, if memory serves

Tracking the obfuscated coordinates can be useful, or at least simply a way to have them at all without using View Global Variables stopping the whole game to a halt for 30 seconds

**Comment by Huffie56** [comment]
same of the other OB issue i think those have been fixed as we don't have anyone bring it up and it hasn't been reproduce...

**Comment by morrowwolf** [comment]
No repro and old as hell.
