### ISSUE TITLE
Sorted vendor doesn't sort some items too well

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1659]
## Testmerges:

#1650

## Description

While working on #1650 I noticed the sorted vendor sorted some items a bit oddly. First, some special ammo gets sorted below its ammo boxes (should be the other way around if it's to follow how other ammo is sorted):

![image](https://user-images.githubusercontent.com/964559/203162093-1f5b994c-11a0-49d4-9537-46bc16ecb9b4.png)

Then, a lot of the grenades, their packets and their boxes get sorted all over the place:

![image](https://user-images.githubusercontent.com/964559/203162229-4f5c27e5-bb40-42ef-9b7e-6971a07d0810.png)

I think they are just sorted alphabetically, might be better if they got sorted like ammo boxes (perhaps it should go grenades > packets > boxes).

## Difference between expected and actual behavior

The sorted vendor should handle those items a bit better.

## Steps to reproduce

1) Use #1650
2) Go to Requisitions vendors
3) See for yourself

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/1759
this is the PR related that as been merged.
need to test if it's still relevant...

**Comment by Huffie56** [comment]
![image](https://user-images.githubusercontent.com/117036822/236616119-0a4ca446-9eb1-4fa8-883a-a5f7a2e39efd.png)
![image](https://user-images.githubusercontent.com/117036822/236616135-219c9682-1dbc-42c9-84b3-380062a1aae7.png)
@ItsVyzo this bug as been fixed all the sorting is way better.
you can close this issue thanks.
