### ISSUE TITLE
uncloaked GUI element

### ISSUE THREAD

**Issue by LynxSolstice** [cmss13-devs/cmss13#1665]
## Description
While cloaked, the interaction circle (blue one) is not cloaked.

## Difference between expected and actual behavior
Every other GUI element from a player character is cloaked except for the interaction circle.

## Steps to reproduce
go into cloak, hold laser designator and designate a spot.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Heya, just a heads up, you have to delete the space between the [ and ] so it looks like this: [x] instead of [ x ] for the issue bingo to work properly.

**Comment by LynxSolstice** [comment]
Just a head's up, the red circle also shows up uncloaked.

**Comment by Segrain** [comment]
Closed by #2456. Github is picky about how specific you have to word your PR for it to autolink as closing.
