### ISSUE TITLE
New escape pod tgui doesn't replace old ui

### ISSUE THREAD

**Issue by Googles-Hands** [cmss13-devs/cmss13#1673]
## Description
The new escape pod control tgui made here: #1176 doesn't actually replace the old UI, it just layers over it, though the old UI isn't what it was anymore either. I've made a screenshot

![pod issue](https://user-images.githubusercontent.com/59937074/203434433-99779c7f-bd6e-42d8-9836-19cd05e82272.png)
(I know I probably should have made a recording and moved the new ui, but trust me, at least for me it happens every time)

## Difference between expected and actual behavior
It should just get rid of the old UI box entirely, no?

## Steps to reproduce
Go into an escape pod and click on the pod control panel

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/1176
The merge that change to TGUI
