### ISSUE TITLE
WO story announcement spelling error

### ISSUE THREAD

**Issue by Googles-Hands** [cmss13-devs/cmss13#1682]
## Description
In the fifth story announcement of WO, the one by Major Ike Saker there is a spelling mistake.
Though I have another issue with it, Captain Naiche is the CO of all marine forces on LV and a Major, who outranks him, suddenly speaking to us is weird, lorewise it doesn't make sense either since only the Dust Raiders were sent to the Tychon's Rift, the Falling Falcons are nowhere nearby, so I am additionaly providing a new announcement.

### Spelling Error:
Announcement as is:
Major Ike Saker speaking, The Captain is still trying to try and get off world contact. An engineer platoon managed to destroy the main entrance into this valley this should give you a short break while the aliens find another way in. **I have also received word that the 2nd 'Falling Falcons' Battalion. Should be near. I used to be stationed with them, they are top notch!**

The highlited area should be a single sentence like so: **I have also received word that the 2nd 'Falling Falcons' Battalion should be nearby. I used to be stationed with them, they are top notch!**

### Lore friendly revision:
First Lieutenant Ike Saker, Executive Officer of the Captain, speaking. The Captain is still trying to try and get off world contact. An engineer platoon managed to destroy the main entrance into this valley this should give you a short break while the aliens find another way in. I have also received word that marines from an overrun Outpost are evacuating to you and will help you. I used to be stationed with them, they are top notch!

## Steps to reproduce
Survive until the announcement plays on WO

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
This is an easy fix even if you don't know coding just go to the file: https://github.com/cmss13-devs/cmss13/blob/master/code/game/gamemodes/colonialmarines/whiskey_outpost/whiskey_output_waves.dm

1-click on the pencil icon 
2-go to line 341 and change the text.
3- go to the bottom and fill the field as required
4-click propose change.
5-click pull request in green.
6-Fill the PR as best as you can as a draft and @ me if needed

I could do this fix but i rather see someone that can spot spelling error being able to propose PR on is own.
If you don't want to make the PR just reply to this message.
Thanks for your contribution.

**Comment by Googles-Hands** [comment]
I suppose I could, but which should I PR, the simple spelling mistake or the lore-revision?
If it needs input from lore maintainers or whatever they are called I have no way to notify them as I am temporarily banned from the discord.

**Comment by Huffie56** [comment]
> I suppose I could, but which should I PR, the simple spelling mistake or the lore-revision? If it needs input from lore maintainers or whatever they are called I have no way to notify them as I am temporarily banned from the discord.

I can't tell you wish is best i guess if lore team don't respond just do the PR for spelling mistake...
i will put a link to the issue on lore channel on discord for you i guess...
If you have other spelling or lore revision to do just make them in same PR.
It's easier to have one bigger PR with same scope than 5-10....
