### ISSUE TITLE
Crystalizing Chems randomly give bionic vision to PO/DPs

### ISSUE THREAD

**Issue by FGRSentinel** [cmss13-devs/cmss13#1694]
## Description
More or less exactly what it says. A crystalizing chem put into a camera matrix will cause the PO using the weapon console to retain the extended vision range at random.

## Difference between expected and actual behavior
The vision range should go back to normal when not using the camera. As a PO told me last round, when they used the weapons console's cameras and left the view, they would retain the extended range. With Crystalizing 4, the level that specific chem was apparently at, this gave them an extra two tiles of vision in every direction. Every time they used the cameras, there was a chance their vision would retain the extended range, revert back to its normal range, or remain the same.

## Steps to reproduce
1. Make a chem in research with the crystalizing property. I'm not sure if the actual level matters or not, but the effect was confirmed with Crystalizing 4.
2. Insert a matrix with this chem into the dropship's weapon console.
3. Using an object in the hangar as a reference point, launch for CAS and use the cameras until the vision range appears to remain at the larger range. Check against the reference object. If you're able to test on a private server, spawning an object in space just at the edge of the PO's vision range before starting the tests will likely make this easier.

## Issue bingo (not required to be all checked)
- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Unknownity** [comment]
Issue occurs when the user is automatically ejected from the camera view, it does not occur if they manually exit.
