### ISSUE TITLE
Cannot move marines from operating table in the APC as xeno

### ISSUE THREAD

**Issue by Faunenschnitt** [cmss13-devs/cmss13#17]
Description
I tried to cap a marine who was on an operating table in the apc. I assume that surgery was performed on the marine. I could not grab the marine to capture it. Slashing was possible. It is not possible to destroy the operating table as xeno, cause it is resistent to acid and slashes. Asking an admin to remove the operating table allowed me to capture the marine,

Difference between expected and actual behavior
I can either grab the marine and capture it or I need to be able to destroy the operating table.

Steps to reproduce
Perform surgery on a marine on an operating table in the apc. Try to grab and capture it as xeno.

Specific information for locating
Operating tables in APC

Length of time in which bug has been known to occur
I dont know

**Comment by realforest2001** [comment]
This is obsolete now as APC no longer has surgery.
