### ISSUE TITLE
Praetorian Strains giving Runner Blood components

### ISSUE THREAD

**Issue by Diegoflores31** [cmss13-devs/cmss13#170]
## Description

Praetorians with strains give only Acidic blood and cathetomine plasma instead of dark acidic blood 

## Difference between expected and actual behavior

even if its a strain change the main component of their blood should not change . also it gives them no repercution from diying because their blood will be useless in research

## Steps to reproduce

extract praetorian strains blood and realize its the same as a runner

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Kiara-Miller** [comment]
Unable to reproduce ingame, as of right now.

/datum/reagent/blood/xeno_blood/royal
	name = "Dark Acidic Blood"
	id = "xenobloodroyal"

![image](https://user-images.githubusercontent.com/115281303/195100610-71057ea6-d3e8-4b5f-acee-42bb4a560285.png)
