### ISSUE TITLE
Doors on Almayer are missing hazard markings

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1708]
## Description

A number of floors beneath various doors on Almayer don't have hazard markings and they should:

![image](https://user-images.githubusercontent.com/964559/204072515-3c79087e-4044-4091-a84f-9b6fbeff4933.png)

![image](https://user-images.githubusercontent.com/964559/204072509-409135cc-6c0f-41e8-a6e7-6f472f5e37a2.png)

![image](https://user-images.githubusercontent.com/964559/204072504-4e29ed52-6c40-4698-b847-87d49470696f.png)

Last one is also related to issue: #1699

## Difference between expected and actual behavior

Doors should have hazard markings beneath them, but they don't.

## Steps to reproduce

Check around Almayer.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Googles-Hands** [comment]
Just so you know, at the doors related to my Issue, there is a second hazard marking, it's on the tile under the window, the decals are all right in place, the window/door placement just got goofed up.
