### ISSUE TITLE
Xenomorph Minor Victory doesn't get triggered

### ISSUE THREAD

**Issue by Googles-Hands** [cmss13-devs/cmss13#1727]
## Description
When the conditions for a Xenomorph Minor Victory are met, they don't register, still counting as a Xenomorph Major Victory.
## Difference between expected and actual behavior
The situation is this: Xenomorphs crash into the Almayer and the marines decide to evacuate, and they do so successfully (pods and lifeboats launch + a few extra minutes until ARES declares a "complete evacuation") and the round doesn't end before this happens.

Now, after all that, if the round ends by all the remaining marines being dead, it still declares it a Xenomorph Major Victory, when it should be a minor one. It should only be a major victory if all marines die before the "complete evacuation" alert I've described above sounds or if the Queen stops the evacuation alltogether.

It SHOULD register as a Xenomorph Minor as soon as the "evacuation confirmed" announcement plays and there are living marines on the lifeboats, as if all surviving marines evacuated, the round would end immediately, and the correct round end result would be a Xenomorph Minor.
## Steps to reproduce
1. Have Xenomorphs crash into the Almayer and evacuate.
2. Survive the ten minutes required until the pods/lifeboats launch.
3. Wait a few more minutes until ARES declares, "evacuation complete"
4. Check the round end statistics
## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
Are you referring to this ?
The Infestation Gamemode (Default game mode in CM) previously has 5 victory conditions. Marine Major Victory is total eradication of the Aliens, and Marine Minor Victory is when the Hive has no queen for 20 minutes. Alien Major Victory is the complete eradication of the Marines, and Alien Minor Victory is when the entire crew of the Sulaco has successfully evacuated from alien infestation. And Planetary Eradication, where both sides are eradicated.
https://cm-ss13.com/wiki/History

**Comment by Googles-Hands** [comment]
I am referencing this line of code:

if(EvacuationAuthority.dest_status < NUKE_EXPLOSION_IN_PROGRESS) //If the nuke ISN'T in progress. We do not want to end the round before it detonates.
		if(!num_humans && num_xenos) //No humans remain alive.
			round_finished = MODE_INFESTATION_X_MAJOR //Evacuation did not take place. Everyone died.
		else if(num_humans && !num_xenos)
			if(SSticker.mode && SSticker.mode.is_in_endgame)
				round_finished = MODE_INFESTATION_X_MINOR //Evacuation successfully took place.

This is from: code/game/gamemodes/colonialmarines/colonialmarines.dm starting at line 240
If the code is outdated, I suppose updating it to count this properly, since the marine minor victory is working in the code as well. Like I suggested, if the lifeboats launch it should be a Xenomorph minor, after all the queen can disable the lifeboats.

**Comment by Googles-Hands** [comment]
Ah, I also just realised that if marines survive past the 30 minutes (I think it was 30) of hijack, a Xenomorph Minor also gets triggered. Addind a Xeno Minor condition to evacuating allows confident CO's to think they can get a Xeno Minor by clearing/holding the Almayer and CO's that don't think they can survive an onslaught to get it via holding lifeboats for 10 minutes.

**Comment by ItsVyzo** [comment]
Major/Minor victory system is no longer in use.
