### ISSUE TITLE
Tequila Sunrise is invisible.

### ISSUE THREAD

**Issue by SexmasterWasTaken** [cmss13-devs/cmss13#1733]
## Description
Tequila Sunrise sprite is gone.

Also as a sidenote you can't feed xenos drinks, very sad.
## Difference between expected and actual behavior
No Tequila sunrise sprite, there should be.

## Steps to reproduce
Step 1. Attempt to make Tequila Sunrise
Step 2. Watch in awe as it disappears from your hand (no sprite)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by moltoretardo** [comment]
I feast on these type of issues
