### ISSUE TITLE
Mortar shell doesn't explode out and on a rack

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#1737]
## Description

when you flame a mortar shell it doesn't explode

## Difference between expected and actual behavior

the mortar shell should explode like ammo

![image](https://user-images.githubusercontent.com/117036822/204134382-33e577b7-54e0-4089-b59b-f39a8807bc7f.png)

## Steps to reproduce

1-flame them
2-wait and see that nothing explode

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DylonBR** [comment]
do shells even explode outside of racks?
![shell](https://user-images.githubusercontent.com/95513530/204184709-5b1d17da-7bc1-451f-bfa6-1f269f9b6f5c.png)
this was just last round

**Comment by Huffie56** [comment]
> do shells even explode outside of racks? ![shell](https://user-images.githubusercontent.com/95513530/204184709-5b1d17da-7bc1-451f-bfa6-1f269f9b6f5c.png) this was just last round

they normally do i did order mortar shell via req and flame them they explode instant.
your picture confirm their is something wrong not just with rack....
maybe OB fire don't trigger explosion?

**Comment by Huffie56** [comment]
Updating because i did retest the mortar shell being flame and they don't explode when expose to fire.
Still a bug or an inconsistency.

**Comment by SexmasterWasTaken** [comment]
From what I could tell after looking through the code, this was never coded. Not sure if it's oversight or intended, will ask and update.

**Comment by SexmasterWasTaken** [comment]
Just messaged Stan, said it was intended as the code for it was never written.
