### ISSUE TITLE
WY Corporate Security Goons are considered hostile by turrets/MD's

### ISSUE THREAD

**Issue by MusselMain** [cmss13-devs/cmss13#1742]
Testmerges:
Weyland-Yutani Corporate Security Goons by Geevies

Description:
The WY Corporate Goons Survivor spawn on LV-624 strangely enough isn't found under the Survivors section, and is instead located in the Human section, which (I think) causes them to show up as hostile on Motion Detectors, as well as turrets. I understand they are supposed to be considered Officers serving on a WY colony, but this doesn't seem intended, as turrets don't fire on other Survivors, and MD's work fine for other survivors. (I also just heard that this might extend as far as the Role's wallet as well, no money, although it was one new player, so I cannot confirm)

Steps to reproduce:
1. Play a map as WY Corporate Security (or Goon) survivor
2. realize they're considered Humans, and not survivors on the follow tab
3. constantly be bothered as you try to use a Motion Detector to locate Xenomorphs, and can't as you're constantly setting it off yourself, as well as getting mowed down by turrets, which consider you a target.

**Comment by Misttyy** [comment]
[https://github.com/cmss13-devs/cmss13/pull/1777](url)

Not the hardest job, but a quick fix.

**Comment by Misttyy** [comment]
Unfortunately I can't get sprites to work with adding them - may end up closing if I can't fix it.
