### ISSUE TITLE
Burning Xeno Bodies Emit Light After Extinguished

### ISSUE THREAD

**Issue by IsProbablyCatto** [cmss13-devs/cmss13#175]
## Description
While a once burning warrior body was dragged and extinguished, it still emitted light around it.

## Difference between expected and actual behavior
It should emit light when burning, then not when when extinguished. It emits light always.

## Steps to reproduce

1. Burn the xeno
2. Pat out the xeno corpse
3. Notice the light difference

## Issue bingo (not required to be all checked)
- [unsure] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Confirmed, if you kill an XENO via fire, the body will stay as a light source even after being extinguished.  (Just tested)
If you kill it with bullets, it doesn't.
