### ISSUE TITLE
Broken Research Stuff

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#1770]
thought I'd leave another couple of bugs, maybe some people can use it to farm some good boy points

-Centrifuge : You use this to label custom autoinjectors, but some characters cause the labels to break, like /
-Turing : making it bottle to smartfridge then unanchoring and dragging the fridge out of range breaks the Turing forever
-Synthesis : New bug, having a relate paper inserted locks all other operations until the relate paper is ejected
-Synthesis : mashing finalize after performing an operation still lets you skip reagent picking and produce two-reagent recipes
-Synthesis : In relate mode, you can click another property on the relate chemical to cancel out of the reagent picking screen
-Synthesis : the machine itself can be slashed 3 times and deleted, apparently an oversight
-Botany : shovel still does not work, it should let you quickly remove plants from trays but atm it does nothing. Removing plants from trays must be done by right clicking and flushing trays one by one
-Botany : backpack sprayer worthless, it consumes 50u per spray no matter what setting you leave it on and only transfers 2u to trays it hits
-Botany : weeds, pests, no food, no water etc don't matter at all for single harvest plants (after gene modifying), the plant matures before the damage kills the plant and harvests aren't affected by plant health.

**Comment by Weuyn** [comment]
another one:
- Botany : using wirecutters on a plant to get anseed is supposed to have a chance to reduce the growth a bit, but this is flipped and it increases growth instead

**Comment by Diegoflores31** [comment]
Another one : 
DDI found on synthesis papers cannot be scanned and doesnt proc the PMC team as intended

**Comment by Segrain** [comment]
It is... _complicated_, to put it simply. But less in a "bug" sense and more in a "desperately needs a rewrite" sense. One day^tm.

**Comment by Unknownity** [comment]
> Another one : DDI found on synthesis papers cannot be scanned and doesnt proc the PMC team as intended

any synthesis paper obtained from buying them is already treated as discovered, that's why it won't proc.
This is intended otherwise you could potentially be able to get PMCs infinitely

**Comment by Weuyn** [comment]
another one:
Reagents : at some point, all OT properties broke and started causing mixtures to explode when mixed above OD thresholds. This used to just be the case for the Explosive property. This bug includes Hyperthermic, Viscous, Flowing, Oxidising, Fueling, any OT property.

**Comment by Diegoflores31** [comment]
> > Another one : DDI found on synthesis papers cannot be scanned and doesnt proc the PMC team as intended
> 
> any synthesis paper obtained from buying them is already treated as discovered, that's why it won't proc. This is intended otherwise you could potentially be able to get PMCs infinitely

Not really since you can only discover DDI once

**Comment by Unknownity** [comment]
> > > Another one : DDI found on synthesis papers cannot be scanned and doesnt proc the PMC team as intended
> > 
> > 
> > any synthesis paper obtained from buying them is already treated as discovered, that's why it won't proc. This is intended otherwise you could potentially be able to get PMCs infinitely
> 
> Not really since you can only discover DDI once

False, you can trigger the PMCs multiple times if you find DDI more than once (from the colony of course)

**Comment by Diegoflores31** [comment]
> > > > Another one : DDI found on synthesis papers cannot be scanned and doesnt proc the PMC team as intended
> > > 
> > > 
> > > any synthesis paper obtained from buying them is already treated as discovered, that's why it won't proc. This is intended otherwise you could potentially be able to get PMCs infinitely
> > 
> > 
> > Not really since you can only discover DDI once
> 
> False, you can trigger the PMCs multiple times if you find DDI more than once (from the colony of course) (and that the property has to be in a different chemical) This can occur in regular playthroughs as it did for me like 2-3 times total.

Thats a bug . You can even get multiple PMCs with the same chem since there seems to be a problem with DDI and synthesis example i have seen some times that synthesis wont give you the traits even after scanning them. 

Anywyas pmcs are just there to take away your fun so i guess multiple is at most hilarious but not usually game breaking ( unless they kill everyone)

**Comment by Diegoflores31** [comment]
Plus buying papers its so comically expensive that i donr see why you should not get pmcs on a RNG lvl 4 (14 credits) paper

**Comment by kiVts** [comment]
Okay I thought this was fixed but no, you can set rare/rare/rare and get very cheap chem, then START and THEN change the complexity to basic basic basic. This allows to create basic/basic/basic for uh, 15 credits and with comically overpowered potencies. you can also change the potencies/OD same way. very abuseable and very funny

**Comment by DylonBR** [comment]
> Okay I thought this was fixed but no, you can set rare/rare/rare and get very cheap chem, then START and THEN change the complexity to basic basic basic. This allows to create basic/basic/basic for uh, 15 credits and with comically overpowered potencies. you can also change the potencies/OD same way. very abuseable and very funny

this trick does not work and I don't think ever worked. It still takes away the correct ammount of credits if you change the properties unless theres something I'm missing.

**Comment by kiVts** [comment]
> > Okay I thought this was fixed but no, you can set rare/rare/rare and get very cheap chem, then START and THEN change the complexity to basic basic basic. This allows to create basic/basic/basic for uh, 15 credits and with comically overpowered potencies. you can also change the potencies/OD same way. very abuseable and very funny
> 
> this trick does not work and I don't think ever worked. It still takes away the correct ammount of credits if you change the properties unless theres something I'm missing.

Did this ever worked? Yes it did, it will take the correct amount of money but if you are poor you can go into negative(obviously without actually going into negative debt)

**Comment by Herotitan772** [comment]
> > > Another one : DDI found on synthesis papers cannot be scanned and doesnt proc the PMC team as intended
> > 
> > 
> > any synthesis paper obtained from buying them is already treated as discovered, that's why it won't proc. This is intended otherwise you could potentially be able to get PMCs infinitely
> 
> Not really since you can only discover DDI once

not true! you can get multiple chem response teams

**Comment by Huffie56** [comment]
this is really bad written issue. you shouldn't have 8 issue into one how are we suppose to fallow anything this way?

**Comment by Huffie56** [comment]
spade is just a small shovel as you can see in the code.
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/08922e26-9453-468a-aac2-6c2d5e80a157)
their is no intend in the code to give it a role to botany it's just here to decorate i guess...
feel free to make a suggestion it's not a bug that it can remove plants from hydroponic.

**Comment by Huffie56** [comment]
plant will get damage and will die if their is no water or that the weed took over the tray...
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/8178d2ad-9d3c-4f32-872d-6477f97b462e)
didn't find where is the part killing the plant via weed sadly...
but lacking nutriment doesn't kill your plant. so going to make an issue for that.

**Comment by Diegoflores31** [comment]
> plant will get damage and will die if their is no water or that the weed took over the tray... ![image](https://user-images.githubusercontent.com/117036822/239558016-8178d2ad-9d3c-4f32-872d-6477f97b462e.png) didn't find where is the part killing the plant via weed or pest sadly... but lacking nutriment doesn't kill your plant. so going to make an issue for that.

Weed does work . Tested ingame

**Comment by Diegoflores31** [comment]
> spade is just a small shovel as you can see in the code. ![image](https://user-images.githubusercontent.com/117036822/239551456-08922e26-9453-468a-aac2-6c2d5e80a157.png) their is no intend in the code to give it a role to botany it's just here to decorate i guess... feel free to make a suggestion it's not a bug that it can remove plants from hydroponic.

It should remove plants from botany . Code for it is somewhere else i think

**Comment by kiVts** [comment]
XRF: if player A places vial in XRF, and player B takes it out when Player A still has do_after going, the XRF will break forever. only admin help, sadge
