### ISSUE TITLE
Pouncing as runner doesn't toggle hide icon state

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#1784]
### Testmerges

N/A

### Description of the bug

Hiding and then pouncing as a runner does not remove the outline from the hide ability.

### What's the difference with what should have happened?

When pouncing while hidden, the outline around the hide ability should be removed to accurately reflect that you are no longer hidden.

### How do we reproduce this bug?

1. Be runner.
2. Hide.
3. Pounce.
4. Notice Hide still has the "activated" outline around it.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Aracino** [comment]
I believe this is occurring for all instances of pounce. I've seen a similar issue with Facehuggers.

**Comment by Huffie56** [comment]
i think i will have a  go at this since a PR as already been made

**Comment by Drulikar** [comment]
Patch to resolve this @Huffie56 is 
[patch.diff.txt](https://github.com/cmss13-devs/cmss13/files/11413625/patch.diff.txt)
See https://git-scm.com/docs/git-apply on how to apply a patch in your git client. Otherwise just open the file and you will see the 3 new lines and where.

**Comment by Huffie56** [comment]
> Patch to resolve this @Huffie56 is [patch.diff.txt](https://github.com/cmss13-devs/cmss13/files/11413625/patch.diff.txt) See https://git-scm.com/docs/git-apply (e.g. `git apply PATH_TO_PATCH_FILE`) on how to apply a patch in your git client. Otherwise just open the file and you will see the 3 new lines and where.

so i tried to paste the code you give but it didn't work.
if you want to make the PR yourself i am all for it... as i have no idea on how to fix it....
