### ISSUE TITLE
light floors do not work

### ISSUE THREAD

**Issue by Unknownity** [cmss13-devs/cmss13#1799]
### Testmerges

N/A

### Description of the bug

Light floor tiles do not work as intended,
trying to install them to the plating will not actually install them and you would be wasting the tile you have.
Another issue related to them is that if they are installed on the floor, they are turned off when they shouldn't be.

### What's the difference with what should have happened?

you should be able to install light floors on the plating and they should be turned on when installed.

### How do we reproduce this bug?

make light floor tile, try to install it on plating

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by moltoretardo** [comment]
I think they have been broken for 6 months
