### ISSUE TITLE
Left click only works on some things in interface

### ISSUE THREAD

**Issue by Commissar12** [cmss13-devs/cmss13#183]
## Description
Able to left click to use items held in hands, but left click can not move items in inventory or pick up/interact with stuff on tiles such as vending machines or food.

## Difference between expected and actual behavior
I've been playing on the SS13 CM server to some time now and have never had any technical issues. Then after launching into my first round today, I started having this issue and wasn't able to fix it despite the advice of some players. Fix interface, relaunching the game, closing other programs on my computer, didn't work.

## Steps to reproduce
I have no idea what has resulted in this bug affecting me.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
do you have the last version of byond ?

**Comment by MidwayAtom** [comment]
Closing due to isolated incident.
