### ISSUE TITLE
Some Camera Console Issues

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#1837]
### Testmerges

Longstanding issues

### Description of the bug

1. After opening a cam console, it never closes afaik so for example if you open the console and set it to CIC, you could watch the CIC from afar without actually needing a console. Power being out or the console breaking might break the screen as I've never tested this, however......

2. While cam console window is open, cameras are unbreakable. They CAN be broken and become glitchy, but for example I was watching the DS cams, and xenos were hijacking big time and had destroyed cams- marines beat them back, but much later they returned to hijack again. Because I never closed the console, I was able to call out the queen's location by watching via the cockpit's cams out of its windows. Later on I tried swapping to a different cam and back, and this properly completely broke the camera view

3. While watching APC exterior cams, walking away from the console breaks its view- the APC will drive off, leaving the view behind. You can use this to essentially spawn a permanent & invisible camera view anywhere you want presumably.

### What's the difference with what should have happened?

1. Cam window should force close when its home console is outside the player mob's view

2. While watching cams, if a xeno breaks its camera, console's view should force refresh to break the view. 

3. Not ONLY should the camera stay with the APC, I'd strongly argue exterior APC cams should use an actual camera- that way APC crew who are clever/have a supporting MT can watch exterior cams to help them LISTEN to people talking or screaming outside.

### How do we reproduce this bug?

So I often install Security Camera Consoles inside the APC. Why? Because it gives access to Interior/Exterior APC cams. Why in the world would you want that, you have a window? Because while driving, gunning, manning gun doors, or acting as dedicated Medic, you can keep a Cam open- people speaking inside have their text appear above their head so it helps to differentiate people talking to you inside the APC vs tons of radio chatter, or watch inside in general while driving, or if you're dedicated medic you can watch outside while continuing to treat people inside, in case there's an emergency you need to deal with outside. Normally idgaf about cameras but this is how I realized the issues, so it's possible they may not occur for whatever reason on consoles Almayer side.

1. Open cam console. Set to a camera. Walk as far away as you want. Never closes.
2. Watch camera(perhaps specifically DS cockpit one?) and break said camera- becomes glitchy but not unwatchable until you swap cams or close and open the console.
3. Watch exterior APC cams. Walk away. Oh god oh fuck where is the APC going
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
Also funny mortar camera bug, you can lase coords or CAS laser from camera console

**Comment by nuklearcellphoneg** [comment]
Well, as an aside, like... let's say you're watching the Interior APC cams from the Interior of the APC. You can fully control your character, point, and most but not all other things from inside that view.

**Comment by ItsVyzo** [comment]
![image](https://user-images.githubusercontent.com/46250991/235365142-9635d6bc-8aa4-40e0-b3e6-c33267cff71c.png)


Actually intended

APC no longer in use - redundant
