### ISSUE TITLE
When Spotter Designator broke while zoomed in, vision remains zoomed. Forever.

### ISSUE THREAD

**Issue by rudew** [cmss13-devs/cmss13#1884]
### Testmerges

#1760 #1841 #955 #1707

### Description of the bug

I got CAS'ed, which broke my Spotters Designator, which was in my left hand at the time. After which, regardless of looking through new binoculars, blinding myself, or ghosting and being put back into my body, my vision remained zoomed. Whenever I was ghosted, however, the vision was not zoomed, meaning it was probably attached to the body itself.

### What's the difference with what should have happened?

My binoculars breaking should not force me into being forever zoomed.

### How do we reproduce this bug?

1. Hold binoculars, maybe specifically the spotters variety.
2. Have them break while you are holding them, maybe specifically in the left hand, maybe specifically from CAS, but likely any explosion.
3. Voila, I guess?

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Probably fixed in #3079

**Comment by ItsVyzo** [comment]
Not fixed

**Comment by ItsVyzo** [comment]
Duplicate #266
