### ISSUE TITLE
Item ghost duplication

### ISSUE THREAD

**Issue by Firecharge123** [cmss13-devs/cmss13#1885]
### Testmerges

#1760, #1841, #955, #1707

### Description of the bug

Putting an item on a table or rack and alt+clicking will leave a 'ghost' of the item that was on the table
This has been an issue for a long time but held no major issue, however recently has become a abused issue.
makes issues like: 
![image](https://user-images.githubusercontent.com/110747929/206353805-7d1638c1-dbac-4027-97a5-35af9046bf84.png)

### What's the difference with what should have happened?

Items should NOT leave a ghost on where they have been left

### How do we reproduce this bug?

1.place item on table rack etc
2.alt click it

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by moltoretardo** [comment]
CM tables are so weird compared to other codebases, is there any reason why they're weird like that, lagless?

**Comment by harryob** [comment]
> @moltoretardo: CM tables are so weird compared to other codebases, is there any reason why they're weird like that, lagless?

that was the intent but we’re 90% sure it doesn’t do much

**Comment by Diegoflores31** [comment]
> CM tables are so weird compared to other codebases, is there any reason why they're weird like that, lagless?

pretty sure it was because "performance" but i think it did nothing

**Comment by ItsVyzo** [comment]
Duplicate
#2080
