### ISSUE TITLE
Duplicated Announcements/Bioscans (x2-3)

### ISSUE THREAD

**Issue by MidwayAtom** [cmss13-devs/cmss13#1888]
### Testmerges

#1760 #1841 #955 #1707

### Description of the bug

A broadcast from either ARES or the acting CO via the images shown broadcast not only once but several times. It is not everytime however, it is on different occasions however common enough to warrant a bug report. 

Examples:
https://i.imgur.com/ecDt8gB.png
https://i.imgur.com/u8HLzzn.png
https://i.imgur.com/OP89RWt.png

### What's the difference with what should have happened?

It should broadcast once. It broadcasts up to possibly 6 has been witnessed.

### How do we reproduce this bug?

Unknown on how to duplicate. Witnessed several times over past missions. Attend and you should see at least once incident. 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Does this still happen? @MidwayAtom

**Comment by Huffie56** [comment]
@ItsVyzo and @usnpeepoo could you tag this with need reproducing please

**Comment by Huffie56** [comment]
didn't experience of it in a while and forest worked on bioscan so i am sure he fixed it....
