### ISSUE TITLE
Xeno handlefire runtime

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1897]
### Testmerges

1760, 1841, 955, 1707

### Description of the bug

```
runtime error: Cannot read null.fire_smothering_strength
proc name: handle fire (/mob/living/proc/handle_fire)
  source file: living_defense.dm,189
  usr: null
  src: Mature Hivelord (KAT-523) (/mob/living/carbon/Xenomorph/Hivelord)
  src.loc: the concrete (55,135,3) (/turf/open/asphalt/cement)
  call stack:
Mature Hivelord (KAT-523) (/mob/living/carbon/Xenomorph/Hivelord): handle fire()
Mature Hivelord (KAT-523) (/mob/living/carbon/Xenomorph/Hivelord): Life(2)
Mature Hivelord (KAT-523) (/mob/living/carbon/Xenomorph/Hivelord): Life(2)
Xeno Life (/datum/controller/subsystem/xeno): fire(0)
Xeno Life (/datum/controller/subsystem/xeno): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

### What's the difference with what should have happened?

Not runtime

### How do we reproduce this bug?

???

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by moltoretardo** [comment]
So that happened when a xeno tried to pat fire? would it be because the fire extinguished as the xeno was tapping it?

**Comment by moltoretardo** [comment]
Or is it when a xeno was set on fire my brain is too small to read logs

**Comment by ThePiachu** [comment]
Looking at the code (living_defense.dm,189), it's the weather smothering fire:

```
	if(current_weather_effect_type)
		adjust_fire_stacks(-SSweather.weather_event_instance.fire_smothering_strength, min_stacks = 0)
```

@kugamo I think that's one of yours.
