### ISSUE TITLE
Inconsitent/Coding 

### ISSUE THREAD

**Issue by Maxim-inc** [cmss13-devs/cmss13#194]
## Difference between expected and actual behavior

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Maxim-inc** [comment]
Ok so for some reason it didn't show up, great.

**Comment by Shad0vvs** [comment]
> Ok so for some reason it didn't show up, great.

You can edit your initial post by clicking the 3 dots in the top right corner.

**Comment by Maxim-inc** [comment]
> > Ok so for some reason it didn't show up, great.
> 
> You can edit your initial post by clicking the 3 dots in the top right corner.

I don't know what I'm doing wrong but here is my post.

Description
Cardboard Matchbooks don't fit inside the helmet. Something irl the same size or smaller than a Zippo Lighter

Difference between expected and actual behavior
its somehow too bit to fit into the helmet, it should fit into the helmet or cigarette pack

Steps to reproduce
attempt to put matchbook into helmet and fail
