### ISSUE TITLE
Getting Queen roll roundstart glitches out if you don't pick a hivespawn within a certain time?

### ISSUE THREAD

**Issue by ThiccFucc** [cmss13-devs/cmss13#1985]
### Testmerges

#1765, #955, #1908. Not sure if any of them are causing the issue.

### Description of the bug

Got queen at roundstart. Got the usual prompt to choose a starting hive location to spawn. Tabbed in I think 1-2 minutes after roundstart, chose a starting location. The menu dissapeared, I was stuck on the Lobby Art, but physically in the world. Wasn't a ghost. Had an empty human inventory. Couldn't move.
Happened twice now, both times I had to ghost and then rejoin round by autospawning as larva. The menu to join the game or observe also dissapears, since it considers me "in the game." Speaking to admins, they say a queen is shown to have spawned, not freemob. However, the queens that take over always evo'd into it, so I don't know where I went as queen.

### What's the difference with what should have happened?

After choosing a location, you should spawn into the world planetside as a young queen at the location. 

### How do we reproduce this bug?

1.Queue up for queen on high
2.Get queen, you'll know when you obtain the prompt to "choose a start hive location" with a menu of different places on the given map.
3.I don't know what's going wrong after. Maybe just wait a minute or two after roundstart before choosing a location? Or maybe it's because a larva evolves into queen before you load in? If queen spawns in late, roundstart larva see that the queen has no hive, no compass.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
thats prob because when you get the stuff you are spawned as a human or something and then spawned into an actual queen body. in gamemodes like Greenshift you used to be able to spawn as a humanized queen if you dared to roll it during the event

**Comment by Diegoflores31** [comment]
not caused by any of the TMs . pretty sure this is a bug that has been going for quite a time
