### ISSUE TITLE
Performance issues with Fire effects

### ISSUE THREAD

**Issue by Diegoflores31** [cmss13-devs/cmss13#1988]
### Testmerges

unrelated

### Description of the bug

Fire effect when done in excess completely obliterates client´s FPS. for example OBs or excesive mortar can lag you client heavily if you have enought tiles of it on your screen.

### What's the difference with what should have happened?

not lag to comical levels.

### How do we reproduce this bug?

1. Incendiary OB mostly
2. lag
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by TosterIMC** [comment]
Theres a small chance this pr couses this https://github.com/cmss13-devs/cmss13/pull/1395
Probably clients will generate huge amounts of particles and possibly lag couse of that

**Comment by ItsVyzo** [comment]
Single threading~~

**Comment by Diegoflores31** [comment]
It seems TG did implement something similar to our fire particles but they somehow fixed the performance issues will check on that maybe we can steal it :)

**Comment by Huffie56** [comment]
i think fire performance issue is no longer as bad to be marked as  a bug.
