### ISSUE TITLE
Transfer Health icon should be improved

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1992]
### Testmerges

NA

### Description of the bug

I recently looked at the transfer plasma and health sprites, and I think the transfer health could be tweaked a bit.

![image](https://user-images.githubusercontent.com/964559/208417225-f0f2df94-d578-4ff8-a2be-eeb7ea2275a0.png)

The transfer plasma came first and has some nuance to its outline, and then the transfer health uses just solid green which doesn't look that great and even cuts into the outline a bit. But most importantly, I think it replaced the wrong part of the sprite - blue is for plasma, green is for health, so we should replace the inside part of the sprite not the outside.

If someone could fix the icon up that would make it less confusing to play something like a Drone Healer.

### What's the difference with what should have happened?

The icon should be different.

### How do we reproduce this bug?

Play a Drone Healer.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ultimate-Fluff** [comment]
![image](https://user-images.githubusercontent.com/13158711/209417357-67b0cb75-82ca-454d-a6da-c3ec8d982773.png)
The new icon should look like this (drone applying a resin salve to boo boos) but it currently isn't displaying properly for some reason. We're looking into it.

**Comment by Ultimate-Fluff** [comment]
Hey, uh, could you close this? This has been fixed weeks ago.

**Comment by Ultimate-Fluff** [comment]
Refer to PR #2330 for an update!
