### ISSUE TITLE
invis items on maps (due to instanced filepaths)

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#204]
## Description

tldr, due to docker if you instance a filepath for an item (such as its icon path) it will break and become invisible because it doesn't change properly or something.

## Difference between expected and actual behavior

should not be happening, either fix that (v hard) or fix all the instanced paths (easier)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Fixed with #278.
