### ISSUE TITLE
Healer drone

### ISSUE THREAD

**Issue by Patriota654** [cmss13-devs/cmss13#2073]
### Testmerges

#1908,#1941,#1902,#1350

### Description of the bug

Healer drone is able to heal xenos that are on fire

### What's the difference with what should have happened?

Healer drone should not be' able to heal xenos that are on fire just like the queen eye heal

### How do we reproduce this bug?

1.take xeno  that is on fire (boiler hit by a flame mortar shell,for exemple)
2. Take healer drone
3. Drone heals the boiler that is on fire saving its life 
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
not a bug . queen eye DOES heal xenos even if they are on fire from what i am aware

**Comment by Patriota654** [comment]
> 

Weird,the only reason i posted this is because i ahelped about it out of Curiosity and the answer that i got basically said that it wasnt supposed to work when the xenos were on fire

**Comment by Patriota654** [comment]
Im going to close this issue since insertnamehere123 has picked it up and has been accepted.( feel free to notify me if it needs to stay open,i have never used  github until now)
