### ISSUE TITLE
Was able to make a facehugger into a brown webbing

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#2081]
### Testmerges

No

### Description of the bug

Was able to make a facehugger into a brown webbing

### What's the difference with what should have happened?

you shouldn't being able to... at least i think
![image](https://user-images.githubusercontent.com/117036822/209415079-1dad2e7b-899c-47ca-8696-fab36c003b44.png)

### How do we reproduce this bug?

1.take a hugger 
2.click on brown webbing(without it being on an uniform not sure if it's matter but it's how it worked for me)
3.wait and hear your hugger died while you could do nothing to save him....
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Crowbar764** [comment]
The hugger is programmed to instantly hug any human opening the webbing / backpack / whatever, so this seems pretty intentional.

**Comment by Huffie56** [comment]
delete it because i am pissed

**Comment by Huffie56** [comment]
that doesn't seem like a bug to me...
