### ISSUE TITLE
Cannot build at new dropship

### ISSUE THREAD

**Issue by MaxFallen** [cmss13-devs/cmss13#2094]
### Testmerges

N/A

### Description of the bug

Apparently there its a bug with the new dropship that makes that if you are xeno and try to build some structures at it when in hijack you only can build it on the lower part of where should be the APC, if you try to build at the chairs part it will be cancelled and in the chat log will be the "There is no space to build this", this as told only happens on the chairs part of the DP not below.

### What's the difference with what should have happened?

That the xeno can build hive cluster hive cores and others at the chairs part of the DP

### How do we reproduce this bug?

1.Be xeno in a construction caste, Drone hivelord or queen
2.Order construction in the dropship at the chairs part
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
tm issue #1795 (also fixed)
