### ISSUE TITLE
cannot interact with any storages

### ISSUE THREAD

**Issue by maxo1243** [cmss13-devs/cmss13#2097]
### Testmerges

#2090 #1350 #1902 #1908 #1941 #1795

### Description of the bug

cannot interact with any item conatiners such as venders, marine storage rack things and more.
its my first time on the server and i cannot do anything so hoping you find a way to fix this, it looks fun.

### What's the difference with what should have happened?

to be able to recieve and add items to fixed wall storages

### How do we reproduce this bug?

1.login as one of the few people i have seen with the same issue
2.interact with any of the item containers
3. tada...nothing!
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
server issue, would be resolved in the subsequent restart
