### ISSUE TITLE
impaler burrower

### ISSUE THREAD

**Issue by Loldaddy5676** [cmss13-devs/cmss13#2101]
### Testmerges

#2090, #1350, #1902, #1908, #1941, #1795, #2089

### Description of the bug

burrower impaler strain can go under things they should not be under

### What's the difference with what should have happened?

not suppose to go under prefabricated structures, and crates

### How do we reproduce this bug?

1. become burrower impaler strain
2. use burrow ability
3. go under prefab strucures or a cargo crate or truck, etc
4. get stuck
5. be able to attack marines while they cant attack you

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
tm issue #1350
