### ISSUE TITLE
Bug When Opening Menus

### ISSUE THREAD

**Issue by TTaxer** [cmss13-devs/cmss13#2119]
### Testmerges

#2

### Description of the bug

Sometimes When Opening Certian Menus Like The Cigar Vendor Or Other Similar Machines With An Interface It Just Doesnt Open.
For Example I Go To Buy A Cig And What Happens Is That The Screen Is Showing Blank Then When I Try Again More And More Just Like Gets Removed Instead Of Showing Me The Buy Menu.

### What's the difference with what should have happened?

What Should Have Happened Was That The Buy Menu Would Pop Up And Let Me Buy What I Need

### How do we reproduce this bug?

1.Open Up Random Menus Until A Blank Pops Up
2.Continue Closing And Reopening The Menu
3.Get To A Point Where Its Just Blank And You Cant Close It With Fix Interfaces
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by TTaxer** [comment]
Really Noone?

**Comment by harryob** [comment]
> Really Noone?
> 
> 

what?

**Comment by TTaxer** [comment]
is it fixed?

**Comment by TTaxer** [comment]
look mate I commented that a day ago after the bug went for 6 hours without
noone noticing

**Comment by harryob** [comment]
> look mate I commented that a day ago after the bug went for 6 hours without noone noticing
> […](#)

if this bug is simply the fact that your interfaces weren’t opening - this was a server issue, not a repo issue. they were also both resolved
