### ISSUE TITLE
When a smartgun on burst fire jams, it creates a runtime

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#2147]
### Testmerges

-

### Description of the bug

I noticed we got a lot of runtimes that looked like this:

```
runtime error: Cannot read null.damage_falloff
proc name: apply bullet effects (/obj/item/weapon/gun/proc/apply_bullet_effects)
  source file: gun.dm,1578
  usr: Masar \'Misfortune\' Ratoz (/mob/living/carbon/human)
  src: the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun)
  usr.loc: the cave (176,131,3) (/turf/open/mars_cave)
  src.loc: Masar \'Misfortune\' Ratoz (/mob/living/carbon/human)
  call stack:
the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun): apply bullet effects(the armor-piercing smartgun bu... (/obj/item/projectile), Masar \'Misfortune\' Ratoz (/mob/living/carbon/human), 1, 0, 0)
the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun): Fire(the smartgun drum (/obj/item/ammo_magazine/smartgun), Masar \'Misfortune\' Ratoz (/mob/living/carbon/human), /list (/list), 0, null)
the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun): Fire(the smartgun drum (/obj/item/ammo_magazine/smartgun), Masar \'Misfortune\' Ratoz (/mob/living/carbon/human), /list (/list), 0, null)
the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun): repeat fire(Masar \'Misfortune\' Ratoz (/mob/living/carbon/human))
ImmediateInvokeAsync(the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun), /obj/item/weapon/gun/proc/repe... (/obj/item/weapon/gun/proc/repeat_fire), Masar \'Misfortune\' Ratoz (/mob/living/carbon/human))
the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun): full auto start(Rafar9 (/client), the smartgun drum (/obj/item/ammo_magazine/smartgun), /list (/list))
CallAsync(the M56B smartgun (Wielded) (/obj/item/weapon/gun/smartgun), /obj/item/weapon/gun/proc/full... (/obj/item/weapon/gun/proc/full_auto_start), /list (/list))
Rafar9 (/client):  SendSignal("client_lmb_down", /list (/list))
Rafar9 (/client): MouseDown(the smartgun drum (/obj/item/ammo_magazine/smartgun), the cave (176,134,3) (/turf/open/mars_cave), "mapwindow.map", "icon-x=19;icon-y=27;left=1;scr...")
```

When I started looking into it, I could somewhat rarely reproduce it by taking a smartgun, toggling full auto and emptying a few magazines. Sometimes it wouldn't trigger for a few magazines, sometimes it would be faster.

The wrong bullet is already loaded by the time `load_into_chamber` proc is called, and checking a printout in the game I think I found the culprit - a printout saying `The M56B smartgun (Wielded) jammed! You'll need a second to get it fixed!`. So I'm guessing the gun jamming caused the runtime.

### What's the difference with what should have happened?

Not runtimes

### How do we reproduce this bug?

1. Go smartgunner
2. Toggle Burst Fire Mode
3. Keep shooting until you get the runtime, possibly due to a jam

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ThePiachu** [comment]
To trigger a jam, move while burst firing.

**Comment by silencer-pl** [comment]
This also causes the come back of the good old bug where the bugged bullet in the changer prevents firing of the SG, meaning SGers have to unload their clip, clear the chamber and reload the gun.

**Comment by boskoramen** [comment]
https://github.com/cmss13-devs/cmss13/blob/afc1694e995f29b8869b9ce1a64d9ead96007b9d/code/modules/projectiles/gun.dm#L1187

fun
