### ISSUE TITLE
rain sounds play in space

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#2191]
### Testmerges

irrelevant

### Description of the bug

rain plays in space areas outside the almayer

### What's the difference with what should have happened?

obvious, it should not

### How do we reproduce this bug?

wait for a rain event or trigger one then go into space outside almayer

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i tested it and we still got weather noise in space. trying to investigate it but it's weird only the sound seem to be playing not the rain...
as far as i remember it was there since geeves added weather...

**Comment by Huffie56** [comment]
it seem to ignore the fact that weather_enabled = FALSE for the space area.
![image](https://user-images.githubusercontent.com/117036822/233989670-b48742df-37f9-450f-bc94-563e7da56e97.png)
seem to me that it mean that sound trig erring is separated from the animation of rain being on.

**Comment by Huffie56** [comment]
could be this part of the code responsible
![image](https://user-images.githubusercontent.com/117036822/234070056-622b391a-d3e3-4823-a1b7-968cc0d7459c.png)

**Comment by Huffie56** [comment]
this PR will remove the weather sound in space.
https://github.com/cmss13-devs/cmss13/pull/3145

**Comment by Huffie56** [comment]
@ItsVyzo my PR got merge it fix this issue.
https://github.com/cmss13-devs/cmss13/pull/3145
