### ISSUE TITLE
Chat is broken

### ISSUE THREAD

**Issue by LynxSolstice** [cmss13-devs/cmss13#2264]
### Testmerges

The following pull requests are currently test merged: #2203: '[WIP] Round Results (Internal use stuff)' by morrowwolf at commit 06cb3e0eda  #2229: 'tg shuttle port - Big and Mini ERT' by mullenpaul at commit 3413ceb5e2  #2257: 'fixes the goofy out of LOS typing indicators' by harryob at commit 8331e233bf 

### Description of the bug

SyntaxError: Expected ']' in regular expression
   at A (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:117677)
   at Anonymous function (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:247426)
   at Anonymous function (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:41113)
   at map (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:90914)
   at t.setHighlight (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:246785)
   at Anonymous function (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:237602)
   at onChange (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:267327)
   at o.handleOnChange (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:350630)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"lynxsolstice","window":{"fancy":0,"locked":0}}

### What's the difference with what should have happened?

Dunno

### How do we reproduce this bug?

1.
2.
3.
...
assign the chat to highlight [Charlie
match case match word

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by LynxSolstice** [comment]
I can't use TGUI, it just crashes immediately

**Comment by SexmasterWasTaken** [comment]
Do you use linux? I've heard some people have trouble with TGUI on linux systems.

**Comment by harryob** [comment]
> Do you use linux? I've heard some people have trouble with TGUI on linux systems.

not a linux bug

**Comment by Huffie56** [comment]
> ### Testmerges
> 
> The following pull requests are currently test merged: #2203: '[WIP] Round Results (Internal use stuff)' by morrowwolf at commit [06cb3e0](https://github.com/cmss13-devs/cmss13/commit/06cb3e0edace195df94bd4a15823cd1442ff8505) #2229: 'tg shuttle port - Big and Mini ERT' by mullenpaul at commit [3413ceb](https://github.com/cmss13-devs/cmss13/commit/3413ceb5e2c21d71d441353e9026f16ca44fddc9) #2257: 'fixes the goofy out of LOS typing indicators' by harryob at commit [8331e23](https://github.com/cmss13-devs/cmss13/commit/8331e233bf29de710b3b7b905b334619f8479cf3)
> ### Description of the bug
> 
> SyntaxError: Expected ']' in regular expression at A (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:117677) at Anonymous function (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:247426) at Anonymous function (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:41113) at map (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:90914) at t.setHighlight (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:246785) at Anonymous function (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:237602) at onChange (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:267327) at o.handleOnChange (http://127.0.0.1:1124/tmp15132/tgui-panel.bundle.js:1:350630) User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0) State: {"ckey":"lynxsolstice","window":{"fancy":0,"locked":0}}
> ### What's the difference with what should have happened?
> 
> Dunno
> ### How do we reproduce this bug?
> 
> 
> ... assign the chat to highlight [Charlie match case match word
> ### Issue Bingo
> 
>     * [x]  Issue could be reproduced at least once
> 
>     * [x]  Issue happened in a recent (less than 7 days ago) round
> 
>     * [x]  Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

is this bug still a thing?

**Comment by harryob** [comment]
yes

**Comment by Huffie56** [comment]
is this still a bug?

**Comment by ItsVyzo** [comment]
Does not seem to happen anymore...?
