### ISSUE TITLE
Above head chat bug

### ISSUE THREAD

**Issue by Doom-external** [cmss13-devs/cmss13#2274]
### Testmerges

N/A

### Description of the bug

If you make a word bold or italicised in a message and post it, if you have above head chat enabled the entire message after that word will be bold/italic.

### What's the difference with what should have happened?

Should only have made the intended word bold.

### How do we reproduce this bug?

1. Type message with bold/italic word
2. Hit enter
3. Now half the message is bold

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by NewyearnewmeUwu** [comment]
I could not reproduce this bug.

**Comment by Huffie56** [comment]
tested it and couldn't reproduce the bug so after being on cleanup flag it's time to close this issue.
