### ISSUE TITLE
Xeno ERT can't launch shuttle

### ISSUE THREAD

**Issue by mullenpaul** [cmss13-devs/cmss13#2283]
### Testmerges

#2100, #2203, #2244, #2257

### Description of the bug

When xeno ERT spawns they are unable to launch the shuttle. This is because they can't use the console. The shuttle needs to be force launched.

### What's the difference with what should have happened?

When the xeno ERT spawns in, the shuttle should immediately select a landing pad on the almayer and go

### How do we reproduce this bug?

1. spawn xeno xrt
2. be unable to launch the shuttle

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
is this still a bug ? pretty sure it was already fixed

**Comment by ItsVyzo** [comment]
> is this still a bug ? pretty sure it was already fixed

Tested on 29 April 2023, still a bug // having the shuttle auto launch maybe a good option
