### ISSUE TITLE
Two missplaced stuff involving brig

### ISSUE THREAD

**Issue by LC4492** [cmss13-devs/cmss13#2294]
### Testmerges

N/A

### Description of the bug

1. Military Police stamp:

I found out not long ago that the Military Police have a stamp, but because the stamp is completely generic (If you stamp something with it, it literally says "This document have been stamped with a rubber stamp") its completely useless in any aspect. It is located on a table between the interrogation room and the armory.

2. Missplaced flooring in the hall between brig and the conference room:

Some of the flooring between those two areas is still marking entrances that no longer exist, such as the brig entrance, which changed its emplacement in the last brig update or the door for the no-longer-existent parade uniform room.

### What's the difference with what should have happened?

Those two missplacements are probably easy to fix but they are around for months, if not a full year, because apparently nobody noticed them.

### How do we reproduce this bug?

1. Enter the server
2. Spawn as part of the USCM on your desired role
3. Move yourself to the mentioned area
4. Have fun
5.
6.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Waseemq1235** [comment]
1. For the MP stamp, we don't currently have any custom stamps for MPs, can probably be easily and swiftly done though. I'll look into doing that.
2. I'm assuming you mean this 
![image](https://user-images.githubusercontent.com/42235601/215260198-bba3307e-83bd-46c5-9ee6-2eca9fb735b4.png)
as missing flooring. If there's more let me know.
