### ISSUE TITLE
Items taken from a table via the alt-click menu will not update the table's sprite.

### ISSUE THREAD

**Issue by blackdragonTOW** [cmss13-devs/cmss13#2326]
### Testmerges

#2203: '[WIP] Round Results (Internal use stuff)' by morrowwolf at commit 06cb3e0eda #2244: 'Dancer mini buff' by Git-Nivrak at commit 83cde98ec4 #2100: 'Sentry gun UI' by mullenpaul at commit 7264f2781e #2014: 'Adds Ludicrously In-Depth Black Market to Recquisitions.' by carlarctg at commit ac9c9f9780 #2273: 'tacmap refactor' by harryob at commit 96d409bfa5

### Description of the bug

Taking an item via the alt-click menu will give you the item as expected, but will not alter the sprite you took it from.  

### What's the difference with what should have happened?

When you take an item from a table, it should be removed from the sprite

### How do we reproduce this bug?

1. Find a table with any items on it.
2. Alt-click the table
3. Click the item name in the Byond UI to pick it up
4. ---> The item is in your hand, but the item is still shown on the table as if you never picked it up.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Duplicate. Mentioned above.

> #1885 #2080
