### ISSUE TITLE
Sentry Gun network laptop

### ISSUE THREAD

**Issue by Wolf3993** [cmss13-devs/cmss13#2347]
### Testmerges

.

### Description of the bug

i found a issue with the Sentry Gun network laptop. im able to move around with it open on a desk far from me

### What's the difference with what should have happened?

it should probably close when walked away from

### How do we reproduce this bug?

1.
2.
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by mullenpaul** [comment]
As in, the UI stays open when you move away from it or that the laptop stays open?

**Comment by ItsVyzo** [comment]
> As in, the UI stays open when you move away from it or that the laptop stays open?

I believe that the UI stays open (general issue w/ tgui actually)

**Comment by ItsVyzo** [comment]
#1837 related

**Comment by ItsVyzo** [comment]
![image](https://user-images.githubusercontent.com/46250991/235365052-3077e626-8da5-429b-a808-0beeb548d0d6.png)
Intended
