### ISSUE TITLE
cmss13 github broke, devs help

### ISSUE THREAD

**Issue by AGasCanister** [cmss13-devs/cmss13#2422]
### Testmerges

No TMs on the cmss13 github as far as I know

### Description of the bug

Github broke no idea what's going on

### What's the difference with what should have happened?

I think we should have actual issues instead of the same thing going all over again, like what the fuck is this??
![image](https://user-images.githubusercontent.com/55928412/213499505-65d314d6-d7d4-47d9-9055-8027f9c6ad38.png)

### How do we reproduce this bug?

1. Go to CM github
2. Move to the issues category
3. HUH???
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by SexmasterWasTaken** [comment]
We fixed it woo
