### ISSUE TITLE
Electropack configuration inconsistencies.

### ISSUE THREAD

**Issue by Waseemq1235** [cmss13-devs/cmss13#252]
## Description

Electropack's frequency shows as a decimal (default 145.7) , while frequencies used by the signaler are in thousands (e.g. 1457).
While it is still possible to trigger the electropack if the frequencies are matched and the decimals are ignored, it still confused a player.
Additionally, the other variable is named "code" in the electropack, while it is named "signal" in the signaller.

## Difference between expected and actual behavior
It should simply show the frequency in thousands, with no decimals, similar to that of a signaller. Additionally, the "code" should be changed to "signal".

## Steps to reproduce
1. Grab signaller
2. Grab electropack
3. ???
4. Notice what is described above.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
Actually, in the interest of consistency this should be inverted with signaler showing the decimal. Frequencies all across the codebase are four digits with the fourth separated by a decimal point.
