### ISSUE TITLE
Tail Stab Unable To Hit Some Lights

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#2550]
### Testmerges

No PRs tested durring the round the images were taken in however this bug has existed since tail stabbing was first merged.

### Description of the bug

Tail stab fails to proc when an object like a barrel or locker occupies the tile that the light is in.

### What's the difference with what should have happened?

Tail stab should be able to break lights that happen to occupy a tile with an object like a locker or barrel since a regular slash can break said lights without disturbing objects occupying the same tile. Attached are a couple situations where the tail stab refused to proc as well as the chat logs for those stabs.
![Tail Stab Light Bug](https://user-images.githubusercontent.com/105765670/216716893-d7db6992-b300-4be6-814c-9ab4126a7a36.png)

![Tail Stab Light Bug 2](https://user-images.githubusercontent.com/105765670/216716936-c5297462-7cd3-422a-a6fa-271418ee38da.png)

![Tail Stab Light Log](https://user-images.githubusercontent.com/105765670/216716999-f1967c4a-f17d-4c58-bdd2-670e60a9995b.png)

### How do we reproduce this bug?

1. As xeno, find a light with an object that prevents movement into the tile it occupies like a closed locker or barrel that also occupies a tile with a light.
2. Attempt to tail stab the light.
3. Say"*hiss"

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by NewyearnewmeUwu** [comment]
I'll take a crack at this.

**Comment by ItsVyzo** [comment]
This is not a bug, rather when you stab anything that's in the way would block the stab. It's like someone wearing a stab vest and you try to stab them but the vest stops your stab to put it simply. A slash on the other hand is not "straightforward" which is why you can slash lights.
