### ISSUE TITLE
Keybinds not saving and reverting to hotkey mode.

### ISSUE THREAD

**Issue by brjoaoed** [cmss13-devs/cmss13#2577]
### Testmerges

BYOND Version: 515.1597 Server revision compiled on: 2023-02-05T21:10:09+00:00 Master commit: c92c01892f160281c37854cee1b2cb2b2bf6e72f The following pull requests are currently test merged: #2559: 'makes vendors a little more responsive' by harryob at commit c67a3e7600 #2548: 'mentors/admins can now appear to players as a ghostly SEA' by harryob at commit be35c061aa

### Description of the bug

I use non hotkey mode, usual SS13 standard arrow keys + numpad macros (pick macros, scope, etc).

It started after this update:

harryob changed:

the tacmap is now better, everywhere it appears, for the queen and cic 
the orbit menu now has icons (from the minimap) 
ghosts now get a minimap 
extended now actually works, and doesn't spawn in inhuman abombinations 
refactor's admin VV 
can now edit lists with any reliability, can now edit bitfields without maths 
added the particle editor and colour matrix editor (from tiviplus and Y0SH1M4S73R respectively) for admins via VV 
you can now keybind every emote 
emotes are now datums 

My guess is that the 'you can now keybind every emote' may have something to do with it, my keybinds get reseted from:

Input Settings:

Mode:Send to Chat _as i used to leave_

to:

Input Settings:

Mode:Hotkeys Mode.

Even after reverting it, the hotkeys get reinstated so i have to clear all hotkeys buttons over again, except for the ones to move or that i have changed earlier (WASD to arrows)

![Screenshot_7576](https://user-images.githubusercontent.com/20135391/216918617-3af2b430-9631-4d4e-8bea-7b03ce402d15.png)

As you can see here, in one part of the mode, this entire list should be cleared as i have left, but they come back after a round restart.

Also, my toggle chat bar gets re-enabled after round restart, even with me disabling it time and time again.

_By the way, i do used the 'save slot' button after changing my hotkeys, it didn't work._

### What's the difference with what should have happened?

Expected behavior means the keybinds and 'send to chat' mode should save as any preferences, and but don't, same for over the head chat.

### How do we reproduce this bug?

1.  Use setup character, change 'hotkey mode' to 'send to chat'
2. Clear hotkey mode buttons on the view keybinds panel
3. Change 'toggle abovehead chat' to disabled
4.  Restart the server and it will show up again as if you have never modified them.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
will be resolved by #2576
