### ISSUE TITLE
NVG Sprite Bug

### ISSUE THREAD

**Issue by Katskan** [cmss13-devs/cmss13#2622]
### Testmerges

2203, 2585, 2519

### Description of the bug

When you put NVGs in a patrol cap, then wear the cap, if you take the cap off the NVG sprite stays on your head but the cap goes away. Only way to fix it I found was to put the cap on again, take the NVGs out of the cap's inventory, then take the cap off.

### What's the difference with what should have happened?

NVG sprite should disappear when taking the cap off. 

### How do we reproduce this bug?

1.Put NVGs in a patrol cap's inventory
2.Wear the cap
3.Take the cap off
4.NVGs should still be on your head even though the cap is gone

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ultimate-Fluff** [comment]
This might be fixable with base icon states. If the NVG is applied to the cap, the cap itself could change icon states instead of the NVG overlay applying itself.

**Comment by Huffie56** [comment]
doesn't military nvg need to be attach to an helmet to work?
simple fix could be to forbid it be on cap.

**Comment by Huffie56** [comment]
NVG as been remove and replaced by helmet optics...
feel free to reopen this one if i am wrong...

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/1819b318-8565-4ca6-9055-09391fb3e3f2)

**Comment by ItsVyzo** [comment]
Tested on live - seems to have been fixed.
