### ISSUE TITLE
Slicing meat with butcher's cleaver/kitchen knife doesn't produce cutlets sometimes

### ISSUE THREAD

**Issue by VolsungaSaga** [cmss13-devs/cmss13#2646]
### Testmerges

#2203, #2613, #2642

### Description of the bug

When attempting to slice meat with the butcher's cleaver or the kitchen knife, the cutlets sometimes do not appear at all, or fewer than 3 appear, although the meaty sound effect still plays and the chat log output "You slice up the meat." still appears. The meat is destroyed in the process.

### What's the difference with what should have happened?

Cutting meat with a knife or a cleaver should always produce 3 cutlets (or at least, not zero cutlets).

### How do we reproduce this bug?

1. Become the chef.
2. Take some meat from the meat fridge.
3. Take a kitchen knife or a butcher's cleaver
4. Repeat until the bug is seen. The bug may not manifest for your first attempt, but it seems pretty regular.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by moltoretardo** [comment]
![image](https://user-images.githubusercontent.com/53326609/218610921-4a47a73f-17db-4b3b-a752-d2ce002c8d4e.png)

Hello hello! It's not supposed to give you 0 but it's also not assured to give you 3, it goes from 1 to 3 randomly

**Comment by moltoretardo** [comment]
Ah, you are right though, it does spawn 0 from time to time, will fix
