### ISSUE TITLE
dismantle mortar results in death

### ISSUE THREAD

**Issue by smrtak716** [cmss13-devs/cmss13#2663]
### Testmerges

BYOND Version: 515.1597 Server revision compiled on: 2023-02-15T04:37:01+00:00 Master commit: 739145c6b693c4dfbb2282e18a03e6e1de1407f5 The following pull requests are currently test merged: #2203: '[WIP] Round Results (Internal use stuff)' by morrowwolf at commit 03d1283199 #2613: 'Gives Researchers Intel 1' by morrowwolf at commit 081a765cc5 #2642: 'Debug TM - Polio Stage 1 - Identifying offending mobs' by fira at commit cf5a1bc840 #2652: 'Say\Hearing performance 515 edition' by Git-Nivrak at commit 5854cfd630 #2657: 'Fixes polio?' by Zonespace27 at commit 137143579d  Local commit: 447eac36704fb7bcd3acdc6433e253d191441fe5 TGS version: 5.3.1 DMAPI version: 5.3.0

### Description of the bug

I clicked on the mortar and looked at the flare camera. Meanwhile, a colleague dismantled the mortar and I was suddenly dead (dissolved without a corpse).

### What's the difference with what should have happened?

Not to die.

### How do we reproduce this bug?

1. Open/activate mortar camera
2. Dismantle mortar

### Issue Bingo

- [X] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
This is something Nanu and I were able to reproduce, and is specific to the camera UI (and any other camera UI) rather than the mortar itself.
