### ISSUE TITLE
Whiskey Outpost HUD Icons bugged

### ISSUE THREAD

**Issue by Kitsunemitsu** [cmss13-devs/cmss13#2673]
### Testmerges

Merged PR.

### Description of the bug

Icon for the HG Spec is working, none of the other new ones are.

### What's the difference with what should have happened?

The Icons should be as prescribed in the PR #2292

### How do we reproduce this bug?

Play on Whiskey Outpost.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
![image](https://user-images.githubusercontent.com/41653574/228638353-e699d282-0c59-4bd7-ac43-97e114d80546.png)
Seems to be working appropriately at least in TDome. Will try to keep an eye out for an actual WO round.
