### ISSUE TITLE
Placing items on tables sucks now

### ISSUE THREAD

**Issue by Doom-external** [cmss13-devs/cmss13#2717]
### Testmerges

#2203 #2642 #2130 #2711

### Description of the bug

Any time you try and place an item on a table, it puts it on the same tile, in the centre. It doesn't actually put it on the table.

### What's the difference with what should have happened?

You should place an item on the table, anywhere on the table.

### How do we reproduce this bug?

1. Get any item
2. Find any table
3. Place item on table

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
testmerge issue #2130
