### ISSUE TITLE
Duplicate icon state names in suits_0.dmi

### ISSUE THREAD

**Issue by Ultimate-Fluff** [cmss13-devs/cmss13#2734]
### Testmerges

#2203, #2642, #2130, #2723, #2641, #965, #2332

### Description of the bug

There are duplicate ```rig_syndie``` icon states:
![image](https://user-images.githubusercontent.com/13158711/221436518-556c62d9-7cc8-48ca-8603-bcbabcb18246.png)
![image](https://user-images.githubusercontent.com/13158711/221436561-e7bf8d82-4de8-4f6e-91b2-5a633851e472.png)

And duplicate ```bomber_2``` icon states, both of which are the exact same icon.
![image](https://user-images.githubusercontent.com/13158711/221436691-c00d8d74-3c51-4a8d-95a6-716041be994f.png)

I can remove the duplicate bomber_2 in a separate PR but I am unsure what the maintainers would want to do with the duplicate syndicate suits.

### What's the difference with what should have happened?

The ```rig_syndie``` icon states should be differentiated or one should be deleted, and one of the duplicate ```bomber_2``` icon state should be deleted.

### How do we reproduce this bug?

1. Open suits_0.dmi.
2. Look through the dmi file.
3. Find the big, red, duplicate text.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ultimate-Fluff** [comment]
Someone add the sprites tag.

**Comment by ItsVyzo** [comment]
@harryob this should be fixed - should close

**Comment by ItsVyzo** [comment]
already resolved
