### ISSUE TITLE
you can get stuck in your corpse as an alien, can leave by ghosting

### ISSUE THREAD

**Issue by restedwaves** [cmss13-devs/cmss13#2759]
### Testmerges

#2642 #2332 #2733 #2318

### Description of the bug

died from gunfire specifically a rifle bullet as a sentinel, stayed in my immobile corpse, could not see the ghost menu but weirdly i could still see deadchat.
attempting to follow a ghost leads to the message "this resin marker no longer exists"
![image](https://user-images.githubusercontent.com/90993960/222644786-62ee2d09-cfca-45e1-92a6-a35dcbdeede9.png)

### What's the difference with what should have happened?

should be able to leave my corpse by moving, i stayed inside, was able to leave by manually ghosting

edit as of 4/9/2023, also affects humans obvious ability icon was added allowing easier manual ghosting, good enough

### How do we reproduce this bug?

1.as far as i can tell whats in the screen shot is what i know
2.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Were you clicking on the 'ghost' verb or using it in the command bar? It may just be your OOC panel bugged for a bit. If it worked on reconnect, I would not worry too much about it.

**Comment by restedwaves** [comment]
I used the command bar due to apparently blinding it in the OOC panel so I cant say if that works, I never reconnected and all the deaths after worked as expected.
Weird and minor bug, likely would be a pain in the ass to figure out what went wrong but I figured its good to make note of it anyway but if it's too troublesome to track down someone can just close this issue anyway.
