### ISSUE TITLE
Stripping the bipod on a gun while it's deployed gives you a permanent movement debuff

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#279]
## Description

As per title

In Game Fix is to attach the bipod again but to manually undeploy it

## Difference between expected and actual behavior

Well it shouldn't

## Steps to reproduce

Deploy the bipod, strip it while it's deployed, move and see you have a near permanent speed debuff.

I've tried it with the HPR, XM42B and it probably works with anything that allows the bipod to be attached.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
Does it means if you take it off on HPR it gives you permanent IFF?
But I think it it was fixed

**Comment by Sargeantmuffinman** [comment]
> Does it means if you take it off on HPR it gives you permanent IFF? But I think it it was fixed

And it does not give permanent IFF if you take it off while deployed.
