### ISSUE TITLE
Revolver not loading from special speedloaders bug

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#28]
## Reproduction:

Revolvers such as the m44 refuse to load from special ammo speedloaders such as heavy ammo etc if they have bullets remaining in them, saying that "this xyz doesn't fit"

Also happens with other revolvers

Been happening only recently

**Comment by hotimep** [comment]
yeah this happens with the mateba too, iirc something from the R4T broke it, since this has been happening ever since it got merged, probably
