### ISSUE TITLE
Mysterious White Box

### ISSUE THREAD

**Issue by LeDoktor** [cmss13-devs/cmss13#2800]
### Testmerges

None to my knowledge

### Description of the bug

Anytime I try to open a window in-game (i.e. adminhelp, using vendors, etc.) I get a WY error screen. Refreshing TGUI simply replaces the WY error screen with a white box where the error screen was that can sometimes be removed by reopening the exact same window, but has a chance of being permanent. I know the issue exists only for this game because other servers do not have the same issue. It's actually worse on creating test servers as any window instantly becomes a white box that cannot be fixed at all.

### What's the difference with what should have happened?

The window should open normally.

### How do we reproduce this bug?

1.Maybe messing with macros
2.Open windows
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
you can close "permanent" windows by focusing on the window( clicking it) and hitting alt f4. no Im not joking.

**Comment by LeDoktor** [comment]
Sorry for the late response, got incredibly busy this week. Also, thanks for the tip. I'll try it if it happens again.
