### ISSUE TITLE
M4RA Unintended IFF

### ISSUE THREAD

**Issue by eMiiXi** [cmss13-devs/cmss13#2853]
### Testmerges

#2521, #2656, #1683, #2851, #2850, #2848

### Description of the bug

Putting a B8 scope on the M4RA currently gives it IFF by itself, no bipod even required as attachment.
You can run and gun and shoot over marines with IFF

### What's the difference with what should have happened?

Get IFF only when using bipod(deployed)

### How do we reproduce this bug?

1. Get a M4RA
2. Add a B8 Scope
3. Enjoy the IFF
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Intentional
