### ISSUE TITLE
When spawning as security survivor you don't get any mags in your belt and magazine pouch.

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#2890]
### Testmerges

No

### Description of the bug

When spawning as security survivor you don't get any mags in your belt and magazine pouch.
on shiva snowball and on LV
and i spawn with a M37-17 Pump Shotgun on both maps

### What's the difference with what should have happened?

The security survivor should spawn with magazine in is belt and is magazine pouch.

### How do we reproduce this bug?

Spawn as a security survivor.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
This is quite possibly one of the least in-depth bug reports I have seen.

What map? What loadout did you end up rolling? What gun?

**Comment by Huffie56** [comment]
> This is quite possibly one of the least in-depth bug reports I have seen.
> 
> What map? What loadout did you end up rolling? What gun?

from what i ask it happen to every sec survivor so i didn't specify.
on shiva snowball and on LV
and i spawn with a M37-17 Pump Shotgun on both maps

**Comment by Huffie56** [comment]
will be fix by this PR
https://github.com/cmss13-devs/cmss13/pull/2934
