### ISSUE TITLE
Placing items in the surgery tray creates the hitting sprite

### ISSUE THREAD

**Issue by IsProbablyCatto** [cmss13-devs/cmss13#2929]
### Testmerges

#2761 #2723 #2846 #2703 #2924 #2928

### Description of the bug

When placing items back into the surgery tray it creates the star sprite that appears when hitting something. 

### What's the difference with what should have happened?

It shouldn't create that sprite.

### How do we reproduce this bug?

1. Place an item in the surgery tray

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
not a bug in master, on #2924
