### ISSUE TITLE
Quemistry Rounding error?

### ISSUE THREAD

**Issue by Marqui2156** [cmss13-devs/cmss13#2947]
### Testmerges

#2761: 'Combat Correspondent' by morrowwolf at commit eaaf698028 #2723: 'ERT Station Hangar Locks' by realforest2001 at commit 3817a53a0f #2846: 'Wall Nesting >:0' by kugamo at commit dbd24310ef #2924: 'fixes broken attackchain code' by harryob at commit 1ab22af54e #2934: 'More Surv Tweaks' by morrowwolf at commit 008a13810b #2940: 'Removes long range from Globber Boiler' by BeagleGaming1 at commit 05500a98c2

### Description of the bug

Sometimes when i am making some sweet sweet quemicals i get 0.9999 on some random amount and i have to start the whole process again
![image](https://user-images.githubusercontent.com/128855959/227641034-a0e88664-2480-428c-9923-8cb00a100e05.png)

### What's the difference with what should have happened?

The bucket being filled with 1 instead of 0.999

### How do we reproduce this bug?

Try to spam transfer liquids when making something as OT

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
as above
