### ISSUE TITLE
WY PMC Survivors can't use M39B/2s on Solaris Ridge

### ISSUE THREAD

**Issue by WolfOrion** [cmss13-devs/cmss13#2975]
### Testmerges

#2940, #2952, #2970

### Description of the bug

![image](https://user-images.githubusercontent.com/20691979/228462365-c36e9e6d-a75e-4be9-963f-9fc1c2d351d1.png)

![image](https://user-images.githubusercontent.com/20691979/228460537-d8c2c92c-5e56-4e06-8439-06e1868bfc0b.png)

As a WY PMC survivor, we recovered the M39B/2s and found out too late that despite being WY PMCs, they still considered us unauthorized users.

### What's the difference with what should have happened?

I, as well as the synth (Sawyer) with us and the rest of the survivors, imagined that since we were WY PMCs, we could actually use the weapons that WY PMCs normally do.

### How do we reproduce this bug?

1. Hope for the PMC squad nightmare insert on Solaris Ridge
2. Break into Eta using the fuel tanks in engineering to grab the M39B/2s
3. Attempt to shoot them and realize that you can't
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
Intended that the survivors can't use the ID locked gear, oversight that the current gear on Solaris is still ID locked. Fix needs to change the guns to be unlocked rather than change survivor faction access.
