### ISSUE TITLE
Data entered in Character Records is not presented in game

### ISSUE THREAD

**Issue by Nanu308** [cmss13-devs/cmss13#30]
#### Description

We have three categories of Character Records in our character edit screen - Medical, Employment and Security records. None of these are in any way carried over into the game, even in spots where they seemingly should.

#### Difference between expected and actual behavior

The Character Records are split into thee categories, here is where I'd expect them to pop up:

**Medical Records** should show up in both the files the CMO and CO gets at roundstart and respective personnel records in security terminals.

**Employment Records** should show up in the files the CL, CMP and CO get in their respective offices and again, in the security terminal entries.

**Security Records** should show up in the files the CMP and CO get at roundstart in their filing cabinets and, you guessed it, as entries in the security terminal.

This is all fluff, but many players put some nice info in there that is currently only viewable by accessing VVs.

#### Steps to reproduce

Access Security Records or look at the files pregenerated for the respective heads in their offices - all the formatting is already done, the entries exist as VVs on player characters, the security terminals have places to display the information,  they are just never properly transferred from the VVs/character settings onto the actual files and Security Records. 

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

For as long as I've played CM, a year and a half.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://gitlab.com/cmdevs/colonial-warfare/issues)

GitLab Bug Report from https://gitlab.com/cmdevs/colonial-warfare/-/issues/749

**Comment by Anthem2000** [comment]
Tested this on the terminals, it looks like the notes are saved for medical and employment history. I didn't see anything for the security notes though.

**Comment by K4rlox** [comment]
bumping (attempting)
very old issue
still not fixed
