### ISSUE TITLE
Blank paper(sprite) after copying paper with writing

### ISSUE THREAD

**Issue by TopHatPenguin** [cmss13-devs/cmss13#300]
## Description

Written pieces of paper when copied will come out as blank pieces of paper (sprite wise).

## Difference between expected and actual behavior

The pieces of paper ejected from the copier should have the paper with writing sprite.

## Steps to reproduce

1.  Write on paper
2.  Insert into copier
3. Copy
4. Watch as blank pieces of paper appear, but when examined have your paperwork on.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
probably happens because it only calls update_icon on being written on, not on creation
