### ISSUE TITLE
Invisible pills

### ISSUE THREAD

**Issue by Marqui2156** [cmss13-devs/cmss13#3012]
### Testmerges

#2940: 'Minor Globber Nerf (Temporary)' by BeagleGaming1 at commit 9d1ac70f7f #2970: 'redis connection for msay and asay' by harryob at commit dd8f2dace2 #2963: 'Let (whitelisted) ghosts join in as Working Joes' by victorjosephespinoza at commit 9c7fe38cd7 #2846: 'Wall Nesting >:0' by kugamo at commit 22a2633673 #3011: 'Goonify chemical retrieval (round two)' by morrowwolf at commit 6cfe60e312

### Description of the bug

When you hold a pill bottle and while using the same hand, you eject a pill but the pill is invisible
![image](https://user-images.githubusercontent.com/128855959/229567495-a645f3a8-b2f8-4ea2-9b55-a9a283f4578c.png)

### What's the difference with what should have happened?

the pill being visible

### How do we reproduce this bug?

click on a pill bottle with the same hand you are holding it with

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
This is the identical bug I had reported long ago when we used gitlab. Interestingly, I have also noticed a possibly related bug that came back from the dead: https://github.com/cmss13-devs/cmss13/issues/897 in recent rounds but occurring rarely.
@segrain had fixed it last time but something clearly has been changed.

**Comment by morrowwolf** [comment]
I have not been able to reproduce this. Please give a more in-depth reproducibility when re-opening a new ticket.
