### ISSUE TITLE
You can pick up deployed claymores with the Pick Up Dropped Items Command

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#3014]
### Testmerges

#2940, #2970, #2846, #3011

### Description of the bug

As per title. If you deploy a claymore and press the Pick Up Dropped Items Command. You'll pick up the ACTIVE AND LIVE claymore. The IFF on the claymore will be reset and if anyone walks over it, it explodes.

### What's the difference with what should have happened?

Well, you shouldn't be able to do that in the first place.

### How do we reproduce this bug?

1. Deploy Claymore
2. Pick it up with the Pick Up Dropped Items Command
3. Put it back down.
4. Walk over it.
5. Kaboom.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by NewyearnewmeUwu** [comment]
I'll handle this one
