### ISSUE TITLE
Forum link at the lobby is deprecated

### ISSUE THREAD

**Issue by Edgardo813** [cmss13-devs/cmss13#3024]
### Testmerges

#2940, #2846 #3011, #3003, #3016, #2938

### Description of the bug

So more than a bug the forum link in the lobby description is old, it directs you to

https://cm-ss13.com/forums/

new forums are 

https://forum.cm-ss13.com/

### What's the difference with what should have happened?

pretty much what did I said upthere

### How do we reproduce this bug?

1. join the server
2. Click on the forums hyperlink in the description
3. get redirected to old forums

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
this isn’t a code bug, this is a config error on the cm server
