### ISSUE TITLE
Specific CLF Survivor Variation does not spawn with a vest rig or any space to store gun spawned with.

### ISSUE THREAD

**Issue by Zalycon** [cmss13-devs/cmss13#3027]
### Testmerges

#2944 
#2940

### Description of the bug

During a game of CM the game mode was as normal Distress Signal, I rolled CLF Survivor on Kutjevo Refinery and spawned next to as small armory with ammunition however I did not have a vest rig to store said gun and the ammunition I spawned next to could not be stored due to the fact all the space was filled by engineer tools.

I'm fairly certain this was the engineer variation of the CLF Survivor due to the fact I spawned with a ton of tools. However I may be wrong.

### What's the difference with what should have happened?

The CLF Survivor should've spawned with a chest rig/vest to store the gun as well as some empty space to store miscellaneous items like ammunition.

### How do we reproduce this bug?

1. Launch up CM and start the round on Kutjevo Refinery
2. Spawn in as the engineer/mechanic variation of CLF Survivor
3. Notice the lack of a vest to store weapon spawned with and no space to store items found.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@ItsVyzo does this feel like a bug to you?
i feel the lack of vest to allow storing weapon spawn with or storage space when you spawn is intended?

**Comment by ItsVyzo** [comment]
> @ItsVyzo does this feel like a bug to you? i feel the lack of vest to allow storing weapon spawn with or storage space when you spawn is intended?

Not a bug no. Gear the survivors spawn with was changed, not spawning w/ it is not a bug. This is moreso a suggestion.

@Huffie56
