### ISSUE TITLE
Buckshot Projectiles Not Hitting Targets Simultaneously

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#3053]
### Testmerges

#2944 , #2964, #3031, #3039 , #3046 , #3040 , #3048 at time of report but this issue has existed for months.

### Description of the bug

When firing a buckshot round from a shotgun, the round has two parts to it: the buckshot slug which causes the stun/slowdown/damage and the additional buckshot that just does basic damage but a lot of it. The issue is that when firing, the buckshot slug hits the target well before the additional buckshot. In most cases this does not matter because it all hits eventually. However, if a person shoots a warrior that has lunged a marine outside more than 1 tile away(not a point blank hit) the warrior is stunned by the slug, releases their target, and the additional buckshot then 'catches up' and hits the warrior's target due to the target instantly standing up. 

### What's the difference with what should have happened?

The projectiles should hit at the same instant. It makes zero sense that, if you shoot a warrior that has lunged a marine, you are going to hit the marine on the ground with your damage rather than the warrior. I asked in the coding section of the Discord if this was intended and every single person said it was absolutely not intended projectile behavior.

### How do we reproduce this bug?

1.See marine lunged by a warrior.
2. Shoot warrior with a buckshot round while not PBing but also so that the slug portion of the round will stun said warrior.
3. Observe the warrior fall stunned while the marine that was lunged soaks all the damage.
4. Seethe.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by usnpeepoo** [comment]
This is actually due to Fira´s SS projectile subsystem PR which adds a variation to bullet speed on all projectiles.

https://github.com/cmss13-devs/cmss13/pull/1608

**Comment by ItsVyzo** [comment]
#1764 potentially related

**Comment by Huffie56** [comment]
i think we would need to revert fira change for shotguns and it should fix the weirdness

**Comment by Ansekishokuu** [comment]
Should be fixed with #7406.
