### ISSUE TITLE
Character Records dont show in game

### ISSUE THREAD

**Issue by K4rlox** [cmss13-devs/cmss13#3135]
### Testmerges

#3073 #2984 #3118 #3129

### Description of the bug

the security records and medical records that is entered into the character records in fluff information tab do not show in ingame character or medical records, due to this it cant effect character roleplay in certain situations

### What's the difference with what should have happened?

the info entered into character records should have shown up in the person's records

### How do we reproduce this bug?

1. open character setup
2. go to character records in fluff info
3. enter anything into any of the records
4. join a game
5. go to a medical or security records console
6. look up the person's records
7. empty records

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
https://github.com/cmss13-devs/cmss13/issues/30

**Comment by K4rlox** [comment]
> 

its from 2022
still not fixed nor is anybody planning to fix it

**Comment by K4rlox** [comment]
@ItsVyzo 
existing issue is from 2022 and its not fixed nor is anybody planning to fix it

also theres a 3000 issue gap between these if you can see.

**Comment by ItsVyzo** [comment]
> @ItsVyzo existing issue is from 2022 and its not fixed nor is anybody planning to fix it
> 
> also theres a 3000 issue gap between these if you can see.

Duplicate is duplicate.
Having 1000 issues that report the same issue doesn't help.
If you can code and can fix it great, otherwise it's until someone who volunteers his time decides to do it.
