### ISSUE TITLE
Marine Law Book does not open marine law

### ISSUE THREAD

**Issue by TopHatPenguin** [cmss13-devs/cmss13#319]
## Description

As per title

## Difference between expected and actual behavior

as per title

## Steps to reproduce

- Open marine law
- Be directed to a broken version of the wiki

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
That explains a lot actually.

**Comment by Maciekkub** [comment]
I don't seem to be getting the same issue on my end 

![image](https://user-images.githubusercontent.com/30427887/174486573-7fe96d00-954f-44b1-89ab-f81fe94fea2c.png)
