### ISSUE TITLE
Hearing Xeno Messages as Marine while in Cryopod

### ISSUE THREAD

**Issue by VashVandez** [cmss13-devs/cmss13#3205]
### Testmerges

BYOND Version: 515.1607 Server revision compiled on: 2023-05-01T21:13:49+00:00 Master commit: b726e6a8b6eb2d174ed025998fe1d8304268b3ba The following pull requests are currently test merged: #3073: 'Squad Team Leader' by morrowwolf at commit 55a7eaf7ac #3088: 'Fixes offset issue for multithreading test' by LynxSolstice at commit 95d6c01a9c #2652: 'Say\Hearing performance 515 edition' by Git-Nivrak at commit 0c8a0b70a3 #3179: 'Dancer buff + Bug Fixes' by Git-Nivrak at commit 4eada46c39 #3185: 'GAU buff. ' by Tisx1 at commit cddf0efc22 #3115: 'Fix huggers unable to hug unconscious people' by TeDGamer at commit dad181b95c

### Description of the bug

https://prnt.sc/aiKFpgeg-soM -- Submitting this on behalf of another player, player reports seeing a bloody larva speaking in their chat tab after spawning in as marine while still in their cryo pod shortly before getting out.
![download](https://user-images.githubusercontent.com/132308648/235540775-1618aba4-bf83-430b-85be-34f26df01635.png)

### What's the difference with what should have happened?

This is not supposed to happen, I think.

### How do we reproduce this bug?

1. If I were to hazard a guess, I'd say this likely happens somewhere in-between the jump between being a ghost observer and spawning in as a marine. Or something. I dunno, I don't do this here code stuff, unless the occasionally edit counts. Then I guess. On second thought, I...
2.
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Need more info

**Comment by Huffie56** [comment]
@VashVandez until you can reproduce this or give us more info on what happen i will close this PR.
feel free to reopen if you can update it....
