### ISSUE TITLE
Flare sprites are often on the wrong tiles

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3216]
### Testmerges

#3073: 'Squad Team Leader' by morrowwolf at commit 55a7eaf7ac #3088: 'Fixes offset issue for multithreading test' by LynxSolstice at commit 95d6c01a9c #2652: 'Say\Hearing performance 515 edition' by Git-Nivrak at commit 0c8a0b70a3 #3179: 'Dancer buff + Bug Fixes' by Git-Nivrak at commit 3985fd08a6 #3185: 'GAU buff. ' by Tisx1 at commit c75cbb5947 #3192: 'discord certification' by harryob at commit 46c90b2253

### Description of the bug

Flare sprite positioning was a cool flavor change. However, it results in a VERY LARGE amount of flare sprites being on the wrong tiles. This makes it very annoying to acid the flare.

### What's the difference with what should have happened?

Flare sprites should be on the same tile as the actual flare. 
Randomized flare sprite positioning on a tile should not exceed the tile's boundaries.

### How do we reproduce this bug?

1. Throw/shoot flare
2. Get lucky
3. The random position of the flare sprite puts it on a tile other then the tile its actually on.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
I will bump this and add the flares are on the right tile when thrown, the problem seems to come from explosives or possibly gunshot projectiles causing the flare sprite to spin off the tile it actually occupies. As said, it can make applying acid to the flare a headache.

**Comment by Superwelder** [comment]
![Flare Sprite Bug](https://user-images.githubusercontent.com/105765670/236954700-31f614d5-f738-47e8-b581-e946bf9c4695.png)

Got a good screen cap of exactly why this is a problem. Flare in the picture has a sprite on a walled spot after an explosion. No ability to figure out where to go to melt it.a

**Comment by hislittlecuzingames** [comment]
Is the "TestMerges" section telling me the merges of attempts to fix this issue?

Or is that information irrelevant?

I ask because I'm curious if I should spend time investigating this bug or if it's being worked on already.

**Comment by Drulikar** [comment]
> Is the "TestMerges" section telling me the merges of attempts to fix this issue?
> 
> Or is that information irrelevant?
> 
> I ask because I'm curious if I should spend time investigating this bug or if it's being worked on already.

The "Testmerges" section for an issue report is merely what additional test merges were active at the time of the report. If there was a TM active that fixed the issue, there'd be no reason to create an issue report saying there is a problem. Its just to help with diagnosing the cause of the issue (such as a TM _causing_ the problem).

**Comment by hislittlecuzingames** [comment]
> ![Flare Sprite Bug](https://user-images.githubusercontent.com/105765670/236954700-31f614d5-f738-47e8-b581-e946bf9c4695.png)
> 
> Got a good screen cap of exactly why this is a problem. Flare in the picture has a sprite on a walled spot after an explosion. No ability to figure out where to go to melt it.

Did you right-click the wall tile to see if the flare was on the wall tile?

I haven't seen the flare go into a wall myself. I've seen flares look like they're on different tiles, but they're still at least partially on the tile they're supposed to be "in." 
Thinking back I thought I saw this bug, but when I was checking it, it was never "wrong."

@Drulikar I can't quote your reply as well, so I'll just write you. 
Thanks. I didn't see anything in THOSE test merges even talking about the flares. 
The GAU buff seems to have some scatter info & modifications to how it shoots, but I'd imagine these are just "how accurate the GAU is" and doesn't change any logic in how the bullets do anything to the objects hit. 

I'm going to look around and see if I can see the flare's logic in how it may be displaced. 
If you have any pointers to how objects may be moved as all kinds of debris may be moved, that would help me see if I can't figure this out. 


What I think is happening is that the flare can for some reason sometimes go into walls.

**Comment by ItsVyzo** [comment]
> > ![Flare Sprite Bug](https://user-images.githubusercontent.com/105765670/236954700-31f614d5-f738-47e8-b581-e946bf9c4695.png)
> > Got a good screen cap of exactly why this is a problem. Flare in the picture has a sprite on a walled spot after an explosion. No ability to figure out where to go to melt it.
> 
> Did you right-click the wall tile to see if the flare was on the wall tile?
> 
> I haven't seen the flare go into a wall myself. I've seen flares look like they're on different tiles, but they're still at least partially on the tile they're supposed to be "in." Thinking back I thought I saw this bug, but when I was checking it, it was never "wrong."
> 
> @Drulikar I can't quote your reply as well, so I'll just write you. Thanks. I didn't see anything in THOSE test merges even talking about the flares. The GAU buff seems to have some scatter info & modifications to how it shoots, but I'd imagine these are just "how accurate the GAU is" and doesn't change any logic in how the bullets do anything to the objects hit.
> 
> I'm going to look around and see if I can see the flare's logic in how it may be displaced. If you have any pointers to how objects may be moved as all kinds of debris may be moved, that would help me see if I can't figure this out.
> 
> What I think is happening is that the flare can for some reason sometimes go into walls as Superwelder stated in his investigation.

Is this still an issue? Click the sprite should allow you to melt the flare regardless of location from observations thus far
