### ISSUE TITLE
Almayer bathroom inaccessible. 

### ISSUE THREAD

**Issue by Al-1ce** [cmss13-devs/cmss13#3245]
### Testmerges

#3088 #3185 #3192

### Description of the bug

This is the only bathroom on the Almayer. The typical access point has been restricted due to Engineering being moved around - and the maintenance entrance is locked behind an `engineer` ID access flag for... _some reason._ 
![ванная](https://user-images.githubusercontent.com/71247506/236606091-261da0c0-bfc6-4eb7-8eaf-6dc4293d221e.png)

### What's the difference with what should have happened?

It doesn't make sense for the only bathroom on the ship for standards boots to use being... well, impossible to reach without blowing the damn door down. This faculty has always been accessible through maintenance, but no longer. Why?

### How do we reproduce this bug?

N/A

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Not a bug, that's engineering department bathroom. There are public showers and toilets in marine bunks and a public toilet south of the staff officer canteen.
