### ISSUE TITLE
Fultons Broken?

### ISSUE THREAD

**Issue by WolfOrion** [cmss13-devs/cmss13#3253]
### Testmerges

#3088, #3185, #3192, #3225, #3235

### Description of the bug

Attempted to use my fultons, and while they attached to the xenomorphs it did not then just send them into the air and the dropship pilot could not retrieve them.
![image](https://user-images.githubusercontent.com/20691979/236654308-2627b96c-a9f8-4782-bc8a-d66b4da221ca.png)
It also left "ghost fultons" or something after we dragged the corpses away.
![image](https://user-images.githubusercontent.com/20691979/236654318-b1e99050-3a29-4988-ade2-5bb48c931636.png)

### What's the difference with what should have happened?

After attaching the fultons to them it should've sent them into the air for the dropship to retrieve.

### How do we reproduce this bug?

1. Attach the fulton to a dead xenomorph or crate.
2. Nothing will happen probably.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/3239
