### ISSUE TITLE
SEA rank change in Charatur setup resets

### ISSUE THREAD

**Issue by Chocollateral** [cmss13-devs/cmss13#3255]
### Testmerges

#3088, #3185, #3192, #3225, #3235

### Description of the bug

When I first set my SEA rank to ME9E, and saved it worked. Next round when I changed SEA roll chance from high to low it was back at ME7. The following round when I didnt change anything and rolled SEA I was  gunnery sergeant.

### What's the difference with what should have happened?

Once a pref rank is set for SEA it should not chance unless the player makes a change to it. It should stay to what it is set to.

### How do we reproduce this bug?

1.Boot up game.
2.Click setup character
3.Set SEA rank to ME9E
4.Play round of CM
5.Let server restart and click setup character again
6.If SEA is not set to ME9E issue is there.

### Issue Bingo

- [x] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by XanHiroki** [comment]
This also happens with the Doctor/Surgeon and I'm going to assume it affects the Combat Reporter as well.

**Comment by blackcrystall** [comment]
this is feature... you don't know!

**Comment by Chocollateral** [comment]
Tried this playing as is since last week, issue is def reoccurring. Also like other have said other roles with similar rank changes are having the same issue. Roles like, doctor, reporter, and survivor need to be looked at too.
