### ISSUE TITLE
Sideways 8(Mobius strip(infinite)) Torch fuel + No eye damage

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#329]
## Description
Torch never uses fuel, minimizes handicap of having to wear eye protection while welding

## Difference between expected and actual behavior
 In fact!! Torches should use fuel!! And staring directly into a welder welding, by God, should damage your eyes!!

## Steps to reproduce
 activate welder, start repairing something, deactivate welder before finished, no fuel is used(ditto w/ welding goggles to avoid eye damage and minimize vision handicap)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
Not really consistency...

1. Turn on welder
2. start repairing a cade, APC part, w/e, probably anything except walls afaik
3. immediately turn off welder before your in progress indicator finishes
4. you finish the repair but use no fuel

1. start repairing w/ goggles over eyes
2. immediately flip goggles off eyes
3. you will finish the repair AND it won't damage your eyes AND you won't be half blind while waiting for the repair to finish

**Comment by nuklearcellphoneg** [comment]
1. start repairing w/ goggles over eyes
2. immediately flip goggles off eyes
3. you will finish the repair AND it won't damage your eyes AND you won't be half blind while waiting for the repair to finish

**Comment by hotimep** [comment]
MORBIUS STRIP????

**Comment by nuklearcellphoneg** [comment]
> MORBIUS STRIP????

See, _this_ guy gets it.

**Comment by nuklearcellphoneg** [comment]
#859
