### ISSUE TITLE
Commited suicide with smartpistol

### ISSUE THREAD

**Issue by RagingLemons1** [cmss13-devs/cmss13#3302]
### Testmerges

There were a lot of them but I'm pretty sure they have nothing to do with this. 

### Description of the bug

Smartpistol, while claiming to have IFF, allowed me to successfully commit suicide. 

### What's the difference with what should have happened?

Bullet should have smartly avoided my head. IFF weapons are supposed to avoid IFF tagged individuals. 

### How do we reproduce this bug?

1. Obtain smartpistol
2. Select mouth on the target doll
3. Click self
4. Wait approx 5-10 seconds
5. Die
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Not a bug. You're a dingus.

**Comment by Wintermote** [comment]
I think the smartpistol should fail to fire and inform the user you can't suicide with it

these sort of little things add SOUL
