### ISSUE TITLE
Trijent Elevator works without power restore + apc slashed

### ISSUE THREAD

**Issue by TeDGamer** [cmss13-devs/cmss13#3312]
### Testmerges

#3088, #3271, #3284, #3303

### Description of the bug

Likely not related to the test merges.

The elevator works even when the APC is slashed. It can be called from a different elevator call button even if the APC of the main elevator is slashed.

### What's the difference with what should have happened?

If the APC of the elevator is slashed, it would need to be restored before it can be used.

### How do we reproduce this bug?

1. Slash APC of elevator on Trijent
2. Call Trijent elevator on Trijent ( Bug#1 - even with a slashed APC, it can be called )
3. Use the elevator button in the elevtor to move ( Bug#2 - Elevator does not require power )

Round#16821

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i am going to try and fixed this.
