### ISSUE TITLE
Zombie Virus Infected Corpses do not turn into Zombies.

### ISSUE THREAD

**Issue by fluffe9911** [cmss13-devs/cmss13#3331]
### Testmerges

#3088: 'Fixes offset issue for multithreading test' by LynxSolstice at commit 95d6c01a9c #3303: 'Yautja armor rebalance' by morrowwolf at commit 9a9576ff58 #3126: 'Sniper / Spotter Cooldowns are handled in check_can_use' by TeDGamer at commit 9275ec531e #3298: 'Project ARES - Resurrection' by realforest2001 at commit 1c7c6da316 #3328: 'Event toggle for Permadeath' by BeagleGaming1 at commit e245050bbe

### Description of the bug

It seems that diseases do not tick/process when the mob is dead as such corpses will never end up reaching the level required disease stage-wise for it to cause zombification.

### What's the difference with what should have happened?

>Zombie bites corpse
>Corpse is infected
>Corpse rises up after like 5 minutes

or

>Infected marine kills himself
>Corpse rises up after like 5 minutes

### How do we reproduce this bug?

1. Get infected but not yet zombified
2. Die
3. Watch your corpse for like 30 minutes and realize you aint coming back

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/2803
this PR got close but was about zombies...
https://github.com/cmss13-devs/cmss13/pull/1377
another PR about zombies...
there is also a tons of fixes that didn't solve it just search PR with zombie that are closed...

**Comment by Huffie56** [comment]
going to investigate this and try to make it that all the dead infected revive as zombie.

**Comment by Huffie56** [comment]
after testing infection seem to die at stage 3... going to dig into the code now...
