### ISSUE TITLE
Hotkey doesn't accept Ctrl-R. Always refresh page & crashes

### ISSUE THREAD

**Issue by ghostsheet** [cmss13-devs/cmss13#3356]
### Testmerges

no

### Description of the bug

Ctrl-R refreshes the hotkey page
not a big deal except you need it to BIND HIGH-THROW

### What's the difference with what should have happened?

Ctrl-R should be any normal key, instead of refreshing the page

### How do we reproduce this bug?

1.Click Edit hotkey on Perference Tab
2. Try to input Ctrl R onto any Hotkey
3. See that the TGUI page refreshes and crashes on you
4. Cry about never being able to rebind High Throw mode
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
when i use  ctrl + r to toggle high trow it doesn't crash.....
 can't reproduce what you have it so i put up the cleanup flag.

**Comment by Huffie56** [comment]
> Though I don't know what really we can do about this. The page is a browser, and responds to the refresh key combination.

my bad didn't read carefully enough was just thinking it was a ctrl + r issue....
yes hotkey edit window is very very laggy for me it double the usage of CPR and add another 100mo of memory...
it is a less intense version of this issue:
https://github.com/cmss13-devs/cmss13/issues/3498

**Comment by Huffie56** [comment]
like in term of comparison right now Firefox for me consume around 10% of my CPU to be on discord and on GitHub
but the edit hotkey on is own was consuming 20% it's not normal....

**Comment by Drulikar** [comment]
It lagging is a separate issue, but yes both are issues.

**Comment by Huffie56** [comment]
> It lagging is a separate issue, but yes both are issues.

did you test it and notice an increase in your consumption of resources by your computer CPU and memory?
my guess is that if your PC is Ok you will lag if it's bellow that on performance you will probably crash.
and if you have a good PC you will not see any lag...

**Comment by Huffie56** [comment]
> 

should it be turn back to HTLM to cause less lag we don't really need him to update all the time....
or maybe cut it in multiple section or tab (ADMIN CARBON CLIENT etc.....)so it only update them....
right no it's updating XX lines for no reason......
