### ISSUE TITLE
Bug Turing Dispenser no longer working and being bugged when connect smart-fridge is out of reach.

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#3366]
### Testmerges

not relevant

### Description of the bug

When you unwrench the smart-fridge that is connected to Turing Dispenser  and move it out of range of Turing Dispenser .
you will get this window after interacting with Turing Dispenser:
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/9e0219b0-1e11-4b70-af91-25f2693b0bf9)
Turing Dispenser will also spam a message telling you that Turing Dispenser connection is severed

TypeError: Can't call method on undefined
   at e.exports (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:75285)
   at e.exports (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:80350)
   at keys (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:107083)
   at t.Autodispenser (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:358601)
   at Be (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:161096)
   at Anonymous function (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:161364)d
   at Te (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:161342)
   at Anonymous function (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:161284)
   at Te (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:161226)
   at Re (http://127.0.0.1:50247/tmp4124/tgui.bundle.js:1:168360)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"julian56","interface":"Autodispenser","window":{"key":"[0x200a273]-main","size":null,"fancy":1,"locked":0}}

Weyland-Yutani (c) 2100-2182 Building better user interfaces. 

Turing Dispenser will return back to normal once you put back the smart-fridge at is place

### What's the difference with what should have happened?

1-You should be able to interact with Turing Dispenser even if the smart-fridge is out of reach?
2-the error message make me think it's not suppose to happen?since it say Turing Dispenser had a fatal error instead of telling me that the Smart-fridge is out of reach....
3-Turing Dispenser is spamming the log with Connection severed message. that's not normal...

### How do we reproduce this bug?

1.Unwrench the smart-fridge connect to Turing Dispenser .
2.grab him and drag him to get it out of reach of the Turing Dispenser 
3.interact with the Turing Dispenser .

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
Tested this after seeing a bug related to turing dispenser on this issue https://github.com/cmss13-devs/cmss13/issues/1770

**Comment by Weuyn** [comment]
this also happens if the smart fridge is blown up

**Comment by Huffie56** [comment]
that as been fixed. even if you delete the smart fridge no more out of reach error screen...
