### ISSUE TITLE
Bug botany backpack sprayer is weird and inconsistent.

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#3369]
### Testmerges

not relevant

### Description of the bug

/obj/item/reagent_container/spray/hydro is is code name i think.
1-you can set different output but when you spray it always consume 50U of water.
2-when you spray a tray it give it 2U and sometime a bit more after a while.

### What's the difference with what should have happened?

1-being able to choose the volume output or remove the option to do so.
2-having a consistency between what you hose is consuming and what get in the tray.

### How do we reproduce this bug?

1.take a botany backpack on your back.
2.spray a tray
3.see that it only go up by 2-7 U.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
found this bug testing what was say in https://github.com/cmss13-devs/cmss13/issues/1770 and give it is own issue.
this is the way if we want issues to be fixed...

**Comment by RenaRenaRe** [comment]
I've actually looked into this before. You can change the amount that gets sprayed using a"set transfer amount" verb in the object tab (or right click the backpack) when you have the nozzle drawn, but if you put the nozzle back in the backpack and take it out again then it resets back to 50. If you try to use that same verb when the nozzle is in the backpack it just doesn't do anything.
