### ISSUE TITLE
Boiler Slowdown From Extended Sight Ability Not Going Away In Some Instances

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#3385]
### Testmerges

#3088, #3303, #3298, #3271, #3185, #3223 however this has been an issue since new boiler was merged.

### Description of the bug

Base boiler gains a slowdown when using their far sight. This slowdown disappears once you manually end the far sight ability however, manually using the far sight ability again is not the only way to end far sight. For instance, clicking on the (F) hyperlink in chat to observe a fellow xeno or use of hivemind to observe another xeno will end your far sight while also not triggering the end of the slowdown from the far sight ability. This causes the boiler to be in a permanent slowdown state until they use the ability multiple times again to reset themselves.

### What's the difference with what should have happened?

Being in a permanent slow down state without feedback is a recipe for a michelin star level noob trap. Further, using hive mind or chat to quickly observe other xenos has proven extremely convenient. This bug makes that mechanic an extreme inconvenience.

### How do we reproduce this bug?

1.Be base boiler.
2.Use your far sight ability.
3.Click on a hyperlink to observe a xeno or marker.
4. Return to your own vision by moving or the observe button. 
5. Notice your slowdown.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Somebody told me about this some months ago, but this is the first time since I hear somebody else also experiencing it. Will check.
