### ISSUE TITLE
Cigars/Cigarettes in ears will light automatically

### ISSUE THREAD

**Issue by FoxyStalin** [cmss13-devs/cmss13#340]
## Description
When you have a lit cigar or cigarette in your mouth, and you put one in your ear slot,  the ear cig will be lit.

## Difference between expected and actual behavior
It should be unlit, and just stay in the ear slot, for future smoking.

## Steps to reproduce
Step 1: Put cigarette in mouth
Step 2: Light Cigarette
Step 3: Put cigarette in ear
Step 4: Observe effects

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Reproduced.

**Comment by HochDieAnarchie** [comment]
Glad I double checked before I reported this but yeah this happenin
