### ISSUE TITLE
I accidentally make my view bigger?

### ISSUE THREAD

**Issue by CookieBoy21** [cmss13-devs/cmss13#3405]
### Testmerges

N/A

### Description of the bug

I used Scout Tactical Binoculars for check where I can find xenos and mortar hit me with fire shell and insta killed me, after it my view ranger was this same like from I used binoculars. This bug stay with me every after medic revived me.

### What's the difference with what should have happened?

It's shouldn't look like this...

![obraz](https://github.com/cmss13-devs/cmss13/assets/132950198/b5754881-1713-4811-8149-07a2a39c35b9)

### How do we reproduce this bug?

1.Make sure you have low hp for insta kill from mortar
2.Now use Scout Tactical Binoculars and keep looking.
3.Fire with mortar at you with fire type shell

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
similar to this close issue maybe bug wasn't fix after all
https://github.com/cmss13-devs/cmss13/issues/1884

**Comment by Vytian** [comment]
Just had this occur today. Similar scenario, was shelled and died while using the spotter range finder. When I was revived I maintained the zoomed-out camera even when backing out of binoculars.

**Comment by ItsVyzo** [comment]
Duplicate #1884
