### ISSUE TITLE
When a person is eaten by xenomorphs, a light remains

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3413]
### Testmerges

N/A

### Description of the bug

After a xeno eats a person, the position where you ate them is lit up by any lightsources of the target, even though there is no lights there 
(the lightsource usually being the marine's armorlamp)

### What's the difference with what should have happened?

Marine lamps should not emit light at all once a marine is eaten by a xeno, let alone emit it at the wrong location.

### How do we reproduce this bug?

1. be xeno
2. eat marine
3. A light is stuck where you ate that marine (the wrong location)
4. spit out marine
5. The light is moved back to where it should be (being emitted at the right location)
...
//
it COULD be a clientside visual bug (haven't tested this with others // only seen it as xeno since i dont play marine often). And it's relatively minor. But it happens pretty consistently and often.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
aren't light suppose to stop when you get eaten?

**Comment by gitbirb** [comment]
Fixed by #3668
