### ISSUE TITLE
IO /intel officer intel faulty

### ISSUE THREAD

**Issue by lurzefromgermany** [cmss13-devs/cmss13#3420]
### Testmerges

Not that I know

### Description of the bug

Vial boxes sometimes spawn empty, making them useless, they still give a ping on the data detector, Making more pings then necessary, while being totally worthless. 

### What's the difference with what should have happened?

Would be nice for empty vials and empty vial boxes to no longer be detected, or the ability to mark them as not intel with the detector itself

### How do we reproduce this bug?

1. Play IO, or obtain Data detector
2. Deploy, Find vial box
3. Check vial box contents, sometimes will be empty.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@lurzefromgermany could it be that someone have empty them before you came?
because i know it's possible to find vial box with no chemical in them but i have never found an empty vial box except the one left by other IO or marine or even survivors....

**Comment by lurzefromgermany** [comment]
> @lurzefromgermany could it be that someone have empty them before you came? because i know it's possible to find vial box with no chemical in them but i have never found an empty vial box except the one left by other IO or marine or even survivors.... and you experience this at-least twice already?

almost every round. either from boxes being tossed around, blown up ect. But once there is nothing valuable about it, it should stop being pinged

**Comment by Huffie56** [comment]
i found the idea of a the data detector silly i would rather someone work on a better mechanic of search for IO than simplify even more they work...

**Comment by Wintermote** [comment]
I don't think empty vials and empty vial boxes should ping for intel when they do not provide any intel points like full vials do
