### ISSUE TITLE
Pounce/Lunge does not trigger stun effect from claymores

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#3426]
### Testmerges

#3088, #3185, #3411, #3271, #3298, #3422

### Description of the bug

If a lurker, runner, or warrior lunges or pounces at a marine, and intersects a claymore (for example, the claymore is between the warrior and the marine) the alien will move through the claymore, trigger the claymore, take (some) damage from the claymore, but will not be stunned by the claymore.

Presumably other leap and pounce like abilities also work for this, allowing xenos to bypass or run over claymores without any risk

### What's the difference with what should have happened?

When an alien moves over a claymore and triggers it, they should be stunned; pounces and lunges should be canceled and the alien drops to the ground where they claymore exploded.

### How do we reproduce this bug?

1. Place a claymore
2. Put a marine on the safe side of the claymore
3. Lunge or pounce through the claymore as a runner, lurker, or warrior to hit the marine
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
your issue report is better and more specific than the oldest one. thanks
i am going to ask the issue managers to delete the old one....
old one 
https://github.com/cmss13-devs/cmss13/issues/914

**Comment by ItsVyzo** [comment]
Seems to have been fixed? Eitherway, the way claymores work is there is a split second delay before they activate (even IRL) so this is intended.
