### ISSUE TITLE
Disconnections from server due to xeno eyeing a xeno before they gib

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3444]
### Testmerges

N/A

### Description of the bug

If you xeno eye a xeno, and they gib (like in an acid runner explosion), you will disconnect from the server for a bit.

### What's the difference with what should have happened?

Getting disconnected can mean life or death. Ideally, there would be no disconnect here.

### How do we reproduce this bug?

1. Be xeno (not queen)
2. Eye (watch xenomorph) an acid runner while they are exploding 
3. When the acid runner explodes, your client will disconnect from server
...
//
This is pretty consistently reported from what i know, for a lot of people it WILL disconnect you if you eye an acid runner while they are gibbing.
Not sure if it's exclusively acid rouny gibbing though. 

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
I am not able to reproduce this locally on a server using two clients on the same computer using the current latest commit on master [c697607]. https://youtu.be/g1jfwD53wI8

There is either a test merge that is relevant, or something else required in your reproduction steps.

**Comment by gitbirb** [comment]
whoops i didn't mean to write "client will crash" its client will disconnect from server. My mistake

**Comment by gitbirb** [comment]
> I am not able to reproduce this locally on a server using two clients on the same computer using the current latest commit on master [[c697607](https://github.com/cmss13-devs/cmss13/commit/c697607c00e5ef1e6414723cf640ad8c82ee164b)]. https://youtu.be/g1jfwD53wI8
> 
> There is either a test merge that is relevant, or something else required in your reproduction steps.

It might be something that only happens to normal xenos, not sure how queen eye works with it or if its coded differently.

**Comment by Drulikar** [comment]
A non-queen xeno watching a xeno get gibbed xeno behaves the same as it does for queen. However, a non-queen xeno watching a xeno get killed will not cancel the overwatch. I can fix that (it is doing `observed_xeno == DEAD` instead of `observed_xeno.stat == DEAD`; queen's override of this proc uses .stat), but the former issue is more concerning.

If you think just the black screen is a disconnection, that's just you overwatching the xeno teleported to nullspace - and in my opinion it side the side effect of the connection being severed briefly

**Comment by Segrain** [comment]
If I recall correctly, I _might_ have also experienced this as SO overwatching a marine being gibbed (by a queen, maybe?).

**Comment by stagda** [comment]
I have had this happen to me also, occurs when observing an acider exploding.

**Comment by Superwelder** [comment]
Anyone had it happen with a boiler death(they always 'gib')?
