### ISSUE TITLE
Xeno death + Xeno eye bug // Camera stays on corpse after death of xeno

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3445]
### Testmerges

N/A

### Description of the bug

If you xeno eye a xeno before they die, your camera position stays on their corpse, even after they die.

### What's the difference with what should have happened?

Xeno eye should stop automatically once the xeno you are watching dies.

### How do we reproduce this bug?

1. Xeno eye a xeno before they die
2. Xeno dies
3. You stay in xeno eye, despite them being dead // Your xeno eye (camera) is on their corpse.
...
//
While this is rarely abused, it should probably be fixed. Probably a main factor of #3444 because upon gibbing there is no corpse left for your camera to view.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
I am not able to reproduce this locally on a server using two clients on the same computer using the current latest commit on master [c697607]. https://youtu.be/g1jfwD53wI8

There is either a test merge that is relevant, or something else required in your reproduction steps.

**Comment by Drulikar** [comment]
Only applies to non-queen xenos.
