### ISSUE TITLE
Acid Runner "For The Hive" slowdown stays, even after cancelling the ability

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3446]
### Testmerges

N/A

### Description of the bug

If you activate "For The Hive" (the bomb ability) you will get a slowdown. The problem arises, because if you use the ability again to cancel it, the slowdown is not removed.

### What's the difference with what should have happened?

Acid Runner "for the hive" slowdown should not be permanent

### How do we reproduce this bug?

1. Be Acid Rouny // Also, have 250 acid for ability
2. Activate for the hive
3. Use ability again to cancel
4. Permanent slowdown!
...
//
Currently, a bandaid fix is to deevo and reevo to runner, then choose acider again. You lose all your stored acid by doing this though, and it costs some of your stored evo.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
The slowdown is not permanent - its ~27 seconds, but regardless I can confirm this behavior and it should clear up on canceling.
