### ISSUE TITLE
Trijent Dam's Shuttle APC UNREPAIRABLE

### ISSUE THREAD

**Issue by ghostsheet** [cmss13-devs/cmss13#3461]
### Testmerges

no

### Description of the bug

Trijent's Dam Shuttle or Ferry's APC is unrepairable
Since you cannot crowbar up the floor to reach the wire underneath

### What's the difference with what should have happened?

When repairing the APC a step is to uncrowbar the floor to rewire it
You cannot crowbar up the floor tile
So you cannot repair the APC

### How do we reproduce this bug?

Break APC on Trijent's Ferry
Proceed to follow the steps on repairing it
Gets stuck at Re-wiring the APC as you can't pull up the plate to lay down wires

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
that's an APC on a shuttle so i it's normal if you can crowbar it...
maybe put the floor layer below the wiring so it's always visible....

**Comment by Huffie56** [comment]
will make a fix for it...

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/1799ef8b-4c3c-4c72-8b83-8ae6caa8af01)
