### ISSUE TITLE
Rifleman vendor display issues

### ISSUE THREAD

**Issue by piterskiy2** [cmss13-devs/cmss13#3490]
### Testmerges

#3088 #3298 #3424 #3470 #3481

### Description of the bug

some items in the rifleman vendors are displaying wrong icons
![image](https://github.com/cmss13-devs/cmss13/assets/40919763/0ab24f91-ed2f-443b-8af2-4e561302ada9)

### What's the difference with what should have happened?

items should have proper icons

### How do we reproduce this bug?

open the vendor

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by SpypigDev** [comment]
Phew! I thought I had messed something up in the code and have been freaking out. I'll have a look into the files and see what I can see

**Comment by piterskiy2** [comment]
by the way, it's not just rifleman vendors. i've seen wrong icons in corpsman and comtech vendors, too

**Comment by fira** [comment]
Should be fixed.
