### ISSUE TITLE
View Keybinds Button freezing and crashing game

### ISSUE THREAD

**Issue by BuffJokester2448** [cmss13-devs/cmss13#3498]
### Testmerges

#3088, #3298, #3424, #3470, #3481

### Description of the bug

Pressing "view keybinds" button in setup character menu or "edit hotkeys" in preferences causing game to freeze and crash. Sometimes i see hotkey for few seconds before game freezes. It seems to be working fine in other servers so far.

### What's the difference with what should have happened?

Hotkey menu would have opened normally.

### How do we reproduce this bug?

1. Go to Character Setup.
2. Go to Settings.
3. Press View Keybinds.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
for me it lag a lot when i open the keybind option even after closing everything it seem to be very consuming in resources for no reason.
