### ISSUE TITLE
Rank Board cannot be attached to medical scrubs

### ISSUE THREAD

**Issue by GulDreggrod** [cmss13-devs/cmss13#3538]
### Testmerges

#3088, #3298, #3480, #3509,#3470, #3533, #3534

### Description of the bug

Medical staff cannot attach rank boards to blue scrubs, may be an issue with all of them.

### What's the difference with what should have happened?

I assume this in unintended since rank boards are on medical scrubs when new medical staff spawn in.

### How do we reproduce this bug?

1. Take off rank boards
2. Try to attach to scrubs (blue or otherwise)
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Could not reproduce. Attached properly for me.

**Comment by GulDreggrod** [comment]
I'm a massive retard and didn't realize new scrubs vend with new rank boards attached.
