### ISSUE TITLE
Acid pillar ignores crit xenos which are on fire

### ISSUE THREAD

**Issue by piterskiy2** [cmss13-devs/cmss13#3542]
### Testmerges

N/A

### Description of the bug

i've seen countless situations when acid pillars ignore nearby crit xenos which are on fire. i'm not exactly sure how and why, but this is a thing that keeps happening

### What's the difference with what should have happened?

acid pillars should try to extinguish crit xenos if they're on fire, not ignore them

### How do we reproduce this bug?

1. be in crit & get set on fire
2. get near acid pillar
3. acid pillar ignores you
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
I am not sure if this is related but I have also recently seen acid pillars TARGET nested humans that were awake and ignore others that were not awake/in a critical state.
