### ISSUE TITLE
new anti-DS-sentry thing griefs the M56D, and it's not in a way that should happen

### ISSUE THREAD

**Issue by thatoneyeeter** [cmss13-devs/cmss13#3554]
### Testmerges

#3470, #3540, #3537, #3298

### Description of the bug

whatever update removed the ability to place sentries in dropships eats your M56D mount making it unusable

### What's the difference with what should have happened?

one, i feel like comtechs are already getting enough shit, with the whole "not being able to do their one and only purpose" when it comes to sentries not working (cades are already gone, now its all engineer things full stop)

two, once the comtech places the M56D in the dropship, the mount ✨ CANNOT ✨ be removed and the only option is to unmount the gun and craft a new mount (which is stupid)

so either bring M56D use on dropships back or make them impossible to place entirely so people don't do it smh

### How do we reproduce this bug?

1. enter a dropship
2. place an M56D
3. congratulations, your mount has been eaten, i hope you have 5 plasteel and 10 metal that you're not using to build cades 👍 (sarcasm, if you need to place a 56D in a dropship there's no way you have mats to spare)

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/issues/436 link to this probably
