### ISSUE TITLE
Xeno Ability Use While Watching

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#356]
## Description
Some xeno abilities can be used while watching another xeno.

## Difference between expected and actual behavior
One example of this is how a runner or boiler can watch another xeno and use their vision-boosting abilities to see more in a remote area. Another example of this is how a praetorian can remotely shield xenos, but I'm unsure if that's intended.

## Steps to reproduce

1. Be boiler (or runner).
2. Watch other xeno.
3. Boost vision.
4. Your vision area around the watched xeno is now increased.

Note that you can also vision-boost after looking up a ladder.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Kiara-Miller** [comment]
Prea shielding is/was intened.

**Comment by Huffie56** [comment]
Still present go runner observe any xeno and use your ability to see further...
