### ISSUE TITLE
Hard Resin Node don't Expand on LV-51X Blown Away Rocks.

### ISSUE THREAD

**Issue by Venuska1117** [cmss13-devs/cmss13#3568]
### Testmerges

N/A

### Description of the bug

Hard Resin don't want to expand on Blown Rocks (under them is ground)
![image](https://github.com/cmss13-devs/cmss13/assets/89580971/127b7901-b6a0-484d-a558-62d30c05813b)

### What's the difference with what should have happened?

It should expand and cover ground, this is why gardener Hard Resin exist for.

### How do we reproduce this bug?

1. Go Drone and Choose Gardener Strain
2. Find Rock with got blown away with OB
3. Place Hard Resin, and watch how it don't want to grow.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
I told bobby about this shortly after Chance's was added. They said it was added to a very long list of things to work out for the map. Thanks for making an official report.
