### ISSUE TITLE
Green beret on loadout is tan in-game

### ISSUE THREAD

**Issue by MrBinkers** [cmss13-devs/cmss13#3573]
### Testmerges

#3470, #3530, #3298, #3558, #3559, #3560

### Description of the bug

I wanted to use the green beret from the character preferences loadout. But when I spawn in-game the beret is beige/tan colored.

### What's the difference with what should have happened?

The beret should be green.

### How do we reproduce this bug?

1. Choose the green USCM beret on character preferences
2. Spawn in-game
3. See that it is not green
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Does that happen every time? The beret changes color with maps
