### ISSUE TITLE
Almayer Space Access

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#359]
## Description

Space is accessible for xenos via north vents in lower engineering. The last vent (air injector in this case) on the line is in space.

## Difference between expected and actual behavior

Space should never be accessible outside of an event.

## Steps to reproduce

1. Be vent-crawling (i.e. small) xeno.
2. Get into lower almayer vents.
3. Go to lower engineering, north to where there's a lone canister.
4. Follow the vent line, crawl out of it in space.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
![alt text](https://i.imgur.com/IoMXBl7.png)
