### ISSUE TITLE
Dropship has a chance to land in AA protected areas.

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#3593]
### Testmerges

#3470, #3552, #3298, #3588, #3576

### Description of the bug

The dropship has a chance to land in the AA protected areas even when they have been deterred the first time.

### What's the difference with what should have happened?

Well, it shouldn't. It should land somewhere else.

### How do we reproduce this bug?

1. Set AA to a protected area.
2. Crash land the dropship to said protected area.
3. AA delays the crash but does not deter it from landing there
4. Dropship lands at AA protected area.

Observed twice on the live server.

![Broken](https://github.com/cmss13-devs/cmss13/assets/104228030/04e1296a-5e85-46e4-957c-107b6aa05b81)

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
How often does this happen?

**Comment by Sargeantmuffinman** [comment]
I've seen it happen a handful of times.

**Comment by Wintermote** [comment]
Maybe related - I've seen a few rounds now with the dropship crash landing onto areas it shouldn't particularly stairwells but I've seen the interiors of lifepods get caught in the crashlanding explosions as well.

I think it may be that the exclusion range isn't large enough for these areas and maybe that is what's also happening in the case of landings in AA protected areas.
