### ISSUE TITLE
Invisible Walls on Chance's Claim

### ISSUE THREAD

**Issue by IsDogHour** [cmss13-devs/cmss13#3604]
### Testmerges

#3470, #3552, #3588, #3590, #3576

### Description of the bug

Neither a boiler or crusher could walk into a segment of the map. When trying we got a message saying "You cannot go this way." This area was by some walls north of the fitness complex and was late in the round.
![bug](https://github.com/cmss13-devs/cmss13/assets/133113739/9e61e88f-baee-4401-96b3-b18dd958c093)

### What's the difference with what should have happened?

I should be able to walk into the area.

### How do we reproduce this bug?

1. Try walk into the area north of fitness.

 I'm not sure if it is a mapping bug or if something earlier in the round caused it.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by NewyearnewmeUwu** [comment]
This is a known issue. The APC for the map spawns there and is pre-wrecked, it likely got deleted by an OB or melted, something.
