### ISSUE TITLE
Buckle-Boosting

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#361]
## Description

Buckling yourself to something bypasses movement delays.

## Difference between expected and actual behavior

You can walk a tile and buckle yourself to something on another tile instantly, resulting in a near-instant movement of two tiles, which is faster than anything realistically possible.

## Steps to reproduce

1. Go on dropship (lots of seats here).
2. Spot a seat that isn't adjacent to you, but is close enough to be adjacent after traveling one tile towards it.
3. Click-and-hold on your sprite, then hover the mouse over the target seat in preparation.
4. Start the move to a tile that is adjacent to the seat.
5. Immediately let go of the mouse button while it's over the target seat (before you're even done moving into the first tile), buckling yourself to the seat instantly.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by usnpeepoo** [comment]
This is intended, you can click drag yourself to seats. It doesn't bypass any movement delays as buckling yourself to a seat is instant.
