### ISSUE TITLE
Lurker Fast Tackling

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#362]
## Description

Using crippling strike ability as a lurker bypasses tackle delay.

## Difference between expected and actual behavior

The crippling strike ability should only reset the slash delay (the messages it gives you always refer to the next "slash"). It shouldn't reset the tackle delay.

## Steps to reproduce

1. Be lurker.
2. Tackle victim.
3. Immediately use Crippling Strike ability (preferrably via key-binding).
4. Immediately tackle the victim again (achieving two tackles in quick succession).

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DoomLaser9** [comment]
Crippling strike also allows you to put out fires on other xenos faster.

**Comment by PhantomEpicness** [comment]
Alright its something to do with 
`X.next_move = world.time + 1 // Autoattack reset`
this straight-up skips movement delays by a second

**Comment by stanalbatross** [comment]
Intended, this would be a balance change if you want to remove it
