### ISSUE TITLE
Being thrown/punched/tailslapped into a wall can sometimes instantly kill you

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#3631]
### Testmerges

#3470, #3605, #3609, #3619, #3601, #3298

### Description of the bug

https://files.catbox.moe/a2tbon.png

>DEAD: Larry Corneliolious (F) says, "ETA was just killed by a throw-bug "
>DEAD: Unknown (as Eta) (F) says, "throw bug?"
>DEAD: Larry Corneliolious (F) says, "Check their damage, it's only 140"
>DEAD: Unknown (as Eta) (F) says, "sounds like something to bug report"
>DEAD: Larry Corneliolious (F) says, "It's been in the game since warrior was added"

I am not sure how or why this happens. It wasn't even apparent to me until someone in deadchat pointed it out. I think this screenshot illustrates it's clearly happening as the health scan confirms the synth should still be alive but is not.

### What's the difference with what should have happened?

Expected:
Being slapped into a wall does not instantly kill you

Actual:
Being slapped into a wall instantly kills you

### How do we reproduce this bug?

I don't know how to reproduce it or what triggers it

Perhaps it happens when you get flung into a resin door for some reason?

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by JackieEstegado** [comment]
There is a feature that when someone in crit is thrown they get instakilled, I thought that its only supposed to happen when thrown by a human, but it may also be that being bounced off a wall mistakenly triggers it too?
I think it was introduced in the early days of Sorokyne.
Will ckeck it out.

**Comment by ItsVyzo** [comment]
Was unable to reproduce this. Seems people only insta die when they're crit which is not really a bug considering damage taken.
