### ISSUE TITLE
Tools over-prioritize G8A - General Utility Pouch when pressing E to store them

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#3634]
### Testmerges

#3470, #3605, #3609, #3619, #3601, #3298

### Description of the bug

Unlike every other backpack-like storage, the G8A - General Utility Pouch prioritizes taking tools over webbing, so your tools get dumped into it when there's room, instead of back into the webbing they came from. (I think this problem also occurs with medium/large general pouches)

This causes major headaches when you're trying to juggle storage without using a backpack - for example, carrying a sentry in the G8A, M56D on back, tools in webbing; place the sentry somewhere opens space in the G8A, using tools and pressing E to quickly store them, fills the G8A first. Go to use tools from webbing and - they've disappeared?? (into the G8A). (I have this problem also with screwdrivers, which will store into the knife slot of the boot preferentially over ear/mouth/webbing and may be the reason for any 'disappearing screwdriver' bug reports)

I don't know why the G8A prioritizes tools like this. It's not a tool pouch and not the behaviour I expected. 

It would be better if things went back to the last place they were placed

Or if there were an option to right click and disable this behaviour on the pouch so I can manually prioritize where my tools go

The workaround for now is to always keep the pouch full when quickly storing tools, or to manually put them back in your webbing.

### What's the difference with what should have happened?

Expected:
With G8A - General Utility Pouch equipped, grabbing a tool from your brown webbing and pressing E to put it away should put the tool back where it came from.

Actual:
With G8A - General Utility Pouch equipped, grabbing a tool from your brown webbing and pressing E to put it away, puts it in the G8A - General Utility Pouch instead.

### How do we reproduce this bug?

1. Wear G8A - General Utility Pouch, brown webbing, put tools in brown webbing
2. Pull tool out
3. Press E to put tool back
4. Tool goes into G8A - General Utility Pouch, not brown webbing

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by gitbirb** [comment]
This is an issue with most storage items.

AFAIK, for most items, putting things away using E prioritizes any open spots you can put things in going in this order:
Fully open slots (ie: if you have no belt)
Pouch
Belt
Armor
Webbing/Drop Pouch
Backpack

But yes, it makes no sense that putting away an item using E does not return it to the storage you took it out of

**Comment by ItsVyzo** [comment]
Not a bug - ideasguys / change how code priority works
