### ISSUE TITLE
Ghosting as xeno does not free up the mob (instantly) for someone else to take.

### ISSUE THREAD

**Issue by Mammle2** [cmss13-devs/cmss13#3635]
### Testmerges

#3470: 'The nuclear option' by morrowwolf at commit 7700ef2469 #3605: 'added camera shake and stun to OB.' by Cthulhu80 at commit 0672a9b33e #3619: 'Shipside role weight nerf' by morrowwolf at commit a0d172af69 #3601: 'InfluxDB Metrics Backend' by fira at commit 02b721e3cb #3298: 'Project ARES - Resurrection' by realforest2001 at commit 5844c05427 #3633: 'Black Goo Patch' by realforest2001 at commit d01bdfb6c8

### Description of the bug

I ghosted as xeno (was a leader vampire lurker) since I was going to be busy and the hive was also going to be attacked in a bit so I decided to ghost so someone could take my lurker and go ham instead. 

However when I ghosted and took a glance back a couple of minutes later no one had taken the xeno yet and when I attempted to hit join as xeno myself it just told me there were no xenos available and the runner who woulda taken it (well they said "please free mob") pretty much confirmed that the lurker wasn't freed.

### What's the difference with what should have happened?

Ghosting as xeno frees up the mob instantly (and in the case of larva usually just has them burrow), when I ghosted as xeno the mob ended up being "SSD" but it wasn't freed for someone to take when usually it will be free and pretty much everyone and their mother who is dead takes it instantly.

### How do we reproduce this bug?

1. Ghost as xeno. (Dunno if it was being leader or a vampire might've been a problem but I'd doubt)
2. Try to take the xeno using the join as xeno button.
3. Realize the mob is still "occupied" and can't be taken.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
I was the runner in question and can confirm mob wasn't freed. I even ahelped it, but too late.

**Comment by SupernovaXTS** [comment]
This is part of a bigger problem, players can reenter their bodies after they ghosted
