### ISSUE TITLE
Infinite Blood

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#364]
## Description

You can have a blood level over 100%, with no apparent limit on it.

## Difference between expected and actual behavior

You shouldn't be able to be a walking blood bank.

## Steps to reproduce

1. Acquire fork/spoon/knife.
2. Acquire ridiculous amounts of food.
3. Use fork/spoon/knife to force-feed yourself all the food.
4. Use health analyzer/scanner to see that your blood level keeps increasing past 100%.

Note: Use of a fork/spoon/knife can be substituted by extreme toileting sessions (to generate hunger).

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
I believe the human body is a like, 500u reagent container....? could def be wrong, but you can hold your regular blood + gain surplus + medicines.

Also I imagine if you put a beaker with nutriment and sugar in cryo and made sure to remove the cryox and clonex that would rapidly & I believe exponentially fill you with nutriment.

**Comment by stanalbatross** [comment]
Intended, but being over like 120% should hurt you

**Comment by Huffie56** [comment]
this one seem easy i am going to do it ... just going to make it so that you start loosing blood when your above maximum.
