### ISSUE TITLE
Yautja are stunned for a very long time if they resist out of warrior's lunge grab

### ISSUE THREAD

**Issue by piterskiy2** [cmss13-devs/cmss13#3646]
### Testmerges

N/A

### Description of the bug

Title. If a yautja tries to resists a woyer's lunge the time they spend being stunned is much longer that it should be, which is stupid.

### What's the difference with what should have happened?

this shouldn't happen

### How do we reproduce this bug?

1. get lunged as pred
2. resist
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wintermote** [comment]
I think there is also a bug that stacks movement slows for each tile you're dragged over; not sure if there's a PR for that or it's been fixed already. I've been seeing people talking about it in dchat and ooc however.

But if it's still there, this may be a contributing reason to excessive stun times; e.g. if you're dragged over 5 sticky resin the delay until you can move again would be the movement delay of all 5 of those tiles at once which could be 10+ seconds.

**Comment by piterskiy2** [comment]
by the way, this also affects synthetics and i assume basically anyone that has abnormal stun resistances

**Comment by Cthulhu80** [comment]
> I think there is also a bug that stacks movement slows for each tile you're dragged over; not sure if there's a PR for that or it's been fixed already. I've been seeing people talking about it in dchat and ooc however.
> 
> But if it's still there, this may be a contributing reason to excessive stun times; e.g. if you're dragged over 5 sticky resin the delay until you can move again would be the movement delay of all 5 of those tiles at once which could be 10+ seconds.

#5332

**Comment by Cthulhu80** [comment]
were you dragged after being snagged by the warrior?

**Comment by Cthulhu80** [comment]
I could only reproduce this with the old code before the fix, and it only occurred after dragging the pred through weeds which was stacking the slows as stated in the comment above. @Huffie56 , Think we can close this issue.

**Comment by piterskiy2** [comment]
> I could only reproduce this with the old code before the fix, and it occurred after dragging the pred through weeds which was stacking the movement speed modifier 

nah this definitely had something to do with crawl code. either way it seems like it got fixed after fira fixed the buggy effect system we had, so you can pretty much close it
