### ISSUE TITLE
Escape pods able to launch with more than three people if in cryo

### ISSUE THREAD

**Issue by Lalipar** [cmss13-devs/cmss13#3650]
### Description of the bug

Escape pods launch even when more than three people are present, as long as any numbers over three are in the cryo cells

### What's the difference with what should have happened?

Escape pods with more than three people should not be able to launch

### How do we reproduce this bug?

1. Have more than three people in a pod
2. Make sure at most three are out of cryo
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by gitbirb** [comment]
AFAIK pods are supposed to launch regardless of amount.
The intended result for carrying too much people is the pod will crash land onto the colony.

**Comment by Huffie56** [comment]
for what i gather it will create an explosion and launch 
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/74aabedb-b4ab-4f40-9597-b43db897559d)
just have to test it i guess.

**Comment by Huffie56** [comment]
i tested and when you are over the number the pod just explode and don't launch.
now that i re see the issue i need to test it with people in cryo i guess....

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/1278870f-b710-47e0-99c1-ed9edd05e79b)
this issue is real can be solve in many way
