### ISSUE TITLE
Infinite Shotgun Ammo

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#367]
## Description

Weapons vendors can be abused to dispense unlimited shotgun shells.

## Difference between expected and actual behavior
Shotguns shells shouldn't be unlimited. The fact that there are fewer flechette boxes seems to imply that they should be more limited.

## Steps to reproduce

1. Get box of shells (any kind).
2. Empty the handfuls out of the box.
3. Restock the vendor with the empty box.
4. Now dispense a full box of shells.
5. Profit?

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
This was ruled on long ago. It is a non-issue. If anything, it should be encouraged to reduce clutter in the squad preparation areas. Everyone should have access to basic ammunition like buckshot, slugs, etc.

**Comment by Diegoflores31** [comment]
this only happens on shotgun shells since they are supposed to be common ammunition .. as you can see here the AP and special ammo is protected against this behaviour 
![image](https://user-images.githubusercontent.com/47069269/170184342-9baf5f19-677b-43dc-bd36-e64da6175e92.png)

**Comment by DoomLaser9** [comment]
I've done a bit more testing, and it seems you can also infinitely restock any kind of ammo vended from the automated weapons rack (which includes AP ammo for the 88 Mod 4).

Mainly what prompted me to submit this issue is that there are always fewer flechette shell boxes than other kinds of shotgun ammo boxes, making me believe that flechette was not intended to be unlimited. Perhaps it was limited in the past before the common ammo all became unlimited, in which case the only possible code change that would make sense is changing the number of flechette boxes to be the same as buckshot and slugs (since they're all unlimited anyway).

**Comment by Diegoflores31** [comment]
Flechette is literally one of the weakest shotgun ammo variant and only good with MOU ... also i dont think restocking is really an issue since all the ammo from the prep vendors winout restocking is more than humanly usable on a round

**Comment by Segrain** [comment]
Not really a bug in a meaningful way. There is so much of any kind of standard ammunition that it can be reasonably inferred that it is meant to be readily available in sufficient quantity for any marine to fill his loadout. There is room for general discussion on whether it makes any sense that rifles/SMG have AP ammunition as limited and coveted resource while shotguns have all their ammo types available at all times, but that room is not here.
