### ISSUE TITLE
Radio Language Translation

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#368]
## Description

Shortwave radio doesn't preserve human language when it's in a container (or whispered to).

## Difference between expected and actual behavior
When held in hand, or on the floor, a sentence in another human language will usually go through the radio as being in that same foreign language. However, once the radio is in webbing or a bag on your body, it auto-translates everything you say into English. The same thing happens if you get in a locker or tarp with a radio and whisper (":w") into it in a different language (it's in English over the radio).

It seems that when you whisper, even when holding the radio or having it on the floor by you, it auto-translates.

Placing a radio into a bag seems to cut off its microphone ability, except when you whisper, in which case it forces speech into English.

## Steps to reproduce

1. Turn shortwave radio microphone on.
2. Place radio in backpack.
3. Say something (whispering or not) in a different language.
4. Observe that the radio text is in English, not your language.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
@DoomLaser9 if you ping my on discord when the tape recorder fix goes live on the server I'll try and take a look at this.

**Comment by ItsVyzo** [comment]
Tested on local. Not an issue anymore.
