### ISSUE TITLE
Intel items have strangely large click-boxes, which can block tunnels

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3703]
### Testmerges

N/A

### Description of the bug

Intel items have strangely large click-boxes that are larger then their actual sprites. 
This can result in intel items blocking things "under" them, such as tunnels, even though the sprite doesn't seem to cover the tunnel whatsoever.

A good comparison would be that its like a table and fills almost the whole tile, even though it should only fill the sprite itself.

### What's the difference with what should have happened?

Intel item click-boxes should be reduced to fit their sprite size.
Or alternatively, make it so it doesn't block things like tunnels // make it so xenos can click through the sprite, since theres no purpose to letting them click intel sprites anyway.

### How do we reproduce this bug?

1. Drop a intel paper scrap on tunnel 

// if this doesnt work, fill someones pockets with 2 intel pouches full of intel paper, then egg morph on the tile next to a tunnel (it might be caused by the paper popping out? idk)

2. Xeno tries clicking tunnel
3. They click the intel paper scrap instead because the click-box is so large
4. Xeno tries to acid paper scrap (they cannot acid it because it is intel)
5. Xeno forced to alt-click

//
While at first it might seem to be a rare bug, it is actually really common and really annoying. 
Since intel isn't destroyed upon egg morphing, if you egg morph an IO corpse in an egg morpher next to a tunnel, the intel will sometimes pop out onto the tunnel, blocking it. You can't acid it either in order to unblock it, since it's intel.
//
this might only be with intel paper scraps (i haven't tested other intel items like the chem trays)

### Issue Bingo

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wintermote** [comment]
Perhaps have tunnels automatically push items off them?

It'll always be annoying no matter what changes are done to the size of the intel sprite and its clickable area and simply downsizing could cause some usability problems for IO players and intel grabbing.

I think it's just all around better to push items off the tunnel in whatever valid direction; no changes to sprites needed, and the tunnel is always able to be clicked on. It'd be good even if it were just intel items which cannot be destroyed by aliens.

**Comment by Drulikar** [comment]
This is pretty situational; basically only if you place a morpher next to a tunnel. And the morpher is likely going to be removed at some point. Though the items getting dropped this way keeping MOUSE_OPACITY_OPAQUE I don't think is intended so I can make a PR for that.
