### ISSUE TITLE
Synthesis Machine: you can just press the finished button and skip reagent picking

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#3716]
### Testmerges

nevah

### Description of the bug

after doing a relate, amplify or suppress you can just press finalize without picking any reagent and the machine will just let you. This produces recipes with 2 reagents or recipes that are the same as the previous step

### What's the difference with what should have happened?

the button should be greyed out

### How do we reproduce this bug?

1. amplify something and wait for the reagent picking step
2. just mash finalize instead of clicking any reagent
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
#6568
