### ISSUE TITLE
Strange visuals when inspecting tile with wall by using alt+click

### ISSUE THREAD

**Issue by Venuska1117** [cmss13-devs/cmss13#3738]
### Testmerges

N/A

### Description of the bug

Strange visuals when inspecting tile with wall by using alt+click
![image](https://github.com/cmss13-devs/cmss13/assets/89580971/2e1ecb77-6536-4579-be05-0bd0ed549f21)

### What's the difference with what should have happened?

just normal list of stuff, not some strange junk

### How do we reproduce this bug?

1. Inspect tile with Alt+Click
2. See wierd visual stuff
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Clear your byond cache.
