### ISSUE TITLE
balaclava+body paint bug

### ISSUE THREAD

**Issue by Twomoon-Github** [cmss13-devs/cmss13#3754]
### Testmerges

nope

### Description of the bug

when wearing a balaclava and applying the full body paint (didnt tested if its the same with the heat coiffe etc nor with other paints), it doesnt add the paint on your character (it still apply it and you cant remove it except with paper, but it doesnt appear visually)

### What's the difference with what should have happened?

it should add the paint on head and arms

### How do we reproduce this bug?

1.have balaclava and facepaint in loadout
2.use the facepaint with the balaclava on
3.profit?
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Tested on live - does not seem to be an issue anymore
