### ISSUE TITLE
Bookcase Inconsistency On New Veradero

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#3775]
### Testmerges

#3676 New Veradero

### Description of the bug

These bookcases behave completely differently. The one with books in them is passable, as in it can be walked through. The one without books behaves like a wall that blocks vision and cannot be walked though. Inconsistency strongly suggests an oversight. Given the area is often bombed by CAS/Mortar, this inconsistency does have a large impact on rounds since the area is highly traveled.
![Bookcase Passable](https://github.com/cmss13-devs/cmss13/assets/105765670/41f1eedb-53c4-4c4e-9e94-871d918cb240)
![Bookcase Acting As Wall](https://github.com/cmss13-devs/cmss13/assets/105765670/c26b9e10-650e-4a5d-a078-b2bb17787b24)

### What's the difference with what should have happened?

Bookcases should be consistent in either blocking vision/movement or not blocking it. Specifically, the bookcases without books act as walls while the bookcases with books magically act as.... nothing beyond a visual?

### How do we reproduce this bug?

1. Check in to your local New Veradero library.
2. Try to walk through the different bookcases like a ghost in Ghostbusters(not as a ghost in CM).
3. Do not become the slimer ghost from Ghostbusters.
4. Sing the song and have a nice day.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wintermote** [comment]
I remember this being a problem also with the library on solaris ridge.

Quick fix would be making all the bookshelves empty (I think this was done on solaris)

Better fix would be not just applying consistent sight/movement blocking but also enabling bookshelves to be removed using engineering tools the same as tables, chairs, etc. Probably also xeno slashes, which I don't think work although acid I'm pretty sure does.

**Comment by AnuvKH** [comment]
Did not know this was a thing! Will address next passover.

**Comment by AnuvKH** [comment]
Empty ones replaced as of the latest push.
