### ISSUE TITLE
You can understand Xenos when you're about to die.

### ISSUE THREAD

**Issue by NessiePendragon** [cmss13-devs/cmss13#3778]
### Testmerges

#3644 #3676 #3690 #3755

### Description of the bug

![Screenshot_14](https://github.com/cmss13-devs/cmss13/assets/105026445/c09c3f77-db62-42f0-89b5-4b1b67980511)
as you can see here, I could understand Xenos when I was about to die as a human.

### What's the difference with what should have happened?

A human shouldn't understand what xenomorphs are talking about, I guess...

### How do we reproduce this bug?

1. Get closer to losing consciousness before you die.
2. Make some Xenomorphs talk close to your body.
3. Observe the chat.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
is this still a thing?

**Comment by pedr69** [comment]
ludo

**Comment by private-tristan** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/54422837/966e3de7-8593-45be-8591-cf0e49b15e3e)
yep.

**Comment by NessiePendragon** [comment]
Update
It's still not fixed.
