### ISSUE TITLE
Incorect sprites on LV-624

### ISSUE THREAD

**Issue by ro3ger** [cmss13-devs/cmss13#3779]
### Testmerges

14e6836c07962b55389fc32f04d3ee5d956d0454

### Description of the bug

https://imgur.com/a/zsnvcxC
the description is to the right

### What's the difference with what should have happened?

happened-Wrong sprite
Should happen-Correct sprite

### How do we reproduce this bug?

1. South west jungle of LV-624 is where this spawned
2.
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i will look into it.

**Comment by Huffie56** [comment]
can't find your mask when i click your link i just get a tons of authorization request to make it function so no thanks.
can't you send a copy pasta with paint? way simpler....

**Comment by Drulikar** [comment]
This is the image from the imgur link: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/a4bdf096-d7fa-4334-b439-4d136f41ce88)

**Comment by Huffie56** [comment]
> This is the image from the imgur link: ![image](https://user-images.githubusercontent.com/76988376/257630367-a4bdf096-d7fa-4334-b439-4d136f41ce88.png)

i think it's the nightmare insert for SW but i didn't saw a mask let me double check....

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/1a3bca64-91ab-4121-8e36-417089e3b80a)
it's not in the nightmare he is showing.... 
oh i see what he is refering to the alien blade saw a PR fixing that...
https://github.com/cmss13-devs/cmss13/pull/3870
that's fixed with the PR above

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/048b159e-ee95-4881-95de-cfe96fcf37c6)
