### ISSUE TITLE
Typo in Koorlander Matchbooks

### ISSUE THREAD

**Issue by Ben10083** [cmss13-devs/cmss13#3795]
### Testmerges

#3644, #3676, #3690, #3755, #3783, #3784

### Description of the bug

There is a Typo in Koorlander Matchbooks regarding how many matches are in the matchbook 
![image](https://github.com/cmss13-devs/cmss13/assets/91219575/39e40adf-917d-4964-9c4d-2b8643687414)

### What's the difference with what should have happened?

Match**e**s, not matchs

### How do we reproduce this bug?

N/A

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ben10083** [comment]
Should be a very easy fix

**Comment by Huffie56** [comment]
> Should be a very easy fix

you could easily do it typo fix don't even need to have anything setup beside github.
if your interested i just reply to this and i will help you out.

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/07d1629b-75bb-4c10-9664-f7e19138a342)
that's a bit more complicated that it appear at first...
