### ISSUE TITLE
Ghost health scan enables people to scan their own revivable corpse.

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#381]
## Description

A relatively recent addition allows for ghosts to right click any human corpse and scan its health as if with a medical hand scanner at maximum medical skill. The change was a welcome one for observing but this new ability enables players to metagame knowledge their character would not have and in most cases, would not even have the skillset to see on themselves with a scanner while alive.

## Difference between expected and actual behavior

As a ghost, you can right click a human body---scan health to obtain every point of damage and of what type, broken bones, etc.
As a ghost you should NOT be able to scan your own body while there is a chance for your body to be revived and you to then rejoin the round. Even just disabling the ability to scan your own corpse would be worth the loss in order to prevent this type of metagaming.
Although true another ghosted player/observer could scan a player's revivable body and relay the information to the dead player, that would entail generating actionable logs for someone to issue a metagaming report.

## Steps to reproduce

1. Die
2. Ghost
3. Right click your body, navigate to scan health and notice you can see all the damage it has sustained via the scan.
4. Get revived and tell the medic/doctor that revived you exactly what damage you have sustained and the exact medications you need to heal(This has happened to me 3 times as medic since the ability was added and is the primary reason I am making this issue)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MusselMain** [comment]
I understand why this was made, and I fully agree with this change (although I'd like to have someway of knowing if I've perma'd so I can either leave or join as a xeno), but god I hate that this had to be put in place, why do people always have to meta-sweat just to get a slight advantage?

**Comment by Superwelder** [comment]
You can tell if your corpse is brain dead by the icon next to the head if you have the medical hud enabled in ghost vision. The icon changes from a colored line to a skull if you can no longer be revived. I agree though. Its a nice ability as a ghost but just must be kept from being abusable.

**Comment by Segrain** [comment]
To be honest, ghosts scanning health was originally requested as a feature for staff, but nobody seemed to mind letting all observers have it anyway, so here we are.
I am not really certain that there is much of a problem here. Any ordinary human already can check himself for which bones he has broken and which limbs he has injured. Yes, the specifics are a little more detailed on a scan, but if you are being revived, then by the time you will get back into your body it will quickly become outdated.
And if a random marine is telling a medic exactly what damage he has sustained and exactly what treatment he needs... Firstly, any competent medic already knows all of that and is fully in his right to tell him to be quiet with his uneducated and unwanted opinion. Secondly, if said random marine does walk around telling medics and doctors what to give him - in my humble opinion, that should be treated as a rulebreak on its own, regardless of whether he got that information from a ghost scan or out of general idea that "I am blind - I should tell doctor "give me IA" as if I know what that is and as if he needs me to tell him how to do his job".

**Comment by TellyLsc** [comment]
Why remove it? At least I'd know to just go DNR if there are very few medics around and I'm practically husked.
Also, those "unwanted advice" are based on your assumption that bald medic/doctors who doesn't know about stuff like bicard OD IB heal doesn't exist, IC in OOC is a different matter though, Also technically everyone can always just carry a health analyzer.
