### ISSUE TITLE
Lv-522 Windbreaker light issue

### ISSUE THREAD

**Issue by Tangerineje** [cmss13-devs/cmss13#3819]
### Testmerges

0

### Description of the bug

Colony Windbreakers - Observation light issue

![image](https://github.com/cmss13-devs/cmss13/assets/113033323/bacf52f9-9e16-4f0f-9dba-2f15e6dd9b78)

### What's the difference with what should have happened?

no light, full dark.

I think you can sholve this problem with changing area type or something idk

### How do we reproduce this bug?

area issue

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Uhm, can you elaborate more? What do you mean exactly?

**Comment by Drulikar** [comment]
If I understand correctly, its a room that has no lightbulbs but is considered full bright.

**Comment by Huffie56** [comment]
this is probably lacking an APC so it's not working properly?

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/abf916a0-1ae6-44fc-adcc-395cc7a1ec38)
this as been fixed
