### ISSUE TITLE
Filling up the IMP Ammo Rack backpack does not change sprite until it's taken off and worn again

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#3823]
### Testmerges

#3644, #3676, #3783, #3784, #3799, #3806, #3792, #3815

### Description of the bug

If you wear the IMP Ammo Rack backpack and then put ammo boxes into the backpack while it is worn on your back, the sprite will not update to indicate the backpack has filled up with ammo boxes. To update the sprite you instead have to take the backpack off, and then put it back on.

### What's the difference with what should have happened?

Expected:
Putting ammo boxes into the IMP Ammo Rack backpack while it is worn updates the sprite

Actual:
Putting ammo boxes into the IMP Ammo Rack backpack does not update the sprite while it is worn

### How do we reproduce this bug?

1. Wear IMP Ammo Rack backpack
2. Put ammo box in the backpack
3. IMP Ammo Rack Backpack sprite does not update
4. Take off the IMP Ammo Rack Backpack
5. Wear the IMP Ammo Rack Backpack again
6. The sprite has now updated

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This has been fixed since
