### ISSUE TITLE
How 2 Git 8-13 ish bottles of Ultrazine as CL(Or impants too?)

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#383]
## Description
When you buy from his suitcase, just mash that click, I filled a whole medkit with bottles.

## Difference between expected and actual behavior
And it lets you go like -96/50 points inside its UI

## Steps to reproduce
Fire up your personal auto clicker and see how many Ultrazine bottles/implants you can dupe as CL

Or pens or w/e

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
Autoclicker, thats naughty technology :O

**Comment by nuklearcellphoneg** [comment]
I have 1200 satellite ping, if I click quickly ten times in a row the game will warn me that it knows I'm using an autoclicker and that it has informed the admins and boots me.

V useful feature

**Comment by nuklearcellphoneg** [comment]
Also, I confirmed that you can get multiple implants as well, most I could get in one pass was four, like a $150 points out of budget
