### ISSUE TITLE
all the fancy menus bluescreen

### ISSUE THREAD

**Issue by K4rlox** [cmss13-devs/cmss13#3846]
### Testmerges

#3676 #3783 #3784 #3837 #3814

### Description of the bug

upon joining the server all the winows are white, ahelp doesnt work, mhelp doesnt work, none of the menus work correctly

i have been trying to get help for this for the past week, nothing works at all, at this point im 100% sure this is not a client side issue and i am bug reporthing this

chat:        
 

  \+++++\@@@@@@@@@@/++++\@@@@@@@@@@/+++++/
  \+++++\@``````@/++*+*+\@``````@/+++++/
   \+++++\@````@/++++++++\@````@/+++++/
    \+++++\@``@/++++++++++\@``@/+++++/
     \+++++\@@/+++++/\+++++\@@/+++++/
      \+++*+\/+*+++/@@\+++++\/+++++/
       \++++++++++/@``@\++++++++++/
        \++++++*+/@````@\++++++++/
         \++++++/@@@@@@@@\++++++/
 
 
A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
 TypeError: Tanımsız veya boş referansın 'indexOf' özelliği alınamıyor
   at isStyleSheetLoaded (http://127.0.0.1:50882/tmp8848/browseroutput.html:259:7)
   at node.onload (http://127.0.0.1:50882/tmp8848/browseroutput.html:346:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)

Weyland-Yutani (c) 2100-2182 Building better user interfaces. 
 
![image](https://github.com/cmss13-devs/cmss13/assets/118483925/ff458201-2893-4184-bcfb-3258f21eb856)

ahelp: 
  \+++++\@@@@@@@@@@/++++\@@@@@@@@@@/+++++/
  \+++++\@``````@/++*+*+\@``````@/+++++/
   \+++++\@````@/++++++++\@````@/+++++/
    \+++++\@``@/++++++++++\@``@/+++++/
     \+++++\@@/+++++/\+++++\@@/+++++/
      \+++*+\/+*+++/@@\+++++\/+++++/
       \++++++++++/@``@\++++++++++/
        \++++++*+/@````@\++++++++/
         \++++++/@@@@@@@@\++++++/
 
 
A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
 TypeError: Tanımsız veya boş referansın 'indexOf' özelliği alınamıyor
   at isStyleSheetLoaded (http://127.0.0.1:50882/tmp8848/tgui-window-2.html:259:7)
   at node.onload (http://127.0.0.1:50882/tmp8848/tgui-window-2.html:346:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)

Weyland-Yutani (c) 2100-2182 Building better user interfaces. 
![image](https://github.com/cmss13-devs/cmss13/assets/118483925/0a392628-77b7-495e-89de-6c9c130973ee)

### What's the difference with what should have happened?

literally work correctly

### How do we reproduce this bug?

1. join the server
2. all menus are white
3. cant ahelp
4. nothing fixes it

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
Try fix chat verb, helps for me

**Comment by K4rlox** [comment]
> Try fix chat verb, helps for me (playing via wine)

how hard is it to see
i have been trying EVERYTHING for the past week

nothing you say here will fix it

**Comment by Faunenschnitt** [comment]
Which windows version and internet explorer version (mshtml/trident) are you using? e.g. Windows 7 probably wont run it properly cause there are upgrades made in tg which require at least ie10 or ie11 despite the game being quite old

**Comment by Drulikar** [comment]
The error translated is: `TypeError: Cannot get property 'indexOf' of undefined or empty reference`
And apparently that occurs for you here:
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/bbd37477-4e48-4379-aac0-5a4973141270)
meaning that somehow the parameter `url` is undefined or is an empty reference.

This is core to TGUI, so this is a client side issue for you somehow. So my recommendations; do all of these:
- Clear your Byond cache: Open Byond, click gear on top right, Preferences..., Games tab, Clear Cache.
- Clear your internet explorer cache: Windows Key + R (opens Run), enter `inetcpl.cpl`, OK, Delete..., Ensure at least `Temporary Internet files and websites files` and `Cookies and website data` are selected, Delete.
- Update/downgrade your byond to the latest stable (514.1589). If you're an older version, just update in Byond. If you're on a beta, then uninstalled, and download the latest stable from Byond.

If you *still* have issues, try moving your byond user directory to a path with only English characters:
- Open Byond, click gear on top right, Preferences..., Advanced tab.
- Click ... and point it to some new directory that only uses english characters such as `C:\BYOND Data\`.
- Click OK.

If you *still* have issues, try reinstalling Byond in a directory with only English characters.

**Comment by peearler** [comment]
I had a similar problem, as it turned out later because of the Internet provider. Try the Green Tunnel program or similar, it helped me

**Comment by Drulikar** [comment]
> none of these fixes helped me

Try installing IE11 then per https://github.com/tgstation/tgstation/issues/55481
