### ISSUE TITLE
Ghosts unable to view photos (normal restrictions apply)

### ISSUE THREAD

**Issue by JosephBiell** [cmss13-devs/cmss13#3855]
### Testmerges

BYOND Version: 515.1609 Server revision compiled on: 2023-07-09T21:00:06+00:00 Master commit: 99adec907c9cf1b5893df6451c3eceeac49cd3a0 The following pull requests are currently test merged: #3676: 'New Varadero revamp' by AnuvKH at commit 7ccd90c034 #3783: 'Project ARES - Apollo Controller' by realforest2001 at commit c4269d68ba #3784: 'Adds 10 more apollo consoles' by realforest2001 at commit b387f271ae  Local commit: 11c0cb15ec04c71dfb8f6e8f6955ed01b946ab40 TGS version: 5.12.7 DMAPI version: 5.6.1

### Description of the bug

Ghosts are unable to view photos unless they are next to it. Same with some papers.

### What's the difference with what should have happened?

Ghosts should not be constrained by this.

### How do we reproduce this bug?

Ghost , Look at papers/phtos

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Cthulhu80** [comment]
Interesting choice to remove the good first issue label.

**Comment by Cthulhu80** [comment]
this should have had the good first label.
