### ISSUE TITLE
bug m39 with armbrace

### ISSUE THREAD

**Issue by peearler** [cmss13-devs/cmss13#3873]
### Testmerges

BYOND Version: 515.1609 Server revision compiled on: 2023-07-12T20:40:01+00:00

### Description of the bug

the second time there is a bug when my hand with an attached submachine gun with an armbrace is cut off, and then I pick it up with my good hand, it sticks to it and cannot be detached or dropped, the armbrace button does not appear at the top left. This can be fixed in the game only after robotic surgery and replacing the stock with a regular one.

### What's the difference with what should have happened?

not bugged armbrace

### How do we reproduce this bug?

1.
2.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
I feel like this bug was reported on the old gitlab long ago. There were also major bugs related to the arm getting cut off and other people using the gun.

**Comment by peearler** [comment]
> I feel like this bug was reported on the old gitlab long ago. There were also major bugs related to the arm getting cut off and other people using the gun.

Yes today i got my arm cut off again with an armbrace and another marine with both good arms picked up my submachine gun he stuck to it too

**Comment by Huffie56** [comment]
should be fixed with this PR:
https://github.com/cmss13-devs/cmss13/pull/4655
