### ISSUE TITLE
Pred Cloak Drains Power While Deactivated After Teleporting

### ISSUE THREAD

**Issue by Steelpoint** [cmss13-devs/cmss13#3876]
### Testmerges

3676, 3784, 3729, 3850, 3851

### Description of the bug

If a Predator uses their relay beacon (handheld device to teleport to Pred Ship or Almayer) while cloaked, the cloak effect will disappear upon successful teleportation, however the predators energy will continue to drain as if the cloak was still engaged. 

When the predator activates their cloak, it will state that they have deactivated their cloak and the energy will cease to drain. 

### What's the difference with what should have happened?

When the cloak disengages, the predators energy should no longer be drained. 

### How do we reproduce this bug?

1. Spawn as pred. Grab your Relay Beacon and teleport to any location while cloaked. 
2. On arrival your cloak will disengage but you will still drain power
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
maybe add a check to forbid to us the teleporter with the cloak on?

**Comment by Huffie56** [comment]
new change make it so that pred cloak don't drain power now...
so it's no longer an issue?
https://github.com/cmss13-devs/cmss13/pull/3757

**Comment by Huffie56** [comment]
this one clearly fix it...
https://github.com/cmss13-devs/cmss13/pull/4527
