### ISSUE TITLE
Help intent cures sentinel Nuero-slash

### ISSUE THREAD

**Issue by aceroyuno** [cmss13-devs/cmss13#389]
## Description

Help intent can be used to instantly fix a human slashed by sentinel neuro toxin.

## Difference between expected and actual behavior

You know, not that.

## Steps to reproduce

Slash, fall, help intent. It's gone.

## Issue bingo (not required to be all checked)

- [x ] Issue could be reproduced at least once
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
i am pretty sure that is intended .. help intent is suposed to help people to stand up when they get stunned/pounced/screeched / slept .. etc

**Comment by PhantomEpicness** [comment]
Help cures the daze() that the sent neuro uses
Changing help intent will break a ton of shit so I am just gonna make a custom neurotoxin chemical for this one

**Comment by GoldenDarkness55** [comment]
Not a bug. It's intended to be like this.

Open a PR to buff it by shortening the delay b4 stun/raise stun time instead?

**Comment by usnpeepoo** [comment]
Intended.
