### ISSUE TITLE
Research: Defibrillating can't be created higher than level 1

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#3894]
### Testmerges

none that'd effect it

### Description of the bug

Defibrillating gets stronger the higher level it is and has a special healing effect at potency 7 or higher since Warcrimes, but it is functionally impossible to actually create a chemical with so much defibrillating because the property is limited in Create mode to level 1. 

While technically you could amplify 6 times from level 1 to 7, this would cost like, 30 more points than it should, and 30 points is half of your round.

### What's the difference with what should have happened?

The property should have whatever flag it has that limits it to only level 1 removed.

### How do we reproduce this bug?

1. Get defib
2. put it in a create mode chemical
3. try to increase potency
4. receive a chat log message: 'Max level for defibrillating is 1.'
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
you got you answer with the chat log.
it as been nerf previously probably because it was too strong?

**Comment by Weuyn** [comment]
Defibrillating has never been nerfed, its always been sorta bad because it lets xenos drag farther and cap easier, and has had problems with not alerting/ grabbing ghosts properly so marines are left playerless.

I mean warcrimes was merged a year ago, two years ago? And no one noticed defibrillating was impossible to make in sufficient potency to activate its touch effect, that's how little it gets used.

It's a bug for sure, a relic of when amplifying it did nothing and level 1 was as strong as level 10.

**Comment by Segrain** [comment]
One day I will get to cleaning up all the utter mess that those "warcrimes" made...
