### ISSUE TITLE
If you open Issue order in the IC tab and close it puts issue order on CD without issuing a order

### ISSUE THREAD

**Issue by Cooliecan** [cmss13-devs/cmss13#3916]
### Testmerges

.

### Description of the bug

.

### What's the difference with what should have happened?

.

### How do we reproduce this bug?

1.
2.
3.
...
.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
please fill the issue properly as soon as possible. thanks

**Comment by ItsVyzo** [comment]
As @Huffie56 mentioned, fill this up properly then feel free to tag us to reopen it. @Cooliecan
