### ISSUE TITLE
Grenade launcher on the M41A Mk2.5 doesn't function properly

### ISSUE THREAD

**Issue by BladeburstNINJA** [cmss13-devs/cmss13#3922]
### Testmerges

#3676: 'New Varadero revamp' by AnuvKH at commit 22e1d929bf #3783: 'Project ARES - Apollo Controller' by realforest2001 at commit 0c6722c470 #3729: 'Ravager and Hedgehog changes' by GoldenDarkness55 at commit 16b30ac8f2 #3850: 'Donator Kits' by realforest2001 at commit 3190146bfe #3879: 'Yautja Rework Holder' by realforest2001 at commit 442019a3d5 #3749: 'Re-balances acid damage' by Diegoflores31 at commit 19f32dfa4e #3897: 'Explosive pouch size doubled' by morrowwolf at commit 589d4aa069 #3909: 'Ports TGMC autofire' by Zonespace27 at commit 071bc99c48

### Description of the bug

When switching to the grenade launcher on the Mk2.5, the toggle button icon won't light up green, breech sprite won't function, and grenades won't fire/get eaten.

### What's the difference with what should have happened?

Grenade launcher should work as intended.

### How do we reproduce this bug?

1.Get Mk2.5
2.Attempt to use grenade launcher with grenades.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment]
Mk2.5 was an admin-made gun for a test/event. Cannot repro with mk2
