### ISSUE TITLE
Body bags dont hold burst bodies

### ISSUE THREAD

**Issue by restedwaves** [cmss13-devs/cmss13#3958]
### Testmerges

#3783: 'Project ARES - Apollo Controller' by realforest2001 at commit 2390908a00 #3908: 'Changes to squad color code' by BeagleGaming1 at commit 270557fdcd #3832: 'New CAS Weapon: BLU-200 Dragons Breath, thermobaric bomb' by blackdragonTOW at commit 315dd7b709 #3939: 'Lesser Drones' by morrowwolf at commit c9583d7cab #3950: 'Decreases blood bag IV insertion time' by morrowwolf at commit 45bcdf069f #3931: 'Experimental: Bump rust_g to 2.1.0' by Drulikar at commit c9e4e7ed08 #3955: 'Yautja Rework Holder' by realforest2001 at commit 945cfc931b

### Description of the bug

upon zipping up a body bag the body is left outside of it
upon bursting i couldnt fit the marine in a body bag, they were dosed with antiparasitic before said bursting.
bag cannot contain live humans. likely intended but eh may aswell note it.

### What's the difference with what should have happened?

they should have been able to enter the bag as i zipped it up

### How do we reproduce this bug?

1.infect marine
2.let them burst like you secretly wanted to
3.fail to bag their body
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DaTruRiZZoB** [comment]
adding to this after testing

bursted bodies **CAN** be put into a body bag, you just have to wait 5 or so minutes _(which is still an issue)_
