### ISSUE TITLE
Bonus evolution lost when taking a strain

### ISSUE THREAD

**Issue by GoldenDarkness55** [cmss13-devs/cmss13#3965]
### Testmerges

#3783, #3908, #3832, #3939, #3931, #3955, #3962

### Description of the bug

When taking a strain, bonus evolution progress is lost instead of remaining like normal evolution.

### What's the difference with what should have happened?

Bonus evolution progress should not be lost.

### How do we reproduce this bug?

1.Spawn as runner, accumulate bonus evo progress
2.Take acid runner strain
3.Your bonus evolution is now gone
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Cannot reproduce this issue on master, or with all TMs:
![strain](https://github.com/cmss13-devs/cmss13/assets/76988376/3bac8a95-1a14-4eca-ad77-e895c9153fda)

**Comment by Huffie56** [comment]
waited a week time to close couldn't reproduce
