### ISSUE TITLE
Dismounting the pre-made M56Ds on Whiskey Outpost places you under the M56D instead of behind it.

### ISSUE THREAD

**Issue by Mark9013100** [cmss13-devs/cmss13#3971]
### Testmerges

N/A

### Description of the bug

See title, getting off the mapped in M56Ds will put you under the M56D, instead of behind it.

### What's the difference with what should have happened?

Expected: Dismounting a M56D should put you behind it.

### How do we reproduce this bug?

1. Get on Whiskey Outpost
2. Mount an M56D
3. Dismount an M56D

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
does it only happen with pre-made M56D on WO?

**Comment by Huffie56** [comment]
i will just make it so that you can dismantle pre-made M56D as they are static defense....

**Comment by Huffie56** [comment]
couldn't reproduce this but dismounting via button or resist seem to work perfectly for me on all the different type of M56 on WO.
putting up this issue on cleanup flag.

**Comment by Huffie56** [comment]
couldn't reproduce
