### ISSUE TITLE
CL lockbox contains wrong ammo [this should probably be labeled a oversight not bug]

### ISSUE THREAD

**Issue by MusselMain** [cmss13-devs/cmss13#3976]
### Testmerges

 PR #3583 Adds a CL-Exclusive pistol, the ES-4

### Description of the bug

the CL's WY lockbox spawns with Mod88 mags instead of ES-4 mags, not sure if this is a bug, but as the CL doesn't get a MOD88 by default anymore, and has to go get one from req this makes less sense than before. Maybe this is overthinking things, but wouldn't having extra ammo for the sidearm they actually have access to roundstart make more sense.  [if i'm wrong, and this is intended, let me know so i can remove this issue.]

### What's the difference with what should have happened?

Lockbox should probably contain ES-4 AMMO, as that's the weapon the CL actually spawns with roundstart.

### How do we reproduce this bug?

1.spawn as CL
2. open lockbox in your closet 
3.receive ammo for a weapon you don't have

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
yes CL should have ammo corresponding to the gun is spawn with.
