### ISSUE TITLE
Missing drone caste T2 guaranteed slot

### ISSUE THREAD

**Issue by VEN0M5** [cmss13-devs/cmss13#398]
## Description
No guaranteed slot for burrower
![image](https://user-images.githubusercontent.com/15703585/170840632-c4661bfd-5b1a-4732-be41-ce46fb9249b5.png)

## Difference between expected and actual behavior
I expected a guaranteed slot for every drone caste T2 but no burrower slot.

## Steps to reproduce
Unsure

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Guaranteed slot is not consistent, example:

1. Guaranteed slot for burrower
2. Have 2-3 burrowers and Guaranteed is still there

**Comment by Huffie56** [comment]
code is in xeno_define.dm as far as i can see.

**Comment by Huffie56** [comment]
no clear way on how it should be fixed so i am not going to make a fix on it.
