### ISSUE TITLE
Fire Extinguishers on the Lifeboats Have no Water Inside Them.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#3998]
### Testmerges

#3962 #3917 #3843 #3985

### Description of the bug

Grab a fire extinguisher from the neat little lockers built into the lifeboat > turn off the safety on the fire extinguisher > immediately find out that they have no water inside. I have not had the chance to try and fill one of these extingushers up since if the life boats doors are opened, worse things are happening. 

Have a video of the issue: https://streamable.com/31a25l

### What's the difference with what should have happened?

Fire extinguishers on the lifeboats should have water inside of them :)

### How do we reproduce this bug?

1. Enter the Lifeboat and Grab a fire extinguisher
2. Examine the fire extinguisher, no water is inside.
3. Attempt to use the fire extinguisher, nothing happens.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
hello @mullenpaul sorry to bother you but since you ported new shuttle system....
could you tell me if the extinguisher in the shuttle  cabinet being bugged is because of how shuttle are loaded in the game?

**Comment by mullenpaul** [comment]
It shouldn't be an issue. My guess would be that the included extinguisher has no water when it spawns?

**Comment by Huffie56** [comment]
> s would be that the included extinguisher has no water when it

as far as i understand the extinguisher cabinet use same code as the one in brig it just use a reskin.
the extinguisher in the cabinet of the lifeboat is totally bugged you can't refill it...
my wild guess:
could it be that it doesn't do the initialization since the step is before shuttle is spawn?
