### ISSUE TITLE
Shoulder holster not reholstering properly.

### ISSUE THREAD

**Issue by hotimep** [cmss13-devs/cmss13#4]
#### Description
pulling out a gun with the shoulder holster drops whatever's in your exosuit slot and doesn't  reholster guns properly I HATE IT

#### Difference between expected and actual behavior
before the rework shoulder holster re-holstered guns into itself, ignoring open spaces in the inventory, also it didn't kick out whatever's in your suit slot

#### Steps to reproduce

1. put something in suit storage
2. use keybinds to pull out your awesome revolver (emphasis on keybinds)
3. reholster m44 (it goes in suit storage instead of the holster if its empty) 

#### Specific information for locating
M44 combat revolver

#### Length of time in which bug has been known to occur

idk, probably since the shoulder holster rework got merged

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://gitlab.com/cmdevs/colonial-warfare/issues)

**Comment by Nanu308** [comment]
Changed Title.
@hotimep In the future what does "also something else" in your title mean?

**Comment by hotimep** [comment]
> Changed Title. @hotimep In the future what does "also something else" in your title mean?

unholstering the revolver dumps whatever's in your suit storage, probably should've worded that better whoops!!
