### ISSUE TITLE
Yautja thermal goggles cause sprite error

### ISSUE THREAD

**Issue by Chainsawicus** [cmss13-devs/cmss13#400]
## Description
When Yautja have their thermal overlay activated, the sprite/item that spawns in the eye slot now shows up as an orange exclamation mark next to the actual mob.

Has been happening since #343 was merged onto the live game.

## Difference between expected and actual behavior
Expected behaviour: 
![image](https://user-images.githubusercontent.com/103772903/170851484-6e95e5af-7ed6-454f-8ab5-35836ad39f06.png)

Actual behaviour: 
![image](https://user-images.githubusercontent.com/103772903/170851512-d1abc431-4835-4e63-8e50-2f467decbb8d.png)

## Steps to reproduce
1) Spawn as pred
2) Activate thermal vision

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
Found cause, attempting fix

**Comment by PhantomEpicness** [comment]
Fixed, new sprites added, tested working.
