### ISSUE TITLE
Floor tile sprite issues

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#402]
## Description

Floor tile sprites don't change after a crowbar is used on them. Also, certain floor tiles appear black on the Almayer.

## Difference between expected and actual behavior

Using a crowbar on a floor tile should change the floor tile sprite. Currently, you can crowbar off a tile and pick it up, but the floor looks the same afterwards. Additionally, placing a glass tile on the Almayer shouldn't turn the floor black.

It also seems impossible to turn the tile back to "normal".

## Steps to reproduce

1. Find a standard, normal-looking floor tile on the Almayer (gray with 4 squares).
2. Crowbar it, grab tile. **Notice no visual difference in the floor.**
3. Place carpet on it.
4. Crowbar the carpet, pick it up (toss to side perhaps). **Notice again no visual differernce.**
5. Place glass tile. **Notice that floor turns completely black.**
6. Crowbar glass tile, toss to side.
7. Place normal tile. **Notice that floor is still black. Same thing would happen if you substitute carpet for glass.**

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
from what i am aware this is because the whole almayer is an overlay so basically the floor you can see as a player is basically painted into the floor . i guess it could be fixed but probably needs a considerable amount of work

**Comment by moltoretardo** [comment]
Oh yeah I fixed the black glass tiles a while ago

**Comment by ItsVyzo** [comment]
not a bug anymore... probably
