### ISSUE TITLE
Marines Can Build Walls on Tunnels

### ISSUE THREAD

**Issue by stagda** [cmss13-devs/cmss13#4028]
### Testmerges

BYOND Version: 515.1610 Server revision compiled on: 2023-07-27T21:09:09+00:00 Master commit: 6314aef5cf8c567798c2e13fa855302b210fcc93 The following pull requests are currently test merged: #3962: 'Drastic Changes to the USS Almayer research department' by spartanbobby at commit e28eab7c72 #3917: 'Sweeping LV522 Changes + FORECON GL replaced by FORECON Sniper (Without the sniper)' by spartanbobby at commit 6b52cf3ed0 #3985: 'Xeno endgame content part 1: pylons and larva' by morrowwolf at commit 5d8a9ed39e #4003: 'Brings automatic weaponry to the marine and surv arsenal' by Zonespace27 at commit e11e2a78c9 #4021: '2.5 squad marines per 1 larva latejoin' by morrowwolf at commit 524c08bd6b

### Description of the bug

Walls can be built on top of tunnels, blocking them off (and can trap bald xenos who dont know to right click to exit or alt click the tile to re-enter.)

 ![Wall on Tunnel](https://github.com/cmss13-devs/cmss13/assets/106484997/d84e89ac-1682-4971-887e-faa25694a627)

### What's the difference with what should have happened?

Tiles around the tunnel should be able to be walled off but not the tile with the tunnel on it. 

### How do we reproduce this bug?

1.
2.
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/4831
this PR fixed it.
