### ISSUE TITLE
Wood Alchemy via Tile Transformation

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#403]
## Description

Different types of floor tiles can be combined into a single stack, all being turned into one type of floor tile. **This has extremely high potential for abuse.**

## Difference between expected and actual behavior

You shouldn't be able to transform floor tiles into different types of floor tiles.

Also, deconstructing a stack of tiles in-hand should decrement the number of tiles shown in the UI.

### How to turn wooden planks into lots of metal, glass, and cable coils:
1. Make a single light tile (this is only necessary once, as it is reusable).
2. Make a stack of wood floor tiles from wooden planks.
3. Pick up the light tile.
4. Click the stack of wood floor tiles with the light tile. **Notice that you now have a stack of many light tiles.**
5. Pick up crowbar in alternate hand.
6. With crowbar in active hand, click on light tile stack in offhand. **This produces one metal sheet and a wired glass tile, which could be further deconstructed via wirecutters to produce 1 glass and 1 cable coil. Also note that the number of tiles in the light tile stack that is visually shown on your hand slot does not change.**

**Using this process, each wooden plank consumed creates 4 metal, 4 glass, and 4 cable coils. Focusing on just the metal yields a very rapid process of converting whole stacks of wood over.**

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DoomLaser9** [comment]
This could also create infinite metal, by creating floor tiles out of the metal and turning those into glass tiles

**Comment by nuklearcellphoneg** [comment]
I promise not to abuse it for metal, I just want wood tiling

**Comment by kiVts** [comment]
whats the chance devs will completely remove tiles able to pried because of this?
