### ISSUE TITLE
Private Server Hosting bug

### ISSUE THREAD

**Issue by KevinGlitch** [cmss13-devs/cmss13#4050]
### Testmerges

Unknown

### Description of the bug

After building the server with build.bat, the server refuses to run and gives error code 3221225477
![image](https://github.com/cmss13-devs/cmss13/assets/24706185/3cd5aeea-6ac5-4743-8322-e0aad73e815e)
![image](https://github.com/cmss13-devs/cmss13/assets/24706185/164a7b9e-2c9f-4d11-8cb5-6d7b1f38d9a1)

### What's the difference with what should have happened?

Server should have started correctly and normally. No matter how you start is it fails.

### How do we reproduce this bug?

Uncertain how to other then hosting it privately.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
1609 is a broken byond build. Don't use it.
