### ISSUE TITLE
SG care package

### ISSUE THREAD

**Issue by FotisLight** [cmss13-devs/cmss13#4054]
### Testmerges

Doesn't really matter in this

### Description of the bug

The care package has not been updated to include the proper battery yet.

### What's the difference with what should have happened?

Should have gotten the new SG battery instead of a high cap cell. 

### How do we reproduce this bug?

1. Use care package grenade 
2. Wait for crate.
3. Cry, because there is no battery for you to use
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by FotisLight** [comment]
this is for WO forgot to add that

**Comment by Huffie56** [comment]
Will make a fix for that
