### ISSUE TITLE
symptoms of brain damage continue to show after surgery

### ISSUE THREAD

**Issue by Mister-moon1** [cmss13-devs/cmss13#4058]
### Testmerges

#3985 #4003 #4024 #3726 #4035 #3942 #4046

### Description of the bug

After getting surgery to repair the brain, the symptoms can sometimes stay, likely caused by https://github.com/cmss13-devs/cmss13/pull/4052

### What's the difference with what should have happened?

symptoms go away

### How do we reproduce this bug?

1. get copious amounts of brain damage
2. get surgery to fix brain damage
3. profit

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
considered fixed since https://github.com/cmss13-devs/cmss13/pull/4061 got TM and merge
