### ISSUE TITLE
Hugger Health Only Updates When Resting

### ISSUE THREAD

**Issue by IsProbablyCatto** [cmss13-devs/cmss13#4062]
### Testmerges

#3945, #4003, #4024, #3726, #4035, #3942, #4046

### Description of the bug

While running around off weeds, huggers usually take small health damage, stopping until they rest. Health is only updated when the hugger rests, meaning you can run around infinitely until you rest and immediately explode.

### What's the difference with what should have happened?

Should take gradual damage off weeds until exploding, rather than health updating only when resting.

### How do we reproduce this bug?

1. Run off weeds
2. Rest
3. Explode/Lose health
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Hopekz** [comment]
Addressed in #3726
