### ISSUE TITLE
Egg Duping/Glitch/Sum Sum

### ISSUE THREAD

**Issue by tholker** [cmss13-devs/cmss13#4064]
### Testmerges

Eggs Dup without any special process, just the usual.

### Description of the bug

The eggs are "dupping", the process is simple as, so pretty much anyone can do it. Even accidentally, like my lucky ass.
Pick egg
plant egg (Hive)
translucide egg appears on hand previously holding the egg
Can't plant, so drop the egg
Egg can't be picked up (By lesser/xenos at least)
Now those pretty eggs are around doing... nothing, just bugged out.
Happened twice or thrice 

### What's the difference with what should have happened?

They shouldn't be multiplying.

### How do we reproduce this bug?

1. Pick egg
2. Plant egg (Hive)
3. translucide egg appears on hand previously holding the egg
4. Can't plant, so drop the egg
5. Egg can't be picked up (By lesser/xenos at least)
6. Now those pretty eggs are laying around doing... nothing, just bugged out.
Happened twice or thrice 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i had a similar bug but didn't noted the steps when it happen.
all i remember now is that it had to do with being a carrier and with the ability store eggs.....
manage to get a special eggs like it's say above then with this special eggs you can duplicate i think....
i

> Cannot reproduce on master or with current tms (instructions maybe unclear?): https://youtu.be/CkBJzUFNKpY

**Comment by Huffie56** [comment]
similar issue there https://github.com/cmss13-devs/cmss13/issues/4270

**Comment by ItsVyzo** [comment]
duplicate #4270 / closing older one as the other one is more detailed
