### ISSUE TITLE
Getting caught directly next to a fuel tank explosion causes your held item to get deleted.

### ISSUE THREAD

**Issue by Wulfestwulf** [cmss13-devs/cmss13#4072]
### Testmerges

3985, 4003, 4024, 3726, 3942, 4061, 4063, 4067

### Description of the bug

If you are caught directly next to a fuel tank explosion (in my case caused by a runner attacking it) while holding a gun with a mag harn on it, it will be entirely deleted from the game. 

### What's the difference with what should have happened?

Not having your gun deleted from existence.

### How do we reproduce this bug?

1. Stand next to fuel tank
2. Hold a gun with a mag harness on it
3. Have the tank explode and notice there is no gun.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wulfestwulf** [comment]
Note: I was using automatic fire from #4003 and was shooting at a Prime Runner.

**Comment by morrowwolf** [comment]
Not a bug
