### ISSUE TITLE
Pylon breaks hivestatus

### ISSUE THREAD

**Issue by ihatethisengine** [cmss13-devs/cmss13#4086]
### Testmerges

#3985: 'Xeno endgame content part 1: pylons and larva' by morrowwolf at commit 48336c4b99  #4024: 'Log Updates' by realforest2001 at commit 0c7bf41d0d  #3726: 'New facehugger strain: Watcher' by Hopekz at commit 554bc58f1c  #3942: 'Updates Yautja Plasma Rifle' by Steelpoint at commit 2b02926713  #4063: 'Yautja Change Holder' by realforest2001 at commit 42f2cf08e5  #4067: 'Research Biohazard Lockdown' by realforest2001 at commit 6e263a8dce  #4081: 'Auxiliary Support Officer' by morrowwolf at commit 0cdbf93ea7 

### Description of the bug

When xenos put a cluster next to a tcomms tower and it turns into a pylon, hive status breaks and doesn't open correctly. I think it happens with a single pylon, not sure if it breaks with two. 

### What's the difference with what should have happened?

Hive status should open correctly.

### How do we reproduce this bug?

1. Wait till 01:35
2. Put one cluster next to a tcomms tower (probably don't put second one)
3. Try to open hive status

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
Actually I couldn't reproduce it now. Maybe the issue is not pylons, maybe something else breaks hivestatus.

**Comment by ihatethisengine** [comment]
Status tab also breaks for unknown reason, it doesn't update.

**Comment by morrowwolf** [comment]
I have no been able to reproduce this at all. Re-open when reproducibility is confirmed. When Queen dies hive status does die iirc.
