### ISSUE TITLE
LV secured storage. No inner door buttons.

### ISSUE THREAD

**Issue by Yellows91** [cmss13-devs/cmss13#4095]
### Testmerges

#3985: 'Xeno endgame content part 1: pylons and larva' by morrowwolf at commit 48336c4b99 #4024: 'Log Updates' by realforest2001 at commit 0c7bf41d0d #3726: 'New facehugger strain: Watcher' by Hopekz at commit 554bc58f1c #4063: 'Yautja Change Holder' by realforest2001 at commit 664c11ea4e #4067: 'Research Biohazard Lockdown' by realforest2001 at commit 902022485b #4081: 'Auxiliary Support Officer' by morrowwolf at commit 635f240c34 #4076: 'Assigned job slots and cryorines.' by Segrain at commit 7de7b942a6

### Description of the bug

Both corporate dorm and administration in nexus only has OUTER SECURE STORAGE buttons. Making it impossible to access.

Not sure if this is a bug or a feature as before you could open both the inner and outer provided if you get to those buttons before.

### What's the difference with what should have happened?

There should be an inner and outer secured dorm buttons

### How do we reproduce this bug?

1.Play LV. Check corporate and adminstration. Both are outer 
2.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
There is one inside nexus security armory

**Comment by Huffie56** [comment]
and another one in research.
