### ISSUE TITLE
Toggle Abovehead Chat doesn't save.

### ISSUE THREAD

**Issue by Lagomorphica** [cmss13-devs/cmss13#4101]
### Testmerges

TM doesn't influence it, but latest was #3985, #4024, #3726, #4063, #4067, #4081, #4076, #4097

### Description of the bug

Toggle Abovehead Chat does not save or persist between rounds. I believe this started a while ago with a PR done by BeagleGaming or someone else to change how preferences work? I'm not entirely sure what it changed or if its related at all, though.

I believe this is different to the abovehead chat INDICATOR issue report (https://github.com/cmss13-devs/cmss13/issues/3215), as this one it is actually back on - turning it off again says its been disabled, and it isn't just a visual bug; it's actually been turned back on.

### What's the difference with what should have happened?

Abovehead chat should stay off if you turn it off. It does not stay off if you turn it off.

### How do we reproduce this bug?

1. Turn off abovehead chat.
2. Wait for next round.
3. Abovehead chat back on.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Lagomorphica** [comment]
For clarification this is the runechat that pops up above peoples heads not the typing indicators.

**Comment by Huffie56** [comment]
this issue as already been reported with this issue https://github.com/cmss13-devs/cmss13/issues/3215

**Comment by Lagomorphica** [comment]
They're talking about the abovehead chat *indicator*, not abovehead chat itself. To quote the other issue they made with the same verbiage/description, https://github.com/cmss13-devs/cmss13/issues/3217, 

'The Abovehead Chat Indicator (talky bubble thing) sometimes doesn't go away after your done talking. Reconnecting seems to fix this, which makes me think it might just be a clientside visual bug. It's still very annoying, either way though.'

My issue is Abovehead Chat itself toggling itself back on, which isn't the same as the indicator.

**Comment by Huffie56** [comment]
> They're talking about the abovehead chat _indicator_, not abovehead chat itself. To quote the other issue they made with the same verbiage/description, #3217,
> 
> 'The Abovehead Chat Indicator (talky bubble thing) sometimes doesn't go away after your done talking. Reconnecting seems to fix this, which makes me think it might just be a clientside visual bug. It's still very annoying, either way though.'
> 
> My issue is Abovehead Chat itself toggling itself back on, which isn't the same as the indicator.

https://github.com/cmss13-devs/cmss13/issues/3217
like on this one?

**Comment by Lagomorphica** [comment]
No, my issue is different than BOTH of those issue requests, I'm just using 3217 as an example to demonstrate that they are not talking about the same issue I am.

My abovehead chat *itself* is toggling off, aka runechat. Those two issue reports are talking about the abovehead chat *indicator*, which is what shows up when you are *typing*.

**Comment by fira** [comment]
Is this still a thing? I can see proper saving for Toggle Abovehead Chat in code

**Comment by ItsVyzo** [comment]
Duplicate #3215
