### ISSUE TITLE
Second cluster doesn't turn into pylon on fiorina

### ISSUE THREAD

**Issue by ihatethisengine** [cmss13-devs/cmss13#4109]
### Testmerges

The following pull requests are currently test merged: #3985: 'Xeno endgame content part 1: pylons and larva' by morrowwolf at commit c3b6e3b273  #4063: 'Yautja Change Holder' by realforest2001 at commit e88f1b4fdc  #4067: 'Research Biohazard Lockdown' by realforest2001 at commit 902022485b  #4078: 'Overwatch Console TGUI Refactor' by TheGamerdk at commit 21d918708a  #4081: 'Auxiliary Support Officer' by morrowwolf at commit dc00de1546  #4055: 'New Healer Drone Ability: Sacrifice' by ihatethisengine at commit 95b1c5396e  #3942: 'Updates Yautja Plasma Rifle' by Steelpoint at commit 2b02926713 

### Description of the bug

Queen put cluster on second tcomms tower but it didn't turn into pylon despite her even trying to rebuild it on another tile. So xenos didn't get CAS/mortar protection. First cluster turned into pylon as intended. We already had that issue few days ago and morrow had to replace cluster with pylon manually.
![2023-08-05_11-05-54](https://github.com/cmss13-devs/cmss13/assets/115417687/e3a90816-27c5-48bf-aa1f-9a8cfbfddcfc)

### What's the difference with what should have happened?

Cluster should turn into pylon.

### How do we reproduce this bug?

1. Play Fiorina
2. Wait till 1:35
3. Put one cluster near first tcomms.
4. Put second cluster near second tcomms.
5. It won't turn into pylon.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/3985 link to this PR.

**Comment by morrowwolf** [comment]
Something strange is happening where the signal isn't attaching to the comms relay for weed growth on init. I can't reproduce it consistently but I am aware of it.

**Comment by Drulikar** [comment]
> Something strange is happening where the signal isn't attaching to the comms relay for weed growth on init. I can't reproduce it consistently but I am aware of it.

That signal will only occur if the weeds upgrade (because it deletes the old and places new) or grow there. If you say have a hive core w/ hive weeds, then place pylon, that won't cause the weed growth signal to occur. But could still be something else since I wasn't there for that round.

**Comment by ihatethisengine** [comment]
Hivecore was in engineering. There was no other source of hive weeds. Queen even destroyed the cluster and placed it again, but it didn't help.

**Comment by morrowwolf** [comment]
> > Something strange is happening where the signal isn't attaching to the comms relay for weed growth on init. I can't reproduce it consistently but I am aware of it.
> 
> That signal will only occur if the weeds upgrade (because it deletes the old and places new) or grow there. If you say have a hive core w/ hive weeds, then place pylon, that won't cause the weed growth signal to occur. But could still be something else since I wasn't there for that round.

No like the signal is literally not registering when the comms relay is initiated.

**Comment by morrowwolf** [comment]
Fixed!
