### ISSUE TITLE
Dying doesn't change armor light sprite 

### ISSUE THREAD

**Issue by ihatethisengine** [cmss13-devs/cmss13#4119]
### Testmerges

#3985: 'Xeno endgame content part 1: pylons and larva' by morrowwolf at commit 0821f4107d  #4081: 'Auxiliary Support Officer' by morrowwolf at commit dc00de1546  #4003: 'Brings automatic weaponry to the marine and surv arsenal (also partial ammo economy rebalance)' by Zonespace27 at commit b127bb0bfc  #4063: 'Yautja Change Holder' by realforest2001 at commit e88f1b4fdc 

### Description of the bug

Dying disable lights, but sprite stays the same as if lights were on. 
![2023-08-06_12-44-16](https://github.com/cmss13-devs/cmss13/assets/115417687/18828bcf-1c5f-4276-951f-eed6baa20332)

### What's the difference with what should have happened?

Sprite should be changed to "turned off" state.

### How do we reproduce this bug?

1. Be marine.
2. Wear armor and turn on your lights.
3. Die horribly. 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/79eb8aa9-05b3-45e8-a304-d15e77d88544)
confirmed it's still on

**Comment by fira** [comment]
Could not reproduce for now

Testing methodology: 

Spawned USCM Cryo Riflemen in Briefing
Turn suit light on, expire subjects by application of VV 400 BURN/OXY
Tested both in char and ghosted

**Comment by ihatethisengine** [comment]
Yeah it seems to be fixed, just re-tested it on live server
