### ISSUE TITLE
Solaris Ridge General Store lighting broke

### ISSUE THREAD

**Issue by Smov1** [cmss13-devs/cmss13#4148]
### Testmerges

4003,4063,4035,4104,4134

### Description of the bug

I was in Tcomms duty in general store when lights went out for me and the other fobbit next to me. I had the armor lights and gun light on, so its probably a bug. I had to walk around quite a bit for it to come back to normal.

### What's the difference with what should have happened?

lights should have stayed on. Even if power was cut out, lights from both the gun and the armor should have given us some source of lighting.

### How do we reproduce this bug?

1. Go to general store
2. walk around for a bit in the screenshot's location until it happens.
(Only saw this once)

https://gyazo.com/ba028e9b8c34d81d50df11e0972afc96

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
had some issue with lightning like that but i think it as to do with lag and server issue nothing code wise....
and it's impossible to reproduce outside of main server....
