### ISSUE TITLE
LV-624 safes

### ISSUE THREAD

**Issue by kacperro968** [cmss13-devs/cmss13#4157]
### Testmerges

none which would affect this issue

### Description of the bug

I was playing as an IO on LV-624, we had both the safe combinations for the safes but after putting them in the safes didnt open, the codes weren't mixed up either, i put in both in both safes.

### What's the difference with what should have happened?

It should have openned.

### How do we reproduce this bug?

You can't.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
their is three safes on LV-624 what was the name of the two safes codes you got? @kacperro968

**Comment by kacperro968** [comment]
Yes i did, i also checked the locations and both matched

**Comment by ItsVyzo** [comment]
this has not been reported for over a year, will assume its fixed / a non-issue for now.
