### ISSUE TITLE
A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation

### ISSUE THREAD

**Issue by Alpella18** [cmss13-devs/cmss13#4165]
### Testmerges

#1

### Description of the bug

I have been encountering this bug for months and theres no fix for it i hope someone got a solution

(i did cleared all the internet explorer caches byond caches but nothing worked)

A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation

### What's the difference with what should have happened?

![bug](https://github.com/cmss13-devs/cmss13/assets/142051351/8ccf5495-1f7d-40b5-9618-1a39eab73ffd)

### How do we reproduce this bug?

1.
2.
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
seem like TGUI crashing?? that's weird.

**Comment by Huffie56** [comment]
is it something that happen every-time you join CM server @Alpella18  or is it random?
did you ask for help to admin by ahelping them? or use discord channel called staff help?

**Comment by Alpella18** [comment]
its always happening also asked everyone in game admin discord admin every fricking people but no one got a solutin

**Comment by Alpella18** [comment]
i used staff help chat also talked with admins but no one found a solution

**Comment by Huffie56** [comment]
you could look for similar issue on byond it's maybe a problem of compatibility ....

**Comment by Drulikar** [comment]
See https://github.com/cmss13-devs/cmss13/issues/3846#issuecomment-1627711720

And https://github.com/tgstation/tgstation/issues/55481

**Comment by harryob** [comment]
install IE
