### ISSUE TITLE
Cigars and other Smokeables catch fire if you have a lit one in your mouth

### ISSUE THREAD

**Issue by Youtubeboy139** [cmss13-devs/cmss13#418]
## Description

Cigars and other Smokables will light on fire if you pick one up with a lit Cigar or other smokeable in your mouth

## Difference between expected and actual behavior

It lights smokeables on fire when you grab them by hand. It should not do this.

## Steps to reproduce

Have lit Cigar or other smokeable in your mouth and then simply pick up another smokeable item.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment]
The issue already brought up with #340 
Closing as a duplicate issue.
