### ISSUE TITLE
alamo's control hijack impossible to fix

### ISSUE THREAD

**Issue by piterskiy2** [cmss13-devs/cmss13#4188]
### Testmerges

N/A

### Description of the bug

you can't properly restore alamo's controls after queen locks it down. instead, after finishing the long circle action, it just tells you that the control's are on cooldown for X minutes.

### What's the difference with what should have happened?

certainly not this

### How do we reproduce this bug?

1. queen locks down DS
2. try to unlockdown DS
3. epic fail
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by piterskiy2** [comment]
> Pretty sure there is a cooldown before you can even try to fix a dropship . But fr it should tell you BEFORE attempting the long ass 3minute thing

after waiting for 5 minutes it just fixed itself, i didn't even finish the circle action for the second time

**Comment by Huffie56** [comment]
so this look like a qol just need to put the check for cooldown before you try to take back control....
