### ISSUE TITLE
Lesser Drones Attack feel like it deal less damage than it state in "Status" panel.

### ISSUE THREAD

**Issue by Venuska1117** [cmss13-devs/cmss13#4199]
### Testmerges

N/A

### Description of the bug

Lesser drones got a lot of nerfs, cannot nest, less health and stuff.

But i noticed that it still state you deal "20 slash damage" but when you attack marine and die, they actually got less damage than expected, i dont know if its some armor value, but it feel less damage than before nerfs. (?)

_(i am not 100% sure if this is true, but it feel like damage is less than its stated)_

### What's the difference with what should have happened?

Show "true" value of lesser drones "slash damage"

### How do we reproduce this bug?

1. Be lesser drone
2. Slash marine 3-4 times
3. Die from marine
4. Notice that you deal less damage than normal drone with same slash damage.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Does not appear to be incorrect. 20 damage exactly is performed on an unarmored target: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/715495af-9ba7-4ad9-a0e8-2f4de8eb22cd)
