### ISSUE TITLE
Cryooversight-APC loophole

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#420]
## Description
Building a cryogenic oversight console on APC allows for dispensing of Almayer's cryo goods, even when planetside- APC is in space on Almayer's  z-level I suppose? Also, this means station bounced radio users like survivors can never radio to the VCs because VCs can only hear the Almayer bounced radio.

## Difference between expected and actual behavior
No cryo goods should dispense thru a magic portal

## Steps to reproduce
Build and use a cryo oversight console on the APC

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
Smoke Weed Every Day

**Comment by MidwayAtom** [comment]
APC being removed soon ;)
