### ISSUE TITLE
Overwatch Console Perma Crashes When Loading Foxtrot Squad

### ISSUE THREAD

**Issue by Steelpoint** [cmss13-devs/cmss13#4200]
### Testmerges

#4003 #2536 #4182 #4131 #3865 #4178 #4132 #4196

### Description of the bug

When attempting to make a overwatch console swap to over watching Foxtrot squad, this will result in the console crashing and displaying a error message. This effect is permanent and can not be fixed or resolved in game (such as resetting the CIC APC power)

### What's the difference with what should have happened?

Should be able to interact with Foxtrot squad via overwatch. 

### How do we reproduce this bug?

1. Activate Foxtrot
2. Load them on a overwatch console
3. ...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
not an issue on master, refer to #4178
