### ISSUE TITLE
Macros Ruined my gameplay

### ISSUE THREAD

**Issue by DooMLover222** [cmss13-devs/cmss13#4201]
### Testmerges

#4196

### Description of the bug

So. I Decided i wanted to change some macros for better gameplay, i asked moderators and they gave me the tips. When i managed to "get them to work" Every key i pressed was now being written in the *Say"* tab. EVERY. SINGLE. KEY. I uninstalled and re-installed BYOND. Deleted all macros in cmss13 macros dreambuilder. reconnected more than 5 times in a row and the problem is still there. Any help is appreciated 

### What's the difference with what should have happened?

The damn macros should've worked 

### How do we reproduce this bug?

1. go to BYOND Folders in documents
2. go to Skins folders
3. go to exadv1
3. go to macros (open in dream maker)
4. make whatever macros you want
5. right click game window
6. click macros and select the macros
7. restart

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
literally nothing to do with macros, this is just your “send to chat” preference in character setup

**Comment by DooMLover222** [comment]
> literally nothing to do with macros, this is just your “send to chat” preference in character setup

I already tried it. The problem IS still there. Do i have to remind you that everything i try has no effect?
