### ISSUE TITLE
nutrition constantly declines when heart damage shows symptoms

### ISSUE THREAD

**Issue by Mister-moon1** [cmss13-devs/cmss13#4203]
### Testmerges

not needed

### Description of the bug

an issue caused by https://github.com/cmss13-devs/cmss13/pull/4137 where if the patient has around 10 heart damage, their nutrition will constantly decline no matter how much blood is in the body, this is theorised to because of the overall blood volume lowering and the body trying to generate more blood to get up to the "blood capacity" which does not scale with heart damage

### What's the difference with what should have happened?

nutrition should scale with heart damage if blood volume is to be decreased

### How do we reproduce this bug?

1. spawn 2 humans, 1 as a control variable
2. edit one so it has 10 heart damage
3. check the "nutrition" variable and see how the human with heart damage has considerably less nutrition than the other

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
This is not a bug. It does need changing around a bit though.
