### ISSUE TITLE
Whiskey outpost chemistry: smart fridge not connected

### ISSUE THREAD

**Issue by TormodS** [cmss13-devs/cmss13#4207]
### Testmerges

I assume it has always been like this. Not newly introduced.

### Description of the bug

See title. 

When smart fridge is not connected, I have to manually go and insert every produced pill bottle, leaving the work station.

### What's the difference with what should have happened?

Smart fridge should be connected at start. There is a "connect smartfridge" button, but it doesn't work and engies are busy on WO

### How do we reproduce this bug?

1.
2.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
/obj/structure/machinery/smartfridge/proc/is_in_network()
	return networked && is_mainship_level(z)
	
seem it require to be on the main ship level to have any hope to work .....
