### ISSUE TITLE
Happy birthday steve banner spelling error (HORRIBLY IMMERSION BREAKING)

### ISSUE THREAD

**Issue by hotimep** [cmss13-devs/cmss13#421]
## Description
THE HAPPY BIRTHDAY STEVE BANNER'S DESCRIPTION SHOULD **NOT** SAY "A depressed looking paper banner wishing someone named Steve a happy birth ay"!!!! and i FEEL the MOMENT i OBSERVED THIS HORRIBE banner my IMMERSION was IMMEDIATELY BROKEN and I INSTANTLY started LOW ROLEPLAYING

## Difference between expected and actual behavior
it should not say this
![faac95ee248feb1361b3b871ef57aeda](https://user-images.githubusercontent.com/59359762/171803457-814a14e0-9d3a-493f-a65f-c120baf2ee30.png)

## Steps to reproduce
observe the happy birthday steve banner on kutjevo

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
Intended
