### ISSUE TITLE
Improper Pipe placement

### ISSUE THREAD

**Issue by TR-Blackdragon** [cmss13-devs/cmss13#4213]
### Testmerges

c427580e166ea9ed107ced55990f89d17ea33e59, #4003, #4182, #4131, #3865, #4035, #4111

### Description of the bug

there is a T pipe 1 tile above the research door that is flipped arrow is facing up, So when you flush either of the two disposals in Research it just ejects it out the other disposal in research.

### What's the difference with what should have happened?

When flushing items down disposals it should send it threw the disposal system and not eject it back out in research. The T disposal Pipe should have its arrow facing Down

### How do we reproduce this bug?

1.Place something into research disposal chute
2. Flush the disposal chute
3.Watch as contents eject out of other research disposal chute
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by LC4492** [comment]
This bug is being already looked at by PR #4096, there are much more missplaced pipes than you could ever think of.
