### ISSUE TITLE
Research Chemical Duplication

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#4220]
### Testmerges

#4003: 'Brings automatic weaponry to the marine and surv arsenal' by Zonespace27 at commit db622ab58d #4182: 'Project ARES: Admin Console' by realforest2001 at commit cb4d9713bb #4131: 'Telephones Networking' by realforest2001 at commit 992e759b1a #3865: 'New UPP guns' by CapCamIII at commit 2b2ba4a34e #4035: 'Faction Access & Almayer Security Overhaul' by realforest2001 at commit 59b87453d9 #4111: 'Project ARES: Functional Access Tickets' by realforest2001 at commit da5106e9a2  Local commit: 30805a71e553a9fbfc906da9a86a1ac83725f70d TGS version: 5.13.7

### Description of the bug

You can mix chemicals in a certain way to duplicate them and massively overload containers

### What's the difference with what should have happened?

it probably shouldn't double for free

### How do we reproduce this bug?

1. produce two variants of the same base chemical by relating, or amplifying or suppressing.
2. Add 420u of one variant to a janitor bucket
3. Add 20u of each of the three reagents of the other variant to the bucket
 (if all was working correctly, the bucket should be filled with 450u of variant two)
4. Something magical will happen intsead, the bucket will be filled with 900u of variant two, exactly double.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
i dont quite understand but . we do have a mechanic that basically absorbs older variants into new variants or smth like that

**Comment by Weuyn** [comment]
Yeah and it works except when the container is nearly full, then instead of absorbing it doubles the volume and goes way over the containers capacity. 900u in a janitors bucket that can usually only hold 500u!

**Comment by Huffie56** [comment]
damn why are you closing everyone of your PR @Weuyn ?
