### ISSUE TITLE
Resisting fire as zoomed out trapper boiler causes speed to remain at the zoomed out state.

### ISSUE THREAD

**Issue by UntoldTactics** [cmss13-devs/cmss13#4228]
### Testmerges

#4003 #4131 #3865 #4035 #4063 #4224

### Description of the bug

If you zoom out as a trapper boiler, you are slower than when not zoomed out. If you get set on fire and resist whilst zoomed out, it'll knock you out of zoom, but it will not return your speed to the regular values. Notably just zooming and unzooming won't fix this for whatever reason.

### What's the difference with what should have happened?

Trapper speed should be reset to non-zoomed out values when they resist fire and are knocked out of zoom state.

### How do we reproduce this bug?

1. Be a boiler, select trapper strain.
2. Zoom out and get set on fire.
3. Resist whilst on fire and zoomed out. Now you are slow.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
https://github.com/cmss13-devs/cmss13/issues/3385

Its an ongoing bug. Many other actions other than resisting fire can still cause the slowdown. 
The only way I have found to fix the bug in game is to eat a gardener drone's alacrit fruit as it will speed you up then reset you back to normal speed when it expires.

**Comment by Drulikar** [comment]
Should be fixed with #6177 Let us know if you still have issues with boiler speeds.
