### ISSUE TITLE
Research chemical combination limit

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#4235]
### Testmerges

 #4003: 'Brings automatic weaponry to the marine and surv arsenal' by Zonespace27 at commit db622ab58d #3865: 'New UPP guns' by CapCamIII at commit 31c3087cbb #4063: 'Yautja Change Holder' by realforest2001 at commit 377eeb300e #4224: 'ARES Change Holder' by realforest2001 at commit 06e5019359 #4178: 'Overwatch Console TGUI Refactor' by TheGamerdk at commit 815c2114e3 #4067: 'Research Biohazard Lockdown' by realforest2001 at commit a71df9125d #4229: 'fancy lighting' by harryob at commit c596140e96 #4231: 'Changes nutrition with blood loss' by morrowwolf at commit 2b93749d54

### Description of the bug

when having a research chemical combination (in this case, defibing), if there are more than 4(?) chemicals, one of the chemicals (Neogenetic, MST) will be deleted. it might also reduce the levels (sometimes??)

![image](https://github.com/cmss13-devs/cmss13/assets/54422837/0905f6e8-058d-428b-8373-949f943f9684)

### What's the difference with what should have happened?

when a chemical combines, it'd only take as many levels as it can take/until it's full (MST 8 and CDP 1 should combine into MST 7 + defib 2).
and also for it to delete other chemicals in the paper

### How do we reproduce this bug?

1. get a lot of research credits
2. add MST
3. add CDP
4. add any other effects
5. hit print
6. notice that a effect may or may not have vanished from your paper
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Seeing as Research Synthesizes has been made into a TGUI and this has not been reported in over a year. Closing.
