### ISSUE TITLE
New Lighting breaks Camera vision

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#4236]
### Testmerges

#4229

### Description of the bug

Brought Alamo console down to FOB, built several cameras from camera assemblies. Seems like a failure to update but not sure if maybe since it was dark when I built the cameras, that they got stuck that way- 

Either way makes it impossible to see through cameras.

https://youtu.be/TMU8LxZptyo In this video, I basically go back and forth trying to get the FOB S Camera to update, but it just won't. 

### What's the difference with what should have happened?

Should have seen cool lighting through Cameras, saw darkness instead.

### How do we reproduce this bug?

Build cameras ala this video https://youtu.be/TMU8LxZptyo

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
testmerge issues can be posted on that pr, regardless, this is fixed
