### ISSUE TITLE
Incredibely Buggy Textures

### ISSUE THREAD

**Issue by DooMLover222** [cmss13-devs/cmss13#4237]
### Testmerges

.

### Description of the bug

So. Apparently it's because a stress light thing. It happened for one round 2-3 days ago, after that everything went back to normal. I Talked to an admin to see if the issue can be corrected because it's the 3rd round in a row that this crap has been going on. Admin gave me some tips, None worked. He told me that this stress lightning may be kept on FOREVER. This must have a button to toggle it. ¿It should be optional to have it because it fucks up gameplay a lot (for me). HOWEVER. Being a Ghost removes all of the buggy textures. 

### What's the difference with what should have happened?

I Have no idea. 

### How do we reproduce this bug?

1.
2.
3.
...
.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
This is the epitome of "how not to do a bug report." Come back with examples and a better attitude.

**Comment by Zonespace27** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/41448081/821c88e1-4b73-4589-838e-374f21be968b)

This is what he was talking abt btw

Win7
Dx9 reinstallation attempted, didn't work
