### ISSUE TITLE
Incredibely Buggy Textures. (2)

### ISSUE THREAD

**Issue by DooMLover222** [cmss13-devs/cmss13#4238]
### Testmerges

#4229 "fancy lightning"

### Description of the bug

Ever since the stress lighting thing started, my textures have been glitched out incredibely. They have a very dark violet transparent color in almost every single block, Looks "unrendered" too. After the first test (where mods told there would be bugs) I Was able to play normally, happy ending right? No. I Looked for help and contacted an admin via discord, sent my screenshot of the problem and he gave me some tips that unfortunatly did not work. He told me that this may be kept on FOREVER. So im practically BEGGING to the devs to make this a toggable function because for some people may work and for others may not, that includes me. I Cannot play it anymore and the only way to "play" without these textures is being a ghost. I Don't have anything more to try. 

![BUG TEXTURES](https://github.com/cmss13-devs/cmss13/assets/122133092/027a35dd-4b7d-435e-850a-1ef375200929)

### What's the difference with what should have happened?

If it's callend fancy lighting i guess it should've been like a dynamic lightning of some sort? I Can't really tell because i can't see it. All i see is glitchy textures

### How do we reproduce this bug?

1.Join the game as USCM 
2.The glitchy textures appear
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Alright so again, examples and pictures are gonna be a requirement here or we cannot help. This being a toggle feature is not going to happen.

**Comment by DooMLover222** [comment]
> Alright so again, examples and pictures are gonna be a requirement here or we cannot help. This being a toggle feature is not going to happen.

In the closed thread of mine with the same name there is an image of what is happening to me. In the replies section. So you're just gonna let me down?

**Comment by DooMLover222** [comment]
> Alright so again, examples and pictures are gonna be a requirement here or we cannot help. This being a toggle feature is not going to happen.

![BUG TEXTURES](https://github.com/cmss13-devs/cmss13/assets/122133092/e3e203a3-07e3-44bb-95da-7402253ee461)
That's what happens when i try to upload a pic. so i couldn't upload one, thanks to Zonespace you can see my issue via image

**Comment by morrowwolf** [comment]
What version of byond are you on? Try clearing both your byond cache and temporary internet files as well.

**Comment by DooMLover222** [comment]
> What version of byond are you on? Try clearing both your byond cache and temporary internet files as well.

Well my friend, i cleared byond cache and updated to the newest version to fix my interfaces, less than 5 days ago i did that. I Don't think i have any temporary internet files either. I Don't know if this helps but it happened to me some time ago with the server "Goonstation". Can't really tell you if it is still behaving the same, i can't play it anymore...

**Comment by Drulikar** [comment]
What is "latest" version? The latest stable aka 154.1589 or latest beta aka 515.1613. Whichever you're on, try the other. If neither, then try both and tell us what you are on, and if it has any effects.

Past that it would be helpful to know what graphics card you are using (even if you have no dedicated graphics - then what is your integrated graphics aka CPU), and have you already tried updating the drivers for your dedicated graphics or integrated graphics (whichever you are using)?

Finally, is this windows 10? Windows 11? Or some flavor linux via wine? Or what operating system?

**Comment by DooMLover222** [comment]
> What is "latest" version? The latest stable aka 154.1589 or latest beta aka 515.1613. Whichever you're on, try the other. If neither, then try both and tell us what you are on, and if it has any effects.
> 
> Past that it would be helpful to know what graphics card you are using (even if you have no dedicated graphics - then what is your integrated graphics aka CPU), and have you already tried updating the drivers for your dedicated graphics or integrated graphics (whichever you are using)?
> 
> Finally, is this windows 10? Windows 11? Or some flavor linux via wine? Or what operating system? (From Zone in the other issue sounds like Windows 7 and possibly directx 9 redistributable was reinstalled?)
> 
> PS: You're the _only_ person to report this problem so far, so it is highly likely it has something to do with your machine/drivers/configuration/etc.

i have the latest stable! I Am gonna try with the beta to see if there's a difference. I Forgot to mention that when i played the last minutes of a round as a xenomorph the textures where completly fine. I Think it's only when i play as human that happens. I play this with my Old PC, Windows 7 and the drivers are all updated. I Think it's an issue with my computer now that i've read your comment. I'll play as xeno in the beginning of a round to confirm my theory. thnx

**Comment by Huffie56** [comment]
@DooMLover222 is it still happening?

**Comment by Huffie56** [comment]
going to close that since no answer feel free to reopen it if you have still the same issue.
