### ISSUE TITLE
Humans can no longer grab new targets with a filled mainhand

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#4248]
### Testmerges

that xenomorph grab PR

### Description of the bug

You can't swap what you are grabbing with your offhand without swapping hands, dropping the grab and grabbing the next thing. Feels awful and clunky. 

### What's the difference with what should have happened?

Grabbing a new thing should replace an existing grab even if that grab is in the offhand

### How do we reproduce this bug?

1. have gun in mainhand
2. grab one dead body, pull it
3. try to grab another dead body, it doesn't work any more you have to drop the old grab first.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Cannot reproduce on master, on #4246, or on 959f06a52ad706e88c59217f8b2034db47e20c03 (current tgs commit with all TMs). Reproduction steps maybe unclear/unspecific enough? https://youtu.be/PM3t3FyCOGg

**Comment by ItsVyzo** [comment]
They're probably referring to how you can only grab one thing and if you try to grab something else it doesn't override the current thing you're holding.

In other words, you have to empty your hand manually. Or they're referring to how you can only grab one thing at a time.

Anyhow, this is not a bug. It's just how grabbing always worked in SS13.
