### ISSUE TITLE
Camera bug with M56D and Pistol belt on suit storage

### ISSUE THREAD

**Issue by PurpleCIoud** [cmss13-devs/cmss13#4249]
### Testmerges

#3865  #4063 #4224 #4229 #4231 #4246 #4131

### Description of the bug

Vision bug with Mounting a M56D when re-equiping certain equipment

### What's the difference with what should have happened?

Vision should not multiply twice, However it does

### How do we reproduce this bug?

Build and mount a M56D whith armour and a full pistol belt (may work with any weapon),
Remove armour while mounted,
Put armour back on and pthe pistol belt

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
is this still a thing?

**Comment by PurpleCIoud** [comment]
It seems to be fixed now, but I was able to make it happen 2 rounds in a row when I posted this issue

**Comment by Huffie56** [comment]
> It seems to be fixed now, but I was able to make it happen 2 rounds in a row when I posted this issue

thanks
