### ISSUE TITLE
CMP's M3 armor

### ISSUE THREAD

**Issue by Rubenbl4des** [cmss13-devs/cmss13#4252]
### Testmerges

#3862 #4063 #4224 #4229 #4231 #4246 #4131 It's probably #4229

### Description of the bug

So basically the CMPs armor's light doesn't work with the new lighting system EXPECT when you take it off, turn it on while it's off, then put it back on. But aside from that, you have it instantly out of cryo and when you try to turn it on, it does nothing.

### What's the difference with what should have happened?

You should be able to turn it on normally.

### How do we reproduce this bug?

1. Be CMP
2. Try to turn on the armor's light (it shouldn't work)
3. Take off the armor, turn it on, then put it back on (then it should work)
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
This is from a TM not an issue on master, so either could be mentioned on the PR itself or via PR feedback at https://forum.cm-ss13.com/w/pr-feedback/steps/step_1

Regardless, this does not appear to be an issue as of https://github.com/cmss13-devs/cmss13/commit/52a089e7b4bc60beb011ff44e8cd62cee376a146 or maybe one of the other commits around it.

**Comment by Rubenbl4des** [comment]
That's good, thanks for clearing it up!
