### ISSUE TITLE
Pointblank shotgun not working

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#4260]
### Testmerges

#4063: 'Yautja Change Holder' by realforest2001 at commit 377eeb300e #4224: 'ARES Change Holder' by realforest2001 at commit c7db9b4801 #4229: 'fancy lighting' by harryob at commit b54aca6326 #4246: 'Move xeno grab cooldown change to just ctrl+click logic' by Drulikar at commit d4a4aebeea

### Description of the bug

I don't know what was happening, but point-blanks just were not shooting at all. You would click the target in PB range, then it would not shoot.

### What's the difference with what should have happened?

Pointblank shots should shoot.

### How do we reproduce this bug?

1. Grab a shotgun, fill with buckshot
2. Try to PB a corpse (this is how i tested it.)
3. It does not shoot
4. Try to PB something alive
5. It does not shoot

//

Tested this with other people: PBs just weren't working, at least on the Xeno corpses I tested it on. Round ID was 18354 if that helps. 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
True, fix coming up.
