### ISSUE TITLE
Rail Lights Don't Work

### ISSUE THREAD

**Issue by fighterslam** [cmss13-devs/cmss13#4262]
### Testmerges

#4063, #4224, #4229, #4246 

### Description of the bug

Putting a rail light on a gun works. You can turn it on.

Holstering it in your armor or back slot turns it off and it has to be turned on again. I'm assuming this is a side effect of the fancy lighting PR. Also, rail lights are directional now, though I think that's intentional. 

### What's the difference with what should have happened?

The lights have always stayed on when being holstered. 

Not having access to a light/having to sacrifice a pouch slot/belt slot for a weak flashlight is a massive nerf which I don't think is intentional. 

### How do we reproduce this bug?

1. Get a gun with a rail light. Turn it on.
2. Holster it. The light turns off. 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Weuyn** [comment]
soul and intentional, the rifle should need to be held to provide light

**Comment by harryob** [comment]
i entirely intended this
