### ISSUE TITLE
!!! TABLE TOP CONTENTS ARE MISALIGNED WITH SPRITES !!!

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#427]
## Description
Let's say I'm a CT in Req. I throw a pouch on the table- that's fine. If I LClick to play the pouch on the table though, it's difficult to locate where the object 'really' is. Alt click of course usually circumvents the issue but a couple times I have been forced to deconstruct because it outright would not show the table/tile's contents

## Difference between expected and actual behavior
Object should land where I click on the table, and myself and others ought to be able to intuitively pick up things placed on top of tables- like, this has been an issue for a couple of months now and it's driving me bonkers.

## Steps to reproduce
Place something on a table and ponder where is it really at now . . . 

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues) I didnt see one anyway

**Comment by Segrain** [comment]
>If I LClick to play the pouch on the table though, it's difficult to locate where the object 'really' is.

What exactly is difficult in this scenario?
>Object should land where I click on the table

They do.
>myself and others ought to be able to intuitively pick up things placed on top of tables

What exactly is wrong with picking it up as things are now?

**Comment by nuklearcellphoneg** [comment]
So I've spent about a month trying to consistently reproduce this, and I can't seem too. 

1. Sometimes when a CT places something on the table and I pick it up, the sprite remains- if i place it back on the table, it updates the sprite to where I place it, then when I pick it up again, the sprite properly updates and disappears from the table. Spent a month trying to be vigilant and pay attention to what causes this/if it's item specific or what, but it's super rare(but about a month ago it was happening frequently enough to make this issue) 

2. IMO: has to do with those Req line tables, something to do with picking up something someone else put on the table, but did not throw on the table, or it may be item specific?

3. Sometimes when they place something on the table and I go to pick it up, I'm unable to pick it up by clicking the sprite. I have to alt click and pick it up from the tile contents list and I'm not sure 'where' to click to pick it up. Very unsure what causes this, maybe a separate item specific issue

**Comment by nuklearcellphoneg** [comment]
Feel free to close though, I can't seem to reproduce it on my own.

**Comment by nuklearcellphoneg** [comment]
![image](https://user-images.githubusercontent.com/6540760/179167635-407a922b-1d8e-4c61-b850-5599215fddc1.png)
