### ISSUE TITLE
Death while being healed, not taking damage

### ISSUE THREAD

**Issue by Katskan** [cmss13-devs/cmss13#4279]
### Testmerges

#4229, #4246, #4224, #4253, #4063

### Description of the bug

Received a tail stab, had enough time to walk 2 tiles, put myself into a synthetic maintenance station, and receive 2 messages about structural damage being repaired before dying while inside the station. Did not take any more damage, as that is impossible while inside the maintenance station until it is destroyed. 

### What's the difference with what should have happened?

Die at the time of receiving damage

### How do we reproduce this bug?

1. Take presumably lethal damage as a synthetic
2. Walk, take no more damage
3. Put self in charger
4. Die?

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Please confirm if this is reproduced in other rounds

**Comment by Katskan** [comment]
I've had similar happen in other rounds but it's very hard to make happen on-demand because of that very niche circumstance of damage->heal->die. I suspect it happens more often than realized because normally the heal part is missing. 18393 for the round

**Comment by ItsVyzo** [comment]
Could not reproduce. Let me know if it still happens.
