### ISSUE TITLE
Research chems unmodifiable 

### ISSUE THREAD

**Issue by Shadowfgt** [cmss13-devs/cmss13#4285]
### Testmerges

#4246, #4224, #4063, #4274, #4178, #4241, #4280

### Description of the bug

It seems research chems that are not scanned from the random ones on the colony are unable to be amplified, suppressed, or related.  Deltulizine was scanned from a vial an IO brought while the Awoster was scanned from a plant.
![Capture](https://github.com/cmss13-devs/cmss13/assets/10481668/4d49fb7b-dfd2-499a-881b-bd1bbb4616c8)
![Capture2](https://github.com/cmss13-devs/cmss13/assets/10481668/e7925590-5967-42ef-a24b-485beac83fae)
![Capture3](https://github.com/cmss13-devs/cmss13/assets/10481668/5f5b5667-54a6-4f07-a17a-1832959e0478)

### What's the difference with what should have happened?

To be able to modify chems

### How do we reproduce this bug?

1.Either make your round start paper chem or scan chems from plants
2.Try to use resulting analysis paper to modify chem
3.Be told you can not
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Weuyn** [comment]
There are no properties on the target chemical in the screenshot you provided. Did you fuck with the vial after scanning it? Empty it or something? Never do that, it bricks all the papers.

**Comment by Shadowfgt** [comment]
Seem you are right. I tested it just now where I scanned a chem and it was fine but as soon as I empty the vial I scanned it broke the analysis.

**Comment by ItsVyzo** [comment]
Seeing as Research Synthesizes has been made into a TGUI and this has not been reported in over a year. Closing.
