### ISSUE TITLE
Zombies can modify Sec Records

### ISSUE THREAD

**Issue by drawsstuff** [cmss13-devs/cmss13#4309]
### Testmerges

#4246 #4224 #4063 #4290

### Description of the bug

Zombies can modify security records

### What's the difference with what should have happened?

Undead colonists (lacking ID mind you) should not be able to do this

### How do we reproduce this bug?

1.Spawn in as zombie
2.Kill your desired Unga Dunga (in this case I am unable to grab details because my chat log is full of zombies doing push ups
3.Examine them
4.Description should come up, with the relevant "add" button near security records
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by drawsstuff** [comment]
Attaching relevant recording 

https://github.com/cmss13-devs/cmss13/assets/16404218/fbd3e721-d6ce-427b-926e-ab1e1c7c3a64

**Comment by Huffie56** [comment]
can't reproduce it
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/94ad57cd-02f0-4bfe-b185-0d45439d5af4)

probably was caused because your zombie eyes worked as security HUD....?

**Comment by Cthulhu80** [comment]
@Huffie56 it was fixed in the mentioned pr.

**Comment by Huffie56** [comment]
feel free to tag me if anyone can confirmed the bug as happen recently(current month.)

**Comment by Cthulhu80** [comment]
The issue isn't just zombies. If a user puts on hud glasses and then removes them it still displays it. Same thing with medical.

**Comment by Huffie56** [comment]
> The issue isn't just zombies. If a user puts on hud glasses and then removes them it still displays it. Same thing with medical. Is this intended?

i need more info to respond but if you think their is a more general issue(bug or inconsistency (with the code or in term of logic)  with hug glasses you should open an issue for it.
thanks for confirming this bug is real and fixing it.
