### ISSUE TITLE
People Dying Well Before The 200 Damage Threshold

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#4323]
### Testmerges

Issue seen over months with many test merges in those months.

### Description of the bug

People are rarely dying before reaching 200 total damage. I cannot replicate this bug on demand but have noticed it most on survivors dying while getting capped the second they hit pain crit at ~150 damage though I have also seen dead marines with this problem as a medic that scans many bodies. The death also does not seem correlated to organ damage or broken bones being present. Attached is one such survivor I found before being treated that died prematurely:
![Not Dead At 200](https://github.com/cmss13-devs/cmss13/assets/105765670/32784287-a102-4539-9db5-12770a1361cb)

### What's the difference with what should have happened?

People should not be dying inexplicably. Sometimes with minor damage. This bug has strong implications for capturing wounded marines that just suddenly die. I had reported a similar problem with spitter acid causing instant death well before 200 damage long ago on the old gitlab but am noticing the problem much more often lately.

### How do we reproduce this bug?

I really wish I could give a step by step to replicate this bug. I have tried and failed to determine a cause in game. Every time I ask how a person I find with this bug died, they report entirely unrelated causes such as from crusher slashes, boiler gas, explosions, friendly fire, etc. In more than a dozen cases, I can not find a pattern but hopefully someone here can.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by BeagleGaming1** [comment]
Are you sure it's not being caused by excessive pain? If you have too much pain when you get dragged/devoured it can deal oxy damage or kill you outright.
