### ISSUE TITLE
M56D Bugs

### ISSUE THREAD

**Issue by TeDGamer** [cmss13-devs/cmss13#4343]
### Testmerges

#4336

### Description of the bug

#4336 should be the only TM causing these bugs.

Shooting while hugged

Shooting perpendicular

### What's the difference with what should have happened?

Once you're hugged and unconscious, you shouldn't be on the m56d and you shouldn't be able to shoot

I don't remember M56D being able to shoot perpendicular. I thought it was always a forward arc

### How do we reproduce this bug?

1. Get on M56D
2. Hug the person on the M56D
3. Fire the m56d

1. Shoot at a right angle

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
You always was able to shoot ALMOST perpendicular, nothing changed in this regard.

**Comment by Zonespace27** [comment]
Could not reproduce.

**Comment by TeDGamer** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/107966994/b7ec1478-40a1-4b57-a111-2cd64ccc3062)

Umm, people are able to shoot without  being on it

**Comment by ItsVyzo** [comment]
@TeDGamer make another issue
