### ISSUE TITLE
M2C no longer rotates with middle mouse click.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#4346]
### Testmerges

#4224, #4063, #4314, #4332, #4335, #4253, #4336,

### Description of the bug

Upon pressing the middle mouse button down the M2C no longer faces a direction. I suspect this bug was introduced with #4336 due to patches made for the M56d's own rotation issues

### What's the difference with what should have happened?

M2C should rotate upon middle clicking as it used to

### How do we reproduce this bug?

1. place an M2C down, and attempt to rotate it by middle clicking.
2. it no longer rotates.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment]
Due to the new way that the M2C and M56D's firing is handled, this isn't something that can be fixed while keeping the code quality good. Besides, you can rotate the M2C without firing with LMB regardless. Won't fix.
