### ISSUE TITLE
Auto Fire Not Giving Accurate Numbers On Rounds That Connect

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#4348]
### Testmerges

Local commit: b7e94607d2105a18c95b64e8c54c178c91630cb8 TGS version: 5.15.1 DMAPI version: 5.6.1

### Description of the bug

Auto fire, especially now that it is the default fire mode for many weapons, allows marines to fire many rounds easily. However, being on the receiving end of auto fire is currently only showing the first round you are hit by with all subsequent rounds not being shown to the receiving player in chat logs until the firing source begins a new instance of auto firing.

### What's the difference with what should have happened?

Players should have accurate logs for what happens to their character. Both semi and burst fire report each bullet that strikes you. Auto fire should do the same beyond the first round that hits something.

### How do we reproduce this bug?

1. Be xeno.
2. Get shot at by someone using auto fire to hit you multiple times in the same firing instance.
3. Observe your chat logs to count how many bullets struck you and compare it to the damage you sustained.
4. Start using burst fire because its the best.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment]
Not a bug, it's coded this way to reduce client-sided lag from getting shot by many sources in a short timeframe. If you want to make a better logic system for this, you're welcome to (might get to it myself eventually but no guarantee).

**Comment by Superwelder** [comment]
> Not a bug, it's coded this way to reduce client-sided lag from getting shot by many sources in a short timeframe. If you want to make a better logic system for this, you're welcome to (might get to it myself eventually but no guarantee).

Unfortunate. Already this has been a problem for me trying to find who is committing massive FF in a group and overall judging how potent a gun is by reading logs at a later time. If the trade is less transparency to the player for reduced lag with this specific mechanic then so be it.
