### ISSUE TITLE
Minor Grammatical Issue on a Item.

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#435]
## Testmerges:

N/A

## Description
Minor spelling mistake on the 'requisitions officer uniform.' It has a period at the end when it should not.

## Difference between expected and actual behavior
Small text issue, not impactful to gameplay.

## Steps to reproduce
Get the 'requisitions officer uniform.'

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
Included in BugBash 3

**Comment by tempelers** [comment]
@PhantomEpicness Can you also take a look at the other RO items? It seems some of them might have more grammatical errors.
