### ISSUE TITLE
Flare gun's unique ability to shoot flares in the sky does not produce a light

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#4359]
### Testmerges

N/A

### Description of the bug

As per title.

### What's the difference with what should have happened?

Well it should.

### How do we reproduce this bug?

1. Load a flare gun.
2. Use unique action on it.
3. Have it fire into the air.
4. See that it doesn't work.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
How could they do this
