### ISSUE TITLE
[BUG] Broken DS sentries - Electric Boogaloo 2

### ISSUE THREAD

**Issue by 128th** [cmss13-devs/cmss13#436]
## Description
DS modular sentries and engineer's hand-held devices do not trigger on xenos after / or during DS transit.

## Difference between expected and actual behavior
Subj. Some modules and hand-held devices should work like under normal conditions, but for some reason those hand-held devices and modules cease to function at some point.

## Steps to reproduce
1) Install sentry as a module or place it as a hand-held device on Alamo or Normandy. 
2) Activate it. 
3) Complete cycling from surface to ship or from ship to surface.
4) Upon landing or during transit sentries would stop registering xenos as a targets, until you manually re-deploy them with multi-tool (in case of engineer's devices).

It's an old issue about which I reported 1 year ago, but didn't got any response, so it still present - https://gitlab.com/cmdevs/colonial-warfare/-/issues/537.
## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
This will need clarification from a developer, however I believe this may be in part - whilst perhaps unintended - a feature of the game, considering I don't think it's supposed to be possible - the module sentries aside - to fortify the dropships in any manner.

**Comment by Chrismmar** [comment]
i was about to report this bug, but i see its being ignored

**Comment by Huffie56** [comment]
@harryob i think this is intended to work like that and it's not an issue... what do you think ? can we close it?

**Comment by Huffie56** [comment]
so this is two issue in one.
1-we shouldn't be able to deploy deploy able sentry inside vehicle and that also mean DS.
2-DS modular sentries should keep working as long as the PO don't retract them.
