### ISSUE TITLE
Alt + click on certain items loads all the image files for some reason

### ISSUE THREAD

**Issue by TeDGamer** [cmss13-devs/cmss13#4369]
### Testmerges

#4224, #4063, #4336, #4352, #4353, #4354, #4344

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/107966994/7f7434c2-6829-419e-904b-07cbfc4f6a5e)

### What's the difference with what should have happened?

Only show the approriate image

### How do we reproduce this bug?

1. Alt click items. Some of them show multiple items

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
This allegedly should help with this: https://github.com/cmss13-devs/cmss13/pull/4287

Once it's not blowing up the server.
