### ISSUE TITLE
xeno tunnels and eggs are not converted to forsaken 

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#4376]
### Testmerges

happened a while ago, and haven't played forsaken since, so i have no TMs to list.

### Description of the bug

play forsaken xeno
attempt to use tunnel
instead prompts you to destroy the tunnel (which fails because you're a drone)

### What's the difference with what should have happened?

play forsaken xeno
attempt to use tunnel
enter tunnel

### How do we reproduce this bug?

1. make tunnels/on a map with tunnels roundstart
2. launch alamo to turn all xeno weeds into forsaken weeds
3. spawn as forsaken xeno
4. try to use tunnel
5. cry
...

### Issue Bingo

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by TeDGamer** [comment]
Eggs and larva ( in infected poeple) as well aren't changed to forsaken.

**Comment by private-tristan** [comment]
Actually, those who are infected BEFORE hijack on the ground are properly converted to forsaken, but any new hugs using eggs already planted (at hive or around the map from hugger traps/eggsac eggs) will give base hive huggers.
 The only way to get forsaken huggers is to make a egg morpher and fill it.

**Comment by Huffie56** [comment]
the conversion as been first introduce by this PR so it's a good start if someone want to fix it i guess...
https://github.com/cmss13-devs/cmss13/pull/3685
