### ISSUE TITLE
Hive Status Null Error

### ISSUE THREAD

**Issue by TeDGamer** [cmss13-devs/cmss13#4397]
### Testmerges

#4379, #4182, #4378

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/107966994/9edcf2f8-f9a8-4d9c-9d17-e6c6ef949d62)

Just happened in this round. Attempting to access hive status didn't seem to work. 

Was working earlier with second queen but then it stopped.

### What's the difference with what should have happened?

Show regular hive status

### How do we reproduce this bug?

Not sure how to replicate

1.  Click hive status

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by TeDGamer** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/107966994/68319127-ef80-48b6-b038-f8d054259346)

**Comment by private-tristan** [comment]
typically happens when there's lots of xenos (starts breaking around 35-40+ or so?

**Comment by SabreML** [comment]
I get this pretty often too.
It looks like the error is coming from line 31 of `HiveStatus.js`, where the `nicknumber` isn't an entry in `xeno_info`. Although I'm not sure what could be causing a someone to be in `xeno_keys` but not `xeno_info`, considering both loop through `totalXenos` in the same way.
https://github.com/cmss13-devs/cmss13/blob/609dd8d7d7eafa7514c24fcae974061adb635c7b/tgui/packages/tgui/interfaces/HiveStatus.js#L27-L41

**Comment by SabreML** [comment]
Should have been fixed by #5249. @Huffie56

**Comment by Huffie56** [comment]
> Should have been fixed by #5249. @Huffie56

yep thanks PR wasn't link to this issue.
