### ISSUE TITLE
Unable to build on pylon weeds ( when pylon weeds grow in usually unweedable areas )

### ISSUE THREAD

**Issue by TeDGamer** [cmss13-devs/cmss13#4407]
### Testmerges

#4379, #4182, #4378, #4400, #4402, #4405, #4406

### Description of the bug

Happened multiple times in LV rounds. Comms are placed in unweedable areas so the only way to grow the weeds is to pylon it.

However, once the weeds grow, it prevents building of anything defensive so you're shit out of luck if a marine knows this and sets up a turret facing the defenseless pylon.

### What's the difference with what should have happened?

Allow building on weeds

At least expand the  buildable area, comms are way too close to water and unweedable grass so basically hard to do defense on LV compared to other maps.

### How do we reproduce this bug?

1. Pylon NE LZ1 comms on LV
2. Attempt building on new weeds

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
LV624 west and east river crossing towards the LZs are on the list to be looked at.

**Comment by Huffie56** [comment]
i think it was fix recently by https://github.com/cmss13-devs/cmss13/pull/4469
