### ISSUE TITLE
C4 fitting in medkit

### ISSUE THREAD

**Issue by harry3124** [cmss13-devs/cmss13#4408]
### Testmerges

[29a64c896c9639b1b4b4e2009b92e8630e4eece4](https://github.com/cmss13-devs/cmss13/commit/29a64c896c9639b1b4b4e2009b92e8630e4eece4)

### Description of the bug

C4 can fit in the medkit.

### What's the difference with what should have happened?

Shouldn't be fitting in medkit, allowing the marines to gather up C4s in the medkit then put it in a medkit pouch.

### How do we reproduce this bug?

1. Put a C4 out
2. Put it in a medkit
3. Put that in the medkit pouch
4. Put that in your pocket
5. Prepare for drop, see if you got a rifle or a shotgun

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment]
Not a bug. Medkits can fit a lot of non-medical supplies.
