### ISSUE TITLE
Lesser Drone spawning issue when both pylons in same area

### ISSUE THREAD

**Issue by Madventurer** [cmss13-devs/cmss13#4424]
### Testmerges

The following pull requests are currently test merged: #4379: 'Science Annex Yard Readdition' by c4xmaniac2 at commit f6bedf65dc #4378: 'LV Intel Update' by c4xmaniac2 at commit 67b2ec461b #4063: 'Yautja Change Holder' by realforest2001 at commit fcc6c86cd3 #4410: 'Cloaked mobs don't give off visible messages (+cloak logic refactor)' by Zonespace27 at commit 1b5a288001 #4391: 'Hijack objectives' by morrowwolf at commit 263df75edf

### Description of the bug

Both pylons are active:
When trying to use the Join as Lesser Drone command, if both pylons are in the same area, the prompt to select which core/pylon to use will automatically highlight both pylons. One of the pylons cannot be joined through, as it defaults to one of them. The other pylon can still be manually clicked to spawn to.

### What's the difference with what should have happened?

Both pylons should have separate entries in the spawn location prompt.

### How do we reproduce this bug?

1. Have two comms towers both in the same area
2. Attempt to Join as Lesser Drone
3. See image
...
![cm-pylon-bug](https://github.com/cmss13-devs/cmss13/assets/8151904/f81a4696-be5e-4824-99df-2c5f5818e6b0)

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
pretty sure the only map where it happen is fiorina sci annex map...?
beside making an area for coms i don't see a quick fix...
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/f4cfa4c6-b024-4878-8aff-148aa2660a5f)
this could be fix by code or by mapping.
