### ISSUE TITLE
Rolling Foxtrot (cryo marines ert) fucks with your character slot by changing settings

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#4434]
### Testmerges

#4379: 'Science Annex Yard Readdition' by c4xmaniac2 at commit a30f108e38 #4378: 'LV Intel Update' by c4xmaniac2 at commit 67b2ec461b #4063: 'Yautja Change Holder' by realforest2001 at commit fcc6c86cd3 #4391: 'Hijack objectives' by morrowwolf at commit 263df75edf #4422: 'Remove Note Fix' by realforest2001 at commit 2d8f75233c #4182: 'Project ARES: Admin Console' by realforest2001 at commit 3456b54b43 #4423: 'Fixes the tradeband scanner.' by realforest2001 at commit 7e7cc5d637

### Description of the bug

If you roll foxtrot with a character you previously used in the round, the intended feature is this:
You get a random name and appearance

What happens is this:
You get a random name (the appearance is the same as your character slot's), BUT, It saves whatever random name you roll to your character slot, and enables the prefs "Random Name, Random Appearance" 
![image](https://github.com/cmss13-devs/cmss13/assets/44538569/e15a809c-2b16-4b8c-af25-ed21f720ec31)

### What's the difference with what should have happened?

Character slots should not be modified and saved without the person modifying it themselves

### How do we reproduce this bug?

1. Roll for a character at roundstart or midround
2. Die, wait for cryo marines to be bought by CIC
3. Roll for cryo marines
4. Roll cryo marines (since your character name was previously in the round, you get random name)
--
5. After this, check character prefs.
6. For some reason, your character name is changed to the foxtrot marine that you RNG rolled, and your prefs are changed.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
i have roles Foxtrot multiple times and this has never happened to me . has anyone else experienced this ?

**Comment by gitbirb** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/44538569/003f6ade-4d78-4277-ad3e-87e21fef702e)
It breaks a.w. slot names too

> i have roled Foxtrot multiple times and this has never happened to me . has anyone else experienced this ?

You have to roll the same character previously in the round

**Comment by Segrain** [comment]
A minor side effect of how the aforementioned intended functionality is achieved. It changes your current settings on the fly when it needs to give you a random name/appearance, but it does not save those changes to your files. As long as you do not decide to start altering your settings after joining Foxtrot and manually save them while at the same time somehow overlooking that you have a wrong name, it should not be an issue.
