### ISSUE TITLE
Pulling a man from the window frame breaks their movement

### ISSUE THREAD

**Issue by 4310V343k** [cmss13-devs/cmss13#444]
## Description

If you climb on a window frame, then somebody pull you out of it, you'll be unable to move again. First occured on the first left window from medbay's 4th OT door

## Difference between expected and actual behavior

You should be able to move after someone pulls you from the frame

## Steps to reproduce

1. Break a framed window
2. Climb on the frame
3. Tell other human being to pull you from it on the ground
4. Profit!

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by 4310V343k** [comment]
Doesn't work locally, probably something specific happened that round (like spiders)

**Comment by Paperbell** [comment]
Were you able to change your facing direction but not move?
