### ISSUE TITLE
Lights through solid walls bug.

### ISSUE THREAD

**Issue by ClairionCM** [cmss13-devs/cmss13#4453]
### Testmerges

#4063: 'Yautja Change Holder' by realforest2001 at commit fcc6c86cd3 #4391: 'Hijack objectives' by morrowwolf at commit f55e0ba569 #4422: 'Remove Note Fix' by realforest2001 at commit 2d8f75233c #4443: 'Storage rebalance' by morrowwolf at commit 8684ce7cda #4446: 'changes the fallback code' by harryob at commit 6128d75388

### Description of the bug

When an item on the floor is emitting light it can sometimes leak through walls.
I've seen it happen with bits of armor but other items might also cause it.

I also gathered some screenshots of the bug happening.
![image_2023-09-20_194726872](https://github.com/cmss13-devs/cmss13/assets/115504494/ac21a49d-449a-491e-b273-1a0c5cb20762)
![image_2023-09-20_194733029](https://github.com/cmss13-devs/cmss13/assets/115504494/8d99bfe9-e7c6-4631-9141-ccc267441b39)

### What's the difference with what should have happened?

It really shouldnt be doing that because walls are solid, not see-through.

### How do we reproduce this bug?

1. Get a piece of armor that has its light on.
2. Drop it on the floor next to some walls.
3. Go to the other side of the wall and bask in your light.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by BeagleGaming1** [comment]
Known bug, it happens if you can see the glowing item / mob through a wall

**Comment by harryob** [comment]
this isn't really a bug, as it shouldn't be occuring in game that you can see the light source and turfs on the other side of the wall. its only a thing for observers, and is entirely unfixable with the way we implement lighting now
