### ISSUE TITLE
your the cigarette

### ISSUE THREAD

**Issue by Bjornulf97** [cmss13-devs/cmss13#4472]
### Testmerges

NA

### Description of the bug

Your the cigarette when your cigarette goes out

### What's the difference with what should have happened?

Hopefully not become the cigarette

### How do we reproduce this bug?

1.Smoke the Cigarette
2.Your the cigarette
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Bjornulf97** [comment]
plz fix

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/0895a915-6c91-4780-9b9d-7bb37e774f27)

**Comment by Bjornulf97** [comment]
https://i.gyazo.com/a0393a6984d3f14ae7d2bc8de2a608ac.png
