### ISSUE TITLE
Chief Engineer having standard autoinjectors instead of EZ ones

### ISSUE THREAD

**Issue by ro3ger** [cmss13-devs/cmss13#4478]
### Testmerges

 979304bb3c64558d526d6d85a616d92f55c55dc1

### Description of the bug

CE's senior officer vendor comes with a auto injector pouch, these require a medical skill of 1 to use instantly

### What's the difference with what should have happened?

CE's senior office vendor comes with EZ use auto injector pouch that require medical skill of 0 to use instantly

### How do we reproduce this bug?

1. Play CE
2. Get first-Aid pouch(Refillable Injectors)
3.groan on the inside as it takes 4 seconds to use
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Not a bug. EZ injectors no longer exist.
