### ISSUE TITLE
FORECON SOF Frequency works with ship tcomms but NOT ground tcomms even when fixed.

### ISSUE THREAD

**Issue by QuickLode** [cmss13-devs/cmss13#4479]
### Testmerges

The following pull requests are currently test merged: #4391: 'Hijack objectives' by morrowwolf at commit 413ac67bf2 #4463: 'Auto observer fixes, preferences, and QoL' by morrowwolf at commit 33b9c84e4e #4468: 'Drag-n-drop hotfix' by morrowwolf at commit e5ed42da83 #4427: 'Phone Do not Disturb' by realforest2001 at commit c241029ca7 #4469: 'LV Comms Update' by c4xmaniac2 at commit 716917e930

### Description of the bug

Might apply to other survivor frequencies too but for FORECON SOF, it works fine on the ship zlevel with tcomms but not on planet. Hilarious because other freqs work just fine.

### What's the difference with what should have happened?

SOF Freq should work just the same as any other freq - if tcomms is up it should work.

### How do we reproduce this bug?

1. Be FORECON Survivors
2. Go shipside, SOF freq works
3. Go to planet, use other freqs just fine because tcomms repaired
4. try using SOF freq, only SOF freq doesnt work 
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Not a bug. SOF (survivors) are their own faction and therefore must have their access added via multitool by a faction member.
