### ISSUE TITLE
You can skip the larva queue

### ISSUE THREAD

**Issue by ondrej008** [cmss13-devs/cmss13#4498]
### Testmerges

#4391, #4463, #4427

### Description of the bug

While you are a ghost, you can press the join as larva button, and if you are fast enough, join as a buried larva even though you're not the first in the queue.

![image](https://github.com/cmss13-devs/cmss13/assets/8739855/be8ef201-898f-4f15-9166-950ece9bb77c)
![image](https://github.com/cmss13-devs/cmss13/assets/8739855/42a51b8a-b9c4-478a-b1d2-59ea5c120684)

### What's the difference with what should have happened?

You should not be able to perform a Quick Time Event in order to bypass the larva queue.

### How do we reproduce this bug?

1. Have a couple players in the larva queue.
2. Give the hive a larva.
3. Have the players start spamming the join as larva button and then immediately hit buried larva.
4. Congratulations, you've now bypassed the larva queue.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
This is a known possibility and has always been the case even before larva queue. It's very specific timing though and requires you to know the tick when a larva converts or is added to pool.

**Comment by Drulikar** [comment]
Though a solution that comes to mind is to disable join as xeno for buried larva while a queue exists.
