### ISSUE TITLE
"Edit Hotkeys" not working

### ISSUE THREAD

**Issue by zBxnny** [cmss13-devs/cmss13#4500]
### Testmerges

 #4391  #4463 #4427

### Description of the bug

Basically as soon as I want to edit my hotkeys accesing from the tab "preferences" or even in character customization, this error pops up.
I bought this pc 2 weeks ago, it's not brand new but just a few months of use, could be that I'm missing some kind of file or even just having the language system in spanish, idk, some help would be appreciated.
Also, I already cleared the cache of BYOND and tried reconnecting several times.

> A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
>  TypeError: No se puede obtener la propiedad 'length' de referencia nula o sin definir
>    at p (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:507584)
>    at Ie (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:161096)
>    at Anonymous function (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:161364)
>    at Te (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:161342)
>    at Fe (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:162390)
>    at Ee (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:162229)
>    at Te (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:161206)
>    at Anonymous function (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:161364)
>    at Te (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:161342)
>    at Fe (http://cdn.cm-ss13.com/live/78/asset.78ef8920225fdfa619891ad4d13891f4.js:1:162390)
> User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
> State: {"ckey":"bxnny","interface":"KeyBinds","window":{"key":"[0x210426a3]-main","size":null,"fancy":1,"locked":0}}
> 
> Weyland-Yutani (c) 2100-2182 Building better user interfaces. 

![imagen](https://github.com/cmss13-devs/cmss13/assets/145942419/2bf0945d-dd40-424d-aaab-54fa299c6dff)

### What's the difference with what should have happened?

It should've opened up the interface to edit my keybinds normally.

### How do we reproduce this bug?

1. I just click on "EDIT HOTKEYS".

![imagen](https://github.com/cmss13-devs/cmss13/assets/145942419/c7db3739-f7d9-4fdf-b2e6-dd57e6fac9d9)

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Solved by following suggestions here: https://github.com/cmss13-devs/cmss13/issues/3846#issuecomment-1627711720
