### ISSUE TITLE
Infinite Metal

### ISSUE THREAD

**Issue by Underfall00** [cmss13-devs/cmss13#451]
## Description
I was able to duplicate infinite metal from a nan metal stack on a recent Kutjevo map on 2022-06-09 between 03:00:00am to 06:40:00ish server time. I was just a squad engineer at the time, so I don't know where req got the nan metal stack from.

## Difference between expected and actual behavior
Metal stacks should have a number between 1 and 50, not nan.

## Steps to reproduce
1. Pick up a stack of metal without a number, just called nan.
2. Split the nan stack into a 1 stack.
3. Merge the two stacks and the 1 stack becomes a 50 stack.
4. Repeat for infinite metal

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
impossible to reproduce without knowing how the NaN stack came to be in the first place
