### ISSUE TITLE
Firearms Malfunctioning

### ISSUE THREAD

**Issue by Biolock1** [cmss13-devs/cmss13#4511]
### Testmerges

#4391, #4463, #4427, #4501, #4503, #4505

### Description of the bug

I have seen/ handled a few adminhelps now where players are reporting their weapons malfunctioning to the point of complete non-functionality. I have only had reported issues with the MK1 and MK2, however that is possibly due to the popularity of those two weapon systems over the other weapons. In those cases the weapons can not be fired, unloaded, field stripped, or interacted with in any way other than picking up and two-handing the firearm. 

### What's the difference with what should have happened?

Guns should work.

### How do we reproduce this bug?

I have no idea how to reproduce this issue and will be using this bug report to constantly report back on the incidents which arise in the future to assist in looking for a general trend.

Incident  1: "I had a mk2 with agrip reflex and normal stock loaded with ap set on burst. i started too shoot the queen and i got neuroed, when i got up my gun refused to shoot, unload, remove attachments or even put on my belt or back."

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Known issue, the BURST_FIRING flag gets stuck on. We had attempted to fix it with https://github.com/cmss13-devs/cmss13/pull/4344 but it didn't work sadly.

**Comment by Biolock1** [comment]
Sad days

**Comment by morrowwolf** [comment]
Still an issue!

**Comment by Diegoflores31** [comment]
> Known issue, the BURST_FIRING flag gets stuck on. We had attempted to fix it with #4344 but it didn't work sadly.

Weapon jamming HRP what if we add a unjamm weapon proc ?

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/4882/files
this PR should have fix the issue
