### ISSUE TITLE
Play-Internet-Sound Verb

### ISSUE THREAD

**Issue by Biolock1** [cmss13-devs/cmss13#4513]
### Testmerges

#4391, #4463, #4427, #4501, #4503, #4505

### Description of the bug

Verb is broken: is giving, "Youtube-dl JSON parsing FAILED: json_decode error: Unexpected character at  (character 1): " instead of playing sick beats. 

### What's the difference with what should have happened?

No tunes, should be tunes.

### How do we reproduce this bug?

1. Use command to play Youtube link music
2. Get error code instead.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
config issue
