### ISSUE TITLE
New Armor Set

### ISSUE THREAD

**Issue by cnaper-dodo** [cmss13-devs/cmss13#452]
Different variations of armor are good.But here are the benefits of these variations..It is practically not there.Everyone uses light, medium, and rarely M4.Heavy and b12 are not used, because their indicators are much better than usual, and you have to be disabled.So I'm going to add a new set of armor, with its advantages and disadvantages.
A set of heavy assault armor.
It is an expensive and very heavy set of armor.Due to too heavy weight, it is recommended to wear no more than 2 hours, due to the risk of developing deviations in the back and joints.
![image](https://user-images.githubusercontent.com/82310279/172824756-6d90659a-a5c7-4671-9f49-dfe6ae7f0890.png)
armor characteristics:
Armor Melee = 45
Armor Bullet = 30
Armor Bomb = 25
Armor Internal Damage = 25
Armor Bio = 25
Armor Slowdown = 0.15
Once every 10 minutes gives 5 units of brut damaga, due to too much mass.
--
helmet characteristics:
Armor Melee = 40
Armor Bullet = 35
Armor Bomb = 5
Armor Internal Damage = 25
Armor Bio = 5
due to too much mass, it gives 5 units of brut damaga every 10 minutes
due to the small viewing slit, he is able to see only from the front.
-
I propose to make it purchasable in cargo / in SL vendors and engineers for points.For engineers, it will be a convenient armor for repairing barricades in the thick of things.For SL, it is an opportunity to lead people without fear that they will fall behind.
![1](https://user-images.githubusercontent.com/82310279/172833248-3b1f81c2-a7e8-40c9-9310-43a88d51d313.png)
![2](https://user-images.githubusercontent.com/82310279/17283325
![13](https://user-images.githubusercontent.com/82310279/172833301-66c4e291-103d-47fb-8c54-03401ef90f4c.png)
![14](https://user-images.githubusercontent.com/82310279/172833303-26335659-9e87-4f9c-8535-dd0fd374ac4b.png)
5-
![12](https://user-images.githubusercontent.com/82310279/172833282-f79108ab-f086-4a0a-8b69-8ce13f9f9e59.png)

![11](https://user-images.githubusercontent.com/82310279/172833271-66e1a1fb-a1d3-45f1-a38f-d0e0dba20036.png)

![4](https://user-images.githubusercontent.com/82310279/172833267-5a81483e-9e77-4dd5-815e-424a7dfb3f42.png)
1fc9779e-f800-4065-a302-571720581307.png)

**Comment by stanalbatross** [comment]
Make a PR not an issue
