### ISSUE TITLE
huggers permanently activate HUDs

### ISSUE THREAD

**Issue by fighterslam** [cmss13-devs/cmss13#4530]
### Testmerges

#4505, #4391

### Description of the bug

Had Medical Optic active on helmet, as you do.

Got hugged. Helmet deleted.
When I was conscious again, still helmetless, I had the Med-Hud active, despite not having any sort of eyewear/helmet/facewear or anything else. 
Even getting a new Helmet and cycling the optics on that didn't fix it, I could use the medhud AND a technician's Welder Optic at the same time.

### What's the difference with what should have happened?

Your helmet HUD should probably not be embedded into your brain even after you lose your helmet.

### How do we reproduce this bug?

1. Wear Helmet.
2. Switch to Medical Optic.
3. Get Hugged
4. Become Conscious Again

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
I have not been able to reproduce this.

Likely related to a bugged round around that time.
