### ISSUE TITLE
New Surgery Armour Bug

### ISSUE THREAD

**Issue by RavinHobo** [cmss13-devs/cmss13#4548]
### Testmerges

690185f36526b1dfdbb304df0ddcb9c67f2a18fd

### Description of the bug

Starting surgery on someone who is wearing armour will cause it to show that you have started an incision on someone when you inspect them in chat, but in fact, no surgery has taken place, causing them to be angry that you didn't finish their surgery when in fact you did.

### What's the difference with what should have happened?

It shouldn't say there is an incomplete surgery when you inspect them.

### How do we reproduce this bug?

1. The patient is wearing head armour
2. have a scalpel in hand
3. accidentally click on them while targeting the head
4. go on to do chest surgery
5. they come back and say you didn't finish their head surgery
6. remember that you didn't do head surgery
7. be confused

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by gitbirb** [comment]
Yeah this one is pretty annoying. clientside it shows an "unfinished surgery".
The only way to get rid of it at the moment is to scalpel and then cautery the part, so that it resets it to baseline.
