### ISSUE TITLE
Blood on a weed blocks clicks.

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#4551]
### Testmerges

#4505: 'Get Flat Icon Fixes' by Drulikar at commit 602124566b #4391: 'Hijack objectives' by morrowwolf at commit c34cb004ab #4534: '"Fixes" missing window frame icon states' by morrowwolf at commit 7cf004c46a #4535: 'Floodlight rework' by morrowwolf at commit 311b5109a8 #4502: 'Disable join as xeno buried spawns when there is a queue' by Drulikar at commit 1dc175ca21 #4549: 'Helmet Optics Update' by morrowwolf at commit a7820b1907

-----------
### Description of the bug

If theres blood on resin, the blood decal can block clicks (such as knife melee) from hitting the resin. 

### What's the difference with what should have happened?

Blood should not eat clicks. Especially since blood pools can cover like... 2/3rds, if not 3/4ths of a resin weed sprite.

------------
### How do we reproduce this bug?

1. Try to click the weed tiles where the blood is (spriteclick the blood pools)
2. The blood blocks the melee clicks
3. Try to click the weed tile (spriteclick the weed, avoiding the blood pools)
4. You destroy the weed.
...
///
This can get really bad really fast, since destroying weeds is usually time sensitive. Clicking the blood pools counts as a melee mis-click, and adds delay to your next strike. You never know your clicking the blood pools over and over since there's no feedback for missing, except for not destroying the weed.

Idk if it's different either while your moving towards a tile, or standing still. I always slash weeds while moving towards the tile.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by gitbirb** [comment]
im gonna close this and test it more

**Comment by gitbirb** [comment]
Couldn't reproduce, maybe misremembered how it works, or maybe it was a latency issue

**Comment by morrowwolf** [comment]
I've similarly had issues with it recently and I'm not sure why it seems to work sometimes. The code seems to function correctly and it's in there to pass along the attack 🤷

**Comment by ItsVyzo** [comment]
Duplicate #1151
