### ISSUE TITLE
Security Record's photo system doesn't work

### ISSUE THREAD

**Issue by LC4492** [cmss13-devs/cmss13#4580]
### Testmerges

#4505: 'Get Flat Icon Fixes' by Drulikar at commit 37034960e3 #4391: 'Hijack objectives' by morrowwolf at commit 8b7381fe37 #4535: 'Floodlight rework' by morrowwolf at commit 311b5109a8 #4549: 'Helmet Optics Update' by morrowwolf at commit 0be1353643 #4506: 'Add cached larva queue message to observer status panel' by Drulikar at commit 945d18b8e5 #4575: 'Adds discretionary arrests as capital crime' by nauticall at commit 3c52b35869

### Description of the bug

The photos which *should* be loaded by the security records simply don't appear, which is quite disruptive when you want to see the profile of a criminal or anyone else.

![Captura de Tela (459)](https://github.com/cmss13-devs/cmss13/assets/122557086/0bf4c79c-bc1c-4006-ac38-1944dd44c398)

### What's the difference with what should have happened?

The photos should actually appear on the security record's screen.

### How do we reproduce this bug?

1. Install SS13
2. Open the CM server
3. Pick a security-related role
4. Go to the nearest security record computer
5. Open any of the crew's personnel records
6. Have fun
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by gitbirb** [comment]
I faintly remember seeing this happening too. Not sure if it consistently happens.

**Comment by Crowbar764** [comment]
It was intentionally disabled in the code for whatever reason. I am also updated this to TGUI (https://github.com/cmss13-devs/cmss13/pull/4558) which hopefully one day can have the images back.

**Comment by ItsVyzo** [comment]
Photos work again
