### ISSUE TITLE
Invisible Sprite in Character Customization

### ISSUE THREAD

**Issue by Travieso98** [cmss13-devs/cmss13#459]
## Description
Upon dying, when attempting to open my screen to customize my existing character or another, the section to view the sprite is completely invisible. Changing the backgrounds does not fix the problem, nor has reloading, opening and closing the window or re-starting the client.

## Difference between expected and actual behavior
It should allow me to see my sprite to edit but instead it's invisible until next round start.

## Steps to reproduce
Attempt to edit a character upon death and see the result?

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Byond/Connectivity issue really - doesn't seem to happen anymore
