### ISSUE TITLE
Chance's Nest spawn locations facing side

### ISSUE THREAD

**Issue by Edgardo813** [cmss13-devs/cmss13#4591]
### Testmerges

#4575, #4583, #4584, #4587, #4391:

### Description of the bug

So basically After the round starts in Chance's some of the spawn points are facing southside even when there's no wall.

![image](https://github.com/cmss13-devs/cmss13/assets/92234457/19aa0463-d199-4b95-8a4e-dc4adb042e69)

It seeems it specially happens in this spawn point.

### What's the difference with what should have happened?

I'm pretty sure they should be facing according the wall behind them. 

### How do we reproduce this bug?

1. PreLobby
2. Xeno Role in HIGH
3. wait until the game start
4. Check if any of the spawn  show in the photo is working properly 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
link to this older issue.
https://github.com/cmss13-devs/cmss13/issues/4561

**Comment by Huffie56** [comment]
can't find where that is...

**Comment by ItsVyzo** [comment]
Duplicate #4561
