### ISSUE TITLE
CO Sec-hug doesn't work with Flash.

### ISSUE THREAD

**Issue by LoveShacker1** [cmss13-devs/cmss13#4594]
### Testmerges

#4575: 'Adds discretionary arrests as capital crime' by nauticall at commit 3c52b35869

### Description of the bug

I as CO had the Sec-hud enabled and on my head as CO in briefing. There were like 4 marines running in a circle hitting each other that I was going to BE, but when I flashed the room, it also stunned me even with my sec-hud on. The testmerge likely did not cause it.

### What's the difference with what should have happened?

Flash in briefing shouldn't stun me with the Sec-Hud cycled. Also I would check MP sec huds if they also aren't working.

### How do we reproduce this bug?

1. CO Sec-hud on.
2. Hit flash in Briefing.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
CO HUD is not the same as the MP HUD from what i am aware . please check ingame

**Comment by Segrain** [comment]
HUDs have nothing to do with eye protection. MP HUD would not protect you either. (MP _glasses_ would, but that is because they are protective glances, not because they have HUD.)
