### ISSUE TITLE
Lasing works through walls

### ISSUE THREAD

**Issue by Chainsawicus** [cmss13-devs/cmss13#460]
## Description
Laser designators behave in a very wonky way, there is actually another issue (#372) that has a lot of their issues listed, but it seemed to miss this one.

## Difference between expected and actual behavior
Expected behaviour: Laser designator should only be able to target tiles you have line of sight on.
Actual behaviour: Laser designator can target any tile, regardless of whether you have line of sight to it or not.

## Steps to reproduce
1) Pick up designator
2) Lase any tile you like

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DoomLaser9** [comment]
The reason I didn't see this as a bug was because I thought there was a ruling a while back that you are allowed to target tiles behind line-of-sight obstructions such as fog.

**Comment by Diegoflores31** [comment]
i dont really think this is a bug since you can just add numbers to the coords to shoot pretty much anywhere you want

**Comment by tempelers** [comment]
Shooting the laze through a wall is the only upside to using it. You're stuck in one place and can't move, why ever use laze if it can't shoot through walls. CAS flares are already better.

**Comment by PhantomEpicness** [comment]
Fixing this would likely nerf CAS into oblivion
