### ISSUE TITLE
Ballistic goggles no longer show on patrol caps

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#4602]
### Testmerges

#4575

### Description of the bug

Someone changed the ballistic goggles sprites; they no longer show on patrol caps - a functionality they used to have.
There is also a function to flip down the goggles so they show on your face, but this function doesn't work.

### What's the difference with what should have happened?

Expected:
All the old ballistic goggle sprites should have been replaced by the new ballistic goggle sprites
Flipping the goggles down will display the goggle sprite on your face

What has happened:
Some of the old ballistic goggle sprites were not replaced and are now missing
Flipping the goggles down does not display the goggle sprite on your face

### How do we reproduce this bug?

1. Wear patrol cap
2. Wear ballistic goggles in the cap
3. Press the "flip goggles down" UI button

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Probably linked to #4557

**Comment by irRegularGuy646** [comment]
i haven't touched the old sprites, and i apparently didn't name the new goggle's on helmet states correctly.

**Comment by Wintermote** [comment]
This issue is still not actually fixed.
