### ISSUE TITLE
Printer Toner Unobtainable

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4603]
### Testmerges

N/A

### Description of the bug

This seems to be an oversight, but it's currently impossible to get more toner for the printers. There do exist 2 toner cartridges on CORSAT, which is out of rotation. Otherwise, there is no way to get it.

### What's the difference with what should have happened?

It should be possible to obtain toner. This should probably be done through requesting some kind of "office supplies" crate from req.

### How do we reproduce this bug?

1. Use all the toner in the printer (30 pages).
2. Be sad.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
why did you need so many? what role did you play...
need more information to propose a solve...
req crate aren't  a great solution...
prefer to make it directly accessible to you..

**Comment by DoomLaser9** [comment]
Used it while PFC, didn't really need it. Although the role that would use it the most is the combat correspondent, and second-most likely the CL. I've seen people want to distribute a bunch of leaflet copies, and using a printer to copy them would be better than manually copy-pasting the entire content onto each individual paper with a pen.
