### ISSUE TITLE
Object Duplication

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4604]
### Testmerges

N/A

### Description of the bug

Any object that can be picked up, can be duplicated. This seems to be a shallow object copy, i.e. you can throw the object, and then throw the duplicate, and the original thrown object "disappears". Due to it not being a full copy, it seems this would have limited use other than being able to throw something far away repeatedly without going to pick it up.

Also, this can be used to get infinite money from ATMs.

### What's the difference with what should have happened?

You shouldn't be able to pseudo-duplicate items. For example duplicating an M41A will then make your character sprite appear to be holding 2 guns, although in the hands only one gun shows (but the other has the invisible copy).

It might also be unrealistic for an ATM to hold over $45 trillion in cash.

### How do we reproduce this bug?

1. Have a hotkey for throw and a hotkey for "Pick Up Dropped Items", e.g. R for throw and F for pickup.
2. Hold an item.
3. Press R to ready a throw, it has to be to somewhere you can pick it back up with F. This seems to work best when throwing something onto yourself, so the instructions will assume that.
4. Do the following very quickly, alternating in between, until you see an object sprite appear layered on top of your character:
   - Click to throw
   - Press F and R simultaneously to pick it back up and ready the next throw (then repeat in loop).
5. Notice multiple copies of the item being held (it's invisible in your hand but examine your character; it also shows on their sprite). You may even have an extra duplicate for 3 total instances of the item.

ATM Heist:
1. Have ATM screen open. Withdraw cash (or charge card thing) into your hand.
2. Do previous steps to duplicate.
3. Deposit one stack of cash.
4. Switch hands.
5. Deposit other stack of cash. And keep depositing it because it doesn't get eaten by the ATM.
6. Repeat for exponential growth.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
That sounds less like the object being duplicated and more it being in two places at once

I knew we couldn' trust throw code

**Comment by Tsurupeta** [comment]
More like BYOND bug, it can happen via other ways too if you're doing things faster than code can process your actions. The second stack should be moved to nullspace, though, so there's an issue with objects that failed to get qdel'd.

**Comment by fordmichigan** [comment]
@huffie56 I was not able to reproduce the bug in a round by throwing and picking up money in the way described.
