### ISSUE TITLE
Molotov Safe Area inhibitor

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4606]
### Testmerges

N/A

### Description of the bug

`The improvised firebomb's safe-area accident inhibitor prevents you from priming the grenade!`

Molotovs shouldn't have any inhibitors.

### What's the difference with what should have happened?

It doesn't make any sense for a glass bottle with a paper sticking out of it to somehow have advanced electronics to detect that it's on the ship and prevent it from priming. Molotovs should always work.

It's not easy to get molotovs on the ship anyway, so there shouldn't be any worries about someone barbecuing briefing at the beginning of the round.

### How do we reproduce this bug?

1. Acquire molotov.
2. Be on ship.
3. Attempt to use molotov.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wintermote** [comment]
We honestly never even had serious problems with people griefing with grenades on the almayer anyway, and the odd time someone actually set a grenade off it's almost always been an accident.

I'm not even sure why the IFF was implemented in the first place besides thematics, but considering most newer players won't even know how to get or make molotovs, I don't see why it should have IFF.

Accidents are fun anyway

**Comment by Huffie56** [comment]
not a bug as forest say. 
but if you have a better more RP way to do safe area inhibitor for molotov cocktail your welcome to post it on the forum.
