### ISSUE TITLE
Cannot Pick Up Paper Bins

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4607]
### Testmerges

N/A

### Description of the bug

It is impossible to pick up a paper bin with your hands. This also means it's impossible to remove paper bins from inside storages using your hands.

### What's the difference with what should have happened?

Paper bins should be able to be picked up. They can be dragged just fine, since they're normal objects. They've even got a defined throw_speed and throw_range. Yet clicking on one always just gives you the prompt to draw paper out of it.

I believe the best behavior would be being able to pick up by clicking and dragging it onto yourself (currently it also forces you to draw paper with this method).

### How do we reproduce this bug?

1. Try to pick up paper bin.
2. Fail.

If you really need to carry paper bins:
1. Use a trash bag on an object that's on the same tile as a paper bin, the trash bag will suck everything up. Note that you can only get the bin out of the bag by dumping it into a disposal unit.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
Will fix this evening.
