### ISSUE TITLE
Campfire Wood Usage

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4608]
### Testmerges

N/A

### Description of the bug

Campfire consumes wood from hand even if it says you cannot fuel it further.

### What's the difference with what should have happened?

Wood from hand shouldn't be consumed when it can't be used.

### How do we reproduce this bug?

1. Have wood stack in hand.
2. Keep fueling campfire with it, notice the following messages appearing with the use of each wood:
```
John Doe fuels the campfire with the wooden plank.
You cannot fuel the campfire further.
```

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
https://github.com/cmss13-devs/cmss13/blob/651a937e6308e295bab58a682a943f0d50989a06/code/game/objects/structures/props.dm#L811-L814

returns need adding here. Will pr it when I get home from work.
