### ISSUE TITLE
Xenos can see raw HTML tags on papers

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4609]
### Testmerges

N/A

### Description of the bug

Viewing a paper with text as a xeno results in a lot of garbled text, but which contains all of the raw HTML from the paper. The text is also no longer colored and formatted properly (a xeno should still be able to see the overall color/format of the paper).

Sometimes the paper is also just completely blank when viewed.

### What's the difference with what should have happened?

When viewing a paper as a xeno. The text positioning/formatting/colors should be the same as when a human sees it, and there shouldn't be HTML tags in the output.

### How do we reproduce this bug?

1. Have human write `123` on paper.
2. Look at paper as human, see red `123`.
3. Be xeno.
4. Look at paper.
5. See that it has a lot more text and nothing is red.
6. Also, deciphering the paper (viewing multiple times) results in: `<font face="Verdana" color=red>123</font>`

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Cthulhu80** [comment]
I feel like Xenos shouldn't even be able to examine the paper.

**Comment by Cthulhu80** [comment]
blank page came from the output of the stars proc, since it was returning formatted html with random asterisks everywhere. The browser couldn't understand or display it most of the time, depending on what was modified to be a asterisks.
