### ISSUE TITLE
Praetorian can attack through closed doors

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4612]
### Testmerges

N/A

### Description of the bug

Praetorians can use the Pierce ability to attack people through a closed door.

### What's the difference with what should have happened?

Xenos shouldn't be able to attack through obstacles that are meant to completely block things.

### How do we reproduce this bug?

1. Be vanguard prae.
2. Use Pierce on someone standing near a closed door, with you on other side of that door.
3. Watch them take damage.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
Did a little testing I was able to replicate this through this type of door.
![dreamseeker_2023-10-11_18-58-43](https://github.com/cmss13-devs/cmss13/assets/25027759/c75b7bc0-ef66-4d9b-8337-546c1a445fc8)

But not this type of door.
![dreamseeker_2023-10-11_18-58-44](https://github.com/cmss13-devs/cmss13/assets/25027759/bad26609-c750-4773-a401-c415093953f4)
