### ISSUE TITLE
Defnder can't break free from been fortified (skill) when doors close on you

### ISSUE THREAD

**Issue by Doomsdayboo** [cmss13-devs/cmss13#4626]
### Testmerges

i don't know what to fill this with but i get its this Local commit: feb9197d6795212e1511475b28a02714dc438cd1  TGS version: 5.16.0    DMAPI version: 5.6.1

### Description of the bug

well i went in front of barricades and i used the fortify to grap mariens attention so when i did that i was in the middle of an opend double door so the door closed on me and the opend again so after that i clicked the skill again and i couldn't berak from that stance i was in with the skill and i died taking alot of damage

### What's the difference with what should have happened?

well i shouldn't be stunned or more like just not able to do anything i mean 2 doors just opend and closed and then i was stuck in that form also that happend in Sorokyne Strata Map

### How do we reproduce this bug?

1.be a defnder xeno
2. stand between a double door  
3. use the skill FORTIFY while the door open 
4. close and open the door
5. now try to break from fortify

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@Doomsdayboo you open two identical issue report as far as i can see?? can you close one ? thanks

**Comment by Doomsdayboo** [comment]
i can't i think the (deleting issues for the organization's repositories) isn't enabled
