### ISSUE TITLE
Can't Pick Up Dead Animals

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#4629]
### Testmerges

N/A

### Description of the bug

Animals stop being able to be picked up when they die.

### What's the difference with what should have happened?

Being able to pick up an animal shouldn't be affected by whether or not the animal is alive.

### How do we reproduce this bug?

1. Find mouse.
2. Pick up mouse.
3. Drop mouse.
4. Assassinate mouse.
5. Try to pick up dead mouse but fail (nothing happens).

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
https://github.com/cmss13-devs/cmss13/blob/681e3fff15bff4b9db76503391c97073e36592b1/code/modules/mob/living/simple_animal/friendly/mouse.dm#L118-L121

Looked at the code for your example and this behaviour is intended.

**Comment by Huffie56** [comment]
as bird noted above this mechanic is intended feel free to open a post on the forum to change tag it with idea and development
have a good CM day.
