### ISSUE TITLE
You can see through non-glass wide doors.

### ISSUE THREAD

**Issue by Das15** [cmss13-devs/cmss13#4638]
### Testmerges

#4575: 'Adds discretionary arrests as capital crime' by nauticall at commit 3c52b35869
[#4437](https://github.com/cmss13-devs/cmss13/pull/4437): 'Project ARES: Datacore' by realforest2001 at commit 64e77569e7

### Description of the bug

When the wide doors are opened, you can see through one of the tiles even if the doors aren't solid.

### What's the difference with what should have happened?

You should not be able to see through solid airlocks.

### How do we reproduce this bug?

1. Find solid, non-glass wide doors
2. Double check that they are in fact solid.
3. Open the doors.
4. Close the doors.
5. Realise you can still see through them.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
That's because the visibility checks don't seem to account properly for multitile objects. Maybe there's a way to make it so but i haven't found it...
