### ISSUE TITLE
Welding helmet does not stop facehuggers

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#464]
## Description

Welding helmet fails to stop any face-hugging attempts.

## Difference between expected and actual behavior

The welding helmet should definitely have anti-hug capability, especially because things like swat helmets and carved pumpkins stop facehuggers.

Welding helmets have code dealing with how flipping them up and down affect the anti-hug value, yet they don't even have an assigned non-zero anti-hug value.

I noticed that commit 81d3a0917367c67203dd44cae450e23f702fbd1c a few years back included some removals of anti-hug values (including the welding helmet's `anti_hug` of `2`). I'm not sure if this is some sort of oversight, but it's definitely an inconsistency, and perhaps a lot of different clothing items should be re-evaluated for anti-hug candidacy (or removal).

## Steps to reproduce

Walk up to egg with welding helmet (flipped down), get immediately hugged.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
Intended, if you wish to change this then make a PR
