### ISSUE TITLE
Unable to Move has marine/ TP back to the lobby screen has ghost

### ISSUE THREAD

**Issue by Edgardo813** [cmss13-devs/cmss13#4642]
### Testmerges

#4442,#4575,#4437,#4539

### Description of the bug

A'right So   The video is shows what happens https://www.youtube.com/watch?v=LlNbvokKIp8

I was told by a admin that someone else suffered this by pressing the TUTORIAL button of  #4442.

Basically I can't move has a marine, and when I try to move around has ghost I just get teleported to the lobby, something tells me that there's a problem with the tutorial instances keeping me stuck on the lobby even when i'm not in there, so I can't move has a marine cause There's no possible way for me to get teleported again to the lobby without admin help, and has ghost I get teleported instantly because ghosts can actually teleport everywhere they want.

### What's the difference with what should have happened?

I'm pretty sure you should be able to move around

### How do we reproduce this bug?

1. Click the tutorial button
2. Join has a marine/xeno
3. You won't be able to move 
4. Ghost
5.  Try to move and you will be teleported to the lobby

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment]
Suspected #4442, but not a clue why

**Comment by Huffie56** [comment]
so since no 4442 got closed and no tutorial PR are in the make i will just link this to contributor project and put him under clean flag

**Comment by Drulikar** [comment]
4442 is replaced by #5030

**Comment by Drulikar** [comment]
Issue is only related to a PR that isn't merged yet though - and this issue is known and should already be fixed.
