### ISSUE TITLE
MP Armour Colour 

### ISSUE THREAD

**Issue by dead-man-walking** [cmss13-devs/cmss13#4664]
### Testmerges

#4575 #4437 #4539 #4337 #4649

### Description of the bug

The MP's armour on the characters sprite does not match the map armour colour despite this fact the armour in the equipment slot shows the proper armour colour dependent on the map.

### What's the difference with what should have happened?

the armour should be the proper colour on the characters sprite dependent on the map on both the sprite and the equip slot.

### How do we reproduce this bug?

1. Wear MP armour
2. Look at the sprite 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@dead-man-walking
On what maps this is happening?
is MP the only role where this is happening?

and last ... is it still happening?

**Comment by dead-man-walking** [comment]
@Huffie56 
The maps that it happens on depends on what the maps Armour colour is so the MP armour colour is forest green like LV-624 its fine but on the maps where it is Urban(?) cyan like prison station or chances clam, Desert tan like dam or big red but i am not sure for snow maps but on these maps the on character sprite for the armour is incorrect almost always showing it as forest green no matter the map.
as for any other roles that have this issue its only really effecting the MP and MP Warden.
and yes it is still happening just checked today and the on character sprite for the mp armour is still wrong.

**Comment by dead-man-walking** [comment]
seems this issue has been pushed down and i don't suspect it will be fixed any time soon.

**Comment by Huffie56** [comment]
> seems this issue has been pushed down and i don't suspect it will be fixed any time soon.

didn't got push down it's just that more issues got reported.
if you want you can post the issue on spriter channel and ask someone to fix it.

**Comment by dead-man-walking** [comment]
so it seems one of the recent PR's seemed to have fixed the mp armour ( i don't remember what one exactly but i think it was the one that added the urban armour colour ) but as of current it seem what ever PR was ceased

**Comment by ItsVyzo** [comment]
this seems to be fixed now
