### ISSUE TITLE
Pred's tacmap is broken

### ISSUE THREAD

**Issue by JayTacos** [cmss13-devs/cmss13#4688]
### Testmerges

The following pull requests are currently test merged: #4575: 'Adds discretionary arrests as capital crime' by nauticall at commit 3c52b35869 #4539: 'Squad Briefings 2: The Briefening' by Warfan1815 at commit b0a8e023e9 #4337: 'Adds CBRN ERT' by BeagleGaming1 at commit 5915d34738 #4653: 'more robust fix for flyby timer issue' by mullenpaul at commit 8f3a178232 #4475: 'Adds drawing to tacmaps' by Cthulhu80 at commit 2924cab6ca #4678: 'Fixes crash in Join as Freed Mob if some had been deleted' by fira at commit 778a8be2af

### Description of the bug

On the pred ship there's the "Hunter's Globe" which shows the tacmap. We've got the 'Adds drawing to tacmaps' testmerge on and I think it broke it. I assume this is an easy fix but I'm no coder.

### What's the difference with what should have happened?

![Pred bugfix](https://github.com/cmss13-devs/cmss13/assets/104471944/8e6495d9-e01e-4d6a-9bf4-c127892bd8c0)

### How do we reproduce this bug?

1. Join as pred.
2. Click on the hunter's globe.
3. Observe the bug

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Cthulhu80** [comment]
It's in the works, there needs to be a new implementation done for preds.

**Comment by JayTacos** [comment]
Fixed as of 10.17
