### ISSUE TITLE
Sometimes cannot perform IB surgury with Surgical line on red wheeled stretchers as combat medic

### ISSUE THREAD

**Issue by hislittlecuzingames** [cmss13-devs/cmss13#4719]
### Testmerges

That's not in the OOC tab

### Description of the bug

When the surgury incision is open and stretched out with internal bleeding, sometimes medics cannot fix the internal bleeding.

Only certain medics. Both times I saw it happen, there were at least 2 medics and one could fix it. 

First instance, the person who made the incisions could fix the IB, but I could not.

Second instance, the person who made the incisions could NOT fix the IB, but I could. 

I may have had another instance where I could not fix IB, but I don't recall. 

### What's the difference with what should have happened?

When a surgical incision is made AND opened, it is expected that when you use the surgical line and click "Internal bleeding" that the Internal bleeding is to be operated on. 

### How do we reproduce this bug?

1.
2.
3.
...
This may be a little tricky, and I haven't done enough testing. I tried reading the code to see if I could figure it out, but I've mostly been trying to find the things involved in the code thusfar. 

1. Have at least 1 internal bleeding on someone. 
2. Be a medic with a combat knife, surgical line, and a red wheeled stretcher from the standard medic kit. 
3. Make the surgical incision. 
4. Open the surgical incision. (both of these steps can be done with the combat knife from your boot. It's what most medics seem to be doing.)
5. Attempt to use the surgical line on the internal bleeding. 
6. If it failed , the chat message box in the bottom right should say something like "You cannot do that."

Theories:
1. Only 1 internal bleeding can be fixed at a time.
2. If someone opens the internal bleeding panel, he is the only one that will be allowed to fix internal bleeding. 
3. If you cancel fixing internal bleeding you cannot fix internal bleeding on said individual

These theories are based on what I believe MAY have happened. It gets chaotic & I try to medic instead of bug hunt because if a player dies, he could be dead for 2 or 3 hours. 
I am also not familiar with programming the Byond game technology stack. I briefly read some of the programming documentation & got a basic understanding to understand what the code is doing. 

I know a bit of programming, so if you can point me in the directions of what may be useful and involved-Byond seems a bit spaghetti code-I can investigate more into this obscure bug myself. 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by hislittlecuzingames** [comment]
After clicking "Show Server Revision"

BYOND Version: 515.1610
Server revision compiled on: 2023-10-18T18:02:55+00:00
Master commit: [297584d8b3b708ecd32af1c785ce270704bf1758](https://github.com/cmss13-devs/cmss13/commit/297584d8b3b708ecd32af1c785ce270704bf1758)
The following pull requests are currently test merged:
[#4575: 'Adds discretionary arrests as capital crime' by nauticall at commit 3c52b35869](https://github.com/cmss13-devs/cmss13/pull/4575)
[#4475: 'Adds drawing to tacmaps' by Cthulhu80 at commit 57fce31d61](https://github.com/cmss13-devs/cmss13/pull/4475)
[#4699: 'Hijack Objectives & Self Destruct ' by Zonespace27 at commit 2827e03985](https://github.com/cmss13-devs/cmss13/pull/4699)
[#4337: 'Adds CBRN ERT' by BeagleGaming1 at commit 21a4b02f37](https://github.com/cmss13-devs/cmss13/pull/4337)
[#4627: 'M39 being able to use vertical grip again [BUFF]' by irakligabunia at commit 6d4bb12cf6](https://github.com/cmss13-devs/cmss13/pull/4627)
[#4623: 'Reimplements halloween pumpkin helmets event' by fira at commit 46d653a8aa](https://github.com/cmss13-devs/cmss13/pull/4623)

Local commit: 59f318eeb3ddb73bc99dd4e2105cb7e17e40b964
TGS version: 5.16.0
DMAPI version: 5.6.1

**Comment by Katskan** [comment]
Can you provide the map/location where this happened, and if the incisions were opened in one location that was different from where the bleed fix attempts were made

**Comment by hislittlecuzingames** [comment]
I don't recall the exact maps.... but I think it was 
Trijent Dam
I think we were in the NE side of the map. 

It may have also happened on one of the other desert maps:
Kutjevo or Solaris Ridge. 

For when there were 2 surgical incisions, I don't believe the cart was moved.
A medic made 2 incisions and opened them.
He may have been fixing the IB when I tried to fix the other IB and that may have stopped me. 
I don't think he moved the cart. 

The second instance the cart might have moved.
A medic made an incision and held it open.
That medic could not fix the IB. 
I was able to fix the IB. I don't know if I opened the menu causing her to be unable to fix the IB. 
I think I looked to see if I could do the IB, then closed the menu, then she tried and couldn't so I re opened the menu and did it. 


If I remember correctly...
Area #1 was where the two incisions were made and the medic who made the incisions was able to fix the IB.

I don't remember if it was Area #2 or Area #3 where the medic made the one incisions, and couldn't fix the IB herself. 
I also don't remember if it was inside the pits or if I could see either the top or bottom of the pits when we were treating the patient. 

![image](https://github.com/cmss13-devs/cmss13/assets/142365554/3f4c19c6-0856-43e5-ba17-ca82139b9310)

These both may have been in the same match.
I don't remember what day. I don't remember if it was when one of the updates were being applied. I recall an update happened in the past week or so. I don't know if these happened before or after the update.

**Comment by AnuvKH** [comment]
Trijent has areas where you cannot perform surgery and I think this might be the cause. Certain tiles (like the metal grates over rivers) will block surgery. It's extremely obscure, much moreso than trying to do surgery on the DS or an escape pod. But since it seems to happen on this map, there may be other areas that block surgery too.

**Comment by hislittlecuzingames** [comment]
Interesting...
I think I was standing on desert tiles. 
I could have swore I did surgury on metal grates over the rivers....

Would you know what flag might stop that and I can investigate the... I think Byond calls them Turfs.

**Comment by Diegoflores31** [comment]
Questions 
1) was the other medic using sutures/mesh on another bodypart while you were doing surgery ?
2) did you got any message when you tried to suture ?

**Comment by hislittlecuzingames** [comment]
> Questions
> 
>     1. was the other medic using sutures/mesh on another bodypart while you were doing surgery ?
> 
So in the description I think I noted that one of the two internal bleeds was being sutured by the other medic in the first instance.
MAY HAVE. 
But I tried to suture both and neither would let me.
>     2. did you got any message when you tried to suture ?
When trying to suture, it says something along the lines of:
"You cannot perform this action."
I don't recall the exact message as it was a number of days ago and things are chaotic as you know in the games.

**Comment by hislittlecuzingames** [comment]
It's either super obscure or I happened to miss intended mechanics.
Seeming to be more the latter.

**Comment by Huffie56** [comment]
don't hesitate to reopen this issue if it appear again...
