### ISSUE TITLE
Mortar Shells Seem to Randomly Offset when In Pile

### ISSUE THREAD

**Issue by stagda** [cmss13-devs/cmss13#4729]
### Testmerges

BYOND Version: 515.1610 Server revision compiled on: 2023-10-19T14:30:56+00:00 Master commit: fb2b136eaab430c47e930afaf9fecca7aaf73434 The following pull requests are currently test merged: #4575: 'Adds discretionary arrests as capital crime' by nauticall at commit 3c52b35869 #4475: 'Adds drawing to tacmaps' by Cthulhu80 at commit 57fce31d61 #4699: 'Hijack Objectives & Self Destruct ' by Zonespace27 at commit 2827e03985 #4337: 'Adds CBRN ERT' by BeagleGaming1 at commit 21a4b02f37 #4627: 'M39 being able to use vertical grip again [BUFF]' by irakligabunia at commit 6d4bb12cf6 #4623: 'Reimplements halloween pumpkin helmets event' by fira at commit 32229a2621  Local commit: 2a4783d57c1f605d2b0e5a630bec86b6bfee4d5e TGS version: 5.16.0 DMAPI version: 5.6.1

### Description of the bug

When in piles, certain mortar shells seem to flicker/offset/come to the front randomly. 

https://github.com/cmss13-devs/cmss13/assets/106484997/5b3b9131-4eb8-46d6-b877-9c7430ca8e28

### What's the difference with what should have happened?

Mortar shells should remain static when dropped in a pile

### How do we reproduce this bug?

1. Place a certain number (unclear how many) mortar shells on a tile. 
2. Observe shifting
3.
...

### Issue Bingo

- [x] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Please input Round ID too in future so i can check logs :(

**Comment by stagda** [comment]
I think it was Round ID: 19147 or 19148, whichever was LV 522

**Comment by stagda** [comment]
> Please input Round ID too in future so i can check logs :(

Behavior can be seen in quite a few piles in this clip from round 19206

https://github.com/cmss13-devs/cmss13/assets/106484997/a1b0a3e2-1dba-40d1-b35f-bf15453e2ab2

**Comment by fira** [comment]
This is so odd... I could swear I've seen it happen on surfaces to but that should be way impossible

**Comment by cuberound** [comment]
damn I tought this is intentional feature, it looks better spread out then when they are all on one same spot looking as one object...

**Comment by ItsVyzo** [comment]
this seems to have been fixed
