### ISSUE TITLE
Mapping Issue on The Alyamer

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#474]
## Testmerges:

N/A

## Description
There's a missing wall or door on the upper level of the Alyamer, south of the south stairwell.

## Difference between expected and actual behavior
There shouldn't be a missing wall or door there.

## Steps to reproduce
1. Go up the south stairwell near medical.
2. Go south a couple blocks.

## Issue bingo (not required to be all checked)
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
fixed
