### ISSUE TITLE
Using a Megaphone Permanently Shifts Your In-game Chat

### ISSUE THREAD

**Issue by LeDoktor** [cmss13-devs/cmss13#4742]
### Testmerges

The SG Testmerge

### Description of the bug

Using the megaphone for some reason will permanently shift your in-game chat text to the left.

### What's the difference with what should have happened?

In-game chat text should be directly over my character's head.

### How do we reproduce this bug?

1.Use the megaphone
2.Try to chat normally
3.Be seated while using the megaphone? (May have contributed)
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by LeDoktor** [comment]
Forgot to leave images of the bug, here you go.
![Uploading Screenshot_16~2.png…]()

**Comment by harryob** [comment]
fixed by #4741

**Comment by LeDoktor** [comment]
Forgot to upload images of the bug. Here you go.
![Uploading image-2~3.png…]()

**Comment by LeDoktor** [comment]
Wait, so should I close this, seeing as a PR is open already?

**Comment by harryob** [comment]
> Wait, so should I close this, seeing as a PR is open already?

no don't worry, the pr that fixes it'll auto close this once when it's merged

**Comment by LeDoktor** [comment]
Gotcha. Also, sorry for the delay with the pics. Having trouble finding a link that doesn't either work or accidentally dox me

**Comment by LeDoktor** [comment]
Previous pic post almost doxxed me yet again. One more time.
![image-2~3](https://github.com/cmss13-devs/cmss13/assets/127057668/3255edbc-9101-43b6-9fce-a43e70a1ffaa)
![Screenshot_16~3](https://github.com/cmss13-devs/cmss13/assets/127057668/12f3a0f2-4241-4b18-8790-0b84a66dacac)
