### ISSUE TITLE
Clsuter OB hitted somewhere it shouldn't have too

### ISSUE THREAD

**Issue by Tangerineje** [cmss13-devs/cmss13#4743]
### Testmerges

nope

### Description of the bug

Cluster OB pierced and hitted inside DSs floor where it says "nothing supposed get in throught"

![image](https://github.com/cmss13-devs/cmss13/assets/113033323/5f437289-a6e2-4442-9b57-ccf4e8c87524)

unfortunately i wasn't recording while it happened but you guys can check logs. Round id 19160

### What's the difference with what should have happened?

it shouldn't

### How do we reproduce this bug?

fire cluster OB too FOB while any DSs still there

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Faunenschnitt** [comment]
related to this is the question why this did not work:
https://github.com/cmss13-devs/cmss13/pull/3102/
