### ISSUE TITLE
Sprite damage doesn't resolve after healing

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#4764]
### Testmerges

#4475, #4627, #4623, #4699, #4723, #4696, #4558

### Description of the bug

If you injure yourself or become injured, a blood decal overlay will be applied to your sprite.
If you then heal fully, this blood will remain and never go away.

It cannot be washed off, or removed with spray bottles.

Additionally, this is also an issue I've noticed with splints not being removed from your sprite after you've removed them mechanically/been treated and the cause is probably similar.

This issue is older than the current testmerges.

### What's the difference with what should have happened?

What's expected (and used to be normal until recently):
After taking damage and having blood decals applied to your sprite, if you heal the decals will disappear.
(I don't know if washing also did but it was tied to your health so I don't think so)

What is happening now:
After taking damage and healing, blood decals are not being removed from the sprite

### How do we reproduce this bug?

1. Punch yourself
2. Observe blood decals applied to sprite
3. Use tricord or other medicine to heal
4. Observe blood decals are still applied to sprite
5. Use showers, go in water, use spray bottle, etc. to remove blood
6. Observe blood decals are still applied to sprite

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
linked to this other older PR i assumed...
https://github.com/cmss13-devs/cmss13/issues/4382

**Comment by Huffie56** [comment]
i could reproduce part of it with some damage overlay maybe linked to the eyes
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/4c9ccbd0-1979-445f-9b1f-be14bdd22487)
manage to remove it with aheal only...

**Comment by Drulikar** [comment]
I am not able to reproduce this issue as described. Tried punching head. Tried punching eyes. Tried shooting with a m41a in various body parts.

Splint overlay is removed when splints are removed.

Damage overlay is removed when fully healed with meds.

**Comment by Huffie56** [comment]
last time i was able to reproduce was unable to remove the blood overlay sprite near the eyes...(damage to the eyes i think?)
the only way to fix it was aheal...
will check if i can reproduce it myself again... and would put a way of reproduce it....
