### ISSUE TITLE
you cant add your comms to the tcomm tower

### ISSUE THREAD

**Issue by QuickLode** [cmss13-devs/cmss13#4766]
### Testmerges

The following pull requests are currently test merged: #4475: 'Adds drawing to tacmaps' by Cthulhu80 at commit 57fce31d61 #4627: 'M39 being able to use vertical grip again [BUFF]' by irakligabunia at commit 6d4bb12cf6 #4623: 'Reimplements halloween pumpkin helmets event' by fira at commit d628959531 #4699: 'Hijack Objectives & Self Destruct ' by Zonespace27 at commit d80f3b2aac #4723: 'Alternative IFF' by ihatethisengine at commit 091b8cb18b #4696: 'Fixes Smartfridge deletions + Turing/Smartfridge networking issue' by fira at commit 871be8cba3 #4558: 'TGUI / Bugfixes / Improvements: Security Cleanup' by Crowbar764 at commit 4b29dca63d

### Round ID

19180

### Description of the bug

in #4479 someone said you are supposed to multitool to get comms

Well you can't multitool to get comms - this was tested with organic FORECON by CO, Synth and engineer. None work.

Also tested this in a separate round where TWE was spawned - TWE could not add their freq to the tcomms terminals either.

### What's the difference with what should have happened?

By interacting with a powered tcomms using your multitool, you should be able to add any frequencies that you currently have onto the tcomms terminal. 

Unfortunately, when you press "add frequencies" it'll tell you that you added them. But in reality you still can't use your freq.

### How do we reproduce this bug?

1. Be FORECON Survivors
2. Go shipside, SOF freq works
3. Go to planet, use other freqs just fine because tcomms repaired
4. Add your freq via multitool.
5. try using SOF freq, only SOF freq doesnt work because it didnt update
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
aren't forecon freq on the com from the start?
you may just have wiped it from the com by interacting with the multi-tool?
