### ISSUE TITLE
Text Issue on The M5 RPG

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#477]
## Testmerges:

N/A

## Description

When a round is fired or unloaded it will state "It's unloaded but has a round chambered." Which isn't possible.

## Difference between expected and actual behavior
It should state, "It's unloaded."

## Steps to reproduce
1. Load a rocket.
2. Unload the rocket.
3. Success.

## Issue bingo (not required to be all checked)
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
likely some guncode shitcode fuckery that is occuring here.
