### ISSUE TITLE
Flooring Tile Issue

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#478]
## Testmerges:

N/A

## Description
For some reason you can place normal floor tiles over the catwalk mesh on The Alyamer.

## Difference between expected and actual behavior
You shouldn't be able to overlay normal floor tiles over the catwalk meshes, currently  it allows you to and creates a visual error where the catwalk texture disappears.

## Steps to reproduce
1. Place normal floor tiles over the catwalk mesh.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Probably fixed by #434? Reopen if this is still a thing.
