### ISSUE TITLE
Auxiliary Support Officer Access

### ISSUE THREAD

**Issue by drinkmorewater77** [cmss13-devs/cmss13#4785]
### Testmerges

---

### Round ID

---

### Description of the bug

ASO doesn't have access to the Nurse office, research, morgue or the Wey-Med Plus. 

### What's the difference with what should have happened?

ASO is RP'ly third in command of the ship behind CO/XO but doesn't have access to the Nurse office, research, morgue or the Wey-Med Plus. They have access to everything else and this just appears to be an oversight especially since they have specially trained medical skill let alone their command position

### How do we reproduce this bug?

---

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
ASO is not from the medical department nor a supervisor of them . Being third in command doesnt give him all access . If he needs medical supplies he needs to ask a medic to vend it for him . A lot of command jobs (pretty much all of them) have medical skill . That doesnt mean they are supposed to loot medbay or be doctors

**Comment by drinkmorewater77** [comment]
> Medical department is not under ASO. Should ASO end being aCO and need the access for some reason, his ID can be updated accordingly. I do have some thoughts regarding WeyMeds in specific, but that is a story for another day.



> ASO is not from the medical department nor a supervisor of them . Being third in command doesnt give him all access . If he needs medical supplies he needs to ask a medic to vend it for him . A lot of command jobs (pretty much all of them) have medical skill . That doesnt mean they are supposed to loot medbay or be doctors

The ASO not being directly in-charge of the medical department shouldn't prevent them having access to the morgue, research or basic medical equipment on their own accord when they are the first one to be the aCO when no XO/CO is up which happens multiple rounds a day. It's a role that is more inline with being XO/CO rather than being a department head like the CE or CMO and already has full access to the ship except for the aforementioned areas. They have permission to go into the CMO's office and activate security shutters to obtain autoshotguns as they please but not to drag a dead marine into the morgue? This makes zero roleplay sense.

**Comment by Diegoflores31** [comment]
> > Medical department is not under ASO. Should ASO end being aCO and need the access for some reason, his ID can be updated accordingly. I do have some thoughts regarding WeyMeds in specific, but that is a story for another day.
> 
> > ASO is not from the medical department nor a supervisor of them . Being third in command doesnt give him all access . If he needs medical supplies he needs to ask a medic to vend it for him . A lot of command jobs (pretty much all of them) have medical skill . That doesnt mean they are supposed to loot medbay or be doctors
> 
> The ASO not being directly in-charge of the medical department shouldn't prevent them having access to the morgue, research or basic medical equipment on their own accord when they are the first one to be the aCO when no XO/CO is up which happens multiple rounds a day. It's a role that is more inline with being XO/CO rather than being a department head like the CE or CMO and already has full access to the ship except for the aforementioned areas. They have permission to go into the CMO's office and activate security shutters to obtain autoshotguns as they please but not to drag a dead marine into the morgue? This makes zero roleplay sense.

They should not have access to CMO office . I will check on that later
