### ISSUE TITLE
Medical satchel/backpack covers most of the playtime medal sprite.

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#479]
## Description

Equipping a medical satchel/backpack places the iconic <s>red target</s>...  red cross on your chest but this covers most of the playtime medal pinned to your armor/uniform when facing South. I know its a minor spriting issue but it does put a damper on those peeps that want to show off their medic medals as well as well as preventing any newer medic from discovering an experienced medic to observe.

## Difference between expected and actual behavior

Playtime medal visibility should not be hampered by the decision to use the satchel/backpack provided to medics and Medical roles for those that want to show it. The medal is visible when facing West but cut off mostly when facing South by the <s>red target</s>... red cross.

## Steps to reproduce

Equip armor or uniform with a playtime medal then equip the medic satchel/backpack.
With the medical satchel equipped:
![With Satchel](https://user-images.githubusercontent.com/105765670/173727560-04e33758-18ff-4548-8cc5-56d317fd14b6.png)

Without the medical satchel equipped:
![Without Satchel](https://user-images.githubusercontent.com/105765670/173727577-3a033371-7e85-410e-9ba3-0dfd7728ab0e.png)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DoomLaser9** [comment]
I remember this also happens with the USCM technician welderpack.

**Comment by tempelers** [comment]
It's a overlay issue probably. Medals are probably under backpacks in the sprite load order.

**Comment by nuklearcellphoneg** [comment]
Happens with some of the engie backpacks too yeah, namely because it's a chest pack but i'd rather the medal show

**Comment by ItsVyzo** [comment]
Not a bug
