### ISSUE TITLE
Wrong Sprite for Bug-B-Gone Thermals on Fio.

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#480]
## Testmerges:

N/A

## Description
When you disable the thermals, instead of showing the turned off HUD like the medical, it instead shows the ballistic goggles sprite.

## Difference between expected and actual behavior
^ read above

## Steps to reproduce
1. Get the thermals.
2. Turn them off.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
Issue found = No unique deactivate state for syndi goggles ( the bug-b-gone is instanced syndi goggles) so it inherits from parent.

Additional issue: No onmob state.

**Comment by PhantomEpicness** [comment]
Fixed in https://github.com/cmss13-devs/cmss13/pull/455
