### ISSUE TITLE
APC Phone Visual Issue

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#481]
## Testmerges:

N/A

## Description
The phone line that connects to the phone itself gets cut visually when you sit/stand in the seat to the immediate west of the gunner.

## Difference between expected and actual behavior
It's a visual bug that is somewhat annoying.

## Steps to reproduce
1. Call someone on the phone
2. Don't move
3. Success

## Issue bingo (not required to be all checked)
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DoomLaser9** [comment]
This may be related to issue #366 with the disappearing phone tether.
