### ISSUE TITLE
Obstacle Vaulting Canceling Prematurely

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#4814]
### Testmerges

#4475, #4623, #4699, #4564

### Round ID

Issue has existed for some time but the current round as of making this report was: Master commit: [5fbe14390f80225a5d295f07b9acf781fb8aa2b2]
hmmm tried copy pasting the master commit from the round but github keeps making it a link to that PR. Dunno what the deal is.

### Description of the bug

Dropping or otherwise emptying your hand while in the process of vaulting over an obstacle(as in leaping over a window sill or non-wired barricade) causes the process to cancel.

### What's the difference with what should have happened?

Unsure when this started happening(it did not used to be like this) but simply putting something from your hand into your bag or dropping it should not cause you to stop moving over an obstacle. For instance, it is very common to break a window with your boot knife or gun then try to get over said window. With this bug, you can not re-equip your knife or gun after you have started vaulting or it will cancel. If anything, putting away items or dropping them should make getting over obstacles easier not impossible. Really, the bug(oversight?) just makes moving, particularly in very urban maps like Chance's, more clunky in general.

### How do we reproduce this bug?

1.  Have some object in your hand.
2.  Initiate the vaulting process over a window or barricade with no barbed wire.
3.  Drop or store the item in your hand while in the process of vaulting.
4.  Contemplate your character's physical capabilities and have a nice day.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
Not a Bug , this behaviour happens pretty much in all SS13 severs .
