### ISSUE TITLE
Requsition vendors not vending to table

### ISSUE THREAD

**Issue by drinkmorewater77** [cmss13-devs/cmss13#4852]
### Testmerges

---

### Round ID

---

### Description of the bug

Before all three vendors at requisitions would vend to the table while standing next to it at the req line, now the ColMarTechAutomated Munition Vendor doesn't vend to table.

### What's the difference with what should have happened?

The ColMarTechAutomated Munition Vendor should vend to table.

### How do we reproduce this bug?

Handle requisitions, vend from ColMarTechAutomated Munition Vendor.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
I can confirm this is caused by #4803 not sure the solution yet.
