### ISSUE TITLE
Tiles with Bunk Beds and ---Merge Conflict Marker---s in the new Charlie and Bravo Briefing Rooms. 

### ISSUE THREAD

**Issue by stagda** [cmss13-devs/cmss13#4861]
### Testmerges

BYOND Version: 515.1610 Server revision compiled on: 2023-11-06T17:19:32+00:00 Master commit: c05a9cb0f521efac20b07f9566929bfb3a267e25 The following pull requests are currently test merged: #4475: 'Adds drawing to tacmaps' by Cthulhu80 at commit 1a02644785 #4812: 'Dropship weapons console TGUI' by mullenpaul at commit ccde22c3ca #4793: 'ports the tg profiler subsystem' by harryob at commit 4b06b80861 #4756: 'Minor Code Maintenance Bundle (deletes, standards, runtimes)' by fira at commit 3edaadc4a0 #4750: 'Code maintenace of Stats Entities' by fira at commit ac81df4710  Local commit: ffbb9fef4be9435c73f7bfc649defa18bf056aa2 TGS version: 5.16.2 DMAPI version: 5.6.2

### Round ID

19407

### Description of the bug

There is a set of bunk beds in the new Bravo and Charlie squad briefing rooms that share a tile with a '--- Merge Conflict Marker---'
![Merge Conflict Marker](https://github.com/cmss13-devs/cmss13/assets/106484997/4d48f89d-0637-4861-8473-bdfa133f2707)
![Merge Conflict Marker 2](https://github.com/cmss13-devs/cmss13/assets/106484997/0215529a-f5cd-4857-b869-c4986806b632)

### What's the difference with what should have happened?

There should just be chairs on those tiles. 

### How do we reproduce this bug?

1. Examine the tile with the bunk beds on them in the relevant squad briefing room(s).
2.
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stagda** [comment]
Looking into merged PRs, I think I see this occured with #4801 by @harryob it looks like MapDiff bot is showing changes to the tiles in question
![image](https://github.com/cmss13-devs/cmss13/assets/106484997/2fee93b2-a5f2-4cb1-b9d9-2c4242dd01e6)

**Comment by Huffie56** [comment]
it's been fixed  no idea what PR did it ....
