### ISSUE TITLE
Corpsmen gear vendors don't actually give engineering pamphlets when ordered

### ISSUE THREAD

**Issue by restedwaves** [cmss13-devs/cmss13#4913]
### Testmerges

#4475: 'Adds drawing to tacmaps' by Cthulhu80 at commit b2c104175e #4812: 'Dropship weapons console TGUI' by mullenpaul at commit 32c3121bb5 #4793: 'ports the tg profiler subsystem' by harryob at commit 4b06b80861 #4866: 'Radio TGUI backend Tidy-up & Adds Listening Devices' by realforest2001 at commit f9749b2f0d #4879: 'Hotfix for missing Traitbound Elements Handlers' by fira at commit cecf097e0a #4889: 'Echo pad droppod fix' by fira at commit 6c3efedbc7

### Round ID

19502

### Description of the bug

when attempting to purchase a engineering pamphlet from the ColMarTech Squad Medical Gear Rack it deducts the points but does not produce the pamphlet.

edit: but it makes you learn it with no notification

### What's the difference with what should have happened?

it should have deposited the pamphlet onto the floor or into a marine inventory

### How do we reproduce this bug?

1. be corpsman
2. try to purchase an engineering pamphlet
3. realize you wasted your points on something that is bugged
edit: 4. find out it somehow vended it straight into your head?

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
Tested locally on [66e9557](https://github.com/cmss13-devs/cmss13/commit/66e955747d0b18477465c8e813065c185d38ac0e) and the pamphlet vended either to my hands or to the floor. Was this from roundstart?

**Comment by restedwaves** [comment]
yes it was roundstart
if it helps it was in bravo prep, first vendor to the right of the table but i'll see if i can properly reproduce it tonight

**Comment by Birdtalon** [comment]
Ok thanks let me know if you find anything.

**Comment by restedwaves** [comment]
mirrored what i did exactly, unable to reproduce.
i'll just close this since either i blinded into using it without realizing it or worst case it's being caused by something completely unrelated to the user's actions
