### ISSUE TITLE
This one proudly demands that you REMEMBER IO! When it shouldn't

### ISSUE THREAD

**Issue by BadAtThisGame302** [cmss13-devs/cmss13#4916]
### Testmerges

#4475, #4812, #4793, #4866, #4915

### Round ID

19508

### Description of the bug

The Souto, Wey-Yu and alot of other posters should not begin with This one proudly demands that you REMEMBER IO! for obvious reasons

### What's the difference with what should have happened?

The posters shouldn't have This one proudly demands that you REMEMBER IO! when they aren't about IO.

### How do we reproduce this bug?

1. Examine a poster
2. See the description
3. This one proudly demands that you REMEMBER IO!

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
Unable to reproduce locally.
![dreamseeker_2023-11-13_18-04-44](https://github.com/cmss13-devs/cmss13/assets/25027759/bd043cd9-6234-4c7c-8fb8-52e977f11ce5)

**Comment by BadAtThisGame302** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/79063506/f6e9120f-600f-400e-9ac9-eca8a503ced8)
![image](https://github.com/cmss13-devs/cmss13/assets/79063506/cd82c0e3-08ec-45de-ad2b-64f394356e39)

**Comment by Birdtalon** [comment]
Ok so it's the two posters in the CL office, map issue.
```
/obj/structure/sign/poster{
	desc = "A large piece of cheap printed paper. This one proudly demands that you REMEMBER IO!";
	icon_state = "poster14";
	name = "propaganda poster";
	pixel_y = 32
	},
```
