### ISSUE TITLE
CAS UI randomly bricks to varying degrees 

### ISSUE THREAD

**Issue by ULTRANUT99** [cmss13-devs/cmss13#4923]
### Testmerges

#4812

### Round ID

Unknown for #1, 19511 for #2

### Description of the bug

**CRASH #1**: During unknwn Round ID, I loaded 2 lasers, 2 minirockets roundstart. They were fully loaded. I programmed a FM the same name as I always do, "WALL OF DEATH". I gimbaled the first step of RKT1 to -4. This did not work; it removed itself off -4 every time I went to the next step. _**This is a bug I can duplicate every single round on any weapon, without crashing the UI.**_

Whatever. Program RKT1 to -5, -1, -5. Move on to LSR2. Set it to -4. Doesn't work, so set it to -5. Good. Move to next step. Set it to -1. UI crashes. Go to re-enter that FM, can't even reach the display screen for it (where the edit, delete options are). Crashes the second you click on it. Create new FM. Edit LSR2. Set step 1, crashes. Same behavior. Create new FM. Edit LSR3. Skip to setting step 3. Crashes. Same behavior. Get all the way up to 5. Have to have admin delete the FMs via View Variables, because I can't get to the delete screen. Have DCC edit LSR2. Crashes, same behavior. Have DCC try to view the crashed FMs. Crashes, same behavior. LSR FM menu was completely bricked this round, for no apparent reason. Editing RKT was fine the entire time. Every crash kicked out [this stack](https://pastebin.com/zEW1Emre)

**CRASH #2** Latejoin game after apparently being attached to a FEB2021 clusterban(?). Whatever. Reconnecting fixes this. Ask existing PO if he needs any help with CAS, I've been teaching people the new UI and the vector system and all that, since I'm brand new, the new UI isn't new to me its just what I learned on. He says the console is crashed. The _entire console is crashed_. I confirm this. Can't open the UI at all without kicking out [this stack](https://pastebin.com/9GcjMQtC). It bricked for him when he tried to equip Medevac menu. IDK if this was his first time equipping Medevac menu that round. Apparently DCC on the Alamo, at a SEPARATE time in round, also got bricked, but this time it was Fulton menu. This kicked out the same stack as the Medevac brick. 

Bear in mind this isn't just the one menu like the FM one was. Both of these completely bricked their respective weapons consoles. POs were out of a job the entire round. 

### What's the difference with what should have happened?

for it to work

### How do we reproduce this bug?

i don't know. it's completely random. I know, SOMETIMES, if you try to execute a firemission while not having enough ammo, and you go to edit the FM, it'll crash like CRASH #1. IDK if its the same stack. but that one isnt a permanent brick, you can close and reopen the console a few times and it'll fix. 

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ULTRANUT99** [comment]
**it is my opinion that this testmerge should be reverted until such point that it doesn't randomly brick entire rounds and waste an hour of people's time**

**Comment by Grithok** [comment]
I was in the same round as the DCC alamo pilot. We had installed 3 sentries, one on each wing, and one in the center. We had also installed the fulton. All on the alamo.

I went to the weapons console, selected weapons on the right panel, selected fulton, and it crashed.

TypeError: Unable to get property 'getState' of undefined or null reference
   at t.useSharedState (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:245553)
   at t.useEquipmentState (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:587872)
   at t.SupportMfdPanel (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:575431)
   at Be (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:161096)
   at Anonymous function (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:161364)
   at Te (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:161342)
   at Anonymous function (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:161364)
   at Te (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:161342)
   at Ee (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:162195)
   at Te (http://cdn.cm-ss13.com/live/53/asset.53c7e797ffcbe95a606f05d70d0e8d84.js:1:161206)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"anolaaddictus","interface":"DropshipWeaponsConsole","window":{"key":"[0x201793e]-main","size":null,"fancy":1,"locked":0}}

**Comment by ULTRANUT99** [comment]
Oh. Hex location for the Fulton/Medevac stack: A fatal exception has occurred at 002B:C562F1B7

**Comment by ULTRANUT99** [comment]
annnnnd now that stickyban came back

**Comment by mullenpaul** [comment]
Thanks for reporting these issues. Since the issues with the most recent commits have come to light this is off TM. I appreciate the detailed issue report and I will endeavour to have it resolved before a future TM.

**Comment by mullenpaul** [comment]
I'll keep the issue open until I have tested the fix myself.

**Comment by mullenpaul** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/101871009/d033ee83-9c57-4d40-b9af-d9c55d9685e7)
Where there any additional steps here? I'm not having any crashing issues involving setting gimbals. The only issue that I can seem to find right now is offset 12 being funny

**Comment by mullenpaul** [comment]
Medevac/Fulton bugs have been recreated and resolved.

**Comment by mullenpaul** [comment]
There was also a bug with -4, funnily enough so excellent spot. The label came through as '-4 ' rather than '-4' which would cause problems.

**Comment by ULTRANUT99** [comment]
> Medevac/Fulton bugs have been recreated and resolved.

Hey man. I am very fucking impressed how quickly you resolved this (and the -4 bug I mentioned). I have full confidence in this project & while I have been pretty vocal about disliking it (even as a new player), it's grown on me quick. Please keep working on it. 

I actually am an avionics mx guy so I'm very familiar with the MPD. How these things are actually designed is like... I'm gonna DM you an photo of a display. 

Looking at those displays in flight is super nausea-inducing so the UIs are designed to allow minimal engagement. The reality of your targeting page (not a real one lol, they dont work like this, theyre all HOTAS) WOULD BE this: let's say PB 3 (third down, left side) for example would be dedicated to vector. I'd press it and a little stroke display next to it, not on the button because it's a physical tactile button, would cycle between NS SN etc. 

Then PB4 would be dedicated to my PVU (precision velocity update/Doppler heading or as you call it, offset direction). I'd hit it and a little stroke display next to the button would cycle between N S W E. 

Then the rest of my pushbuttons would literally be offset 1-12. You have 20 PBs so thatd leave us 3 PBs (usually M for menu and maybe a BIT button + free space). That offset thing isn't necessary as you've got the scroll thing BUT.... that scroll thing is very imprecise lol, it's hard to get an exact number. Individual buttons would be better! And individual buttons rather than a "touch screen/flatpanel" like you've got really helps with emulating the retro/80s aesthetic of Alien. The jet I work on is 80s-90s models and it still uses physical pushbuttons on all the MPDs... they're CRT too. 


Its all consolidated to one menu. This allows for very explicit tactile interaction with the UI with 0 room for error. And is how such a display would actually work. What I described is actually no shit how our AAI and IFF pages work. Page entirely dedicated to every AAI function. Page entirely dedicated to every IFF function. No navigation outside of them. 

You don't have to do this obviously but it alleviates a lot of the eye strain and frustration and stress. And less separate menus=less chance for shit to go wrong, right? 

Thanks man. Hopefully by the time by stickyban is lifted you'll have that major bug fixed and I can play around with this menu again.

**Comment by ihatethisengine** [comment]
![2023-11-26_10-28-39](https://github.com/cmss13-devs/cmss13/assets/115417687/6238bf78-b4f2-469d-8e25-373e7dc48ea8)
5. If you remove a weapon and even if you put it back, FM that includes the weapon breaks forever. breaks how? You cannot change FM or delete. You can fire it but the gun in question wouldnt work
6. If you click offset arrows too much it begins to tell you "you did to many actions in a minute" and prevents you from changing offset until the minute passes
7. There can be more than 6 targets, but I guess you cannot pick them?

**Comment by Grithok** [comment]
Just to confirm, is that the newer UI or the older UI that is having those issues?

**Comment by ihatethisengine** [comment]
The one TMed rn, it got an update. I figured I could post the issues here without opening a new issue.

**Comment by mullenpaul** [comment]
These issues should be resolved.
