### ISSUE TITLE
getting stuck in the demolitions simulator with two people.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#4927]
### Testmerges

N/A

### Round ID

19518

### Description of the bug

Whenever two people enter the demolitions simulator, after the first person exits the second person can only exit by ghosting, as the exit option/UI goes away. 

### What's the difference with what should have happened?

 The UI to leave goes away when the first person exits the console.
 Right now I have to tell people to ghost then put their ckey back in to get them back into the game. This shouldn't be happening.

### How do we reproduce this bug?

1. Person one enters the demolitions simulator camera/UI.
2. Person two enters also.
3. Someone leaves the UI first, it doesn't matter who. 
4. Once someone leaves, the option for person two to leave disappears. 
5. The only way out that I know of is to ghost.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Cthulhu80** [comment]
click on resist next time it happens.
