### ISSUE TITLE
Water overlay is no longer working.

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#4935]
### Testmerges

not relevant

### Round ID

not relevant

### Description of the bug

go in a water tile and notice that you are walking on water.

### What's the difference with what should have happened?

you should have the water overlay covering your legs.
We use to have an water overlay that cover player sprite when in the water but now it's gone.
i don't think it got remove on purpose.
i don't know when the bug first appeared. 

### How do we reproduce this bug?

Go in a water tile with a marine and see that you are now walking on water.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This was a PR qq
