### ISSUE TITLE
M56D kills cades

### ISSUE THREAD

**Issue by Don2137** [cmss13-devs/cmss13#495]
## Description

At 4 or more tiles, cades have an rng chance to block fired bullets (that are fired from behind them). This change was made to prevent megafobbing. For some reason, M56D does not abide by this rule, and has an rng chance to hit them at even 1 tile. It has to be put on the exact same tile to never hit them. Unsure if this applies to the M2C.

## Difference between expected and actual behavior

Should work the same as normal guns

## Steps to reproduce

![image](https://user-images.githubusercontent.com/63935800/174442296-033d2ebc-03ae-4d65-b723-d4746a14fbe3.png)
Not a very good screenshot but the metal sheets used to be cades. Very easy to reproduce.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Mirvra** [comment]
Probably technically not a bug?

I'm pretty certain that the 4 or more tiles thing was added while the M56D still lacked IFF, so it wasn't included in the change as it would've just been shooting marines then.

Unsure if this is something the person that added IFF to M56D just didn't think of fixing, or if it's been left in as a feature to prevent M56D's from being placed en-masse behind 3-4 layers of cades to create silly last stand holds.

**Comment by PhantomEpicness** [comment]
> Probably technically not a bug?
> 
> I'm pretty certain that the 4 or more tiles thing was added while the M56D still lacked IFF, so it wasn't included in the change as it would've just been shooting marines then.
> 
> Unsure if this is something the person that added IFF to M56D just didn't think of fixing, or if it's been left in as a feature to prevent M56D's from being placed en-masse behind 3-4 layers of cades to create silly last stand holds.

has been in since as long as I remember, IFF MR certainly did not add this

**Comment by usnpeepoo** [comment]
This is intended.
