### ISSUE TITLE
Warriors can decapitate hugged

### ISSUE THREAD

**Issue by fighterslam** [cmss13-devs/cmss13#4977]
### Testmerges

#4793, #4866, #4915, #4934, #4960

### Round ID

19600

### Description of the bug

Warrior lunged me, pulled me back, hugger hugged me, warrior continued dragging me, and then decapitated me. 

### What's the difference with what should have happened?

Xenos are supposed to not be able to do this sort of stuff to caps, queen is mechanically locked from gibbing infecteds for this reason. It doesn't make sense that warrior should be able to bypass it.

### How do we reproduce this bug?

1. Warrior Lunge.
2. Still maintaining the lunge, have hugger grab onto victim.
3. Proceed to tear their head off after the hugger pops off.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
This is caused by a time period between the face hugger attaching and actually inserting the alien embryo. More of an oversight.
