### ISSUE TITLE
Chat resets to the bottom when scrolling up

### ISSUE THREAD

**Issue by r1ks-iwnl** [cmss13-devs/cmss13#5019]
### Testmerges

#4866, #4934, #4960, #4986, #5007, #4828

### Description of the bug

The chat resets back to the bottom of the history when trying to scroll up if a lot of messages are being set rapidly so i have to move my camera somewhere quieter to do it. The chat doesn't reset if it's already scrolled up.

### What's the difference with what should have happened?

The chat scrolls up uninterrupted.

### How do we reproduce this bug?

1.Be in a place where messages are sent rapidly(active frontline)
2.Scroll the chat up

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
tested on live - does not work
