### ISSUE TITLE
M2C Pickup Issue

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#503]
## Testmerges:

N/A

## Description
The M2C goes to your back instead of your hands if you pick it up with your back slot open.

## Difference between expected and actual behavior
It should go in your hands no matter what.

## Steps to reproduce
Take off your backpack
Place the M2C
Pick up the M2c

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
intended, specifically coded in this way. not a bug, make a pr if you want to change it.
