### ISSUE TITLE
CLF/Survivor Private bug

### ISSUE THREAD

**Issue by BadAtThisGame302** [cmss13-devs/cmss13#5043]
### Testmerges

#4866, #4960, #4986, #5007, #4828, #4939, #4812

### Round ID

19689

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/79063506/6654e051-4f33-43ef-a8c9-03b611cada68)

### What's the difference with what should have happened?

They CLF are not supposed to be Privates, they do not have a military rank system (Pretty sure)

Plus I found it's also an issue for UA Riot Survs on Fiorina and other maps, I examined a corpse and it also said private as their title instead of civilian or something else.

### How do we reproduce this bug?

1. Examine a CLF Synth/Medic/Technician etc.
2. Examine a UA Riot Survivor
3. Private [NAME]

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
Confirmed bug though it's a bug in master, not sure when/what caused it. I have a fix :soontm:

**Comment by BadAtThisGame302** [comment]
https://github.com/cmss13-devs/cmss13/pull/5128 Fixed this
