### ISSUE TITLE
Resin walls can't be nested on unless built before cluster.

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#5061]
### Testmerges

N/A
-----------

### Round ID

across multiple rounds

------------
### Description of the bug

If you build a wall, then build a cluster: the hive weeds will attach onto the resin wall and you can nest on it.

If you build a cluster, then build a resin wall on one of its hive weeds: the hive weeds do not attach onto the wall, you cannot nest on it.

If it's anything like #5060 , it's probably that building a resin wall on a weed deletes the weed under it for some reason. Or just doesn't give it that "nestable" flag unless a hive weed is pumped onto it.

-------------
### What's the difference with what should have happened?

You should be able to nest on any resin wall adjacent to hive weeds, regardless of if a cluster "pumps" weeds onto its tile.

--------------
### How do we reproduce this bug?

1. Build a resin wall
2. Build a cluster next to the resin wall (it pumps the hive weeds onto the resin wall)
3. Try to nest on it
**4.** It works! You can nest on it
...
5. Build a resin wall on one of the hive weeds
6. Try to nest on this new wall (the hive weeds were not pumped onto it)
_7._ It does not work... you cannot nest on it

///
Not sure if it's intended, but regardless it should probably be fixed for QOL, since it's pretty unintuitive.
Note: This is from my memory of how it works (because of #5060 making me remember this bug). It's been a while since I've played xeno, but I remember this happening pretty consistently and making whole parts of hives unnestable.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by private-tristan** [comment]
somewhat similarly, if a hivelord upgrades a wall, it loses its' hive weeds, meaning that you can't actually nest marines on them without repairing the hive core/cluster.

**Comment by Birdtalon** [comment]
Fixed in #5096
