### ISSUE TITLE
Lobby screen zoom lags my computer

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#5064]
### Testmerges

N/A

### Description of the bug

The zoom on the lobby screen lags my computer. It's the same with all binocs and whatever, but those situations are not nearly as annoying as the lobby screen lag... It's still usable but very annoying.

By lags my computer, I don't mean uses lots of resources, it just somehow absolutely fucks up the fps of my computer. 
Some hardware issue, maybe graphics card... maybe it's a very uncommon issue.

### What's the difference with what should have happened?

Preference to turn off lobby screen zoomout

### How do we reproduce this bug?

1. Have a bad computer
2. Join the cmss13 Lobby
3. Zoomout automatically activates to see the full portrait
4. Lags bad computers (like mine)
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
I'm fairly sure this is BYOND related and not exclusive to our codebase.

**Comment by ItsVyzo** [comment]
Hardware/Specs issue.
