### ISSUE TITLE
badly placed lz cammeras

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#5071]
### Testmerges

.

### Round ID

19734

### Description of the bug

cammera gets stuck to ds after first landing

### What's the difference with what should have happened?

cam should be next to ds to stay

### How do we reproduce this bug?

1.install lz detector
2.land on lz2 on lv for example (happens on loads of maps)
3.takeoff and check cams again
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
1-on what map did it happened?
2-so if understand correctly LZ camera work before you land for the first time then they don't ?(assuming they have been crushed deleted by the DS landing?..)

**Comment by cuberound** [comment]
> 1-on what map did it happened? 2-so if understand correctly LZ camera work before you land for the first time then they don't ?(assuming they have been crushed deleted by the DS landing?..)

LV lz2 for shure, nv lz1. yes cams work just fine before first drop but get taken away by the ds after first drop, they do not get deleted

**Comment by Huffie56** [comment]
did LZ1 on LV worked?
seem like cameras aren't put the same way on LZ1 and LZ2
