### ISSUE TITLE
Xeno corpses frequently cover marine sprites.

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#5076]
### Testmerges

#4986: 'Projectile smooth movement' by Doubleumc at commit f405a0a3ad #4866: 'Radio TGUI backend Tidy-up & Adds Listening Devices' by realforest2001 at commit a7c0fa5ea1 #4997: 'LV624 Fog Removal + River Change V2' by Steelpoint at commit 107c962ae5 #4939: 'Adds Latejoin scaling to Vendors and ASRS' by fira at commit 9e71b28a1d #5054: 'Egg Changes' by Zonespace27 at commit ecf4515eaf #4842: '/tg/ Status Effects Part 2 - datum, KD, KO, Stuns' by fira at commit f6034d702f #5067: 'Return Ice Classic to CM for the Holiday Season' by BroseidonMOO at commit d7b5745337 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 7e42b87292 #5073: 'Ckey check verb' by realforest2001 at commit 7fdb14bde6

### Round ID

19737

### Description of the bug

Sprite layering issue (?) something causes the xeno corpses to layer above things under it...

![image](https://github.com/cmss13-devs/cmss13/assets/44538569/98b4be16-671c-4b01-8b07-68d27847e39a)

The marine is hidden under the xeno corpse's sprite for some reason... (they are standing up)

### What's the difference with what should have happened?

Xeno corpses aren't supposed to layer above marine sprites... 
it means marines can block xeno point-and-click abilities by standing under large corpses, or even hide from thermal vision completely.

### How do we reproduce this bug?

Not exactly sure  how this happens, but in round what happened is:

1. Xeno dies
2. Their corpse covers marine sprites
3. Marines can hide under the corpse
...

//

This started happening a few days ago i think, around when the first TG status effects pr got testmerged. I've been seeing it happen pretty consistently (i'm not sure if it's 100% of the time or only sometimes), and can probably be abused very easily if people wish to do so

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
We found the reason, going in crit for some reason resets your layer to initial (to unhide hidden mobs, although that's weird) and don't move to dead layer after, well, the death. @fira promised to fix this, but I am not sure if they didn't forget.
