### ISSUE TITLE
ice colony classic is too easy to stalemate

### ISSUE THREAD

**Issue by restedwaves** [cmss13-devs/cmss13#5080]
### Testmerges

#4986: 'Projectile smooth movement' by Doubleumc at commit f405a0a3ad #4866: 'Radio TGUI backend Tidy-up & Adds Listening Devices' by realforest2001 at commit a7c0fa5ea1 #4939: 'Adds Latejoin scaling to Vendors and ASRS' by fira at commit 9e71b28a1d #5054: 'Egg Changes' by Zonespace27 at commit ecf4515eaf #4842: '/tg/ Status Effects Part 2 - datum, KD, KO, Stuns' by fira at commit 2faa171118 #5067: 'Return Ice Classic to CM for the Holiday Season' by BroseidonMOO at commit 889d9ba78c #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 7e42b87292 #5073: 'Ckey check verb' by realforest2001 at commit 73113956b6

### Round ID

19741

### Description of the bug

while a fun and interesting map all the underground sections are too easy to cut off, at least the marines can use the elevators but for the ladders they either get surrounded by eggs or cades
(there's also the topside being too open but personally i like it for making skirmishes a viable tactic other than forever walling as a xeno)

### What's the difference with what should have happened?

multi z maps are interesting and we should have more of them, but getting cut off from those z levels shouldnt be this much of an issue, if there were say, some staircases aswell that would allow crushers to charge through as another way up or allow multiple xenos to attack at once the map would be in a much more reasonable state

### How do we reproduce this bug?

1. play ice colony classic
2. complain about marines and xenos not knowing how to use a ladder for most of the round
3. trap or block ladders to make them unusable for either side
4. leave out of boredom
5.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@restedwaves feel free to open a post on the forum instead if you really want.

**Comment by ihatethisengine** [comment]
Feature
