### ISSUE TITLE
ice colony classic can start without weeds

### ISSUE THREAD

**Issue by restedwaves** [cmss13-devs/cmss13#5081]
### Testmerges

#4986: 'Projectile smooth movement' by Doubleumc at commit f405a0a3ad #4866: 'Radio TGUI backend Tidy-up & Adds Listening Devices' by realforest2001 at commit a7c0fa5ea1 #4939: 'Adds Latejoin scaling to Vendors and ASRS' by fira at commit 9e71b28a1d #5054: 'Egg Changes' by Zonespace27 at commit ecf4515eaf #4842: '/tg/ Status Effects Part 2 - datum, KD, KO, Stuns' by fira at commit 2faa171118 #5067: 'Return Ice Classic to CM for the Holiday Season' by BroseidonMOO at commit 889d9ba78c #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 7e42b87292 #5073: 'Ckey check verb' by realforest2001 at commit 73113956b6

### Round ID

19741

### Description of the bug

map starts with no weeds, we actually needed an admin to make one of the xenos a drone to save the round

### What's the difference with what should have happened?

weeds are needed for roundstart evos, without it it tends to make the map rather difficult

### How do we reproduce this bug?

1.play ice colony classic
2.roll xeno
3.suffer
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
same @restedwaves feel free to open a post on the forum to discuss this if you really want.
