### ISSUE TITLE
Can't cancel evolve with resting any more.

### ISSUE THREAD

**Issue by Sietch1** [cmss13-devs/cmss13#5109]
### Testmerges

no

### Round ID

19775

### Description of the bug

Since the changes to resting, xenos can no longer cancel evolution with resting mid-way through.

It's very nice QoL and it has been this way a long time. Can we get it fixed? Sometimes you mis-click and picking the wrong t3 after 20 mins of evo as a Warrior is absolute torture.

### What's the difference with what should have happened?

Resting should cancel evolution if you're midway through.

### How do we reproduce this bug?

As above.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/5162
solved by this PR it seem. feel free to reopen if it didn't solve it
