### ISSUE TITLE
Buggy Ghost upon reentering corpses eaten by weeds

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#5138]
### Testmerges

N/A (has been happening for a few months now afaik)

### Description of the bug

-----
If you die on weeds, your body goes perma. Eventually, it gets eaten by the weeds...

However
If you reenter your permad body, you get a new buggy ghost upon ghosting again.

It is the same sprite as the weeded body, but unlike other ghosts, you cannot hover over it to see its name. If you ctrl click to try orbiting it, it teleports your ghost to the lobby image z level (for me, it stutters my game/makes it laggy when trying this). 

### What's the difference with what should have happened?

-----
Your ghost should not become buggy upon reentering your body, after it has been eaten by weeds.

### How do we reproduce this bug?

1. Die (on weeds)
2. Ghost
3. Wait until you perma
4. When you are perma, your body should get eaten by the weeds

-------
6. Once eaten by the weeds, enter your body.
7. Ghost again: Your ghost sprite is now the covered up corpse.
8. Your ghost is now buggy... :(

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Linked PR will already fix this issue because the weeded appearance will no longer have mouse opacity. Ghosts already have their mouse opacity corrected (you can confirm this by the ability to right click your self and see both the weeds and your ghost mob). Issue is simply that the weeds are ontop and orbiting the weeds has weird behavior.
