### ISSUE TITLE
Humans are able to draw weapons while stunned (dropping them)

### ISSUE THREAD

**Issue by LoJoFan** [cmss13-devs/cmss13#5140]
### Testmerges

#4986, #4939, #5054, #4842, #5067, #5018, #5127, #5134

### Round ID

Across multiple rounds.

### Description of the bug

Humans can draw weapons while stunned, dropping them on the floor.

### What's the difference with what should have happened?

Humans should not be able to draw weapons while stunned.

### How do we reproduce this bug?

1. Get stunned
2. Draw weapon(s)
3. They get drawn and dropped
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Tested on lives - no longer an issue
