### ISSUE TITLE
Stuck at the lobby image after selecting a spawn.

### ISSUE THREAD

**Issue by blazeitbilly** [cmss13-devs/cmss13#5177]
### Testmerges

#4842, #5130, #5157

### Description of the bug

After the round start timer finished, I selected to spawn as a buried larva. Once I selected to spawn, the GUI that lets the player select their team/spawn was gone, but I was still viewing the lobby image.

### What's the difference with what should have happened?

Normally, I would select "buried larva" and spawn as one, and then play the game as per usual.

### How do we reproduce this bug?

1.Miss initial spawn roll.
2.Rapidly select 'Join the Hive!'
3.Rapidly select 'Buried Larva'
...Could have potentially occurred from clicking too fast, the menu went away but the server never actually received a packet from me selecting my spawn. Haven't attempted to recreate it.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
In general spawning as a larva is going to be handled with the larva queue. Join as xeno is almost always going to only offer afk xenos to take over (buried spawns is only an option when there is no core, first 30 minutes of the game, and there is no queue). Just observe and ensure your xeno candiacy is set.
