### ISSUE TITLE
[Xeno] Sound reverb/echo persists after recovering from crit

### ISSUE THREAD

**Issue by Birdtalon** [cmss13-devs/cmss13#5181]
### Testmerges

#4842 #5067 #5130 #5157

### Description of the bug

After going into crit as a Xeno, when you recover from crit the sound echo/reverb persists.
I experience this and it has also been reported by at least one other player.

### What's the difference with what should have happened?

Sound reverbing/echo should stop when you recover from crit

### How do we reproduce this bug?

1. Be a Xeno
2. Get put into crit
3. Recover from crit
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
Should be fixed as of 2f46a5ed264f5dc3fd97be386aae464fe97b39b3
