### ISSUE TITLE
M3 Pattern, M4 Pattern, B12 Pattern armors have M3-EOD speed.

### ISSUE THREAD

**Issue by LoJoFan** [cmss13-devs/cmss13#5193]
### Testmerges

#4842, #5130, #5157, #5007

### Round ID

Across multiple rounds.

### Description of the bug

The M3 medium, M4 and B12 armor all have M3-EOD level speed.

### What's the difference with what should have happened?

M3 medium, M4 and B12 armors should share the same speed level and be different from the M3-EOD's. When wielding a gun with either of these armors, there will also be no speed reduction, hence why I came to the conclusion the armors meant to have medium speed reduction have heavy speed reduction.

### How do we reproduce this bug?

1. Put either of the bugged armors on
2. Run side to side with your buddy, who is lovingly wearing the M3-EOD for this test
3. Realize that the medium slowdown armors are slower than intended!!!!!!!!!

M3-EOD, for reference, while I'm wearing the B12.
https://github.com/cmss13-devs/cmss13/assets/112346996/f5436392-f31b-40b6-b22d-a0e57439d856

M3 pattern (medium), for reference, while I'm wearing the B12.
https://github.com/cmss13-devs/cmss13/assets/112346996/8459bc14-dc94-4f02-8ae9-51ad23212d9b

M4 pattern, for reference, while I'm wearing the B12.
https://github.com/cmss13-devs/cmss13/assets/112346996/65fee6bb-40e1-40fd-81e1-440963017d9f

THANK YOU TO KRYTH FOR HELPING!!!!

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by InsaneRed** [comment]
https://github.com/cmss13-devs/cmss13/pull/5130 this causes the issue due to pathing

**Comment by Nanu308** [comment]
I checked the variables ingame on all the armors listed, and the heavy has more slowdown than the rest of them on both the vv movement_compensation and slowdown.
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/e36e11d1-7305-42d1-9f05-83128f52eaf3)
![bilde](https://github.com/cmss13-devs/cmss13/assets/59782240/04e773f8-8fef-48e2-ad0d-2778e9113362)

Going to close out this bug report, i cannot replicate your error.
