### ISSUE TITLE
The tgui window for the "config/launch supplypod" admin command bluescreens after 5-15 seconds of being open.

### ISSUE THREAD

**Issue by silencer-pl** [cmss13-devs/cmss13#52]
## Reproduction:

Title pretty much says it all. 

5 - 15 seconds after opening the config/launch supplypod admin command window, regardless of what action (or no action) is taken, the window tgui bluescreens with the following text:

> A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
> 
>  UnhandledRejection: TypeError: Unable to get property 'x' of undefined or null reference
>    at c.fn (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:23127)
>    at y.forceUpdate (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:2082)
>    at Anonymous function (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:2221)
>    at W (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:119055)
>    at Anonymous function (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:2189)
>    at Anonymous function (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:28900)
>    at ie (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:117743)
>    at Anonymous function (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:119408)
>    at r (http://127.0.0.1:59820/tmp27264/tgui.bundle.js:1:69501)
> User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
> State: {"ckey":"silencerpl","interface":"PodLauncher","window":{"key":"[0x21023716]-main","size":null,"fancy":1,"locked":0}}
> 
> Nanotrasen (c) 2525-2562 

There is also a giant black rectangle covering the error window, see attached screenshot
![image_2022-04-16_120625289](https://user-images.githubusercontent.com/103842328/163682554-108d834a-8493-4f75-97d9-54542a5db965.png)

**Comment by stanalbatross** [comment]
believed to be caused by the tooltip offsets being borked 

test with tgui kitchensink
