### ISSUE TITLE
The Security Tuner is not showing the direction to the room's APC

### ISSUE THREAD

**Issue by hungerjames** [cmss13-devs/cmss13#5206]
### Testmerges

#4842, #5130, #5007, #5197, #4477, #5204

### Round ID

Multiple Rounds

### Description of the bug

When I used the security tuner, it did not tell me what direction the APC was, only how far away it was.
The chat printout has an erroneous space where the direction used to be.
e.g., "The local APC is located at 14 units ."

### What's the difference with what should have happened?

It should have told me which direction the APC was from me.

### How do we reproduce this bug?

1. Get a security tuner
2. Use it in hand
3. View the printout in the chat 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/e1c79134-4006-43b5-8a72-b94c2b5734e9)
that's the item i think...
and yes it seem in the code that it should indicate the direction of the APC to... need to test it out...

**Comment by cuberound** [comment]
what location did it happen at?

**Comment by hungerjames** [comment]
I had it happen on the Almayer and the groundside map. I specifically tested it in the Almayer main hallways and lower engie. Then at comms on Chance's and Fiorina.
