### ISSUE TITLE
Darkness progression sometimes completely disappears

### ISSUE THREAD

**Issue by Chainsawicus** [cmss13-devs/cmss13#522]
## Description
Sometimes, when moving around in an unlit area with a small amount of light enabled, such as a suit light, progressive darkness will suddenly turn off and give you fullbright vision on every tile, instead of varying light levels.

## Difference between expected and actual behavior
Expected behaviour: Darkness gets progressively heavier, resulting in gradually less vision per tile until full darkness.
Actual behaviour: This doesn't happen, and all tiles with any level of light are treated as fully lit.

![image](https://user-images.githubusercontent.com/103772903/174500157-44f42ad6-ad46-49b5-afbf-9dd9c963d577.png)

## Steps to reproduce
Wander around with a suit light or any light source for extended periods of time, it will eventually occur.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
never saw this occurred this year and if it was still up people would complain massively...
@ItsVyzo 
i think you can close it or atleast mark it as needing reproduction... thanks

**Comment by ItsVyzo** [comment]
Thank ya @Huffie56 

Probably fixed...?
