### ISSUE TITLE
Metal Barricades Inconsistency

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#5229]
### Testmerges

NA

### Round ID

NA

### Description of the bug

Basically- you can repair/dismantle walls foldable barricades plasteel barricades and reinforced walls one after the other & simultaneously. 

Metal barricades are the exception to the rule as repairing one prevents starting new repairs. I don't think it'd be that huge of a buff considering gas & acid still forces engies to move away. Furthermore you can repair for example about 9 plasteel barricades and one metal barricade but if you repair the metal barricade first you can only repair one metal barricade. Bad design!

### What's the difference with what should have happened?

Should be able to repair multiple metal barricades.

### How do we reproduce this bug?

1.Repair multiple plasteel cades or walls
2.Enjoy
3.Repair multiple metal cades
4.Don't enjoy

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Weuyn** [comment]
this was added intentionally and plasteel cades were overlooked

**Comment by ihatethisengine** [comment]
Definitely not a bug. On the contrary, it's more likely that the ability to repair several folding cades (not only plasteel) is a bug. Not that I want anyone to fix this, but buffing engineers by allowing them to repair multiple metal cades at once seems unreasonable either.

**Comment by nuklearcellphoneg** [comment]
I'm quite unsure- again it's the sole exception to the rule- for example you can dismantle up to four walls simultaneously from a corner. There's also the issue how whoever did it coded it- you can repair 9 plast + 1 metal cade simultaneously but the second you repair the metal cade it prevents repairing new foldable cades. That's just bad implementation imo.

As it stands if metal cades weren't made consistent then technically the optimal gameplay plan is to have your last line of defense to be 100% plasteel cades with its edges reinforced walls/walls- outside cades should all be made of pure metal. Then again I assume that if you made a line of pure foldable cades you'd be able to repair 100% of them simultaneously as well.

**Comment by ihatethisengine** [comment]
Dismantling walls is irrelevant for balance, but repairing cades is crucial for FOB siege gameplay. You are not going to realistically have 9 plasteel cades because of the cost so it's also not a big deal, but I agree it was probably an oversight rather than deliberate decision.

**Comment by Huffie56** [comment]
hopefully this will fix it or part of it...
https://github.com/cmss13-devs/cmss13/pull/5609
