### ISSUE TITLE
Highlight chat settings missing since Linux

### ISSUE THREAD

**Issue by Chainsawicus** [cmss13-devs/cmss13#523]
## Description
Previously you used to be able to make multiple highlight boxes with their own individual settings, such as having your name be one colour, highlighting the entire chatline, and your xeno name a different colour, not highlighting the line. These were lost at some point during the move to Linux, and should be returned.

## Difference between expected and actual behavior
Expected: Multiple highlight boxes with their own separate settings and colours, with the ability to toggle on and off whether the entire line in the chatbox would also be highlighted.

Actual: You can only make one box, so all highlights are the same colour, and you cannot toggle off the entire line being highlighted.

## Steps to reproduce
Log onto the server and hit the cog icon in chat.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Watermelon914** [comment]
consequence of not backporting it to tg.

Modifying the backend components of tgui without backporting means that it'll get overwritten whenever updates of the backend system want to be pulled from upstream. This happened before and it's happened again, if someone decides to try and reimplement this then I recommend they do it at tg first before doing it at CM to prevent this issue from cropping up again.

**Comment by MidwayAtom** [comment]
Reported #122 Closing.
