### ISSUE TITLE
Walls/Reinf Walls take so long to repair new players assume it's broken

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#5233]
### Testmerges

NA

### Round ID

NA

### Description of the bug

When you repair cades you repair a part of the total damage for a consistent amount of time.

With walls/reinforced you attempt to repair the entire thing in one go- and if it's extremely damaged you could sit there for literal minutes. Walls/Reinf should either repair in parts like cades or have their repair time heavily shortened.

### What's the difference with what should have happened?

Shouldn"t take ten years to repair one damaged wall.

### How do we reproduce this bug?

1.damage a wall until extremely damaged
2. repair
3. wait
4. wait
5. wait
6. ad nauseam 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Not a bug / https://forum.cm-ss13.com/c/development/idea-guys/24
