### ISSUE TITLE
MG deploys in inaccessible way on Dropship NE weapons hard point 

### ISSUE THREAD

**Issue by Cooliecan** [cmss13-devs/cmss13#5236]
### Testmerges

#4842: '/tg/ Status Effects Part 2 - datum, KD, KO, Stuns' by fira at commit 595086537a #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 3552058523 #4477: 'Keycard authenticator can call ERT winout admin intervention' by Diegoflores31 at commit 8f625da736 #5204: 'Requisitions elevator lighting fix' by NateDross at commit 12b7a0d07b #5202: 'Adds a way for SLs/SOs/XOs to recommend medals that the CO can then approve/deny.' by TheGamerdk at commit 1ebcc431cb #5219: 'Ghost listening device preference' by realforest2001 at commit afd02c87de #5235: 'Adds closeother to USS Almayer doors.' by realforest2001 at commit 2fd94702ed

### Round ID

19994

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/13284499/8015533e-e83f-4ac0-8155-1e08da2e5bf8)

### What's the difference with what should have happened?

SHould deploy in the other direction.

### How do we reproduce this bug?

1.purchase MG hardpoint, put on NE hardpoint and deploy, NW works.
2.
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by cuberound** [comment]
got fix done
