### ISSUE TITLE
Wall inside of door on Kutjevo

### ISSUE THREAD

**Issue by sargashC** [cmss13-devs/cmss13#5238]
### Testmerges

#4842, 5007,  4477 5204 5202 5219 5235

### Round ID

19996

### Description of the bug

On east side of of medical stormlocks, a door exists that just has a wall in it. Leading south into construction. 
![image](https://github.com/cmss13-devs/cmss13/assets/52183648/6528259e-6262-4120-ba17-1983fecf7f16)

### What's the difference with what should have happened?

Either no wall, or no door (I think it's a good door.)

### How do we reproduce this bug?

1.Go to kutjevo
2.Go to the spot mentioned

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
i tested it and i think that's the spot couldn't find the door
was it on an event round?
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/1429d82d-25b8-409b-859c-e420a7999127)

**Comment by sargashC** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/52183648/7e4fe170-0498-4b31-b9f2-046dcd53f22a)
Its near
![image](https://github.com/cmss13-devs/cmss13/assets/52183648/46c15bac-6222-4171-897c-949a1f4cc960)

**Comment by Huffie56** [comment]
thanks for the new image and yes it was a nightmare insert...
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/a5d2b7bd-9711-47c7-8aec-049b7df147ef)
