### ISSUE TITLE
Xeno double resisting while on fire 

### ISSUE THREAD

**Issue by Strobia** [cmss13-devs/cmss13#5247]
### Testmerges

#4842: '/tg/ Status Effects Part 2 - datum, KD, KO, Stuns' by fira at commit 595086537a this one maybe????? i dunno i dont code bruh..

### Round ID

20011 ( many more rounds before this one I was just too lazy to report )

### Description of the bug

xenos can double resist while on fire reducing their firestacks 2x faster than they should normally be able to ( game breaking !!!!!!!!!)

### What's the difference with what should have happened?

when they resist they shouldn't be able to keep resisting with lower/no cool down 

### How do we reproduce this bug?

1. play xeno
2.get lit on fire
3.spam b
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
same as #5124
