### ISSUE TITLE
CMP cannot vend from sectech vendors

### ISSUE THREAD

**Issue by Drew156** [cmss13-devs/cmss13#5251]
### Testmerges

#4842, #5007, #4477, #5204, #5202, #5219, #5235

### Description of the bug

Chief MP cannot vend items from sectechs in the brig, "no ID detected" message in corner.

### What's the difference with what should have happened?

CMP should be able to vend zip ties, etc, from sectech machines.

### How do we reproduce this bug?

1. Join a round as the Chief MP
2. Open vendor window on any sectech in the MP prep room

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This only happens if you get sent to lobby and join the round as the same character (slot). I've just tested on local and was unable to reproduce this.
