### ISSUE TITLE
"Evilution" typo

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#526]
## Description

Evolution is misspelled as "Evilution" in hive status (there's a few instances of `evilution` in the codebase, including in some JS).

## Difference between expected and actual behavior

Things should be spelled correctly.

## Steps to reproduce

1. Be xeno.
2. Have living queen.
3. Open hive status.
4. Notice the word `Evilution` **(IMMERSION RUINED)**

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment]
For whatever that's worth, this issue came up several time on GitLab, and it's apparently intended

**Comment by stanalbatross** [comment]
intended because xenos are evil
