### ISSUE TITLE
marines can buckle while stunned

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#5277]
### Testmerges

#5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 3552058523 #5202: 'Adds a way for SLs/SOs/XOs to recommend medals that the CO can then approve/deny.' by TheGamerdk at commit 1ebcc431cb #4812: 'Dropship weapons console TGUI' by mullenpaul at commit dec1a84297 #5173: 'New Healer Drone Ability: Sacrifice, another go' by ihatethisengine at commit 126087a42f #5257: 'Fixes Flight Control Operator surv + gave him a windbreaker and one more access.' by BadAtThisGame302 at commit bb26abc620 #5212: 'Refactors Get_Angle() and related procs' by Doubleumc at commit 7dc49c5da6 #5266: 'Fix Crusher Pass Flags' by Drulikar at commit 692029832b

### Round ID

20075

### Description of the bug

marine bucked themselves to a chair while they were tackled

https://github.com/cmss13-devs/cmss13/assets/54422837/c15020a7-c96a-4cc5-ba57-71cf3bb24a60

### What's the difference with what should have happened?

a marine that's tackled shouldn't be able to interact with chairs

### How do we reproduce this bug?

1. stun a marine
2. have a chair next to marine
3. have the stunned marine drag themselves onto the chair

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Cthulhu80** [comment]
skill issue
