### ISSUE TITLE
Vulture sniper rifle gives permanent  night vision if you aim down sight 

### ISSUE THREAD

**Issue by Strobia** [cmss13-devs/cmss13#5300]
### Testmerges

5007,5281,5288,5086,5030

### Round ID

20108

### Description of the bug

Aiming down sight with the sniper rifle gives you night vision for the rest of your life!!!

### What's the difference with what should have happened?

not this!!!!! it should fade away after you unscope!!!

### How do we reproduce this bug?

1.aim down sight with the sniper rifle 
2. stop aiming down sight with the sniper rifle
3.free nvg hack
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Cthulhu80** [comment]
No way

**Comment by Cthulhu80** [comment]
oke doke, should be fixed.
