### ISSUE TITLE
Queen Eye acts as an enemy for the purpose of the base ravager ability Empower.

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#535]
## Description

Using Empower as a ravager scans for all enemies in close proximity and buffs the ravager based on each enemy therein. When using Empower in proximity to the queen eye, Empower counts the eye as an enemy and buffs the ravager with it. Attached below are two instances of using empower, one with the queen eye in proximity and one without-
With the queen eye:
![Empower With Queen Eye Bug](https://user-images.githubusercontent.com/105765670/174684831-23d56d9e-63a4-44af-a4aa-664ab34e14f7.png)

Without the queen eye:
![Empower No Queen Eye Empower](https://user-images.githubusercontent.com/105765670/174684887-77285000-cd3f-44f6-ad0d-edffdf6f58f2.png)

## Difference between expected and actual behavior

The wiki claims Empower counts enemies for the purpose of buffing and one would hope the queen's eye is not an enemy for the ravager using Empower.

## Steps to reproduce

1. As base ravager, move into proximity of the queen's eye.
2. Use the empower ability.
3. Notice the queen's eye is counted as an enemy for Empower.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
bruh

**Comment by Superwelder** [comment]
broski
