### ISSUE TITLE
Penlight Dexterity

### ISSUE THREAD

**Issue by professionallyretarded** [cmss13-devs/cmss13#5353]
### Testmerges

#5298, #5246, #5113, #5285, #5153, #5294, #5086, #5337, #5280, #5278, #5122

### Description of the bug

You cannot use a penlight as a human without getting dexterity check cancelled.

### What's the difference with what should have happened?

I would expect a human to be able to use a penlight.

### How do we reproduce this bug?

1. Use a penlight targeting eyes, as a human

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
#6691
