### ISSUE TITLE
Sythesis Machine In Research Lab 

### ISSUE THREAD

**Issue by RikardSeltz** [cmss13-devs/cmss13#5366]
### Testmerges

12

### Round ID

20214

### Description of the bug

I was reating a custom healing chem using the sythesis machine which would contain 6 properties: BST, ATX, CSL, DFB, TRF and HGN, after hitting simulate 2 of the 6 chemicals had been deleted as shown in the screenshots provided. 

I reported this to the admin team in game during which I spoke to biolock and Hippie who refunded the points used to create the chem. Following this I tried to make another chem with different properties and the same result happened leaving me with 4 out of 6 on the chem paper.

I the then tried to make a chem with only 4 properties and upon sythesis 2 were removed. 
 
![report](https://github.com/cmss13-devs/cmss13/assets/155434846/198f992d-d366-4519-b834-1f99a2b566f9)
![Report2](https://github.com/cmss13-devs/cmss13/assets/155434846/5c422132-9cdf-4b78-ae7b-b76689696ea0)
![report 3](https://github.com/cmss13-devs/cmss13/assets/155434846/a4882c7e-bfc4-4d1a-89bc-a1c867e4cd30)

(for some reason the rest of my printscreens did not save however I got the one from the first instance here)

Admin Hippie confirmed that even though 6 properties show on the sythesis machine only 4 show on the admin panel.

### What's the difference with what should have happened?

Everytime I have used the sythesis machine in the past It has allowed me to make custom chems with 6 properties with all 6 on the paper.

### How do we reproduce this bug?

1. Click on the systhesis machine to make a chem 
2. Choose 4-6 properties
3. view the result

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Weuyn** [comment]
100% skill issue, don't combine properties that are mutually exclusive. NGN/BCD, CRS/ACR, ATX/TXC, MST/RLX, NRS/PST, etc. etc.

**Comment by private-tristan** [comment]
literally none of those chemicals conflict
https://github.com/cmss13-devs/cmss13/blob/787d5fefe2a43a82a7bc2ceb03847e90f481a268/code/modules/reagents/Chemistry-Generator.dm#L321-L336

I made an issue similar to this one  #4235, but it had to do with research chems combining and deleting properties that had nothing to do with the combination

**Comment by Weuyn** [comment]
Check the very last combination on that list against the properties Seltz tried to put into that chemical. Transformative, Anti-toxic. 

The other one deleting BNM is definitely a bug though. Probably related to MST/BNM/CGN turning into hardening if I had to guess.

**Comment by RikardSeltz** [comment]
TRF heals the brute & burn but deals toxic damage to the user and the Anti Tox was added to counter the negative effect to save dylovene usage. Is it possible in the Code of the game that putting these 2 traits together could cause a confliction not known about to the developers?

**Comment by Lukas-Seltz** [comment]
> Check the very last combination on that list against the properties Seltz tried to put into that chemical. Transformative, Anti-toxic.

Alright, so why was that conflict placed in the code? It does not make any sense why you would not be able to use transformative and Anti tox as the anti tox cancels out the damage done by transformative.

**Comment by Weuyn** [comment]
That's exactly why they are mutually exclusive

**Comment by Lukas-Seltz** [comment]
> That's exactly why they are mutually exclusive, so that TRF is not free healing.

That is really bad logic as many other chems are free healing. Such as god chems where you will never die by your logic that means they should not exist.
