### ISSUE TITLE
Polio part 2, unable to walk as a marine

### ISSUE THREAD

**Issue by Doom-external** [cmss13-devs/cmss13#5387]
### Testmerges

#5298, #5086, #5337, #5280, #5278, #5359, #5228, #5301, #5122

### Round ID

20264

### Description of the bug

Unable to walk around at all, reconnecting didn't work. Admin intervention didn't work either.

### What's the difference with what should have happened?

Should be able to move.

### How do we reproduce this bug?

Reporting this on behalf of someone who doesn't have a github account, they aren't entirely sure how this broke. Steps are the most likely thing they thought it could be.
1. Be sat in dropship chair
2. Get warrior flung while seated while it takes off
3. Success maybe?

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Will close this, since #5420 has more details and is a first hand report
