### ISSUE TITLE
Unable to open containers without picking them up

### ISSUE THREAD

**Issue by Reisyns** [cmss13-devs/cmss13#5411]
### Testmerges

#5086, #5337, #5228, #5007

### Round ID

20322

### Description of the bug

Unable to drag a container like a medkit or a box of pills onto yourself to open the box without then picking up the box as well.

### What's the difference with what should have happened?

You've always been able to open a container without having to take it into your hands but some issue has caused it to now take the container into your hand when you try this.

### How do we reproduce this bug?

1.Find a box of pills or a med kit for example
2.Click and drag that container onto your character
3.Proceeds to open the container whilst also taking said container into your hand.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Weuyn** [comment]
turn off click drag override or swap to help intent if you want to do that ya fuckin goober

**Comment by ItsVyzo** [comment]
Not a bug, check your preferences.
