### ISSUE TITLE
Green headband is not green (unless worn on helmet)

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#5413]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit 2320f59c85 #5337: 'Fixes playing cards' by fira at commit 3b08cf34e4 #5228: 'Reduces the burst multiplier on the M39' by VileBeggar at commit 74a1f99dc9 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 2b8b3d283f

### Description of the bug

Green headbands only show up as green when on helmets:

but when worn on head, standalone... for some reason they show up as tan.

### What's the difference with what should have happened?

Green headbands should be green

### How do we reproduce this bug?

1. Have a green headband
2. Put it in the helmet slots.
3. It is a green headband when you put on thet helmet.
4. Take headband off helmet, take off helmet
5. wear headband on head.
**6. _Headband is tan?_**
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
#7790    Now applies to red headbands.

**Comment by Drulikar** [comment]
This no longer seems to be the case; or is map specific and no round id was provided.
