### ISSUE TITLE
CAS location text for xenos doesn't appear until well after the sound and a fraction of a second before the impact, making it a guessing game that was recently damage buffed

### ISSUE THREAD

**Issue by calvindoyl** [cmss13-devs/cmss13#5419]
### Testmerges

N/A, but there are several unrelated testmerges, 

### Round ID

All

### Description of the bug

As Xeno, we hear the CAS sound of the take off, and there is a LARGE pause between the sound and the text saying A BIRD FLIES SOUTH/EAST/NORTH/WEST - It's literally impossible to plan to avoid it and you largely have to guess at where they're targetting.

Mildly annoying before, but with gauss 1hitting everything now it's very annoying - Please update the warning to an appropriate time to react so that you're punished for not paying attention, instead of being punished by a CAS operator who knows how to offset to backlines

### What's the difference with what should have happened?

Cas should have more than a fraction of a second of warning xeno-side

### How do we reproduce this bug?

1. Be Xeno :)There are some good guides on the forums if you've never done this before ;P
2. Have someone call a cas on your location
3. Gamble and maybe die
4. let your passive-aggressive self loose upon the coworker that buggy-CASsed you to death.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This is not a bug, but intended. Move faster and pay more attention.

**Comment by calvindoyl** [comment]
If you cared enough to actually check, you'll see it's .25 seconds where we get the direction before it actually hits, WELL after the sound starts. It's ltierally not enough time to react. Hearing the sound, even if you move as soon as you hear it, is a guessing game.
But I guess it was perfect as is, which is why there were tons of changes made to it in the last week. Thanks for your input!
