### ISSUE TITLE
Character unable to move/not responding to keyboard movement inputs

### ISSUE THREAD

**Issue by CopperKast** [cmss13-devs/cmss13#5420]
### Testmerges

N/A to my knowlage

### Round ID

20343

### Description of the bug

During evac, I had died to a ravager while reviving another marine, during my mauling I was unable to move and subsequently died. I was revived by another medic on the trip back up to the Almayer where I was unable to move but could equip/unequip and look around directionally with my cursor. I had to be dragged off the alamo and after a moment or two of struggling I pinged an admin who suggested fixes that unfortunately had no effect on my problem. buckling to a folding chair nearby, disconnecting and rejoining, and giving them control of my character to see if it was a client-side issue. eventually I requested the admin delete/cryo my character body so I could sit out the hijack where I found my ghost was able to freely move about unlike my body. I'm not sure if its unrelated or not but I have been experiencing beyond crashes whenever a crate landed at fob for this round. 
_Beyond version 515.1625 stable branch_

### What's the difference with what should have happened?

I would assume expected behavior would be my character moving in response to my keyboard input WASD ect.

### How do we reproduce this bug?

1. die on alamo before takeoff, specifically one tile to the left of the last left inboard row of seats
2.have your revive defib interrupted by the alamo landing then be revived successfully after which.
3.I don't know if its reproduceable but this was pretty much the string of events the "anchored" me
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Birdtalon** [comment]
Possibly the same as #5387

**Comment by CopperKast** [comment]
> Possibly the same as #5387

It looks about the same, although I was attacked by a ravager while buckled instead of a  warrior.

**Comment by ItsVyzo** [comment]
This is most likely related to using BYOND 515, will mark as BYOND Issue for now

**Comment by VileBeggar** [comment]
just happened to me at round 20367. was buckled in during evac and was promptly lunged by a warrior. couldn't move at all and trying to buckle gave me the message "You are unable to do this in your current state." though, this is probably a separate issue in itself
