### ISSUE TITLE
Zoom and supply drops are causing crashes since latest beta BYOND update.

### ISSUE THREAD

**Issue by Cooliecan** [cmss13-devs/cmss13#5423]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit e0ff18f0b9 #5337: 'Fixes playing cards' by fira at commit 3b08cf34e4 #5228: 'Reduces the burst multiplier on the M39' by VileBeggar at commit 74a1f99dc9 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 2b8b3d283f #5407: 'Psychic Whisper Deadchat and Use' by realforest2001 at commit 34108e1b9a

### Round ID

20348

### Description of the bug

Using binoculars or witnessing a supply drop causes the game to crash.

### What's the difference with what should have happened?

Not crash

### How do we reproduce this bug?

1.Run Beta.
2.Use binocs
3.crash game
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This is why we do not recommend playing on BETA/BYOND 515. Simply downgrade.

**Comment by Drulikar** [comment]
What *specifically* is latest beta BYOND? Latest is not helpful at all. It has moved from has changed version numbers 3 times in the last few days due to breaking bugs.

**Comment by Cooliecan** [comment]
515.1626

**Comment by Drulikar** [comment]
Should be fixed once the fix resolving https://www.byond.com/forum/post/2908156 is live.

**Comment by Drulikar** [comment]
Try 515.1627.
