### ISSUE TITLE
Duping Attachments

### ISSUE THREAD

**Issue by Debossans** [cmss13-devs/cmss13#5428]
### Testmerges

irrelevant

### Round ID

20358

### Description of the bug

While changing attachments on the M4RA directly next to the attachment vendor, i clicked with a vertical grip on the gun, exchanging it with a angled grip, then, i went and click dragged the angled grip to the vendor machine, which restocked it but didn't disappear, meaning i could do it forever.

### What's the difference with what should have happened?

The Angled Grip should disappear and not allow for infinite restock.

### How do we reproduce this bug?

1.  Take a gun (the M4RA preferably)
2. Exchange attachments while next to the attachment vendor (preferably the angled grip/vertical grip)
3. Click drag the attachment on the ground into the vendor machine

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
#5408
