### ISSUE TITLE
Broken Sprite for Trijent Van

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#544]
## Description
The wheel sprites for the Trijent Van have bugged out and shown a glitched sprite.

## Difference between expected and actual behavior
Not be glitched.

## Steps to reproduce
I saw it once while Queen's Eye, but I'm not sure how to replicate this issue.

## Issue bingo (not required to be all checked)
- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by PhantomEpicness** [comment]
bad issue

the three most important pieces of information are omitted

- which one
- where
- how ( can be covered with a screenshot)

**Comment by Diegoflores31** [comment]
i am almost 90% sure he means the bug when the overlay and APC directions swap

**Comment by Huffie56** [comment]
@ItsVyzo i think you can safely close this issue:
1-it as almost a year and couldn't be reproduce.
2-i had round this year with the van with no  visual bug even if i bump into stuff.

**Comment by ItsVyzo** [comment]
thanks @Huffie56 
cannot be reproduced
