### ISSUE TITLE
M56Ds inmune to crusher charge

### ISSUE THREAD

**Issue by Bagpepos** [cmss13-devs/cmss13#5477]
### Testmerges

#5086 #5337 #5228 #5007 #5407 #5435 #5397 #5469 #5280 #5464

### Round ID

20433

### Description of the bug

M56D machineguns seem to be inmune to momentum-based charger crusher charges.

### What's the difference with what should have happened?

Used to be able to crush them down with enough momentum just as M2Cs, not anymore.

### How do we reproduce this bug?

1. Be charger
2. Have assembled M56D
3. Charge it max speed
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
I don't think this ever worked. Rather this bug seems exclusive to the M56D when its in its not fully assembled state (as in when it is a `/obj/structure/machinery/m56d_post` instead of a `/obj/structure/machinery/m56d_hmg`
