### ISSUE TITLE
Some poncho icon_states are wrongly autonamed

### ISSUE THREAD

**Issue by Vicacrov** [cmss13-devs/cmss13#5484]
### Testmerges

not affected

### Round ID

20441

### Description of the bug

Four ponchos of the six have wrongly auto-named icon states, thus they show up with the placeholder HONK??? sprite. (this was tested on Kutjevo)

These ponchos are fine:

/obj/item/clothing/accessory/poncho
/obj/item/clothing/accessory/poncho/green

These ones are badly named:

/obj/item/clothing/accessory/poncho/brown
/obj/item/clothing/accessory/poncho/black 
/obj/item/clothing/accessory/poncho/blue
/obj/item/clothing/accessory/poncho/purple

For example, the black poncho has the icon state of `d_u_poncho`. It should be either `d_poncho` or `u_poncho`, it should not inherit both d_ and u_.

![image](https://github.com/cmss13-devs/cmss13/assets/49321394/135b1d38-2539-473b-b3d7-a4c976ade5d7)

Tested it on a local master branch, so it is none of the TMs.

### What's the difference with what should have happened?

The `icon_state` should only inherit `d_` or `u_`, never both, or the icon won't show up.

### How do we reproduce this bug?

1. Spawn in as a synthetic
2. Use the left vendor
3. Vend all the ponchos

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by cuberound** [comment]
map related
