### ISSUE TITLE
Clawless Zombies

### ISSUE THREAD

**Issue by ItsVyzo** [cmss13-devs/cmss13#5485]
### Testmerges

Irrelevant

### Round ID

20441

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/46250991/0e70c098-c56c-4114-b587-5ca02077b827)
Claw-less zombies can interact with weapons etc

### What's the difference with what should have happened?

Zombies should get embedded claws in their hands that cannot be dropped etc and stop them from picking stuff up

### How do we reproduce this bug?

Buckled to any bed and turn into a zombie
Spawn without claws

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by RenaRenaRe** [comment]
This happened to me while I was strapped to a surgery bed, dead, with a nurse working to revive me. Interestingly I had not actually shown up as infected on sensormate yet (with the little infection icon), although maybe that's normal.
Might be a coincidence but I figured it was worth mentioning.

**Comment by ItsVyzo** [comment]
> This happened to me while I was strapped to a surgery bed, dead, with a nurse working to revive me. I revived as a zombie yet did not have any claws so I could pick things up but could not claw/infect people. Interestingly I had not actually shown up as infected on sensormate yet (with the little infection icon), although maybe that's normal. Might be a coincidence but I figured it was worth mentioning.

Tested the above with a bunch of beds and chairs. If it's a bed you turn without claws.
