### ISSUE TITLE
Dropship engine system attach point(s) are unreachable. 

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#5494]
### Testmerges

N/A

### Round ID

20461

### Description of the bug

after the unmerge of #5165 the dropship engine system attach point are unreachable, even if you alt click them, no matter where you are standing.

we are forced to VV them and drag them up like so that they are reachable.
![image](https://github.com/cmss13-devs/cmss13/assets/139605145/8468ed4a-9952-4878-ae53-da9ed54d4ded)

### What's the difference with what should have happened?

dropship engine system attach points should be reachable so that people can attach engine upgrades to them.

### How do we reproduce this bug?

1. Walk over to the dropship engine system attach points
2. alt cick the dropship engine system attach point/try to attach an engine upgrade
3. it isn't there.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Vicacrov** [comment]
It was broken by #5475
