### ISSUE TITLE
WO Gamemode Datum Bug

### ISSUE THREAD

**Issue by ro3ger** [cmss13-devs/cmss13#5502]
### Testmerges

97a3c6e63e0fed3ab2ed2efc1e1eb5c756c4763d

### Round ID

20476

### Description of the bug

Go check logs on raw-logs for round 20476
You can find a extensive list of Datum's failing to load

### What's the difference with what should have happened?

WO should work and datums should load
WO broken Datums not loading

### How do we reproduce this bug?

1. Load WO
2.Look at logs
3. So many failures
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Errors reported are just hard deletes. See https://github.com/cmss13-devs/cmss13/pull/5506 for any other game mode start related problems I am tweaking.
