### ISSUE TITLE
Alamo's Aft Door cannot be unlocked.

### ISSUE THREAD

**Issue by Contrabang** [cmss13-devs/cmss13#5503]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit 1a300eff40 #5337: 'Fixes playing cards' by fira at commit 3b08cf34e4 #5228: 'Reduces the burst multiplier on the M39' by VileBeggar at commit 74a1f99dc9 #5397: 'A slurry of Bigred changes' by spartanbobby at commit 57f6fc3951 #5402: 'Databasing whitelists' by realforest2001 at commit cd12902fef #5495: 'Fixes wrong dropship attachment planes' by Vicacrov at commit 097381e88c #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 2b8b3d283f #5165: 'Ports Mapping Backend updates' by fira at commit 1fb4bea8ca

### Round ID

20476

### Description of the bug

Alamo's back door starts locked, and cannot be unlocked using the "Unlock Aft" button on the control console. (DOOR STUCK)

### What's the difference with what should have happened?

Door opens when you push the button

### How do we reproduce this bug?

1. Be pilot trained
2. Try to open the back door
3. It doesn't work
4. Marines yell at you for the rest of the round

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
We're aware of this. It is caused by #5165

**Comment by Contrabang** [comment]
Was fixed in the test merge
