### ISSUE TITLE
Some areas in Solaris ridge have mapper text

### ISSUE THREAD

**Issue by Onetoughcreampuff** [cmss13-devs/cmss13#5504]
### Testmerges

Mapping TMs: #5165, #5397

### Round ID

20480

### Description of the bug

At engineering comms tower and filt security checkpoint, the mapping text 'ASS. LINE' and 'SECURITY' appeared respectively. Second image stolen from Yakup Karaca on the discord.
![image](https://github.com/cmss13-devs/cmss13/assets/84825853/fc465552-3041-49b1-b38e-7fb3fb7d6333)
![image](https://github.com/cmss13-devs/cmss13/assets/84825853/63e9f1d7-84b8-43be-a28d-6d43514becc4)

### What's the difference with what should have happened?

I should not see mapper text in a live round.

### How do we reproduce this bug?

1. Be on big red
2. Go to engineering comms tower or filt checkpoint
3. See immersion breaking mapper text

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by spartanbobby** [comment]
https://i.imgur.com/wbAmQs0.png

https://i.imgur.com/OH6r746.png

Unable to reproduce on my bigred changes local

**Comment by SabreML** [comment]
This is a really weird bug. The very first thing areas do when they're spawned in is nullify their `icon` variable to remove the mapping text:
https://github.com/cmss13-devs/cmss13/blob/cb1d6124d00f6731b9cad36c2f7205342dcb6f20/code/game/area/areas.dm#L96-L108
So in order for the text to be visible, it must have either skipped calling `Initialize()` (which afaik shouldn't be possible), or something somewhere set its icon var back to its initial state.

**Comment by ItsVyzo** [comment]
We're aware of this. It is caused by #5165

**Comment by ItsVyzo** [comment]
This could also be a conflict as a result of #5165 and #5397 being merged at the same time

**Comment by Huffie56** [comment]
should be fixed?

**Comment by Drulikar** [comment]
I believe this is fixed in #5165
