### ISSUE TITLE
Synth comms: IO merge effecting Tactical comms?

### ISSUE THREAD

**Issue by TheeBiggest** [cmss13-devs/cmss13#551]
## Testmerges:

Unsure if the IO merge is effecting Synth comms but I have played other roles with Tactical comms working but using the Synth role, it just doesn't exist.

## Description
Synth comms headset doesn't have working tactical comms.

I think I did this bug report right, I never used github to report bugs until now
![Synth comms](https://user-images.githubusercontent.com/108038953/175188722-97d45617-3b61-4ec0-90b1-fbe989db91e8.png)

**Comment by tempelers** [comment]
It's also missing the Intel channel if the screenshot is correct.

**Comment by stanalbatross** [comment]
Yes this is the IO TM
