### ISSUE TITLE
Ice Architectural oversight Nightmare

### ISSUE THREAD

**Issue by sargashC** [cmss13-devs/cmss13#5511]
### Testmerges

I don't think any affect map spawn

### Round ID

20494

### Description of the bug

Architectural Oversight has a doorway that leads to a prefab wall. I assume this is either supposed to be a maint exit to the outside just to the west, or is meant to be removed. It would be a good flank IMO if it was built correctly.
![image](https://github.com/cmss13-devs/cmss13/assets/52183648/4d8f4b5b-f9fe-4bab-b494-50c4813428c7)

### What's the difference with what should have happened?

The door shouldn't be here, or it should be a maint tunnel that goes a few tiles west. Not sure, but a door going no where isn't what it should be.

### How do we reproduce this bug?

1.Play Ice
2.I think it's a nightmare round
3.Look at Archi oversight.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by private-tristan** [comment]
no this is intended. it's a little joke. the door itself is (as you said) named "Architectural oversight" while its' description is "Huh, it doesn't seem to go anywhere."
![image](https://github.com/cmss13-devs/cmss13/assets/54422837/1b62428f-1b94-47ee-94f0-fe7dc2a58c06)
