### ISSUE TITLE
Hijack dropship can land on reactors, making self distruct difficult.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#5523]
### Testmerges

N/A

### Round ID

20517

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/139605145/d86e91ab-0c61-4eb0-8b7f-09ddbacb1aa5)
As you can see half the reactors are gone due to where the dropship lands when crashing lower aft.

### What's the difference with what should have happened?

Maybe let's not have the hijack dropship land on half the reactors, unless this is intended.

### How do we reproduce this bug?

1. Hijack the dropship and crash it lower aft.
2. Half the reactors are now gone.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
don't look like a bug to me.
if CIC want to guaranty possibility to SD they should set AA on it.
feel free to make a post on the forum if you want it to be change.
