### ISSUE TITLE
Bad Shivas Survivor

### ISSUE THREAD

**Issue by Staykeu** [cmss13-devs/cmss13#5530]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit 1a300eff40 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 9ef47f593f #5493: 'React Migration - part 2' by mullenpaul at commit 707f3585f6 #5392: 'Yautja Weapon Gimmicks, Round Two' by realforest2001 at commit bcd8b2b63d #5490: 'Requisition Centralization [Part 1]' by ItsVyzo at commit f75675449d #5525: 'Fix Weird Inventories' by Drulikar at commit 4787757a5f #5515: 'Nerfs GAU damage by one fifth.' by Birdtalon at commit 3586ae2981

### Round ID

20532

### Description of the bug

During a survivor round on Shiva's Snowball, I spawned in as a pre-starving survivor with a botanist's apron instead of an insulating jacket. Due to this I was left behind and eventually captured. Before I was captured, I was taking damage from the weather and became extremely slow from both the weather damage and lack of nutrition.

### What's the difference with what should have happened?

I believe survivors are supposed to spawn with full nutrition, and spawn with insulating wear on snow maps.

### How do we reproduce this bug?

Roll survivor on Shiva's Snowball under the "Any" survivor preference before the round starts.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by private-tristan** [comment]
This bug appears to only occur with civilian type survivors, as all others have cold/map specific versions.

 shivas has "/datum/equipment_preset/survivor/civilian" as a survivor type, but if there's a cold map it should be forcing civilian survs to spawn with snowgear https://github.com/cmss13-devs/cmss13/blob/1bf868cd279c08ae473a18b9442e99b0d8f97815/code/modules/gear_presets/survivors/misc.dm#L92-L93

https://github.com/cmss13-devs/cmss13/blob/1bf868cd279c08ae473a18b9442e99b0d8f97815/code/modules/gear_presets/_select_equipment.dm#L683-L691

![image](https://github.com/cmss13-devs/cmss13/assets/54422837/a8135658-e021-4727-ad89-3d303c84bbcb)
