### ISSUE TITLE
you cant place eggs under broken lights

### ISSUE THREAD

**Issue by InsaneRed** [cmss13-devs/cmss13#5540]
### Testmerges

isnt required

### Round ID

isnt required

### Description of the bug

you cant put eggs under broken light fixtures

### What's the difference with what should have happened?

you can put eggs under broken light fixtures

### How do we reproduce this bug?

1.carrier
2.egg
3.under light fixture
4. cant place it 
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by SabreML** [comment]
Same as #5362
