### ISSUE TITLE
Marked AHelps do not react to 3rd party responses. 

### ISSUE THREAD

**Issue by blackdragonTOW** [cmss13-devs/cmss13#5547]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit 1a300eff40 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 9ef47f593f #5392: 'Yautja Weapon Gimmicks, Round Two' by realforest2001 at commit bcd8b2b63d #5490: 'Requisition Centralization [Part 1]' by ItsVyzo at commit 87a1febaa3 #5525: 'Fix Weird Inventories' by Drulikar at commit 4787757a5f #5515: 'Nerfs GAU damage by one fifth.' by Birdtalon at commit 3586ae2981

### Description of the bug

If staff marks an AHelp, it is marked as being responded on the ticket, but does not tell others of that if they try to respond.

### What's the difference with what should have happened?

Presently, if Admin 1 Replies to a ticket and Admin 2 clicks "Reply", Admin 2 will get a sound and a notification that Admin 1 is in the process of Replying. 

With Marking, none of those safe guards are there.  If Admin 1 Marks a ticket, Admin 2 can click on reply without knowing that it's Marked.  In the inverse, if Admin 1 Replies to a ticket, Admin 2 can Mark it without knowing that it's being Replied to.

### How do we reproduce this bug?

1. Generate an AHelp ticket
2. Mark the ticket with person 1
3. Click reply with person 2
4. ---> There is no feedback that this is already being handled
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Same applies for Auto response/Reject etc
