### ISSUE TITLE
Scale Transform wont accept decimals.

### ISSUE THREAD

**Issue by blackdragonTOW** [cmss13-devs/cmss13#5549]
### Testmerges

#5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit 1a300eff40 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit 9ef47f593f #5392: 'Yautja Weapon Gimmicks, Round Two' by realforest2001 at commit bcd8b2b63d #5490: 'Requisition Centralization [Part 1]' by ItsVyzo at commit 87a1febaa3 #5525: 'Fix Weird Inventories' by Drulikar at commit 4787757a5f #5515: 'Nerfs GAU damage by one fifth.' by Birdtalon at commit 3586ae2981

### Description of the bug

When modifying the scale of a sprite, you cannot input a decimal.  

In practical terms this means you can never scale a sprite back down.

### What's the difference with what should have happened?

You should be able to enter a decimal number to scale back down a sprite.

### How do we reproduce this bug?

1. Right click any object, VV
2. Modify Transform
3. Scale
4. Attempt to use 0.5
5. ---> The decimal will not place.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Likely fixed by https://github.com/cmss13-devs/cmss13/pull/5651

**Comment by ItsVyzo** [comment]
This has been fixed.
