### ISSUE TITLE
Unable to use the Alamo's Lockdown via Button.

### ISSUE THREAD

**Issue by tempelers** [cmss13-devs/cmss13#555]
## Testmerges:

N/A

## Description
You can't deactivate the lockdown on the Alamo by pressing the button inside the main area. Deactivating lockdown through the console still works perfectly fine.

## Difference between expected and actual behavior
It should have the same effect as the console's lockdown, but it doesn't turn off.

## Steps to reproduce
1. Be a PO or any role that can activate the button
2. Press the button

## Issue bingo
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Maciekkub** [comment]
Looks intended, I assume the button does its function, it locks down the Dropship. 
![image](https://user-images.githubusercontent.com/30427887/179418027-818f34bf-5927-4082-88ff-b29a4666b3f0.png)
