### ISSUE TITLE
Binocs/Las Desig and explosion bug

### ISSUE THREAD

**Issue by LaundryLieu** [cmss13-devs/cmss13#5550]
### Testmerges

#5086, #5007, #5392, #5490, #5525, #5515

### Round ID

20551

### Description of the bug

I was zooming north with a las desig, then I got blown up which either flung the las designator or destroyed it, which made me locked on the zoom-in for some reason.

### What's the difference with what should have happened?

Knocking off the las designator with the explosion off my hand should've toggled me out of the zoom rather than make me stuck on it.

### How do we reproduce this bug?

1. Look through las desig/binocs
2. Get blown up
3. Cry as you can't zoom out because you either can't find your laser designator or it's gone
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Vicacrov** [comment]
Tried it with both as a human (b18 armor) and as a synthetic, it properly resets for me. I threw a HEDP behind me while looking north with binocs. Was there anything different in your case than what is on the video? I cannot reproduce this zoom-is-stuck issue.

https://github.com/cmss13-devs/cmss13/assets/49321394/74269db4-ebde-4e56-81f2-1586961b97e8

**Comment by SabreML** [comment]
Sounds like the same bug as #3405.
I've also tried reproducing it myself before, but I didn't managed to find anything. (Although obviously it can happen *somehow*)

**Comment by Vicacrov** [comment]
based on #5564 it looks like the binocs need to be deleted for this bug to occur?

**Comment by ItsVyzo** [comment]
Duplicate #1884
