### ISSUE TITLE
STUI fails to clear text buffer as of React PT2 PR

### ISSUE THREAD

**Issue by Drulikar** [cmss13-devs/cmss13#5557]
### Testmerges

N/A

### Round ID

N/A Tested locally

### Description of the bug

As of commit d5dfe13 from #5493 the STUI window does not clear its text buffer when changing font size or changing tabs now.

New behavior:
![funky](https://github.com/cmss13-devs/cmss13/assets/76988376/d88802fa-2667-48b1-84ad-0648ff5e9edd)

### What's the difference with what should have happened?

Expected behavior (using commit 37d8e71 ):
![expected](https://github.com/cmss13-devs/cmss13/assets/76988376/0933ab67-d9d4-4201-b99a-8359fb591940)

### How do we reproduce this bug?

1. Checkout master
2. Launch & Start Game
3. Open STUI
4. Swap tabs off of attack tab: Some attack logs are sticky.
5. Optionally change font size: Same sticky attack logs ignore font change.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by mullenpaul** [comment]
Thanks for the issue - will look at soon
