### ISSUE TITLE
BigRed is missing some landmarks for nightmare inserts

### ISSUE THREAD

**Issue by Drulikar** [cmss13-devs/cmss13#5558]
### Testmerges

#5086 at 1a300ef, #5392 at bcd8b2b, #5452 at 830526a, #5536 at 9368476, #5526 at c2a1fce, #5506 at 745cc5b

### Round ID

20572

### Description of the bug

Some landmarks, maybe more than just these, are missing/named incorrectly for nightmare inserts/sprinkles in the Solaris Ridge map.

```
DEBUG: Nightmare Mapload: Could not find landmark: vault
DEBUG: Nightmare Mapload: Could not find landmark: containerroom
```

### What's the difference with what should have happened?

All nightmares should be able to be loaded if they are intended to exist (otherwise delete them)

### How do we reproduce this bug?

1. Optionally increase the probability nightmare sprinkle of `25.containerroom_xenos.dmm` to `100.containerroom_xenos.dmm` and `25.vault_v2.dmm` to `100.vault_v2.dmm`
2. Launch game on Solaris Ridge / Big Red
3. Note debug messages when round starts as nightmares load

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
seem like _ is causing issue... i don't know why so just going to change the name of the insert and see if it work like that...

**Comment by Huffie56** [comment]
changing the name doesn't work... no idea why it's not working...
while checking it i found this insert cave-north_lambdapath that didn't have an insert on the map and did show up on debug the same way as the other two

**Comment by Huffie56** [comment]
could it be because of that PR https://github.com/cmss13-devs/cmss13/pull/1371
didn't check yet
