### ISSUE TITLE
Getting stuck in bino vision

### ISSUE THREAD

**Issue by MemesLauncher** [cmss13-devs/cmss13#5564]
### Testmerges

#5086 / #5392 / #5452 / #5526 / #5506 / #5519

### Description of the bug

Getting stuck in the bino vision when the item is destroyed during use toward the direction you were looking at when using said bino. Moving or finding a new bino to "scope unscope" doesn't fix it but worsen it to getting you a "runner extended vision range".

### What's the difference with what should have happened?

Should not be getting stuck in bino vision range, in particular when the item used to do so is gone and you can now be on the move.

### How do we reproduce this bug?

1.Get a binocular/laser designator / Range finder  (Might also be possible with other forms of vision extension, such as scoped guns with a 2x/4x scope.)
2.Look toward a direction
3.Have it destroyed when looking through it (It happened through explosions on my side, be it from CAS, mortar or C4s. I assume it would be the same with a bino that is being melted).
4. Get stuck with bino vision in that direction. Unable to see whatever's in your other direction.
5. Worsen it by finding another bino/gun with scope, looking through it, seeing nothing changes, unscoping and now having a "runner extended sight range" as your normal vision range.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Vicacrov** [comment]
sounds like #5550

**Comment by ItsVyzo** [comment]
Duplicate #1884
