### ISSUE TITLE
Bypass Explosive IFF

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#5568]
### Testmerges

5f460fb94b20c4e08a46e96c4176892ed01ffaeb

### Round ID

20584

### Description of the bug

Throwing a grenade via ladder bypasses its IFF lock

EDIT: I have no idea why it let me throw it- several attempts afterward and it won't let me

### What's the difference with what should have happened?

Should not ignite

### How do we reproduce this bug?

1. Throw nade down ladder on accident
2. Oh SNAP what??
3. Chase it grab it
4. Run around in a panick open an admin ticket to apologize try to run off to maint so you don't kill someone in medbay
5. Burn to death

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

Addendum: Tried to replicate this several times afterwards and just could not. Here's video proof though:

https://youtu.be/A3iHO8LsBns

**Comment by VileBeggar** [comment]
isn't it red alert in that video? the signs are flashing red n' armories are open. red alert disables the safety check for explosives

**Comment by nuklearcellphoneg** [comment]
Red alert may have caused it- I always assumed only the DS crashing unlocked the IFF

**Comment by AnuvKH** [comment]
Red alert will allow for any explosives to be used, up to or after a hijack crash.
