### ISSUE TITLE
TGUI dev server tools don't seem to be working

### ISSUE THREAD

**Issue by SabreML** [cmss13-devs/cmss13#5575]
### Testmerges

N/A

### Round ID

N/A

### Description of the bug

The TGUI dev server 'Kitchen Sink' and 'Layout Debugger' tools (see [Dev Server Tools)](https://github.com/cmss13-devs/cmss13/blob/master/tgui/README.md#dev-server-tools) aren't working after #5493.
(They work fine on the previous commit 37d8e7147d933a1f3e68072b0d7414e2eb1a15d0, but not after.)

I've tried looking into this myself, and the most I've been able to confirm is that the `debug` variable is `null` when it reaches this part of `Window` code even after spamming F11 and F12 a bunch, when presumably it shouldn't be:
https://github.com/cmss13-devs/cmss13/blob/fcae67e73b158895fadb0bec5725a3d1bf455844/tgui/packages/tgui/layouts/Window.tsx#L77-L80

### What's the difference with what should have happened?

F11 should draw boundary boxes around each part of the UI, and F12 should switch to a different UI with demos of some of the different components.

### How do we reproduce this bug?

1. Start the game.
2. Start the TGUI dev server through your preferred method. (FWIW I use `yarn tgui:dev`)
3. Open a TGUI window. (A green bug icon should show at the top right)
4. Press F11 or F12 with the window selected.
5. ...?

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by mullenpaul** [comment]
I can look into this tomorrow

**Comment by mullenpaul** [comment]
I have spent some time looking into this - it looks as though the state change from debugReducer is not propagating through the application state. I'm still looking into this

**Comment by Drulikar** [comment]
Resolved in https://github.com/cmss13-devs/cmss13/pull/6244 though of note currently running `tgui-dev.cmd` doesn't auto refresh windows (it was doing so at the time of that PR - you must F5 the window or close/reopen currently)
