### ISSUE TITLE
Fire Controll on CAS shows wrong ammo usage

### ISSUE THREAD

**Issue by Oyu07** [cmss13-devs/cmss13#5578]
### Testmerges

#5086, #5392, #5452, #5526, #5506, #5519, #5007

### Description of the bug

Ammo used per run is incorrect, and goes up as you do less steps rather than going down

### What's the difference with what should have happened?

It straight up shows the wrong ammo used

### How do we reproduce this bug?

1. Use the fire control
2. Use GAU-21
3. Change steps and observe numbers

Same goes for others, like mini rocket pod will say 10 rockets per run

![TdKaIR6k1r](https://github.com/cmss13-devs/cmss13/assets/66401072/9face7f8-5da3-42c6-9355-f2269083070d)

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by mullenpaul** [comment]
Thank you for reporting this issue. I have raised a PR to fix this.
