### ISSUE TITLE
Chair Teleporting

### ISSUE THREAD

**Issue by Biolock1** [cmss13-devs/cmss13#5604]
### Testmerges

#5086, 5392, 5519, 5007

### Round ID

20656

### Description of the bug

When you grab someone and click on a chair that is adjacent to you but more than 1 tile away from the person you grabbed, they will teleport to that location.

### What's the difference with what should have happened?

Nothing should happen.

### How do we reproduce this bug?

1. Grab someone
2. Click on a chair not directly adjacent to the person grabbed, and with that grab in your active hand
3. Watch them teleport

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by HaultyAnonie** [comment]
This is like putting someone in a body-scanner.

**Comment by vero5123** [comment]
fixing this would be a shadow nerf.
