### ISSUE TITLE
Lesser Drones can no longer flip tables

### ISSUE THREAD

**Issue by Madventurer** [cmss13-devs/cmss13#5606]
### Testmerges

N/A

### Description of the bug

https://github.com/cmss13-devs/cmss13/pull/5580
Changed the check to see if mobs can flip tables for facehuggers, but the check also includes lesser drones:
Lesser drones have the following line in their code: mob_size = MOB_SIZE_XENO_VERY_SMALL
The linked PR clearly excludes facehuggers and lessers from being able to flip tables, which conflicts with the stated purpose of the PR.

### What's the difference with what should have happened?

Lessers are not mentioned in the PR and should still be able to flip tables. They cannot.

### How do we reproduce this bug?

1. Spawn as lesser drone
2. Attempt to flip table
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by SabreML** [comment]
Heck, yeah that's my fault. I'll get a fix up in a bit.
