### ISSUE TITLE
tgui_input_number with {min,max}_value will not allow you to enter a number inbetween

### ISSUE THREAD

**Issue by harryob** [cmss13-devs/cmss13#5610]
### Testmerges

N/A

### Round ID

N/A

### Description of the bug

tgui_input_number will always take the greatest number when a max_value is provided. you can copy paste values into the field to bypass this, but it can't be entered directly

![CleanShot 2024-01-31 at 13 00 47](https://github.com/cmss13-devs/cmss13/assets/55142896/5bf43485-770b-4ec9-a16d-796918955900)

### What's the difference with what should have happened?

permitted to enter a number between the min_value and max_value

### How do we reproduce this bug?

1. use a tgui_input_number with restricted values, such as the age field on character setup
2. attempt to enter a number
3. you will now be 90

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Copy/pasting is a "temporary" fix
