### ISSUE TITLE
Air Supply Pipes, sprite discoloured/invisible

### ISSUE THREAD

**Issue by MistChristmas** [cmss13-devs/cmss13#5617]
### Testmerges

#5086, #5392, #5007

### Round ID

20667

### Description of the bug

The Air supply pipes. Atleast those on the Alaymer. But I presume all of them are grey when they are wrenched in place. Instead of their usual blue. If they are wrenched and then wrenched back in. They turn invisible. 

I would assume this potentially affects other pipes. But Air Supply pipes are by far the most common to observe this effect on.

EDIT: Uh they also turn into bent pipes for some reason. Presume this is a symptom of why they turn invisible when wrenched back in
### What's the difference with what should have happened?

They should be blue when you look at them, and not invisible when you unwrench and wrench them back in.

### How do we reproduce this bug?

1. Observe/ Spawn as marine
2. Find nearest pipe
3. Wonder if you're colourblind
4. Decide 'no, it must be server', I was already colourblind before they turned grey.
5. Then unwrench and wrench it back in
6. Notice it has now gotten worse as it's invisible
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MistChristmas** [comment]
Aaaaaa I forgot picture.
![New Bitmap image (2)](https://github.com/cmss13-devs/cmss13/assets/7815982/7896083d-2f9f-4a51-9c96-0404223fe30a)

**Comment by MistChristmas** [comment]
Probably something to do with this #5553

**Comment by Huffie56** [comment]
if nobody is doing a fix i will work on one in an hour.

**Comment by MistChristmas** [comment]
![New Bitmap image (3)](https://github.com/cmss13-devs/cmss13/assets/7815982/7d8e35c2-8f56-4e30-9883-05d42c911677)
For some reason pipes turn into bent pipes after you unwrench them. Despite not originating from a bent pipe... I don't think the colours did that.

**Comment by Huffie56** [comment]
seeing that i am revert my PR should fix it letting it open in case the bend pipe stay...
https://github.com/cmss13-devs/cmss13/pull/5626

**Comment by MistChristmas** [comment]
> i can see you have cable in your belt why is it white?

White is just one of the colours cable coil can be? I'm pretty sure it's just the colour it got giving, and not all cable coils are white... Though I don't play engi alot.

**Comment by Drulikar** [comment]
Resolved via https://github.com/cmss13-devs/cmss13/pull/5626

Any other issues like the unwrenching being the wrong state make that a separate issue if it still can occur.
