### ISSUE TITLE
New Liaison Jackets Sprite Error

### ISSUE THREAD

**Issue by danma76** [cmss13-devs/cmss13#5618]
### Testmerges

#5086, #5392, #5007

### Description of the bug

Every newly added suit jacket, bomber jacket, and vest, has appeared as a missing sprite in the game. Basically all the jacket sprites added by #5437 

### What's the difference with what should have happened?

There should have been sprites there instead of big 'hjonks'.

### How do we reproduce this bug?

1. Spawn in as a Corporate Liaison
2. Enter the CL Quarters
3. Jacket sprites not present
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Rubenbl4des** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/134560760/7c22c156-c09c-4ec0-aced-4d74bc141e30)

**Comment by Rubenbl4des** [comment]
And to be specific, the ones that show up as HJONK are: grey vest, khaki bomber jacket, tan vest, grey bomber jacket, khaki suit jacket, brown suit jacket, brown vest, red bomber jacket, formal suit jacket, blue suit jacket, and black suit jacket.
