### ISSUE TITLE
Pipes go invisible, change sprites, and don't connect properly.

### ISSUE THREAD

**Issue by MistChristmas** [cmss13-devs/cmss13#5661]
### Testmerges

#5007,  #5392, #5552, #5628, #5660

### Round ID

20723

### Description of the bug

This issue is low impact and probably gone un-observed for multiple months;

Wrench up a pipe and for some reason it thinks it's bent....
![New Bitmap image (4)](https://github.com/cmss13-devs/cmss13/assets/7815982/bb1eb551-e6d6-496c-9a84-b42609f6ddd7)

Throw the pipe. And it'll magically change it's sprite. Pick it up and put it back down, and it's a straight pipe or whatever again.
![New Bitmap image (5)](https://github.com/cmss13-devs/cmss13/assets/7815982/ed96f157-d4e8-4baf-8f8f-d77df1ef2907)

Wrench it down and it will be invisible... Tested on the server, and when tested locally noticed the pipe didn't connect to any of the other pipes that I didn't mess with.
![New Bitmap image (3)](https://github.com/cmss13-devs/cmss13/assets/7815982/bf2c9177-241b-4710-a4be-65df340d912a)

### What's the difference with what should have happened?

The pipe shouldn't shapeshift? Into a different kind of pipe
The pipe shouldn't shapeshift from the wrong sprite to the correct one.
The pipe shouldn't be invisible whilst re-wrenched down.

### How do we reproduce this bug?

1. Wrench up a pipe. Examine it says it's bent.
2. Pick up and throw the pipe. Observe it change sprites.
3. Pick up and put down the pipe. Observe it has reverted to original sprite
4. Wrench the pipe back in place. Observe you can't observe it, unless you right click the tile.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Blundir** [comment]
Fixed in https://github.com/cmss13-devs/cmss13/pull/7659
