### ISSUE TITLE
Armor Light Not Turning Off

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#5672]
### Testmerges

#5007, #5392, #5552, #5628, #5669

### Round ID

20751

### Description of the bug

Armor light, when removed manually, is not turning off and can not be slashed off by xenos in the same way they can slash flashlights or guns with rail lights turned on. Curiously, the armor light still maintains the directionallity of the person when they removed said armor. 

Armor light turned on while armor is on the ground:
![image](https://github.com/cmss13-devs/cmss13/assets/105765670/02f00d4c-044a-45e6-9f0c-a626f8bb6610)

Me slashing at the armor to no success: 
![image](https://github.com/cmss13-devs/cmss13/assets/105765670/2e5e7553-036f-4ab5-9f05-c3b516f49d6a)

### What's the difference with what should have happened?

Armor light should not be usable as a permanent, non-slashable light source. It also looks really weird being directional while it exists as a sprite on the ground.

### How do we reproduce this bug?

1. Wear armor with a light on it.
2. Activate armor light.
3. Remove armor without turning the light off manually.
4. Pitch armor with light somewhere visible.
5. Profit off the inexhaustible light source.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
saw it once not sure how it's reproduce...
