### ISSUE TITLE
Tutorial rooms spawn right next to each other

### ISSUE THREAD

**Issue by Vicacrov** [cmss13-devs/cmss13#5700]
### Testmerges

#5007 #5392 #5552 #5628

### Round ID

20829

### Description of the bug

There were three tutorials running: basic xeno tutorial, basic marine tutorial, and the basic self-healing tutorial (I forgor their proper names).

The basic marine tutorial with the gun usage was running west of this xeno tutorial. After the room despawned, the wall between the two tutorials also despawned, letting the drone go into spess exploration.

![image](https://github.com/cmss13-devs/cmss13/assets/49321394/53c84588-ef0c-46f9-99aa-c3340bca23b4)

### What's the difference with what should have happened?

There should be one space tile between tutorial rooms.

### How do we reproduce this bug?

1. Start multiple tutorials (with different room sizes?)
2. Observe RNG doing bad things

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment]
Likely a bug w/ turf reservations, no tutorial expands beyond its allocated size

**Comment by SabreML** [comment]
I think I saw someone say that #5165 would fix this issue, although it's gone stale.

**Comment by Huffie56** [comment]
is the PR above fixed it?

**Comment by SabreML** [comment]
> is the PR above fixed it?

Yep, looks like it's fixed now.

**Comment by Zonespace27** [comment]
Resolved by https://github.com/cmss13-devs/cmss13/pull/5165
