### ISSUE TITLE
Long eyesight

### ISSUE THREAD

**Issue by ekcja1** [cmss13-devs/cmss13#5707]
### Testmerges

#5007,#5392,#5552,#5628,#5542,#5584

### Description of the bug

I can see further than usual for no reason at all.

https://github.com/cmss13-devs/cmss13/assets/159834285/3ab7faf7-0a78-46a7-8d19-1ece6a977b2b

### What's the difference with what should have happened?

My eyesight should have been half of what it was.

### How do we reproduce this bug?

It happened to me when I had high ping, like in hundreds to thousands of ms. I activated the B8 scope on my M4RA rifle increasing my eyesight range, but when I moved around and stopped looking through the scope, the eyesight instead of going back to normal actually increased so that I could see further away not just in one direction but in all of them. 

### Issue Bingo

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Duplicate #266
