### ISSUE TITLE
C4 not able to be placed on Alamo during hijack

### ISSUE THREAD

**Issue by s5nt** [cmss13-devs/cmss13#5727]
### Testmerges

#5007, #5392, #5584, #3633, #5401

### Round ID

20908

### Description of the bug

While the Alamo is heading towards the Almayer during hijack, explosive safety that prevents griefers from blowing up brief or something is active on the Alamo, which prevents explosives from being placed, and notably, C4s on ovi queens.
![image](https://github.com/cmss13-devs/cmss13/assets/99336728/530e2a62-c7d7-472d-b8cc-77f1c6fc2431)

### What's the difference with what should have happened?

C4 should have been allowed to have been placed, as the explosive safety shouldn't block things that aren't griefing.

### How do we reproduce this bug?

1. Cause hijack
2. Attempt to place C4 on hijacked DS
3. Woo hoo
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by private-tristan** [comment]
this is because the antigrief isonly disabled once the alamo lands (or CIC red alerts), and not when hijack occurs.

**Comment by ItsVyzo** [comment]
Not a bug / Explosive antigrief has been turned of as of late. Also "Explosive antigrief" is an AI, it blanket stops explosives in specific areas regardless of the player's intent as it CANNOT READ the player's intent.
