### ISSUE TITLE
Family photo doesn't show your own family

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#5730]
### Testmerges

#5007
#5392
#5584 
#3633 
#5401

### Description of the bug

A week or so ago something was changed about the family photo you can buy in the character editor.

Before, the family photo would say something like, "A photo of your family" when examined
Now it says, A photo of a family you do not know.

Probably this should say something like:
A photo of John Marine's family (when examined by someone else)
A photo of your family (when examined by the player who bought the family photo in character creator)

### What's the difference with what should have happened?

Before, the family photo would say something like, "A photo of your family" when examined
Now it says, A photo of a family you do not know.

### How do we reproduce this bug?

1. Buy family photo in character editor
2. Spawn
3. Examine photo

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Could not reproduce. Can you confirm that it still happens?
![image](https://github.com/cmss13-devs/cmss13/assets/4447185/a47a5554-065f-48f9-894c-0f05dc6e5c66)

**Comment by ItsVyzo** [comment]
Could not reproduce / no more issues/reports about this
