### ISSUE TITLE
ARC Door Issues

### ISSUE THREAD

**Issue by GamerRed13** [cmss13-devs/cmss13#5732]
### Testmerges

#5007,#5392,#5584,#3633,#5401

### Round ID

20913

### Description of the bug

- Xenos can enter the Vehicle when the doors are locked

- Doors sometimes invert on which inside door leads to which outside door (E.g. Blue door making the sprite exit out of the red door)

### What's the difference with what should have happened?

In past iterations of the APC, Tank, or Vehicles Etc, when locked the vehicle would prevent all factions from entering the vehicle apart from the drivers. This would prevent xenos from entering the vehicle if the doors are locked, and providing them the ability to only enter when the vehicle was disabled or destroyed. 

The entrances inside and out should correspond with their colour (Red door should lead to red exit) 

### How do we reproduce this bug?

Lock Issue
1. Lock the ARC
2. Try to enter the ARC as a xenomorph of a hostile faction.
3. Enter into the locked ARC.

Color Issue
1. Try Rotating the ARC and leaving
2. On certain rotations the ARC doors invert 

### Issue Bingo

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
For the "lock issue" I'm almost certain it just extended the time for a xeno to get in but I could be misremembering.

The rotating issue (unless consistent) has been an issue forever with CM vehicles.

Probably both of these are unrelated to the ARC specifically.

**Comment by Zonespace27** [comment]
> Xenos can enter the Vehicle when the doors are locked

Not a bug; as morrow said, both are unrelated to the ARC
