### ISSUE TITLE
ASRS Doesn't Have DMR Sentry Ammo

### ISSUE THREAD

**Issue by imapokemonmasta** [cmss13-devs/cmss13#5745]
### Testmerges

3d4ac1cd7dd720111be0174631e6bdbcd5b81b79

### Description of the bug

The ASRS system for REQ has sentry ammo (in the ammo tab) for Flamer, Shotgun and regular Sentry. You cannot currently buy DMR ammo for it. Regular sentry ammo doesn't work for DMR turrets. 

### What's the difference with what should have happened?

Should have DMR ammo in ASRS or the turrets should take regular ammo. 

### How do we reproduce this bug?

1.Use ASRS
2. View Ammo Tab
3. See lack of DMR ammo

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
same goes for m2c

**Comment by Vicacrov** [comment]
Just tested, the DMR sentry can take normal sentry ammo. It can, however, only take ammo when it is completely empty and if you lack the necessary engineering skill to do it, it will just silently fail. (That could use a message, really.)

This makes this a non-issue, but it made me realise that two flamer sentry types did lack orderable ammo.
