### ISSUE TITLE
Admin 'Medals-Panel' broken.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#5768]
### Testmerges

N/A

### Round ID

20976

### Description of the bug

> occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
>  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>    at Ts (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:116883)
>    at g (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:60966)
>    at jl (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:72975)
>    at kc (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:121892)
>    at vs (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:109311)
>    at xs (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:109245)
>    at ps (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:109108)
>    at ls (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:106225)
>    at Wi (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:46865)
>    at ts (http://cdn.cm-ss13.com/live/ed/asset.ed1547734b51361ecc42b8d86f8efd62.js:1:103309)
> User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
> State: {"ckey":"smellyhippie","interface":"MedalsPanel","window":{"key":"[0x21000c4a]-main","size":null,"fancy":1,"locked":0}}
> 
> Weyland-Yutani (c) 2100-2182 Building better user interfaces. 
> 
> ![image](https://github.com/cmss13-devs/cmss13/assets/139605145/e8b8c702-087e-4f03-930d-f09364cc4b69)

### What's the difference with what should have happened?

see above.

### How do we reproduce this bug?

1. Type Medals-Panel into your console to open the admin Medals-Panel
2. it crashes.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
this'll be fixed by #5764
