### ISSUE TITLE
corrupted huggers and lessers do not understand humans

### ISSUE THREAD

**Issue by SolaAqua** [cmss13-devs/cmss13#5783]
### Testmerges

#5007,#5392,#5165,#5401

### Description of the bug

corrupted huggers and lessers  cant understand humans

### What's the difference with what should have happened?

should be able to understand humans

### How do we reproduce this bug?

1.be corrupted hugger or corrupted  lesser
2.find a human who talks
3.dont understand them
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Intended
