### ISSUE TITLE
RMC unable to add their comms frequency to the towers (1216)

### ISSUE THREAD

**Issue by LynxSolstice** [cmss13-devs/cmss13#5797]
### Testmerges

N/A

### Description of the bug

RMC members can multitool the Comms tower on the ground but their frequency will never be added, I've noticed this from running RMC survivor events with the ERT equipment.

### What's the difference with what should have happened?

It should add their comms to the ground tower and let them speak

### How do we reproduce this bug?

1. be RMC ert member
2. Multitool the comms tower and add your faction's frequency
3. Be confused as you can't use your comms frequency on the ground
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
similar issue?
https://github.com/cmss13-devs/cmss13/issues/4766
