### ISSUE TITLE
Cannot remove NVG HUD insert from some helmet(s)

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#5799]
### Testmerges

N/A

### Round ID

21019

### Description of the bug

When attempting to screwdriver some helmets to remove the HUD, the message about the slot being reserved for headgear accessories plays. I'm guessing this is something to do with #5573. I tried putting a helmet accessory into the slot, but could not and got the same message.

![dreamseeker_poeEwPQg7t](https://github.com/cmss13-devs/cmss13/assets/139605145/4fe75258-15bd-48e4-8d15-3404535cbb3b)

### What's the difference with what should have happened?

Screwdrivering a helmet should drop the HUD instead of trying to insert the screwdriver as an accessory

### How do we reproduce this bug?

1. Screwdriver a helmet to remove your HUD (not sure which ones are effected)
2. You try to insert the screwdriver into the helmet instead of removing the HUD.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by private-tristan** [comment]
MARSOC SOF helmets have inbuilt infinite NVG huds, not meant to be removable, the same way that squad optics can't be removed.

**Comment by SabreML** [comment]
> MARSOC SOF helmets have inbuilt infinite NVG huds, not meant to be removable, the same way that squad optics can't be removed.

Yep, looks like this is what's happening. Not a bug, although I will make a PR to change the failure message when this happens since it's a bit confusing.
