### ISSUE TITLE
The 88Mod4 has no in-holster sprite

### ISSUE THREAD

**Issue by Johannes2262** [cmss13-devs/cmss13#5810]
### Testmerges

#5007, #5401

### Description of the bug

The 88Mod4 pretty much has no in-holster sprite and shows up as the funny honk icon with question marks.

### What's the difference with what should have happened?

It should have a real sprite when holstered, like all other pistols and the 88Mod4 from before this bug happened.

### How do we reproduce this bug?

1. Get 88Mod4
2. Get holster belt/pouch
3. Put 88Mod4 into holster
4. Look at the holster

### Issue Bingo

- [X] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
https://github.com/cmss13-devs/cmss13/pull/5785

Can confirm both in uss runtime and shiva. Fix probably just isn't live yet.
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/deac4bc7-b26f-4f76-a737-0ba710bc3556)
