### ISSUE TITLE
Runechat allows you to say hyperlinks

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#5867]
### Testmerges

N/A

### Round ID

N/A

### Description of the bug
![image](https://github.com/cmss13-devs/cmss13/assets/54422837/ed829fa8-9bf2-4b9a-a1b7-eb8d94e5575d)
![image](https://github.com/cmss13-devs/cmss13/assets/54422837/22270300-7a18-4b80-92dc-d0abcce52c2b)
the link is colored blue, and you can click on it to go directly to google from runechat
DEAD: Tristan 'Dies' Quilt ([F](byond:///?src=[0x3000010];track=[0x3000010])) says, "https://www.google.com"

### What's the difference with what should have happened?

it shouldn't.

### How do we reproduce this bug?

1. say "hi https://www.google.com"
2. click on the runechat
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This is not a bug but intended behavior. That being said, there should be no reason to use hyperlinks ICly (not to mention it is LRP)
