### ISSUE TITLE
Xenomorphs can put facehuggers into bags

### ISSUE THREAD

**Issue by Vicacrov** [cmss13-devs/cmss13#5888]
### Testmerges

#5774: 'Updated XM43E1 for Sniper Spec' by Kaga-404 at commit 2bd532a406 #5829: 'Event borers' by realforest2001 at commit bac22e8282 #5007: 'Project ARES TM Holder (v4)' by realforest2001 at commit ea22a09adb #5401: 'M540-A Armored Recon Carrier' by Zonespace27 at commit 9be4807644

### Round ID

21183

### Description of the bug

Xenomorphs can put facehuggers into bags.

### What's the difference with what should have happened?

They should not be able to put things into bags.

### How do we reproduce this bug?

1. Be a carrier
2. Pick up facehugger
3. Click on USCM satchel

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Its fine; doesn't prevent their death.
