### ISSUE TITLE
Ghost Vision & Self-Visibility borked

### ISSUE THREAD

**Issue by ItsVyzo** [cmss13-devs/cmss13#5894]
### Testmerges

Irrelevant

### Description of the bug

Toggling Ghost Vision also makes your ghost invisible. Toggling Self-visibility does not work and the button sends no messages

### What's the difference with what should have happened?

Ghost Vision should keep your ghost and self visibility should actually work

### How do we reproduce this bug?

Toggle Ghost Vision
Toggle Self Visibility
_Enlightenment_

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
toggle self-visibility set's the observer's alpha to 0 which hides it from every mob including itself. 
toggle ghost vision sets the alpha of hud's lighting plane to 0. Effectively hiding that plane from only the source mob's view.

**Comment by ItsVyzo** [comment]
> toggle self visibility sets the observer's alpha to 0 which hides it from every mob including itself. toggle ghost vision sets the alpha of hud's lighting plane to 0. Effectively hiding that plane from only the source mob's view.
> 
> This is why when you toggle the ghost vision you are unable to see yourself regardless of your mob's alpha value. Since the hud's lighting alpha is set to 0 and the mob's ghost exists on that plane it is not visible until that hud plane value is reset to its original number.

Yeah that doesn't help mate, it's still a bug. Toggle Ghost Vision should make other ghosts only disappear and not yours. Toggle Self-Visibility should make your mob disappear and reappear.
