### ISSUE TITLE
Resin Holes Under Weeded Bodies

### ISSUE THREAD

**Issue by Staykeu** [cmss13-devs/cmss13#5907]
### Testmerges

#5774: 'Updated XM43E1 for Sniper Spec' by Kaga-404 at commit ca74842b50 #5401: 'M540-A Armored Recon Carrier' by Zonespace27 at commit 9be4807644 #5887: 'Pizza Station is back on the menu' by Nanu308 at commit 07a0551fac

### Round ID

21230

### Description of the bug

You are able to place down resin traps under weeded bodies, making them virtually invisible.
https://streamable.com/xxc43p

### What's the difference with what should have happened?

You should not be able to place holes under weeded bodies.

### How do we reproduce this bug?

1. See dead body (must be perma if marine or pred)
2. Place a hole under them
3. Profit

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Staykeu** [comment]
Note: This is in no way a rare or unseen issue, it's just an issue with the PR that never got fixed.

**Comment by Drulikar** [comment]
This is not new behavior - the trap would be hidden by the body lying on it. What is new is that the weeded body has no mouse opacity so that entire tile if you hover over it will say it's a trap whereas before it'd say it's a dead body. So if anything the weeded bodies pr has improved this scenario. 

The current trap sprite also cannot work with the weeded bodies either.

**Comment by Staykeu** [comment]
> This is not new behavior - the trap would be hidden by the body lying on it. What is new is that the weeded body has no mouse opacity so that entire tile if you hover over it will say it's a trap whereas before it'd say it's a dead body. So if anything the weeded bodies pr has improved this scenario.
> 
> The current trap sprite also cannot work with the weeded bodies either.

It feels kind of..silly..to have a hugger pop out of a hole that is weeded over.

**Comment by Huffie56** [comment]
hello @Staykeu thanks for taking the time.
i am going to put this as a consistency/balance issue because  it's clearly not a bug.(it work as it's intended.)

i would advice to make a forum post if you want to attract attention on it.
and propose your idea to solve it in it.

**Comment by ItsVyzo** [comment]
Considering nothing was done about this and it's not a bug, will close.
