### ISSUE TITLE
Invisible "Marine" Chest Rig

### ISSUE THREAD

**Issue by Sionnach86** [cmss13-devs/cmss13#5910]
### Testmerges

There are a few test merges.

### Round ID

Unknown?

### Description of the bug

Player picks up Marine Chest Rig from vendor; hand is filled with an invisible "Chest Rig" which has no sprite. Can be dropped and picked up - but has no sprite.

### What's the difference with what should have happened?

Uh, there should be a sprite.

### How do we reproduce this bug?

1. Start a round.
2. Walk up to one of the Marine Vendors where the Chest Rig is spawned.
3. Vendor a chest rig. Initially, it does not appear to vend anything - but the player's hand will be filled with an invisible object which appears to be the Marine Chest Rig - but invisible due to lacking sprite.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Likely just a cache issue locally for you. See https://forum.cm-ss13.com/t/how-to-clear-your-cache/2909#how-to-clear-your-byond-cache-1 for your byond cache.

**Comment by GrrrKitten** [comment]
> Likely just a cache issue locally for you. See https://forum.cm-ss13.com/t/how-to-clear-your-cache/2909#how-to-clear-your-byond-cache-1 for your byond cache.

I have cleared cache many many times and reinstalled byond since the PR merged and ive had this bug since the PR was merged

**Comment by Drulikar** [comment]
Works fine on LV624. I assume then you mean on an ice map then.
