### ISSUE TITLE
Getting hugged, takes your helmet off but keeps the squad overlay

### ISSUE THREAD

**Issue by ItsVyzo** [cmss13-devs/cmss13#5912]
### Testmerges

Irrelevant

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/46250991/3480301b-6704-42e6-bd29-1fb7ec8cda0d)

### What's the difference with what should have happened?

Squad designating overlay should be gone

### How do we reproduce this bug?

Be in a Squad while wearing helmet
Get hugged
You have a snazzy hair paint job

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ansekishokuu** [comment]
The problem occurs when you put 4 visible items on your helmet. for example a helmet netting, broken nvg, bandage and a barcardine bar will cause the overlay to get stuck on your head. Doesnt matter if you get hugged or not, removing the helmet yourself you will also see the overlay stuck on your head.

**Comment by Ansekishokuu** [comment]
Forgot to mention you need to enable your helmet hud, for example a medical hud as the final step to reproduce this issue.
