### ISSUE TITLE
Unable to PB with m41a mk1 consistantly

### ISSUE THREAD

**Issue by Sylphily** [cmss13-devs/cmss13#5919]
### Testmerges

#5774, #5401, #5887, #5696, #5510, #5006:

### Round ID

21252

### Description of the bug

while resisting out of a warrior grab, and running away, the self PB didn't fire, as can be seen in this recording of the moment

https://github.com/cmss13-devs/cmss13/assets/30062054/6e4d6eb0-f56a-4147-a736-056bc0d67729

![dreamseeker_be7mypOKo9](https://github.com/cmss13-devs/cmss13/assets/30062054/84d9bb7c-0ca4-4f18-a0d0-fd4c11f88872)

### What's the difference with what should have happened?

You should be able to shoot your self, when not in a grab

### How do we reproduce this bug?

1. resist out of grab
2.proceed to shoot your self

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by HaultyAnonie** [comment]
@Sylphily 
Sir, you do not PB yourself on help-intent.
You are **supposed** to PB yourself on harm-intent.
You are not a clown. You are the entire circus. ba bumbu bmbumaduabum bu bum

**Comment by Huffie56** [comment]
@Sylphily please try to PB yourself when you can with harm intent(unload your gun first and cock it!)
i am not sure but their is maybe an option in the preference tab under the combat verbs?
if you still can't do it please tag me with your experience i will  reopen it.

**Comment by Sylphily** [comment]
@Huffie56 forgot to update this, it turns out that it was due to Melee cool down from me hitting my self with a rifle before switch to harm intent and trying again, idk if that would be considered a bug or not

**Comment by Huffie56** [comment]
@Sylphily that don't seem like a bug.
bug meaning you do an action and the code doesn't respond as intended by the coder.
and what you describe seem intended.

if you want you can post something about it on the forum to talk about change balance etc around this situation.
