### ISSUE TITLE
Sprite Issue on Pillbottles

### ISSUE THREAD

**Issue by Lagomorphica** [cmss13-devs/cmss13#5931]
### Testmerges

#5401: 'M540-A Armored Recon Carrier' by Zonespace27 at commit 9be4807644 
#5887: 'Pizza Station is back on the menu' by Nanu308 at commit c9aae15da3 
#5696: 'Legcuffs work' by realforest2001 at commit 67672626a9 
#5006: 'Project ARES: Added Tech Unlock logs' by realforest2001 at commit c0645ab04c 
#5927: 'use world.Export instead of rustg http for byond account age' by harryob at commit ed4283bdb4 
#5724: 'XM43E1 in regular gameplay' by Releasethesea at commit 9f897ae069 
#5763: 'Map: Bigred change south lambda padlock and turned it into a checkpoint.' by Huffie56 at commit 646c47711a 
#5838: 'Resprites - 2/2024 Edition' by nauticall at commit 59743e1e37

### Round ID

21290

### Description of the bug

Pill bottles are missing the cap sprite like on the [Resprites - 2/2024 Edition PR](https://github.com/cmss13-devs/cmss13/pull/5838). Image will show the difference between the provided PR and what was in game.

![308054557-00c0ca83-ddd1-4e96-a692-6db5a6095dac](https://github.com/cmss13-devs/cmss13/assets/49899119/f34591b9-f666-4952-9396-3cf6fd3e7bb0)

This was the provided image of what the pill bottles are supposed to look like. Note the white cap on top to give depth.

This is what is visible in game (in belt and on floor)

![image](https://github.com/cmss13-devs/cmss13/assets/49899119/69891c71-7c0f-4356-9e6b-756547496c72)

![image](https://github.com/cmss13-devs/cmss13/assets/49899119/e37c828d-682a-475b-9bcc-961a9f933f12)

### What's the difference with what should have happened?

The sprites should have a noticeable cap or lid on them. The sprites of empty pill bottles (that is, pill bottles you get in boxes from Chemistry) have an open lid on them. I am not certain on if these pill bottles are supposed to have an opened sprite either but they lack them, assuming that is needed.

### How do we reproduce this bug?

1. Get a pill bottle.
2. Look at it.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Looks like the pills_closed state in chemistry.dmi got lost sometime between the time the PR was opened and when it was merged.
