### ISSUE TITLE
Changing item sprites don't work (MP tools)

### ISSUE THREAD

**Issue by Prymalis** [cmss13-devs/cmss13#594]
## Description
When an item has different sprites depending on its status, it doesn't seem to actually work.
![image](https://user-images.githubusercontent.com/79453127/176723433-ff1c2c1d-7276-43d3-994c-8a4bc41f5a3c.png)
![image](https://user-images.githubusercontent.com/79453127/176723465-f40a69db-c869-4924-bab1-d2f330a34820.png)

## Difference between expected and actual behavior
Taser should visually drain itself when shot, it don't. Same with a burned out flash, it appears like as if it still works.

## Issue bingo (not required to be all checked)
- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
is this happening after IO TM ? or before?

**Comment by Prymalis** [comment]
> is this happening after IO TM ? or before?
Not sure.

**Comment by stanalbatross** [comment]
fixing taser, gonna fix flash too
