### ISSUE TITLE
Comtech vendor dupes essential equipment set

### ISSUE THREAD

**Issue by thatoneyeeter** [cmss13-devs/cmss13#5941]
### Testmerges

i forgot

### Description of the bug

vendor gave me two copies of the comtech essential equipment set, probably due to lag

i forgot which round it was or what TMs were up because it was two days ago

### What's the difference with what should have happened?

well the vendor should NOT be duping my mats

### How do we reproduce this bug?

1. be extremely laggy (start downloading war thunder on steam)
2. vend the comtech essential equipment
3. do it again because the button is still available
4. profit??
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Could not reproduce
