### ISSUE TITLE
Can't open Ghost Tacmap

### ISSUE THREAD

**Issue by Tangerineje** [cmss13-devs/cmss13#5969]
### Testmerges

-

### Round ID

it happened on multiple round for months

### Description of the bug

can't open ghost tacmap while ghosted 

### What's the difference with what should have happened?

i should be open ghost tacmap while ghosted

### How do we reproduce this bug?

1. be ghost
2. try to open ghost tacmap 
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Tangerineje** [comment]
by the way this bugs happens randomly for some reason so i don't know how to reproduce it exactly

**Comment by SabreML** [comment]
I've had this quite a lot as well. Haven't been able to find the cause yet unfortunately.

**Comment by Drulikar** [comment]
I can confirm my PR fixes atleast one scenario where it would prevent ghost tacmap from opening, but there could be other ways maybe too.
