### ISSUE TITLE
If a medal was given after the round ended then it will not show up in OOC-view own medals

### ISSUE THREAD

**Issue by ATP2333REAL** [cmss13-devs/cmss13#5986]
### Testmerges

not important

### Description of the bug

so here is it,as the title said,the medal that given after the round ended wont show up in OOC-view own medals
![屏幕截图 2024-03-20 072315](https://github.com/cmss13-devs/cmss13/assets/163058473/328463e3-8f64-4a2c-98b3-317d227ddcc7)
![屏幕截图 2024-03-20 103651](https://github.com/cmss13-devs/cmss13/assets/163058473/355fd5a8-d8f6-44e2-a994-c2fef3207f08)

### What's the difference with what should have happened?

so the medal given after the round end should show up in OOC-view own medals,**man i am fucking upset because it is my first medal that given by the best CO i have ever seen**

### How do we reproduce this bug?

**get medals after the round end then you will know how disappointed i am**

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Medals should be given before round end. There are 3 minutes given after all clear which may be utilized for this and with the addition of the medal recommendation PR this should not be much of an issue anymore. Either way, not a bug as there needs to be a set tight when this stuff gets logged before server restarts.
