### ISSUE TITLE
Queen fails to respawn sometimes when selecting a location

### ISSUE THREAD

**Issue by PhantomEpicness** [cmss13-devs/cmss13#5999]
### Testmerges

#5724, #5763 , #5829, #5006 , #5401 ,#5938 , #5974

### Round ID

21445

### Description of the bug

I was trying to go queen on Shivas Snowball and selected "Research Hab Interior" after a short amount of time (10-45 seconds) of pondering my hive location. 

When I selected it, it did not spawn me in as queen and instead simply closed the GUI, leaving my placeholder character in an unplayable state. No queen spawns at all and it needs admin intervention to rectify so this is **extremely disruptive** for the game flow.

This has been reported before on the discord so I suspect that the map may not have something to do with it.  

### What's the difference with what should have happened?

Queen should be spawned into the selected location instead of being put into a non playable state.

### How do we reproduce this bug?

1. Go Shivas
2. Wait 20-30 seconds before selecting
3. Select "Research Hab Interior"
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
Map was redone recently, gotta @ the mapper who reworked it.

**Comment by Vicacrov** [comment]
I am 90% sure this is map-unrelated, I experienced this on Solaris when I waited for too long. To reproduce it, make sure to wait at least half a minute.

**Comment by vero5123** [comment]
Not able to reproduce the issue.

**Comment by dadlips** [comment]
this happens when someone spawns in as a queen/evolves to a queen while you're still selecting where to spawn.

**Comment by vero5123** [comment]
yep
