### ISSUE TITLE
duplicated items when being examined

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#60]
## Reproduction:

seems that an item can get duplicated in local examines 

![image](https://user-images.githubusercontent.com/66756236/163687466-08780d5a-66c0-4b55-b34c-018a71b7232a.png)

happened here with a combistick but vvs confirmed that the combi was not present in the pred's suit storage

**Comment by Shad0vvs** [comment]
Reported from players:

if you use the hotkey to yank spear
with it on your back
it duplicates on examination
also makes it impossible to equip until it changes hands

does the same thing with the smartdisc
