### ISSUE TITLE
Dropship autopilot behaving badly.

### ISSUE THREAD

**Issue by MistChristmas** [cmss13-devs/cmss13#6016]
### Testmerges

#5763 #5006 #5401 #5938 #5974 #5774 #6013

### Round ID

21474

### Description of the bug

Not really a bug or anything but people keep using the ground console to set up autopilots, which is fine on the primary LZ, but when it's the other LZ that autos the Normandy, fuckery ensues? I.E It'll try to send the Normandy ontop of the Alamo. And maybe get stuck landing or taking off. And results in the ships needed to do a shuffle to get back to their usual pads.

May want to give the cockpit the ability to disable the autopilot.
What might be a bug is that when you try to disable the auto pilot from the Alamyer side consoles the Normandy will claim it's not on autopilot? But when they go down to the to turn off the autopilot from that side it works. 

### What's the difference with what should have happened?

They shouldn't try to land on a pad already occupied? I've only seen this happen once, and it didn't end up with the dropships merging into one, it just got stuck infinitely landing and the shadow animation kept getting spammed. Usually it'll just keep trying to take off from the hanger but not actually taking off until the alamo clears the LZ.

The consoles on the Alaymer should correctly report which dropships are being autopiloted instead of lying.
And the POs shouldn't have to go to the ground to disable the autopilot on the console there

### How do we reproduce this bug?

1. Launch Alamo to the Secondary LZ
2. Use the console there to autopilot the Normandy to do transport for some reason
3. Maybe break things and get the Normandy in the air and having infinite landing
4. Probably just have ARES repeatedly tell you the dropship is departing instead
5. Attempt to disable the autopilot from the bubble or CIC and realise it's lying to you?
6. Head down to the planet to disable it there.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MistChristmas** [comment]
Couldn't get this issue to pop up on Local. So perhaps there's more to it that just using the ground console to trigger this. I don't remember the round that the Normandy tried to repeatedly land on the alamo but maybe someone else does and has the info.

**Comment by vero5123** [comment]
personally, I don't think the ground console should be able to set auto-pilot. Imo that needs to be a cic and ds only thing.

**Comment by MistChristmas** [comment]
Presumably un-replicated since dropship consoles got changed.
