### ISSUE TITLE
Type 71 wielded sprites overlap player (East and West)

### ISSUE THREAD

**Issue by TopHatPenguin** [cmss13-devs/cmss13#602]
## Description

Type71 can be seen from both sides when wielded causing a floating gun effect.

## Difference between expected and actual behavior

Weapon should be partially covered like all other weapons when wielded depending on the side.

## Steps to reproduce

- Be UPP
- Wield Type 71
- Perform floating gun magic trick for the Kolonel

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by moltoretardo** [comment]
![image](https://user-images.githubusercontent.com/53326609/215290541-f13eafd4-6787-4b0b-9954-1f1603e67b36.png)![image](https://user-images.githubusercontent.com/53326609/215290545-beff9c38-0067-49a5-aa99-4ca0d36c4e48.png)

![image](https://user-images.githubusercontent.com/53326609/215290560-bb487ea9-222a-469a-b608-3258b303ce1d.png)![image](https://user-images.githubusercontent.com/53326609/215290571-2bab0872-83ea-4672-9a12-7ceacccf3137.png)

I think I might see what you meant, MK1 top, type71 bottom

**Comment by ItsVyzo** [comment]
Seems to have been fixed already/not an issue anymore
