### ISSUE TITLE
Infrared missing attachable/ready state notification text & Mousetrap unable to be attached

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#603]
## Description
1 You can make one by using an autolathe. I believe it starts out attachable, if you screw it, rclicking allows you to change the laser direction. 

When you screw it, it doesn't show you whether it became attachable or ready, unlike signallers, igniters, et al, and if examined it doesn't show its state either

2. Rat traps can't be screwed to attach to signallers igniters et al.

## Difference between expected and actual behavior
See above

See above

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@ItsVyzo so i looked at the code and tested it and i see nothing that  indicate that you should be able to associate mouse trap to any other component.
it's a suggestion not an issue you can close it.

**Comment by ItsVyzo** [comment]
> @ItsVyzo so i looked at the code and tested it and i see nothing that indicate that you should be able to associate mouse trap to any other component. it's a suggestion not an issue you can close it.

epic thank you @Huffie56
