### ISSUE TITLE
ASRS is unable to be hacked by an MT

### ISSUE THREAD

**Issue by Drewzeedo5** [cmss13-devs/cmss13#6033]
### Testmerges

BYOND Version: 515.1633 Server revision compiled on: 2024-03-27T03:43:33+00:00 Master commit: 0275359284d90b7c3aed4f69734c37cffd051037 The following pull requests are currently test merged: #5763: 'Map: Bigred change south lambda padlock and turned it into a checkpoint.' by Huffie56 at commit 646c47711a #5006: 'Project ARES: Added Tech Unlock logs' by realforest2001 at commit 1f2b803178 #5401: 'M540-A Armored Recon Carrier' by Zonespace27 at commit 9aae279dd9 #5938: 'Adds Shockwaves to Explosions and Xeno Screeches ' by GrrrKitten at commit 23c093ff8c #5974: 'A more breakable Kutjevo' by spartanbobby at commit 02131e9f6a #5774: 'Updated XM43E1 for Sniper Spec' by Kaga-404 at commit 6c68c6197b #5914: 'Ports stripping menu from TG' by ihatethisengine at commit 4bdaa269cb #5697: 'G2 Electroshock Grenade "Sonic Electric Ball Breakers (SEBB)" [No Shitcode Edition]' by PhantomEpicness at commit 4c26ecb541  Local commit: 3fe6a10680085b9bcd7d548e336532c5809a8f46 TGS version: 6.3.1 DMAPI version: 5.9.0

### Round ID

Multiple

### Description of the bug

When following the WIKI guide on how to hack an ASRS console i am unable to hack the board with the modified tuner found in maints., Nothing pops up in chat or in another window and when i use the board in the computer nothing changes.

### What's the difference with what should have happened?

I should be able to use my modified tuner on the board to then access some window or line of text that notifies me that i have changed the board to a "broad" setting

### How do we reproduce this bug?

I play as MT, wearing a fire suit and helmet, gas mask, insulated gloves, welding goggles, tool pouch, welder satchel, medium general pouch and the first aid pouch with bandages
Screwdriver to disconnect the monitor.
 Crowbar to pry out the glass
Wirecutters to remove the cables
Screwdriver to unfasten the circuit board
Crowbar to pry the board back out
Use a Modified Multitool/Access tuner on the board, select "BROAD"
OR
Dispense an ASRS board from vendor
Use modified tuner

Both Fail in the hands of this MT

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drewzeedo5** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/165241351/d843435e-185d-494c-ab03-7f21ebfed2bd)

**Comment by Drewzeedo5** [comment]
> That's the wrong kind of ASRS board

what do you mean? theres only one kind isnt there?

**Comment by Segrain** [comment]
> > That's the wrong kind of ASRS board
> 
> what do you mean? theres only one kind isnt there?

No. There are computers outside Req that can make requests, and computers inside Req that can actually transform requests into approved orders. Hacking is for the latter.

**Comment by ItsVyzo** [comment]
This is not a bug.

You have to partially unbuild one(or all) of the ASRS computers in requestions.

Once you get to the board you'd use the modified security access tuner on it then put the board back in and rebuild the computer.

**Comment by Drewzeedo5** [comment]
i had no clue it was ONLY the ones inside req, my bad yall
