### ISSUE TITLE
helmet squad sprite stays o head after helmet removal

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#6041]
### Testmerges

not relevant, tested on local with no TM

### Description of the bug

when you fully fill helmet with stuff and add medical HUD turn it on and remove helmet squad stripe sticks to your head and can not be removed

### What's the difference with what should have happened?

should not have floting line above head

### How do we reproduce this bug?

1.take m10 helmet, put in 4 items ( I have used old NV , headband flashlight and gauze, might be important but prop not)
2.install med HUD into onto the helmet, put it on and turn on the HUD
3.remove helmet and observe squadline above your head remain
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Duplicate #5912
