### ISSUE TITLE
Dead xenos with "Corrosive Acid" ability can cause the red circle wind up animation to appear on their corpses.

### ISSUE THREAD

**Issue by Veglok** [cmss13-devs/cmss13#6066]
### Testmerges

Don't think it's connected to any of the test merges.

### Round ID

21573

### Description of the bug

As a dead xeno with "Corrosive Acid" ability you can try melting stuff around you to cause red circle animation to appear,
nothing will actually be covered in acid as a result of that.
Only works while you are still in control of the dead xeno body.

### What's the difference with what should have happened?

You should get message like "We cannot do this in our current state." which is the case if you try using any other xeno abilities while dead (or stunned I guess).
Instead, the circle animation will appear on top of your body as if you're actually in the middle of doing something.

### How do we reproduce this bug?

1. Die as a xeno with "Corrosive acid" ability
2. Your corpse must be intact so that your ghost can stay inside of it
3. Have any meltable objects near your corpse
4. Use "Corrosive acid" on any meltable object around your corpse

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
This one seems like an ideal candidate for the good first issue label.
