### ISSUE TITLE
Certain ERT's can't send their shuttle back once on the Almayer.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#6075]
### Testmerges

N/A

### Description of the bug

As the title says, If you try to launch your shuttle from the Almayer, it'll say something like 'no access' This is particularly obvious on any CMB ERT. Others may be effected.

### What's the difference with what should have happened?

ERT's should be able to go home.

### How do we reproduce this bug?

1. Spawn in as a CMB ERT
2. Get to the Almayer on your shuttle
3. Try to go home, you can't. Your ID/Faction is wrong.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
So far I have not been able to reproduce this.

What role were you slotted as, and for which CMB ERT (there are three)? Or what was the roundid and your player name?

**Comment by dadlips** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/139605145/5d591850-3b7c-420c-8997-abb078720d91)
should be this one, I'm not sure how to test it either since I can't get a distress going due to being the only person on my server. I believe they have to be sent from the new lazy ert station.

**Comment by Drulikar** [comment]
You can just add `mob_min = 1` under `/datum/emergency_call/cmb` and then the ERT will be allowed for 1 person. But yeah I cannot reproduce this issue. All the roles have the same access as far as I can tell too. So I need more specifics on what you did or maybe what you got confused about.

I will note however there is a runtime w/ the objectives getting said. I can fix that - but its unrelated to shuttle launch. For example: https://youtu.be/awPuKxfZRco

**Comment by HumiliatedGoblin** [comment]
Dadlips, I think I was the XO on this round. I think the CMB's were at the wrong shuttle, as there were a goon shuttle at east engineering that we swapped places with.

**Comment by dadlips** [comment]
> You can just add `mob_min = 1` under `/datum/emergency_call/cmb` and then the ERT will be allowed for 1 person. But yeah I cannot reproduce this issue. All the roles have the same access as far as I can tell too. So I need more specifics on what you did or maybe what you got confused about.
> 
> I will note however there is a runtime w/ the objectives getting said. I can fix that - but its unrelated to shuttle launch. For example: https://youtu.be/awPuKxfZRco

By all intents that should have triggered the issue. Maybe the confusion comes when someone other than the CMB squad leader tries to launch? It could have also just been people trying to use the wrong dropships all these times.

**Comment by Huffie56** [comment]
feel free to tag me if this issue is still happening. i will reopen it.
