### ISSUE TITLE
Playing a facehugger from a Cross ciphering egg does not result in a predalien.

### ISSUE THREAD

**Issue by The-Sun-In-Splendour** [cmss13-devs/cmss13#6079]
### Testmerges

None (Replicated on localhost with no TMs)

### Round ID

Tested on localhost & 21604

### Description of the bug

Inject an egg with cross ciphering to make it into a "corrupted corrupted egg", if a player plays a facehugger from that egg they will not bear an abomination once infecting a host and bursting.

Sorry if this is already known. I looked up "abomination" and "predalien" in issues and saw nothing.

### What's the difference with what should have happened?

The embryo should burst into an abomination. If people think that playing a cross-ciphering facehugger will give them the abom, it will give them the larva... Just not as an abom, basically soft-griefing the researchers.

### How do we reproduce this bug?

1. Inject cross ciphering into an egg
2. Have someone play a facehugger from that egg
3. Infect a host
4. The embryo will burst as a normal larva, and not a predalien larva.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
It's not supposed to make someone an abomination. Abominations are born from a hugger infecting a Yautja, not from humans.
