### ISSUE TITLE
Switch-Storing-Drawing-Method doesn't work on drop pouches.

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#6089]
### Testmerges

#5938: 'Adds Shockwaves to Explosions and Xeno Screeches ' by GrrrKitten at commit 23c093ff8c #5914: 'Ports stripping menu from TG' by ihatethisengine at commit ac0caebb9d #6020: 'Super Strength Grab Changes (Never skip arm day)' by Ben10083 at commit 924653248a #6015: 'Colony Synthetic variants with a refresh' by QuickLode at commit c6f1f9a71d #6040: 'Better throw logic' by Git-Nivrak at commit 73147634ec #5401: 'M540-B Armored Recon Carrier' by Zonespace27 at commit 6cbd84ffea #5774: 'Updated XM43E1 for Sniper Spec' by Kaga-404 at commit a054def05e #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 20f293b14d

### Description of the bug

This is a oversight that's been around, probably for quite a long time 

//

When using these freeform storage items, you cannot set them to draw on click.
![image](https://github.com/cmss13-devs/cmss13/assets/44538569/ad124686-1bc8-44f5-a800-14e43c897af0)

It makes sense with the satchel, G8-A pouch, and general pouches, since they have no option to do so, However -
![image](https://github.com/cmss13-devs/cmss13/assets/44538569/d4448092-5c59-4900-8f44-6c1a3bc5aac1)
For the drop pouch, it does have an option. It just doesn't work.

### What's the difference with what should have happened?

Either the drop pouch should not have the option (like similar storage items) so that it's less confusing
Or it should be able to be drawn from by click.

### How do we reproduce this bug?

1. Get a drop pouch from Surplus Uniform Vendor
2. Place it on your uniform
3. Attempt to Switch-Storage-Drawing-Method
4. It does nothing.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by rythenx** [comment]
This is still occurring.  I might see if I can find the cause and raise a PR.
