### ISSUE TITLE
shotgunshell boxes and big creates are not linked in reqestion vendor

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#6096]
### Testmerges

#5938: 'Adds Shockwaves to Explosions and Xeno Screeches ' by GrrrKitten at commit 23c093ff8c #5914: 'Ports stripping menu from TG' by ihatethisengine at commit ac0caebb9d #6015: 'Colony Synthetic variants with a refresh' by QuickLode at commit c6f1f9a71d #6040: 'Better throw logic' by Git-Nivrak at commit 73147634ec #5401: 'M540-B Armored Recon Carrier' by Zonespace27 at commit 6cbd84ffea #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 20f293b14d

### Round ID

21640

### Description of the bug

possibly more of an oversight, with nades and other ammo the huge boxes share ammo with normal mags, aka when you take box with 10 m41a mags tere is 10 less m41a mags less in the vendor . does not work with shotgun shell boxes

### What's the difference with what should have happened?

there should be 4 times the number of small boxes as large boxes and when you vend large box it reduces number of small boxes by 4

### How do we reproduce this bug?

1.check number of boxes
2.vend big box
3.check again, it is the same

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
this PR added the logic for it. should be a good start to look into it
https://github.com/cmss13-devs/cmss13/pull/1759

**Comment by ThePiachu** [comment]
As I'm looking at my old code, the Shotgun shell boxes were never integrated into the change since they are a weirder case. `Shotgun Shell Box` contains handfuls of shotgun shells, not full `Box Of XXX Shells`. So you'd have to have a separate code converting Shell Boxes into handfuls and those back into Boxes of Shells. I guess it would be doable, especially if you add individual handfuls of ammo into the vendor itself...

**Comment by ThePiachu** [comment]
Okay, I think I've got it. Will also clean up something else I had an idea to do with vendors years back...

**Comment by ThePiachu** [comment]
Should be completed via #6397
