### ISSUE TITLE
Cannot place/equip autocompressor

### ISSUE THREAD

**Issue by Katskan** [cmss13-devs/cmss13#6099]
### Testmerges

#5938, #5914, #6015, #6040, #5401, #6039

### Round ID

21643

### Description of the bug

Cannot apply the autocompressor to a patient either by clicking on them or using the new inventory screen that's on TM.

### What's the difference with what should have happened?

Normally you can apply the autocompressor by removing a patient's armor, then clicking on their mob sprite will apply the compressor to the armor slot. I also tried to place the autocompressor in their armor slot by using the new inventory screen but it didn't work. 

### How do we reproduce this bug?

1. Get a volunteer or dead person
2. Remove their armor
3. Attempt to apply autocompressor

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
I cannot reproduce this issue on the live server or locally for that PR. Works fine both clicking on the sprite and clicking on the suit slot in the new stripping UI:

![cpr](https://github.com/cmss13-devs/cmss13/assets/76988376/8dc81a0c-6b2b-4279-9d1c-a35ac0b77e5c)
