### ISSUE TITLE
Sentries Target Lesser Drones while Inside of a pipe.

### ISSUE THREAD

**Issue by v3nturis** [cmss13-devs/cmss13#6110]
### Testmerges

No Clue

### Round ID

21658

### Description of the bug

Map was LV-522 I was running around groundside as a lesser drone. While inside of a pipe a sentry drone targeted me and fired at my position, it continued top fire and miss.

### What's the difference with what should have happened?

Im not certain if it's intended or not. I could dump ammo out fo the turret and have it burn everything up if I sat there long enough.

### How do we reproduce this bug?

1. Be lesser drone on LV-522
2.Get inside of vent pip on groundside
3.GO near sentry
4. be shot at and not get hit?
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Repeat of this report: 
https://github.com/cmss13-devs/cmss13/issues/5556
