### ISSUE TITLE
Clicks dont go through bug

### ISSUE THREAD

**Issue by Wintermote** [cmss13-devs/cmss13#6112]
### Testmerges

#5914, #6015, #6040, #5401, #6103, #5957, #6107, #6039

### Round ID

21660

### Description of the bug

If you are moving left and click within 2 tiles but outside 1 tile away from yourself to the left while moving left direction, 90% of your clicks are ignored.

Similarly, if you are moving left and click within 1 tile of yourself to the right while moving left, all of your clicks are accepted.

It appears to be the case that the clicking restrictions for 1 tile around the player to prevent them shooting when they click within 1 tile of themselves, are actually not perfectly updating with what's visually on the screen. Essentially your click block radius is always centered about a half tile in front of your character in the direction of your movement.

### What's the difference with what should have happened?

When clicking >1 tile away your clicks should always work
When clicking <1 tile away your clicks should never work

Instead, your direction of movement influences this and you must click further away or can click closer depending on your direction of movement when you click.

### How do we reproduce this bug?

1. Enable click-drag override
2. Find any gun
3. Enable the safety (for the purposes of immediate clicking feedback)
4. Find a position about 1.4-1.6 tiles away from you
5. Move in that direction while clicking
6. Observe 90% of click inputs do not go through (if you remove safety this will also be the case with bullets fired)
7. Find a screen position within 1 tile of you
8. Move away from that direction and click
9. Observe that almost all all of your clicks work when they shouldn't while you are moving away

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Lag issue, all clicks next to you with a gun don't process iirc.

Byond documentation notes it: https://www.byond.com/docs/ref/#/client/proc/Click

**Comment by ItsVyzo** [comment]
Not a bug
