### ISSUE TITLE
Creating Multiple food items from one set of ingredients.

### ISSUE THREAD

**Issue by Nakijimakai** [cmss13-devs/cmss13#6128]
### Testmerges

9

### Round ID

21689

### Description of the bug

 If you click the Activate button multiple times in the time it takes for the button gray out on a microwave you can spawn Multiple food items into the game using only the ingredients for one item.
![Pile of spagett](https://github.com/cmss13-devs/cmss13/assets/24973622/6a038d81-36c2-43d8-a51a-de5db768ac37)

### What's the difference with what should have happened?

Unsure as the Activate button appears to be tied to the server ticks or even the ping to the server.

### How do we reproduce this bug?

1. Place any food item into a microwave to cook.
2. Spam click, or autoclicker, on the activate button.
3. Aquire a giant pile of food.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
That's actually pretty funny.
