### ISSUE TITLE
Preshure Tank (Oxygen) (that is its name) gets hiden under hiveweeds

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#6132]
### Testmerges

#5914: 'Ports stripping menu from TG' by ihatethisengine at commit 25cba9c18a #6015: 'Colony Synthetic variants with a refresh' by QuickLode at commit c6f1f9a71d #6040: 'Better throw logic' by Git-Nivrak at commit 73147634ec #5401: 'M540-B Armored Recon Carrier' by Zonespace27 at commit 6cbd84ffea #6103: 'Med Vendor Rebalance' by Drulikar at commit 25ff225634 #5957: 'OT CAS rocket' by iloveloopers at commit d9da5fe4b8 #6107: 'Adds medlinks to the marinemeds in medbay' by Drulikar at commit 9b993435ac #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit e46cc87a92 #6114: 'dehardcodes client version warnings' by harryob at commit 653037e4a7

### Round ID

21700

### Description of the bug

the oxygentank has lower layer then hiveweeds but blocks movement

### What's the difference with what should have happened?

should be visible on higer layer then weeds

### How do we reproduce this bug?

1.have said tank
2.place pylon near it
3.watch it be invisible but still block you
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Layering issue
