### ISSUE TITLE
Player controlled facehuggers do not die when caught and squished mid-pounce by a predator

### ISSUE THREAD

**Issue by UntoldTactics** [cmss13-devs/cmss13#6134]
### Testmerges

#5914 #6015 #6040 #5401 #6103 #5957 #6107 #6039 #6114

### Description of the bug

When catched mid-pounce by a Yautja and squished, the typical sound of a facehugger dying will be heard yet the player controlled facehugger will infact, not be dead.

### What's the difference with what should have happened?

Basic facehuggers can sometimes be caught by Yautja mid-air when trying to pounce them, this results in them being squished and a dead facehugger on the ground. This same behaviour functions for player-controlled facehuggers, but when 'killed', the player controlled facehugger won't actually die.

### How do we reproduce this bug?

1. Be Yautja
2. Face towards a player controlled facehugger and allow it to pounce you (Easier to proc the grab if unmasked, I believe)
3. Yautja _should_ be able to grab the facehugger mid-air and squish it, but you'll notice that the player controlled facehugger ain't ded.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
Code for this is pretty funny.
