### ISSUE TITLE
LZ detector showing as not installed in the pilots console on the alamo

### ISSUE THREAD

**Issue by Drewzeedo5** [cmss13-devs/cmss13#6138]
### Testmerges

BYOND Version: 515.1635 Server revision compiled on: 2024-04-12T10:54:55+00:00 Master commit: 177164b78514415a8bc723d31c632c5884f711a6 The following pull requests are currently test merged: #5914: 'Ports stripping menu from TG' by ihatethisengine at commit 25cba9c18a #6015: 'Colony Synthetic variants with a refresh' by QuickLode at commit c6f1f9a71d #6040: 'Better throw logic' by Git-Nivrak at commit 73147634ec #5401: 'M540-B Armored Recon Carrier' by Zonespace27 at commit 6cbd84ffea #6103: 'Med Vendor Rebalance' by Drulikar at commit bc95c5d0ce #5957: 'OT CAS rocket' by iloveloopers at commit d9da5fe4b8 #6107: 'Adds medlinks to the marinemeds in medbay' by Drulikar at commit 9b993435ac #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit e46cc87a92 #6114: 'dehardcodes client version warnings' by harryob at commit 653037e4a7  Local commit: 27378272b3edc2f5604f1c5a88de6f367490988b TGS version: 6.3.1 DMAPI version: 5.9.0

### Round ID

Map: Trijent Dam  Round ID: 21729  Server Time: 2024-04-13 02:22:35  Round Time: 00:37  Operation Time: 08:34   Security Level: GREEN  Primary LZ: LZ1 'Admin'  Operation Name: Peacekeeping Mission Foxtrot-X-ray  View Tactical Map

### Description of the bug

installed LZ detector as PO, not showing as installed, cameras not working in the weapons console

### What's the difference with what should have happened?

see LZ detector cams on weapons console when selecting cameras

### How do we reproduce this bug?

installed LZ detector as PO, not showing as installed, cameras not working in the weapons console

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drewzeedo5** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/165241351/7836d487-da2b-46cb-9faa-aec1dd6ad870)

**Comment by Drewzeedo5** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/165241351/5c9624e4-f636-43fd-b63a-17cfac6b91e0)

**Comment by ihatethisengine** [comment]
Not a bug, you are meant to use camera console to access LZ detector cameras. "Component not found" message is due to the fact there is no menu for the component, as there is nothing to interact with.

**Comment by ihatethisengine** [comment]
![2024-04-15_13-59-53](https://github.com/cmss13-devs/cmss13/assets/115417687/b82c7923-fc18-4596-85b2-57580445e4f9)

**Comment by Huffie56** [comment]
@Drewzeedo5 if you could change your issue name and description to match what ihate say above that would be nice.
your issue isn't a bug but a misleading screen error...

**Comment by ItsVyzo** [comment]
Not a bug, works fine on live.
