### ISSUE TITLE
perament chat deafness caused SOMEHOW by flashbang

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#6156]
### Testmerges

#5401: 'M540-B Armored Recon Carrier' by Zonespace27 at commit 8e87180315 #6103: 'Med Vendor Rebalance' by Drulikar at commit bfdc7f3309 #5957: 'OT CAS rocket' by iloveloopers at commit ce1f761988 #6114: 'dehardcodes client version warnings' by harryob at commit 653037e4a7 #6062: 'Stabilized metallic foam, a gimmick new flamer fuel' by iloveloopers at commit eb2a451306 #6149: 'no more buckling xenos into chairs' by iloveloopers at commit f1bc1b0a0c #6117: 'Project ARES: Reception Remodel' by realforest2001 at commit 64d1351dcb

### Round ID

21779

### Description of the bug

I have gained my hearing back but it did not work in chat, aka I saw runespeak but only deafness in chat https://cdn.discordapp.com/attachments/745447048261795890/1229817510602215486/image.png?ex=66310fcf&is=661e9acf&hm=36048389f2fe9c891e4593ca5a63c7bcc44e2db38b2e106ce7031c84bf2acd29&

BANG
You notice you can't hear anything... you're deaf!
Your ears start to ring badly!
You can't hear anything!
Someone near talks but you cannot hear them.
x2

... You can almost hear someone talking ...
Someone near talks but you cannot hear them.
x4

You start hearing things again!
Unknown (as Alexei 'Ramius' Trofimov) points to the floor
2ndLt Hibiki Morikawa talks but you cannot hear them.
Smith S. Smith has grabbed Randy 'Contraband' Pratt passively!
1stLt Talon Yeskey talks but you cannot hear them.
PFC Alexei 'Ramius' Trofimov(as Alexei 'Ramius' Trofimov) talks but you cannot hear them.

### What's the difference with what should have happened?

the chat should work fine when not deaf

### How do we reproduce this bug?

not shure, I was SG with several damaged organs and got flashbanged

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
can you reproduce this locally? I could not.

**Comment by ItsVyzo** [comment]
Should be fixed by #6857
