### ISSUE TITLE
Xenos can't replace resin nodes. 

### ISSUE THREAD

**Issue by vero5123** [cmss13-devs/cmss13#6169]
### Testmerges

N/A

### Round ID

N/A

### Description of the bug

As a xeno you can't place down resin nodes on top of existing nodes that belong to other hives. Although, putting it nearby works fine and will replace old weeds. 

### What's the difference with what should have happened?

You should be able to place down resin nodes on top of another hives node. 

### How do we reproduce this bug?

1. place down a resin node as a greeno or other hive type. 
2. try and place down a resin node as normal xeno on top of the existing greeno node.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Attack the node.

**Comment by vero5123** [comment]
Even though you can destroy it via a simple attack, I think being able to place a node on top of it should work as well.
