### ISSUE TITLE
Schrapnel unremovable

### ISSUE THREAD

**Issue by Shibouze** [cmss13-devs/cmss13#6198]
### Testmerges

#5401, #6103, #5957, #6148, #6155, #6039, #6150, #6163, #6146, #6178, #5265

### Round ID

21949

### Description of the bug

I could not remove shrapnel with knife.  
"You begin searching your body for shrapnel.
You couldn't find any shrapnel. "
But i still have shrap icon at screen and taking damage when walking.

Shrapnel at left arm, no broken bones. Appears to be after a CAS strike. Admin heal fixed it.

### What's the difference with what should have happened?

Pressing z key to remove schrapnel should work, it dont.

### How do we reproduce this bug?

I dont know how, check the description to try ?

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
You can get embed objects that are not shrapnel (but display as such) in somewhat rare cases. For example hatchet (spawns in hydro) often can stuck in your body. You can see it with examine. To remove it you need to right click yourself and choose verb "yank out object". This may be the actual issue.

**Comment by iloveloopers** [comment]
was it a stuck item instead of shrap? right click on yourself to check then click on yank object

**Comment by dadlips** [comment]
it was indeed shrapnel. I spectated them, saw the shrapnel icon, scanned their health, and saw the shrapnel in their arm.

**Comment by vero5123** [comment]
pain to reproduce.

**Comment by ItsVyzo** [comment]
Cannot reproduce / no new reports/issues about this
