### ISSUE TITLE
Scout can be decaped with a helmet on while cloaked ඞ

### ISSUE THREAD

**Issue by SolaAqua** [cmss13-devs/cmss13#6215]
### Testmerges

#5401,#6103,#5957,#6148,#6155,#6039,#6150,#6146,#6178,#5265,#6212

### Round ID

21980

### Description of the bug

When you are a cloaked scout wearing a decap protection helmet(normal helmet) you are able to be decapitated when invisible .
this only happens while you are invisible might be because it changed you into a human synth who cant fire weapons.
Was tested with sniper and sniper dose not get decaped only scout
This might also help solve it https://github.com/cmss13-devs/cmss13/pull/2978  

### What's the difference with what should have happened?

Not getting your head decapitated

### How do we reproduce this bug?

1.be scout with a normal marine helmet
2.be cloaked and invisible
3.get slashed on your head
4.lose your head
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
you can loose your helmet if you get slashes enought time

**Comment by SolaAqua** [comment]
> you can loose your helmet if you get slashes enough time

not the issue you LOSE your head even with a helmet on while cloaked.it was tested in tdome after i ahelped about this in game.

**Comment by dadlips** [comment]
I can confirm this is more than likely happening because of 'owner.allow_gun_usage'. When the scout cloaks they lose their decap protection, no matter the helmet.

**Comment by vero5123** [comment]
Yup, simple as.

/obj/limb/head/limb_delimb(damage_source)
	var/obj/item/clothing/head/helmet/owner_helmet = owner.head

	**if(!istype(owner_helmet) || !owner.allow_gun_usage)
		droplimb(0, 0, damage_source)
		return**

	if(owner_helmet.flags_inventory & FULL_DECAP_PROTECTION)
		return

	owner.visible_message("[owner]'s [owner_helmet] goes flying off from the impact!", SPAN_USERDANGER("Your [owner_helmet] goes flying off from the impact!"))
	owner.drop_inv_item_on_ground(owner_helmet)
	INVOKE_ASYNC(owner_helmet, TYPE_PROC_REF(/atom/movable, throw_atom), pick(range(get_turf(loc), 1)), 1, SPEED_FAST)
	playsound(owner, 'sound/effects/helmet_noise.ogg', 100)


You get decapitated if you don't have a helmet on or if allow_gun_usage is set to false.

**Comment by vero5123** [comment]
> When you are a cloaked scout wearing a decap protection helmet(normal helmet) you are able to be decapitated when invisible . this only happens while you are invisible might be because it changed you into a human synth who cant fire weapons. Was tested with sniper and sniper dose not get decaped only scout.

It doesn't "change you into human a synth", it's just that the conditional checks for the same thing that is true in non-combat synths. Which is the allow_gun_usage is false, meaning you can't wield guns.
