### ISSUE TITLE
bioscan cant see a part of the new CORSAT map

### ISSUE THREAD

**Issue by gesaf** [cmss13-devs/cmss13#6232]
### Testmerges

#6217 mabye

### Round ID

22014

### Description of the bug

on late game the last xeno devoed and became queen in the upper right quadrent of the new CORSAT map and since i was ghosty when the bioscan came up i saw "no xenos found" so it apears the upper right area is not included in the search of the map

### What's the difference with what should have happened?

the bio scan should be able to see if xenos are in the upper right area of the map

### How do we reproduce this bug?

1. go to upper right area as queen or any xeno dont know if it matters
2. do a bioscan
3. after that it should say something like "no xenos found on planet or shipside"

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Bioscan CAN and WILL give incorrect information at times with a variable between 0 to 2.

not a bug
