### ISSUE TITLE
Abovehead Text Prematurly Disappearing 

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#6242]
### Testmerges

Issue has been ongoing for a loooong time.

### Round ID

Maybe the past 1000+ rounds.

### Description of the bug

Many actions produce text above your character's head such as showing off an object within your hand, using the say "" command, and many emotes. This bug occurs when you use multiple separate ways to produce text above your head. For instance, 
![image](https://github.com/cmss13-devs/cmss13/assets/105765670/f17fa3cd-0c48-4c56-bb00-07f69642c75f)

if you hold an object above your head then type a chat message,
![image](https://github.com/cmss13-devs/cmss13/assets/105765670/95ef044f-fd53-401b-92f7-372b254a1f1a)
and say the chat message just before the hold up object message above your head would disappear naturally, the say "" message above your head seems to be overridden and disappears at the same time as the hold up object message would have thus cutting off the time your say "" message is visible to others around you. Say "" then another say "" command does seem to 'reset' the timer.

### What's the difference with what should have happened?

Although not game crippling, I have had a fair few important medical messages consumed near instantly after holding up what I had in my hand to show other medics what I was using. The latest above head text should 'reset' the timer on all above head text methods since ostensibly, that is what you want to display to people as it was the last thing you did. Also just having text above your head disappear near instantly seems very strange in play.

### How do we reproduce this bug?

I wish I could take a clip to show it off better but this will have to do.
1. Say a message that places text above your head.
2. Just before the timer on the message above your head expires and the text disappears, use the show-held-item verb with an item in your hand.
3. Notice how quickly the above head text for your shown held item disappears.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Duplicate #3215
