### ISSUE TITLE
The USCM Radio Telephone Pack has extremely odd item removal behavior.

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#626]
## Description

When items are placed in the telephone pack, if you do not click directly on the item's sprite when you intend to remove something, a different item entirely is taken from the pack. Also, if you click around the sprite of the first item(left-most in the line), nothing happens.

## Difference between expected and actual behavior

The telephone pack storage should behave in the same way a satchel would. With a satchel, clicking anywhere in the item's designated space removes said item from the satchel into your hand. The problem is most annoying for small or very thin objects like a crowbar since you have to pixel hunt to click on the object to avoid withdrawing something else entirely.

## Steps to reproduce

1.  Place multiple items into the telephone pack.
2.  With a free hand click on the space around an object.
3. Notice the discrepancy between how you remove objects from a telephone pack and a standard satchel.
## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Old known issue born from how the internal transmitter interacts with the basic concept of containers. The most straightforward solution is to overhaul the entire basic concept of containers, but that would take quite some time.

**Comment by nuklearcellphoneg** [comment]
IMO I think an easy solution would be to have the Telephone Pack act exclusively as a backpack,

But when the Telephone pack + Tele Operator Uniform are worn in conjunction(which is the only requirement to wear the pack and use it at the moment afaik), then it gives you a Phone Icon on the HUD(like zooming in, toggling lights, et al)

**Comment by Superwelder** [comment]
Honestly, I would rather have the phone removed entirely from the pack and made into an item that can be stored from the RTOs vendor. Kinda like an RTO specific station bounced radio. The item interaction inside the telephone pack is so bad I have started just not bringing the phone pack anymore. The pack is so rarely used  for the phone and it absolutely can screw you in a tense moment. Large downside for little reward. God forbid you put an injector in there and need it at a moment's notice. Pixel hunting is not what I play RTO for. After sinking in a good chunk of rounds into RTO recently, this is by far my largest grip with the role.

**Comment by nuklearcellphoneg** [comment]
> Honestly, I would rather have the phone removed entirely from the pack and made into an item that can be stored from the RTOs vendor. Kinda like an RTO specific station bounced radio. The item interaction inside the telephone pack is so bad I have started just not bringing the phone pack anymore. The pack is so rarely used for the phone and it absolutely can screw you in a tense moment. Large downside for little reward. God forbid you put an injector in there and need it at a moment's notice. Pixel hunting is not what I play RTO for. After sinking a good chunk of rounds into RTO recently, this is by far my largest gripe with the role.

Sorry if you have, but you tried clicking middle mouse button in while hovering over the pack? Should just auto open it this way
