### ISSUE TITLE
a apc that cant be fixed

### ISSUE THREAD

**Issue by tzTZtzTZqwq** [cmss13-devs/cmss13#6312]
### Testmerges

-

### Description of the bug

o fix the apc the wire needs to be removed
to remove the wire the floor need to be removed
but theres no floor
so the wire cant be removed
so the apc cant be fixed
![b3decc0248f2d65429e8ec2edafca889cc3de1ed](https://github.com/cmss13-devs/cmss13/assets/65105227/be33a49d-7097-47f9-9b8e-113191da6794)
![6ee068431df6f8598f8a1203f42143ad34bd4251](https://github.com/cmss13-devs/cmss13/assets/65105227/a7eac2ea-da88-4087-afdb-ca0040bd2ae0)

### What's the difference with what should have happened?

there should be a floor and wire on that tile so the wire can be removed

### How do we reproduce this bug?

the location of the comms is marked on the img

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by hislittlecuzingames** [comment]
Good first issue

**Comment by Diegoflores31** [comment]
Mapping Issue Tag @Huffie56

**Comment by hislittlecuzingames** [comment]
https://github.com/cmss13-devs/cmss13/pull/6499
