### ISSUE TITLE
Gibber don't work

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#6331]
### Testmerges

N/A

### Round ID

N/A

### Description of the bug

Gibber machine broke. When trying to gib human corpses. Probably for the best since gibbing people is against the rules.

### What's the difference with what should have happened?

Gibber should maybe work.

### How do we reproduce this bug?

1. Try to gib a corpse, it never finishes gibbing.
2. Trying to empty the gibber does not work. The body is now stuck.
3. You can put in a second corpse, which can be removed, but also not gibbed.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
Gibber seems to be perfectly functional, I was unable to reproduce any of the listed issues.

**Comment by vero5123** [comment]
Yes, this is indeed a bug from the looks of it although the fix is pretty trivial. However, i'm not sure if this should be a toggleable admin feature or not.
