### ISSUE TITLE
Handcuffs/Zipties

### ISSUE THREAD

**Issue by Skatuk** [cmss13-devs/cmss13#6347]
### Testmerges

#5957 #6163 #6188 #6225 #6039

### Description of the bug

If your cuffed by handcuffs or zipties and placed onto a bed you can't unbuckle yourself

### What's the difference with what should have happened?

You should be able to unbuckle yourself

### How do we reproduce this bug?

1.Get cuffed
2.Get dragged into a bed while cuffed
3.Press resist
4. Watch as a red circle appears above your head for about 10 seconds and dissapears.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
It's because of the bitflag passed into the do after. Getting your ass kicked by mps and then buckled to a bed applies a floored trait and if the passed in bitflag contains the INTERRUPT_KNOCKED_DOWN interrupt then it will evaluate as false and stop the unbuckling.

**Comment by vero5123** [comment]
good first issue label would go well here.
