### ISSUE TITLE
ARC sprite comes out badly rotated out of the elevator

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#6362]
### Testmerges

none, tested on master 

### Description of the bug

arc comes from elevator with sprite badly rotated, that makes it so that doors are inverted and several visual bugs ,drathek said it is only badly rotated sprite of the main when it  body but it might be more issues with rotating

### What's the difference with what should have happened?

when exiting with doors that apear to be facing south walk out south not north, aka make it work how it works when spawned with wehicle spawner

### How do we reproduce this bug?

1. spawn arc from the elevator
2.use doors
3. look at weard wheel holes
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Of note seems to *only* occur when used via elevator, not via vehicle spawner. It seems only the body is forced 180 degrees in the wrong direction.
