### ISSUE TITLE
Machete self-use will stab yourself instead of cutting flora.

### ISSUE THREAD

**Issue by blackdragonTOW** [cmss13-devs/cmss13#6369]
### Testmerges

#6188: 'Research xenomorph "dissections"' by kiVts at commit 7bfa02d64b #6071: '[V] Sorokyne Strata: fixes and changes .' by Venuska1117 at commit 77b1ffb107 #6304: 'STEEL DIVISON (Re-introduces 200 pop locked tank) [CODE BOUNTY]' by Red-byte3D at commit b51bd40abe #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit c00cb62f5c #5513: 'M5 Camera Gear' by realforest2001 at commit 60fc8bdcbd #6358: 'bump rustg version' by harryob at commit cf4f60d29d #6355: 'ID Mod computer biometrics' by realforest2001 at commit bd4cb15883 #6359: 'Adds CKey to ASRS order staff logs.' by realforest2001 at commit 17886e5828

### Round ID

22482

### Description of the bug

Using your machete on self when next to flora and on help intent stabs yourself. (Tested this with both Hurt Yourself preferences)

### What's the difference with what should have happened?

/obj/item/weapon/sword/machete/attack_self(mob/user) implies that if you use it on self it will clear flora much like how knives can be used to remove shrap.

### How do we reproduce this bug?

1. Create a human next to any flora object
2. Create a /obj/item/weapon/sword/machete/
3. Make sure you're on help intent
4. Use the machete on self
5. --> You will try to stab yourself instead of removing the flora
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by JackieEstegado** [comment]
Cant replicate, can you show in a video how you are doing it?

**Comment by Tyranicranger4** [comment]
You are using the machete on *itself*, not *yourself*, right?

**Comment by blackdragonTOW** [comment]
A fantastic question actually! I am very dumb, when I was reading through the code I assumed that the self refereed to implied the human rather than the self on the machete.  After further testing this does work as intended and I just completely misunderstood the intended use function both in code and in game!
