### ISSUE TITLE
CLF Com Techs don't have Insulated Gloves

### ISSUE THREAD

**Issue by hislittlecuzingames** [cmss13-devs/cmss13#6380]
### Testmerges

#6188 #6071 #6304 #6355 #6363

### Round ID

22507

### Description of the bug

CLF Com Tech ERT doesn't have insulated gloves so when he works on electronics, he zapps himself.

I'd fix it myself, but I will forget as I won't have time to work on this for a lil bit so I wanted to note it incase someone else could do it.
Great first issue bug fix for new coders. 

Worth checking all ERT to assure they all get insulated gloves. 

### What's the difference with what should have happened?

He should have had Insulated Gloves

### How do we reproduce this bug?

1. ERT CLF
2. Be Com Tech Equivilent
3. Notice you don't have insulated gloves

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by vero5123** [comment]
Should be simple to add if you're up for it.

**Comment by vero5123** [comment]
Good first issue label 100%
