### ISSUE TITLE
bug with new human sprites: scoliosis

### ISSUE THREAD

**Issue by HumiliatedGoblin** [cmss13-devs/cmss13#6399]
### Testmerges

its probably https://github.com/cmss13-devs/cmss13/pull/6073

### Round ID

22555

### Description of the bug

makes you look like a t-rex if you remove the jacket of operations uniform. guessing its to do with the way the torso and legs are mis-aligned.
![image_2024-06-08_145731988](https://github.com/cmss13-devs/cmss13/assets/87675952/11057dc5-739d-4a8e-b2a4-0d0a7435bb8a)
i didnt try it without the jacket because the round restarted too fast, but that could also be the problem.

### What's the difference with what should have happened?

my drip x_x

### How do we reproduce this bug?

1. be io
2. wear service jacket and operations uniform
3. remove shirt of operations uniform
4. oh god its hideious

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Not a bug

**Comment by ItsVyzo** [comment]
Not a bug
