### ISSUE TITLE
placing a table on a tile with a flipped table deletes one of the tables

### ISSUE THREAD

**Issue by restedwaves** [cmss13-devs/cmss13#6428]
### Testmerges

#6071: '[V] Sorokyne Strata: fixes and changes .' by Venuska1117 at commit 77b1ffb107 #6304: 'STEEL DIVISON (Re-introduces 200 pop locked tank) [CODE BOUNTY]' by Red-byte3D at commit b51bd40abe #6355: 'ID Mod computer biometrics' by realforest2001 at commit bd4cb15883 #6383: 'Replaces the ARC interior & ARC tweaks' by Zonespace27 at commit c9e49da969 #6363: 'First Drop Protections: Gas and Static Turrets' by Drulikar at commit bb9a7df8e2 #6388: 'gayons' by 567Turtle at commit 4f9151f1ba #6334: 'Xenomorph Endgame' by Git-Nivrak at commit d3db3d792f #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 9f4c76c456 #6392: 'Adds in-game bug reports without needing a GitHub account' by vero5123 at commit 917d68f10e

### Round ID

22591

### Description of the bug

when placing a tan/cream table down on a tile with another tan/flipped table the flipped one is deleted.
I have not tested this with metal tables

### What's the difference with what should have happened?

honestly it's likely not supposed to be possible to place but i wanted to make a flipped table corner.

### How do we reproduce this bug?

1.Flip table
2.try to place table

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Tested on live - could not reproduce.
