### ISSUE TITLE
Chatbox becomes a UI error

### ISSUE THREAD

**Issue by GrrrKitten** [cmss13-devs/cmss13#6454]
### Testmerges

BYOND Version: 515.1640 Server revision compiled on: 2024-06-12T17:38:29+00:00 Master commit: a3b7bc4f4388bf291ccfeceac7d471961c224b45 The following pull requests are currently test merged: #6071: '[V] Sorokyne Strata: fixes and changes .' by Venuska1117 at commit 77b1ffb107 #6304: 'STEEL DIVISON (Re-introduces 200 pop locked tank) [CODE BOUNTY]' by Red-byte3D at commit b51bd40abe #6355: 'ID Mod computer biometrics' by realforest2001 at commit bd4cb15883 #6383: 'Replaces the ARC interior & ARC tweaks' by Zonespace27 at commit 4df6e6ea75 #6363: 'First Drop Protections: Gas and Static Turrets' by Drulikar at commit bb9a7df8e2 #6388: 'gayons' by 567Turtle at commit 4f9151f1ba #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 731e2bab70 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 9f4c76c456 #6392: 'Adds in-game bug reports without needing a GitHub account' by vero5123 at commit 86837a2768

### Round ID

22622

### Description of the bug

nt application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
 Error: Access is denied.

   at isStyleSheetLoaded (http://127.0.0.1:50966/browseroutput.html:247:7)
   at node.onload (http://127.0.0.1:50966/browseroutput.html:325:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)

TypeError: Object doesn't support property or method 'flushQueue'
   at Byond.subscribe (http://127.0.0.1:50966/browseroutput.html:221:5)
   at at (http://cdn.cm-ss13.com/live/73/asset.73152f1db7e41e457e9937398d8d95ed.js:596:495)
   at Anonymous function (http://cdn.cm-ss13.com/live/73/asset.73152f1db7e41e457e9937398d8d95ed.js:596:781)
   at Anonymous function (http://cdn.cm-ss13.com/live/73/asset.73152f1db7e41e457e9937398d8d95ed.js:569:9)
   at Anonymous function (http://cdn.cm-ss13.com/live/73/asset.73152f1db7e41e457e9937398d8d95ed.js:1:14)
   at Global code (http://cdn.cm-ss13.com/live/73/asset.73152f1db7e41e457e9937398d8d95ed.js:1:2)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {}

Weyland-Yutani (c) 2100-2182 Building better user interfaces. 

![image](https://github.com/cmss13-devs/cmss13/assets/158611449/de8e457b-fb51-4a11-9e9c-7746cfa2e423)

### What's the difference with what should have happened?

maybe my chat should load, but for further details, I have to fix-chat a lot at round start from it just not loading, but it giving me a UI error is brand new

### How do we reproduce this bug?

1. Join round
2. Look at chatbox
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
All the isStylesheetLoaded errors as far as I know have been resolved by installing IE11. There's at least three or four issues of the same thing here and on TG. See https://github.com/cmss13-devs/cmss13/issues/4865#issuecomment-1798861032

**Comment by ItsVyzo** [comment]
Duplicate - see above.
