### ISSUE TITLE
Marines can use drawing hotkeys to drop weapons when stunned by knockdowns.

### ISSUE THREAD

**Issue by joookschad** [cmss13-devs/cmss13#6473]
### Testmerges

N/A

### Description of the bug

If you get knocked down and try to pull out a holstered gun you will drop it onto the ground - and there is also no cooldown on drawing weapons which can lead to someone pressing E 3 times resulting in them losing all of their weapons. Very cool.

### What's the difference with what should have happened?

You shouldn't be able to draw weapons while stunned

### How do we reproduce this bug?

1. Get CC'd by a knockdown(such as Vampire Tail Jab or Defender Tailswipe
2. Press E to draw your weapon

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Should be resolved with https://github.com/cmss13-devs/cmss13/pull/6569 but let us know if its still possible.
