### ISSUE TITLE
Cannot Award Medals as CO

### ISSUE THREAD

**Issue by Harrysno** [cmss13-devs/cmss13#6488]
### Testmerges

#6071, #6304, #6355, #6363, #6388, #6334, #6392, #6461, #6400

### Round ID

22677

### Description of the bug

All was normal towards the end of a regular Kutjevo round when I went to hand out a few medals to some of the marines. However, upon hitting the "Award Medal" button it prompted me with "You must have an authenticated ID Card to award medals." which seems out of place considering CO is the only role that **can** award medals. I haven't looked to see if it's persistent across rounds or if it was simply a one-off, but figured it'd be best to get it out there.

![uhohbuggu](https://github.com/cmss13-devs/cmss13/assets/160363875/dfc65198-06cc-43ed-b8e2-63d02e48ac84)

### What's the difference with what should have happened?

When clicking the "Award Medal" prompt it should ask what type of medal the CO would like to award, not outright deny the ability to hand out a medal.

### How do we reproduce this bug?

1. Open up the Command Tablet Menu or Shipside Console Menu.
2. Click on the "Give Medal" button to open the Medals Prompt with medal recipient recommendations.
3. Click the "Award Medal" button and watch as it denies you access!

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
![image](https://github.com/cmss13-devs/cmss13/assets/48099872/4df03d89-af16-4285-9a9b-1b3cd444a7ad)
 in #6411. So Silly
