### ISSUE TITLE
Pyro cannot be used without the fuel backpack anymore

### ISSUE THREAD

**Issue by ondrej008** [cmss13-devs/cmss13#6502]
### Testmerges

#6071, #6304, #6363, #6388, #6334, #6392, #6461, #6400, #6039

### Round ID

22689

### Description of the bug

#6437 is at fault

The PR does not mention that it removes this feature which has been around for several years.

### What's the difference with what should have happened?

You should be able to put flamer tanks in the flamer tank without a fuel backpack, or the PR should be changed to indicate that this feature has been removed from the game permanently.

### How do we reproduce this bug?

1. Go pyro spec
2. Get pyro flamer tank
3. Try to put it in the flamer
4. "The Broiler-T feed system cannot be reloaded manually."

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
That is definitely a bug , you Have to be able to manual reload in order to use custom tanks
