### ISSUE TITLE
Ghost lights

### ISSUE THREAD

**Issue by Onetoughcreampuff** [cmss13-devs/cmss13#6515]
### Testmerges

#6071, #6388, #6334, #6400

### Round ID

22723

### Description of the bug

As a ghost CMP I had visible light which players could see. I dont actually know what caused it, nor does it seem to be reproducible so I'm leaving this here as evidence this bug exists because there was more than one people in the video who had ghost light (look for the ghosts around the queen for example), which probably means something can trigger it again.

https://www.youtube.com/watch?v=2f1OsVQpJVE

### What's the difference with what should have happened?

To not have a light source as a ghost.

### How do we reproduce this bug?

1. Be CMP with armour light on
2. Head to cyro
3. ???
4. Ghosts has light

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Biolock1** [comment]
I have seen this issue extending to numerous humans, and does not seem to reflect whether or not someone had a flashlight on during their life, or even if they had a source of light on them at all.

**Comment by Steelpoint** [comment]
I've heard some people mention it occurs when the King uses their shield ability??? But as others have said it only occurs on the Almayer only, I've never seen it occur before hijack.

**Comment by Drulikar** [comment]
Let us know if this is still a problem with the recent changes to #6334
