### ISSUE TITLE
CMB Ship cannot fly back to CMB space station.

### ISSUE THREAD

**Issue by hislittlecuzingames** [cmss13-devs/cmss13#6530]
### Testmerges

I already logged off. 

### Round ID

22749

### Description of the bug

CMB Shuttle cannot fly back to the space station. 

### What's the difference with what should have happened?

The CMB police squad should be able to fly of their own accord back to CMB station. 

The only destinations that appear are parts of the Almeyer. 
![image](https://github.com/cmss13-devs/cmss13/assets/142365554/54daf8be-0fa9-4764-a4b4-559a27cca0a9)

### How do we reproduce this bug?

1. Be CMB ERT for Req Black Market stuff
2. Use ship flight controlls
3. Don't be able to fly away. 
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
CMB don't get a home station spawned when they spawn.

**Comment by ItsVyzo** [comment]
After speaking with @harryob, concluded this is not replicable. 

> people just get their ids fucked around or get lost and think its broken
