### ISSUE TITLE
Secondary Flamer Hardpoint (Tank) sometimes doesn't fire properly.

### ISSUE THREAD

**Issue by MPhonks** [cmss13-devs/cmss13#6536]
### Testmerges

#6071: '[V] Sorokyne Strata: fixes and changes .' by Venuska1117 at commit 77b1ffb107 #6388: 'gayons' by 567Turtle at commit 4f9151f1ba #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 5de79d5ca1 #6400: 'Adds Sunsets to Roundstart, adds Sunrises to Marine Victories, and Survs can hear Evo Announcement Screeches now' by GrrrKitten at commit 2927345720 #6308: 'Hostile Survivor Rework' by Steelpoint at commit bf51f9e551 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 29745fcac6

### Round ID

22759

### Description of the bug

Firing with the secondary flamer hardpoint of the tank sometimes at specific angles sometimes doesn't work and results in a single tile of flames.

### What's the difference with what should have happened?

The secondary flamer hardpoint has a few more tiles of range attributed to it than just... one.

### How do we reproduce this bug?

1. Get a tank.
2. Get a secondary flamer.
3. Try to shoot a few angles.
...
Profit.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Doubleumc** [comment]
Am unable to replicate. Do you recall if there were any obstacles between the tank and the target? Was the tank actively moving during firing?

If you could describe the specific angles or get a screenshot that would be helpful.
