### ISSUE TITLE
almayer nuked but not a draw

### ISSUE THREAD

**Issue by zzzmike** [cmss13-devs/cmss13#6580]
### Testmerges

it didn't display until it was too late but next round had #6071: '[V] Sorokyne Strata: fixes and changes .' by Venuska1117 at commit 77b1ffb107 #6388: 'gayons' by 567Turtle at commit 4f9151f1ba #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 0a23f6e503 #6400: 'Adds Sunsets to Roundstart, adds Sunrises to Marine Victories, and Survs can hear Evo Announcement Screeches now' by GrrrKitten at commit 2927345720 #6308: 'Hostile Survivor Rework' by Steelpoint at commit bf51f9e551 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 6f1869d83e

### Round ID

22827

### Description of the bug

When self destruct goes off, should be a draw, but this round registered as xeno major

### What's the difference with what should have happened?

should end as draw

### How do we reproduce this bug?

1. self destruct almayer during hijack
2. see if it's a draw

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
SD doesn't set the result to a draw; its just if https://github.com/cmss13-devs/cmss13/blob/4fff70a7c6e0d786dd86b6c3595ba5e9e60a3c2b/code/game/gamemodes/cm_process.dm#L193-L220 has a count of 0 humans and 0 xenos, then it is a draw. SD destroys all living mobs on the ship z level.

**Comment by zzzmike** [comment]
Ah okay thanks. Not sure of the player counts on other areas, might as well close this rather than logdive on something that might not be a bug.
