### ISSUE TITLE
Adding language trait for multiple characters requires a game restart

### ISSUE THREAD

**Issue by Maciekkub** [cmss13-devs/cmss13#660]
## Description
If you decide to setup multiple characters during one sitting and some of them are supposed to be speaking additional languages, you will have to restart your game to apply additional languages to each subsequent character.

## Difference between expected and actual behavior
If you apply additional language to character #2 let's say, and then switch over to character #3 you'll be met with the following screen forcing you to restart the client to apply additional languages.
![image](https://user-images.githubusercontent.com/30427887/178346297-426caa1c-ddb3-483f-9d2d-9c9cc93fa113.png)

## Steps to reproduce
1.  Apply a secondary language to a character
2.  Switch to another character
3.  You cannot apply languages to any other characters until you restart the client. 

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
probably been an issue since the 1 language limitation was added

**Comment by TopHatPenguin** [comment]
Can confirm that this is still an issue for players currently.
