### ISSUE TITLE
XO cant use MP gear

### ISSUE THREAD

**Issue by TheManWithNoHands** [cmss13-devs/cmss13#6605]
### Testmerges

none

### Description of the bug

XO has the option to chose an MP belt, but they dont have the skill to use the stun baton or disabler gun.
Thats not rigth.

### What's the difference with what should have happened?

They shouldnt have the option to take the MP belt or have the skill to use the belt.
But non of the two options are the case.

### How do we reproduce this bug?

1.Take Disable
2. Try using it
3. fail at using it

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Tested on Live - Works fine

**Comment by TheManWithNoHands** [comment]
> Tested on Live - Works fine/Cannot reproduce

Yeah, i fixed it already :p 
https://github.com/cmss13-devs/cmss13/pull/6781

**Comment by ItsVyzo** [comment]
ohhh that explains alot! HAHAHA
