### ISSUE TITLE
cannot push closed crates

### ISSUE THREAD

**Issue by coldironwarrior** [cmss13-devs/cmss13#6621]
### Testmerges

#6334, #6400, #6308, #6039, #6248, #6568

### Round ID

multiple, 22933-22935 for sure

### Description of the bug

closing a crate and then standing behind it to push it didn't work. the crate acted as if anchored and it had to be pulled to be moved.

### What's the difference with what should have happened?

to be able to push the crate

### How do we reproduce this bug?

1. close a crate
2. stand behind it
3. run at it to push it
4. 4. nothing happens

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Fixed in https://github.com/cmss13-devs/cmss13/pull/6248/commits/9582c86272c1762b5506998bcb83f6783ca0f52b
