### ISSUE TITLE
Alt clicking on a ghost marine brings up a massive list of sprites

### ISSUE THREAD

**Issue by Wisemonster** [cmss13-devs/cmss13#6627]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 18cfcab3cd #6400: 'Adds Sunsets to Roundstart, adds Sunrises to Marine Victories, and Survs can hear Evo Announcement Screeches now' by GrrrKitten at commit 2927345720 #6308: 'Hostile Survivor Rework' by Steelpoint at commit bf51f9e551 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 62d1be1e65 #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit 7e583221b0 #6594: 'Ports "Adds a Chat Reliability Layer"' by Git-Nivrak at commit 9b0717ad64 #6568: 'Chemical simulator TGUI' by kiVts at commit f353b22c70

### Round ID

Round ID: 22949

### Description of the bug

Alt clicking on a ghost brings up a massive list of sprites.

### What's the difference with what should have happened?

I'd assume only 1 sprite is supposed to show up, not a massive list of them.

### How do we reproduce this bug?

1. Join a round as an observer
2. Alt click yourself
3. See a massive list of sprites appear

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Tested on Live - Cannot reproduce.

Alt Clicking shows ALL sprites on the turf you click on.
