### ISSUE TITLE
Picking up dropped predator wrist-blade forces it to stay in your hand

### ISSUE THREAD

**Issue by Foxtrot13224** [cmss13-devs/cmss13#6640]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 18cfcab3cd #6400: 'Adds Sunsets to Roundstart, adds Sunrises to Marine Victories, and Survs can hear Evo Announcement Screeches now' by GrrrKitten at commit 2927345720 #6308: 'Hostile Survivor Rework' by Steelpoint at commit bf51f9e551 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 370c1d53f8 #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit d874f97e11 #6594: 'Ports "Adds a Chat Reliability Layer"' by Git-Nivrak at commit 9b0717ad64 #6568: 'Chemical simulator TGUI' by kiVts at commit 5280d571c9

### Round ID

22946

### Description of the bug

A predator died with their wrist-blades extended. When a research cut off the predator's arm to get the wrist-bracers, the blade dropped too. When the blade was picked up by me (Another predator), I was unable to drop it or sheathe it, and had to get an admin to remove it via chopping off my arm and giving me a new one.

### What's the difference with what should have happened?

Wrist blade should've either auto-retracted on death or have been made drop-able once disconnected from the wrist-bracers.

### How do we reproduce this bug?

1. Have a predator die with wrist-blades extended.
2. Chop off one of their arms.
3. Attempt to pickup dropped wrist-blade.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by private-tristan** [comment]
NO_DROP and its consequences.

**Comment by ItsVyzo** [comment]
wrist blades should probably have DELONDROP in addition to NO_DROP
