### ISSUE TITLE
Overhead emotes in chatbox despite not being visible to the player.

### ISSUE THREAD

**Issue by MistChristmas** [cmss13-devs/cmss13#6666]
### Testmerges

#6334 #6400 #6308 #6248 #6633 #6568

### Description of the bug

Overhead emotes go through walls? Or maybe just the Medical walls. Or maybe just the Medical Overhead emotes go through walls.

### What's the difference with what should have happened?

![image](https://github.com/cmss13-devs/cmss13/assets/7815982/85c5342d-4330-4e2a-ad93-108ca54874cb)
You shouldn't see emotes in the chatbox you can't actually see.

### How do we reproduce this bug?

1. Stand in the hallway outside an OR but with the Surgical table in view but not visible with no windows into the OR
2. Have someone performing surgery on someone in an OR.
3. Have the overhead emotes visible in chat but not appear in the empty blackness.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by GrrrKitten** [comment]
Still have zero clue how this could be happening since in the code thats currently live its just a 		

var/list/viewers = get_mobs_in_view(7, user)

for visual only emotes

**Comment by GrrrKitten** [comment]
found the issue, will be resolved with the next major commit to #6633

**Comment by Drulikar** [comment]
(Technically not fixed still even in the PR introducing the bug)
