### ISSUE TITLE
queen can carry/wave around the new flag

### ISSUE THREAD

**Issue by zzzmike** [cmss13-devs/cmss13#6749]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit e04d971cbe #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit fb91839b39 #5829: '(EVENT) Cortical Borers' by realforest2001 at commit 9c9dfb571c #6400: 'Adds Sunsets to Roundstart, adds Sunrises to Marine Victories, and Survs can hear Evo Announcement Screeches now' by GrrrKitten at commit 2927345720 #6737: 'Planted flag bugfix and warcry removal' by Zonespace27 at commit 43f33f81e0 #6308: 'Hostile Survivor Rework' by Steelpoint at commit 423ba8189f #6742: 'Scout Cloak fix' by kiVts at commit 8e33dcdc45 #6745: 'Sound range ' by kiVts at commit 81428cd37f

### Round ID

23115

### Description of the bug

queen can carry/wave around the new flag https://github.com/cmss13-devs/cmss13/pull/6492 - I assume this isn't intended?

### What's the difference with what should have happened?

Queen shouldn't be able to wave the United Americas flag... right?

### How do we reproduce this bug?

I assume you follow the same steps to carry/wave the flag as a human, except do it as queen

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
admin event
