### ISSUE TITLE
Burrowers can create tunnels under LZ turrets.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#6773]
### Testmerges

N/A

### Round ID

23160

### Description of the bug

![image](https://github.com/user-attachments/assets/8e89c9b4-1baa-48e4-ae66-4063ba3e34a3)
Tunnel under da turret.

### What's the difference with what should have happened?

You cannot see this tunnel unless you rightclick the turret. This should not be possible.

### How do we reproduce this bug?

1. I merely found the aftermath of this.
2. I assume you build a tunnel under a collapsed LZ turret.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
https://github.com/cmss13-devs/cmss13/pull/6871
