### ISSUE TITLE
APCs not properly on the wall they should be.

### ISSUE THREAD

**Issue by MistChristmas** [cmss13-devs/cmss13#6792]
### Testmerges

#6686, #6295, #6248, #6334

### Description of the bug

![Screenshot 2024-07-26 010739](https://github.com/user-attachments/assets/f8ca81e7-a951-43f8-a1e8-bbfd904dcaba)
They float.
EDIT:
![image](https://github.com/user-attachments/assets/eae17c53-7ab6-426c-abb7-eee2a518d713)
They also do the funny with Air Alarms.
### What's the difference with what should have happened?

It shouldn't be floating off the wall.
Dunno how many other APCs this affects. But this is the most noticable one due to being a well trafficed area in the Alaymer

### How do we reproduce this bug?

1. Look at said APC.
2. Wonder how many other APCs this affects.
3. Panic as it affects air alarms we still have for some reason.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Venuska1117** [comment]
woops i forgot to fix that APC, i used this specific one to test sprite directions.

**Comment by MistChristmas** [comment]
> woops i forgot to fix that APC, i used this specific one to test sprite directions.
> 
> and that Air Alarm is not from my PR, but i can fix it too.

![image](https://github.com/user-attachments/assets/d3b96269-620d-4b3e-9d83-38a93809c37f)
Also the terminal cables are the wrong dir. Should be the other way. I think this applies to some but not all of the APCs? I dunno didn't check that hard.

**Comment by Venuska1117** [comment]
> > woops i forgot to fix that APC, i used this specific one to test sprite directions.
> > and that Air Alarm is not from my PR, but i can fix it too.
> 
> ![image](https://private-user-images.githubusercontent.com/7815982/352701665-d3b96269-620d-4b3e-9d83-38a93809c37f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjAyOTksIm5iZiI6MTcyMjExOTk5OSwicGF0aCI6Ii83ODE1OTgyLzM1MjcwMTY2NS1kM2I5NjI2OS02MjBkLTRiM2UtOWQ4My0zOGE5MzgwOWMzN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjdUMjIzOTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJhZDk0MTYyZWZjYjdjOGRhMmE5YWNiNjBiNDY4MjM2MzM5NDQ0ZmJhOWRkZjZhYTkzZjFkMzA5MjMyMDQwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M59lDuyX25zgby0MaeTaarT_bEYT_FsU_TREpx2xoUI) Also the terminal cables are the wrong dir. Should be the other way. I think this applies to some maybe most maybe all of the APCs? I dunno didn't check that hard.

this issue existed before i did APC changes, i can try fix this.
