### ISSUE TITLE
Dual Wielding

### ISSUE THREAD

**Issue by 1845292047** [cmss13-devs/cmss13#68]
Reporting a bug real quick regarding dual weilding. So when i tac reload any dual wielded weapons it bugs out and wont reload, like itll say there something inside the gun loaded when there isn't. and it wont unload whatever is inside, it'll just cock the gun over and over. Not sure if there is a way to fix this? I've tried relogging and it doesnt work either. Have to get a whole new weapon which defeats the purpose basically.

**Comment by nuklearcellphoneg** [comment]
Tried testing a bit, works with the old style of dual wielding, but it doesn't when you alternate as far as I can tell; I assume it's not that gun's turn, prolly unloads the proper hand but attempts to put the mag into the already loaded gun, since it's that gun's 'turn' to fire
