### ISSUE TITLE
Xeno ERT Distress is Prime instead of Ferals

### ISSUE THREAD

**Issue by Randomplayer2or3** [cmss13-devs/cmss13#6829]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit f69b5c5dcd #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, allow LAZ for CAS inside most structures, Xenos can now weed everything except LZ's and surrounding of LZ's.' by Venuska1117 at commit 9d5e6d4658 #5829: '(EVENT) Cortical Borers' by realforest2001 at commit b2558cb2ad #6191: '(WIP) Project ARES: AI Service Technician' by realforest2001 at commit b016069809 #6650: 'Comtech Stuff' by Git-Nivrak at commit 6bf15b8615 #5265: '(WIP) Paperwork Prefabs' by realforest2001 at commit 991981d957

### Round ID

23298 (and another round i forgot the id for)

### Description of the bug

Apparently the USS Viress ERT Xenos are Prime (Normal Hive aglined) instead of Ferals (the destroy everything xenos). 
This issue also happened in another round, though at first deadchat believed it to be an admin event

### What's the difference with what should have happened?

Xeno faction should be Ferals instead of Prime

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
There are two different XRTs, one is Feral, second is Normal hive aligned. Also I think all ERTs are admin approved atm but not sure.

**Comment by ItsVyzo** [comment]
Two different ERTs exist. Not a bug.
