### ISSUE TITLE
Shotgun Sentires has strange knockback ish

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#6854]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit f69b5c5dcd #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, allow LAZ for CAS inside most structures, Xenos can now weed everything except LZ's and surrounding of LZ's.' by Venuska1117 at commit 9d5e6d4658 #5265: '(WIP) Paperwork Prefabs' by realforest2001 at commit 991981d957 #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit e947b927db #6821: 'Shrapnel smooth movement' by Doubleumc at commit f8fca5f27e #6783: 'New "Bulky" computers, small bug fixes also related to computers, addition of altitude controller to the CIC' by LC4492 at commit 71f595f697 #6712: 'Use DVIEW' by Doubleumc at commit f4b53dd614 #6692: 'Use RANGE_TURFS' by Doubleumc at commit 834383bfa0 #6682: 'Hugged changes' by zzzmike at commit 901f664a71 #6671: 'Successful AA interceptions now destroy the hijacked shuttle and end the round' by blackdragonTOW at commit 2a5bbd200b #6652: 'autoclimbable handrails on harm intent' by cuberound at commit 7952d21d5d

### Round ID

23336

### Description of the bug

pounce marine behind a shotgun sentry (from infront of it)
get shotgunned

Note that, in the clip, the second shot was from the MOU marine to the southeast, not the shotgun turret

https://github.com/user-attachments/assets/7b8f41a7-d547-4f8c-8ad3-70b1a6ba8b40

![image](https://github.com/user-attachments/assets/6f36b750-842a-4633-a51c-7b93658cf954)

### What's the difference with what should have happened?

Pounce marine from behind a shotgun sentry
Shotgun sends me away from where it's pointing

### How do we reproduce this bug?

1. shotgun sentry
2. pounce
3. stunned AWAY from it???
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
#7045 clearly depicts the issue. Will close this since #7045 is more clear/accurate, though feel free to reopen if you believe this should remain open. @private-tristan
