### ISSUE TITLE
Ghost Toggling zoom. Switching to follow another player allows you to zoom out again. 

### ISSUE THREAD

**Issue by MistChristmas** [cmss13-devs/cmss13#6889]
### Testmerges

#6334 #6071 #6248 #6712 #6692 #6682 #6652 #6860 #6561 #6821

### Description of the bug

Pretty much title. Be a ghost. Hit the zoom. Then follow someone zoom again, And you're extra zoomed out.

### What's the difference with what should have happened?

Probably  shouldn't zoom out so much it lags, and following another player shouldn't allow for the toggle zoom to think you haven't already zoomed out

### How do we reproduce this bug?

1.Toggle Zoom
2. Follow some random marine
3. Toggle Zoom Again
4. Lag and see the 4th Dimension
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by RenaRenaRe** [comment]
The game already has 3 zoom levels, it was added by https://github.com/cmss13-devs/cmss13/pull/5987. Are you saying you are reaching 4+ zoom levels? Or are you mistaking the third one for a bug?

**Comment by Git-Nivrak** [comment]
Can't reproduce most likely just related to the above ^

**Comment by MistChristmas** [comment]
I see. I'm just an idiot. Yeah it's the third level of zoom as intended that I have not noticed for... however long I started playing last. Cloooosing.
