### ISSUE TITLE
Grenade casings count empty space in reagent containers

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#690]
## Description
I was making nades that extinguish marines on fire as OT, it was the M40, and needed to insert:

15u water, 15u water, 15u fluourosurfactant, 15u kelo, 15u derma, 15u leoporazine.

I inserted a bottle, 15u fluouro, 15u kelo, 15u derma, 15u leoporazine, (60u)
I inserted a container of 15u water
I inserted a container of 15u water- won't fit.

## Difference between expected and actual behavior
I could maybe workaround this assuming droppers work inside nades, or I can find some other containers(maybes cigs work doubt it), but as the nade needs to combine water + fluouro as well as 15u water to inject into the foam, and so needs two separate water containers so it isn't all gone due to the reaction, you can't finish this nade using all 90u.

## Steps to reproduce
Try to make an M20 need containing the following 90u of reagents:
15/15/15 kelo/derma/leoporazine, 15/15 Fluorosurfactant/Water, 15 Water

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Intended behaviour.

**Comment by nuklearcellphoneg** [comment]
Is there a work around?
