### ISSUE TITLE
Research: Can't Relate in Conflicting Properties

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#6919]
### Testmerges

None relevant 

### Description of the bug

You are blocked from relating in properties that would cancel out other ones in the chemical.

### What's the difference with what should have happened?

You shouldn't be blocked, sometimes being able to relate something in that squashes a different property is useful. You are also blocked from relating the conflicting property over the property it's conflicting with.

### How do we reproduce this bug?

1. Make anything with TXC1
2. Grab Tricord, try to relate ATX into the chemical
3. You aren't even allowed to select ATX, even if you're trying to replace the TXC

1. Get a chemical with two bad properties you want to squish, IE: BNM5 CDT3 HMR1
2. Try to relate HMG3 from iron onto CDT3 to squash HMR in the same move (it conficts)
3. This should produce BNM3 HMG2 but is blocked instead.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This is not a bug. Just how research currently works.
