### ISSUE TITLE
hugged status mysteriously disappeared

### ISSUE THREAD

**Issue by zzzmike** [cmss13-devs/cmss13#6926]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 8d2cc8fb83 #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, allow LAZ for CAS inside most structures, Xenos can now weed everything except LZ's and surrounding of LZ's.' by Venuska1117 at commit 817ed55a47 #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit f3201d3bcd #6682: 'Hugged changes' by zzzmike at commit 901f664a71 #6860: 'Mentor New Player Markers' by realforest2001 at commit f69c2c4055 #6855: 'Non folding plasteel barricade' by Blundir at commit d277c0e46f

### Round ID

23460

### Description of the bug

Elijah Gardner got hugged planetside near round end, then the hugged/infected status disappeared after like 3 seconds or something, around the time they ghosted? (they did not get surgery) They had to get rehugged later. Sent an adminhelp to see if it was somehow staff fuckery, seems it was not.

### What's the difference with what should have happened?

Status should've stayed put

### How do we reproduce this bug?

NO idea. But I would get someone with access to check the logs - I assume getting hugged is logged...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Randomplayer2or3** [comment]
It's the magic of Anti-Parasitic stim, not a bug.

**Comment by zzzmike** [comment]
> It's the magic of Anti-Parasitic stim, not a bug.

IIRC I saw nothing in their bloodstream but I'm not 100% so I'll close it and open something else if needed later, thanks
