### ISSUE TITLE
CL Surv Prefixes Bugged

### ISSUE THREAD

**Issue by thevandie** [cmss13-devs/cmss13#6935]
### Testmerges

https://github.com/cmss13-devs/cmss13/pull/6334
https://github.com/cmss13-devs/cmss13/pull/6071
https://github.com/cmss13-devs/cmss13/pull/6248
https://github.com/cmss13-devs/cmss13/pull/6682
https://github.com/cmss13-devs/cmss13/pull/6860
https://github.com/cmss13-devs/cmss13/pull/6855

### Description of the bug

CL Survs no longer have paygrades based off of the player's CL hours. They are now all junior executives.

This is unrelated to certain roles which force you into a certain paygrade, such as Hybrisa where the Corporate survs are all normal executives.

(I suspect this was created by the "rank experiment" pr, the one that added a bunch of different ranks for different playtimes)

### What's the difference with what should have happened?

They should be based off of the player's CL hours. (Executive for 25+ hours, Senior Executive for 70+, etc).

### How do we reproduce this bug?

1. Have over 25 hours in CL
2. Select Corporate Survivor and ready up for Survivor
3. Shift Click Yourself
4. Junior Executive
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
This seems to not be the case anymore.
