### ISSUE TITLE
Spearhead Sprite Attachments

### ISSUE THREAD

**Issue by thevandie** [cmss13-devs/cmss13#6950]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 8d2cc8fb83 #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, allow LAZ for CAS inside most structures, Xenos can now weed everything except LZ's and surrounding of LZ's.' by Venuska1117 at commit 817ed55a47 #6248: 'New Map: LV-759 Hybrisa Prospera' by Zenith00000 at commit f3201d3bcd #6682: 'Hugged changes' by zzzmike at commit 901f664a71 #6860: 'Mentor New Player Markers' by realforest2001 at commit f69c2c4055 #6855: 'Non folding plasteel barricade' by Blundir at commit d277c0e46f

### Round ID

23512

### Description of the bug

The spearhead revolver is no longer accurate when placing attachments on it, specifically the top rail attachment.
![image](https://github.com/user-attachments/assets/25ccc916-91a8-487c-b47b-401bd64d382f)

### What's the difference with what should have happened?

It should be shifted down a bit, so it's actually on the top of the gun.

### How do we reproduce this bug?

1. Spawn a Spearhead Revolver
2. Attach a Flashlight/Sight/Whatever toprail attachment to it
3. Hovering
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Blundir** [comment]
https://github.com/cmss13-devs/cmss13/pull/6649

**Comment by thevandie** [comment]
oh you fix it there? k
