### ISSUE TITLE
Smart pack abilities can be used while dead

### ISSUE THREAD

**Issue by TheGamerdk** [cmss13-devs/cmss13#6956]
### Testmerges

N/A

### Round ID

Multiple

### Description of the bug

You can use synth smart pack abilities (like repair and protection mode) while dead, via the action buttons top left 

### What's the difference with what should have happened?

You shouldn’t be able to use them 

### How do we reproduce this bug?

1. Be synth with charger smart pack
2. Die
3. Use repair mode and witness yourself be repaired (not revived)

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ansekishokuu** [comment]
PR #7460 should close this issue when its merged.
