### ISSUE TITLE
Health status check bug.

### ISSUE THREAD

**Issue by RedStar929** [cmss13-devs/cmss13#699]
## Description
Issue with the help inteck click health status report about you.

## Difference between expected and actual behavior
Basically i expect to see red words of damage on my body parts, warnings about bleeding and fractures. If everything fine it should show is blue OK. BUT in my case its aalways blue OK no matter what damage or wounds you have. Staff member asked me to make report.
So i knifed my arms and left leg and as you can see i got yellow hp, blood under me, and bleeding icon
[<a href="https://im.ge/i/FuNKlT"><img src="https://i.im.ge/2022/07/18/FuNKlT.md.png" alt="FuNKlT.png" border="0" /></a>](url)
This is how shift-click or inspect works
[<a href="https://im.ge/i/FuNVic"><img src="https://i.im.ge/2022/07/18/FuNVic.th.png" alt="FuNVic.png" border="0" /></a>](url)
And this is what i got from health check
[<a href="https://im.ge/i/FuPM0F"><img src="https://i.im.ge/2022/07/18/FuPM0F.th.png" alt="FuPM0F.png" border="0" /></a>](url)

Also sometimes it gets little tired and stops showing some bodyparts at all, so here i only have 5 bodyparts.
[<a href="https://im.ge/i/FuPIvf"><img src="https://i.im.ge/2022/07/18/FuPIvf.th.png" alt="FuPIvf.png" border="0" /></a>](url)

## Steps to reproduce
I sadly cought it suddenly and have no idea how. No idea if someone else has it. Also it sticks from round to round. Tried to restart, relog, etc etc, nothing changed.
Please send help its a bit hardcore to play like this.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
I have tried and failed to replicate this issue. I often use shift+click to examine from afar as medic to know what I need to kit as I get closer and never have had it be wrong. Are you using an older version of byond/old CM chat?

**Comment by RedStar929** [comment]
Nevest byond and new chat. Also shift+click works fine its a normal click on yourself aka self exam that doesnt work. problem is im usually cant tell if something is broken without it till its too late. Right now forced to carry medscaner as PRF.

**Comment by RedStar929** [comment]
Well i assidentally solved the mistery.. i spread combat log into a second tab AND as it seems all red text is combat logs soo,, all wounds go into that tab thats why there was sometimes less body parts then needed.
