### ISSUE TITLE
Bipod slow debuff issue.

### ISSUE THREAD

**Issue by RedStar929** [cmss13-devs/cmss13#700]
## Description
When you break bipod by moving in some way it applies huge slow debuff on you for few moments. It also counts the moment when some nade, CAS, mortar, OB blow you up. When aliens grab or push you etc.
 

## Difference between expected and actual behavior
So i expecting it to stop at some point, but it reapplies after every second step you do, no matter what, as if you break bipod stance every step.
[<a href="https://im.ge/i/Fut6R4"><img src="https://i.im.ge/2022/07/18/Fut6R4.md.png" alt="Fut6R4.png" border="0" /></a>](url)
Tried to deploy/undeploy bipod there, tried to get blown by a nade with bipod on and get slugged (thanks to friendly Alpha marine). Nothing helped. 

## Steps to reproduce
-Take bipoded weapon (in my case it was HPR)
-Deploy bipod and start shooting.
-Get blown by friendly OT nade.
-Get up and enjoy permanent slow. (in my case i died choking to death in crit, mb it matters) 

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by africalimedrop** [comment]
Seems likely to be related to #559. Have had issue with a bipodded HPR twice today. In the first instance the effect was as you describe, losing possession of the weapon when the bipod was deployed and with the slowdown icon constantly appearing after moving, hampering movement. The second time I didn't get the icon but with every move I heard the deploy sound effect. Unsure if related, but I became unable to reload the HPR twice today as well. The magazine simply would not eject. I also couldn't field strip it when it was in this state as I was going to see if a particular attachment was causing the problem (using Barrel Charger, Magnetic Harness and Bipod).

**Comment by RedStar929** [comment]
> Seems likely to be related to #559. Have had issue with a bipodded HPR twice today. In the first instance the effect was as you describe, losing possession of the weapon when the bipod was deployed and with the slowdown icon constantly appearing after moving, hampering movement. The second time I didn't get the icon but with every move I heard the deploy sound effect. Both times I was downed by a Xeno, not hit with a 'nade though. Unsure if related, but I became unable to reload the HPR in two rounds as well. The magazine simply would not eject. I also couldn't field strip it when it was in this state as I was going to see if a particular attachment was causing the problem (using Barrel Charger, Magnetic Harness and Bipod).

Have to add that HPR i took and used in my situation also had Harness and BC on it! BC is passive so i think it should be harness that cause the problem.

**Comment by stanalbatross** [comment]
the issue is - when the bipodded gun is removed from your hand by explosion/whatever it still acts as though you are bipodded and applies a movement debuff whenever you move
