### ISSUE TITLE
Platform Edges render on wrong layer.

### ISSUE THREAD

**Issue by Venuska1117** [cmss13-devs/cmss13#7049]
### Testmerges

#6334, #6071, #6824, #6820, #6808, #6977, #7025, #6039

### Round ID

23694

### Description of the bug

![image](https://github.com/user-attachments/assets/9b559a77-3894-48cc-862a-860108dcec15)

### What's the difference with what should have happened?

They should appear under Xenos (mob) sprites

### How do we reproduce this bug?

1. Run any map with Platform edges
2. See Platform Edger overlay ABOVE mob
3. Try to understand why it happend
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
layering issue
