### ISSUE TITLE
Larvae can grow and hatch from Headless corpses

### ISSUE THREAD

**Issue by Willzadl** [cmss13-devs/cmss13#7050]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 97b9492b2e #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, Xenos can now weed everything except LZ's and surrounding of LZ's, allow LAZ for CAS inside structures with light blue Areas on Tacmap (glass ceiling hallways)' by Venuska1117 at commit 817ed55a47 #6824: 'Human bursting sounds + sprite, new hugging sounds' by Blundir at commit 0545431b86 #6820: 'Updates close backpack icon' by Blundir at commit e6e1e493fa #6808: 'Attachments resprite' by Blundir at commit cc4fe40905 #6977: 'Mapping: LV522 Changes to overall map, including the size, poplimit, chokepoints and other such things' by spartanbobby at commit 36502bb625 #7025: 'Fixes giant lizard code breaking when disarmed, and adds some minor features to the mob' by VileBeggar at commit a2771a8ba2 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit 069bcb4f42

### Description of the bug

When hugged and then decapitated, larva can still grow and hatch. 

### What's the difference with what should have happened?

Larva should not hatch from dead headless corpses.

### How do we reproduce this bug?

1. Hug a person
2. Decapitate them
3. Watch as a perma-dead corpse hatches like normal

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
Intended. They burst from the chest not the head.

**Comment by Willzadl** [comment]
> Intended. They burst from the chest not the head.

In which case, shouldn't all dead marines grow and hatch? I don't understand - they're dead.

**Comment by kiVts** [comment]
Suiciding/getting decapped doesnt stop the larva growth. common misconception.

**Comment by Willzadl** [comment]
> Suiciding/getting decapped doesnt stop the larva growth. common misconception.

I don't understand. So, all humans, when hugged, will hatch unless surgically removed? Even if they die straight after?

**Comment by Willzadl** [comment]
I'm testing this now, and it doesn't work. The dead human is not progressing in larva growth

**Comment by Unknownity** [comment]
If a human is hugged and dies, there is a embryo death timer which is synced with the perma death timer.
So usually when they perma, the embryo dies. Being decapped is a unique case where the two timers are no longer synced and the embryo can still grow (until the timer reaches the time where they would perma from a regular death).

**Comment by Willzadl** [comment]
In which case, the original point stands - this is not intuitive. When somebody dies, unrevivably, the larva should too.

**Comment by ItsVyzo** [comment]
> If a human is hugged and dies, there is a embryo death timer which is synced with the perma death timer. So usually when they perma, the embryo dies. Being decapped is a unique case where the two timers are no longer synced and the embryo can still grow (until the timer reaches the time where they would perma from a regular death).

That is incorrect, at least in relation to the timer. The larva has a SEPERATE timer from the body it embodies.

Once a marine dies, the larva inside their body stays alive for a limited time. If it reaches maturity within that time then it can burst otherwise it will eventually die out.

In other words, this is intended behavior were a larva may burst if it is close to maturity and the host dies.
