### ISSUE TITLE
There is no cooldown in attempting to launch an escape pod and failing, allowing the explosion to be spammed

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#7071]
### Testmerges

 #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 97b9492b2e #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, Xenos can now weed everything except LZ's and surrounding of LZ's, allow LAZ for CAS inside structures with light blue Areas on Tacmap (glass ceiling hallways)' by Venuska1117 at commit 817ed55a47 #6824: 'Human bursting sounds + sprite, new hugging sounds' by Blundir at commit 0545431b86 #6820: 'Updates close backpack icon' by Blundir at commit e6e1e493fa #6808: 'Attachments resprite' by Blundir at commit cc4fe40905 #6977: 'Mapping: LV522 Changes to overall map, including the size, poplimit, chokepoints and other such things' by spartanbobby at commit 36502bb625 #7025: 'Fixes giant lizard code breaking when disarmed, and adds some minor features to the mob' by VileBeggar at commit 2ff99d00fa #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit eeaad6736c

### Round ID

23756

### Description of the bug

Expected the escape pod to explode only once, instead it exploded 20~ times and nearly killed a King

https://github.com/user-attachments/assets/eca9d9d2-e042-4813-92ab-450def3751d0

### What's the difference with what should have happened?

only explode once

### How do we reproduce this bug?

1. put too many people/a large xeno on escape pod
2. spam the launch button
3. explode(x100)
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by LC4492** [comment]
Best way to understand what exactly happened, is to ask the player that caused the bug

**Comment by LC4492** [comment]
> Reproducible on local.
> 
>  epodoverload.mp4 
> From what I can see [here](https://github.com/cmss13-devs/cmss13/blob/a8d5f177c2ab6a57afae6dac331377807b26efcb/code/modules/shuttle/shuttles/crashable/escape_shuttle.dm#L81), the ~50 ds sleep between triggering launch and setting the shuttle to SHUTTLE_CRASHED lets this happen, since interaction isn't stopped until that's set.

Good work with the reproduction

**Comment by ItsVyzo** [comment]
Abusing this will result in an immediate ban
