### ISSUE TITLE
Cluster weeds bypass structures it should bypass

### ISSUE THREAD

**Issue by Skatuk** [cmss13-devs/cmss13#7078]
### Testmerges

https://github.com/cmss13-devs/cmss13/pull/6616

### Description of the bug

If you place cluster near the cades it will bypass them and weed behind them allowing xeno's to build where they shouldn't build.

I'm sure its this PR https://github.com/cmss13-devs/cmss13/pull/6616 that broke it.

### What's the difference with what should have happened?

Cluster weeds should stop infront of the cades and not go through them.

### How do we reproduce this bug?

1.Make a cadeline wide enough so cluster weeds can't go around them
2.Place a cluster infront of it.
3.Watch as cluster weeds go through them.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Skatuk** [comment]
I kind of fucked up the title meant to say
Cluster weeds bypass structures it shouldn't bypass

**Comment by private-tristan** [comment]
This isn't caused by #6616 but rather by #25
"Weeds can no longer spread onto tiles with barricades on them from the side that the barricade is protecting if the health of the barricade is over 25%."
Undamaged cades:

![image](https://github.com/user-attachments/assets/2f8bccf7-5396-42b7-88ef-7f0edc7ca950)

Damaged Cades:
![image](https://github.com/user-attachments/assets/7a649940-f2fb-4724-aa6c-9c7fb1980c59)

**Comment by Skatuk** [comment]
so basically this is a feature and not a bug...

**Comment by ItsVyzo** [comment]
> This isn't caused by #6616 but rather by #25 "Weeds can no longer spread onto tiles with barricades on them from the side that the barricade is protecting if the health of the barricade is over 25%." Undamaged cades:
> 
> ![image](https://private-user-images.githubusercontent.com/54422837/363521617-2f8bccf7-5396-42b7-88ef-7f0edc7ca950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzc1NDQsIm5iZiI6MTcyNTI3NzI0NCwicGF0aCI6Ii81NDQyMjgzNy8zNjM1MjE2MTctMmY4YmNjZjctNTM5Ni00MmI3LTg4ZWYtN2YwZWRjN2NhOTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDExNDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMmQyYTQ1YWJjOTBhNzk5MzI2MGUxZWRhMzZlMTE2ZDcwNjE3ZjA0YzcyZDU4N2I5ZmI4YWQ4YzM1MjBlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2R5lPcvDPVmaRQUTeQGrJp9i1pZ7HFCPE303l0Fs-dQ)
> 
> Damaged Cades: ![image](https://private-user-images.githubusercontent.com/54422837/363521715-7a649940-f2fb-4724-aa6c-9c7fb1980c59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzc1NDQsIm5iZiI6MTcyNTI3NzI0NCwicGF0aCI6Ii81NDQyMjgzNy8zNjM1MjE3MTUtN2E2NDk5NDAtZjJmYi00NzI0LWFhNmMtOWM3ZmIxOTgwYzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDExNDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzcwYjczYzYyYzUwMzg0N2Q1YzIyZTFmNzNhOTA2Yzk5ZTBlZGY3ZjI3NjlmZDMyMDg1MTgzYjI4NjdjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V0Hzo2QAqDtdi3LCuXqq-2allA5kGc6K57j7nVZM20I)

As above - though should've used a hive cluster for both tests as the issue is referencing hive cluster not hive core
