### ISSUE TITLE
Top left UI buttons not working.

### ISSUE THREAD

**Issue by dadlips** [cmss13-devs/cmss13#7104]
### Testmerges

N/A

### Round ID

23806

### Description of the bug

Two users have now reported that their top left UI buttons/icons don't work. One user reports that re-downloading byond is the only fix so far.

This does not seem related to windows getting stuck invisible over the game (such as the task bar picture in picture windows when hovering over a program.) Since the taskbar is at the bottom of the screen.

![image](https://github.com/user-attachments/assets/19354f61-f74a-4fb6-aa84-5788428431ca)
They report that these icons specifically don't work on queen, but others do.

### What's the difference with what should have happened?

Top left UI icons/buttons should work.

### How do we reproduce this bug?

Unknown recreation, only known fix is to re-install/update byond + restart computer.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
BYOND/Client issue can't fix/won't fix
