### ISSUE TITLE
Lighting System Issues

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#7113]
### Testmerges

BYOND Version: 515.1640 Server revision compiled on: 2024-09-03T17:24:54+00:00 Master commit: 13f70c374e6cce02767b71327e8888e1bfd1cd5d The following pull requests are currently test merged: #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 97b9492b2e #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, Xenos can now weed everything except LZ's and surrounding of LZ's, allow LAZ for CAS inside structures with light blue Areas on Tacmap (glass ceiling hallways)' by Venuska1117 at commit 817ed55a47 #6820: 'Updates close backpack icon' by Blundir at commit e6e1e493fa #6808: 'Attachments resprite' by Blundir at commit cc4fe40905 #7025: 'Fixes giant lizard code breaking when disarmed, and adds some minor features to the mob' by VileBeggar at commit 023f225ddb #7093: 'ports ipintel subsystem' by harryob at commit 3416fba856  Local commit: 17ee65470ad7150ddf3fb11cfbc874cfb2ad384b TGS version: 6.6.0 DMAPI version: 5.9.0

### Round ID

23814

### Description of the bug

Sometimes squares are not lit. See Screenshots.

![image](https://github.com/user-attachments/assets/f565daf7-aa09-472f-8536-61d3800b1b79)

![image](https://github.com/user-attachments/assets/d3db83e0-ffdd-44a4-a658-61cc1a22efd5)

### What's the difference with what should have happened?

Should be lit.

### How do we reproduce this bug?

No idea. Seems to be generated per round. I notice it in different rounds, and placement isn't always consistent. The ladder in lower engineering has been unlit in several rounds, but it seems to be random.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by LC4492** [comment]
Those squares are being witnessed since the new lighting system, so Im somewhat sure it doesn't involves any of the testmerged PRs.

**Comment by Willzadl** [comment]
BYOND issue? seen this on tgstation too
