### ISSUE TITLE
Dropships aren't supposed to have NVGs by default

### ISSUE THREAD

**Issue by private-tristan** [cmss13-devs/cmss13#7155]
### Testmerges

N/A

### Round ID

N/A

### Description of the bug

dropships have NVGs on camera consoles due to pr  #4812. this buff wasn't mentioned in the PR and nobody has bothered to report it since then.

### What's the difference with what should have happened?

It should look like this, where you DON'T see in the dark.

![image](https://github.com/user-attachments/assets/51df993b-4a2b-4413-b064-f7173f389151)

DS should only have NVGs if research gives them a dropship matrix with a photosensitivity chem inside it.  

### How do we reproduce this bug?

1. play as PO
2. have someone lase/drop a flare
3. free NVGs for the area
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by BOBAMAx** [comment]
#5676 related

**Comment by private-tristan** [comment]
woops, I didn't realize it was a dupe.
