### ISSUE TITLE
Perma icon clobbers all other icons on the same tile

### ISSUE THREAD

**Issue by benrobey** [cmss13-devs/cmss13#7161]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit a7a23fe170
#6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, Xenos can now weed everything except LZ's and surrounding of LZ's, allow LAZ for CAS inside structures with light blue Areas on Tacmap (glass ceiling hallways)' by Venuska1117 at commit 300a41768f 
#6808: 'Attachments resprite' by Blundir at commit cc4fe40905 
#7093: 'ports ipintel subsystem' by harryob at commit 3416fba856 
#7106: 'Flexible Job Icons' by realforest2001 at commit a490c79b43 
#7061: 'Project ARES: Interface Data Proc' by realforest2001 at commit dfe5291875
 #6860: 'Mentor New Player Markers' by realforest2001 at commit 1457cbadfe 
#6938: 'SHARP Rifle Revived' by Nomoresolvalou at commit 4ac3831daf
#5265: '(WIP) Paperwork Prefabs' by realforest2001 at commit b56e5e11e6

### Description of the bug

If a revivable human dies on a tile where there is a permanently dead human, the perma icon (the skull) is shown in front of the  green / orange / red ECG icon. 

### What's the difference with what should have happened?

The ECG icon should be displayed over the top of the perma icon. IMO the way it should work is that the person who died last's icon should be displayed.

### How do we reproduce this bug?

1. Have a unrevivable human dead on a tile
2. Have a human die on that same tile
3. Observe the perma icon clobbering the green ECG icon

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment]
I'll say this is not a bug, rather it is how you would simulate a pile of bodies in a 2d game. Tough shit, don't die in a pile of bodies.

A maintainer is welcome to disagree otherwise.

**Comment by benrobey** [comment]
> I'll say this is not a bug, rather it is how you would simulate a pile of bodies in a 2d game. Tough shit, don't die in a pile of bodies.
> 
> A maintainer is welcome to disagree otherwise.

I think it's more of an oversight than a bug, can we confirm that this is the intended behaviour when multiple corpses are stacked on a tile? I don't think it makes the game better to punish players from dying on a tile that has another body on it. 

A pile of bodies in a 2d game can be simulated in many different ways, the way it works now it is arbitrarily punishing the player from dying on a tile with another body which to me does not make sense.
