### ISSUE TITLE
ERT Stations Cryos are Connected to the Cryo Console

### ISSUE THREAD

**Issue by thevandie** [cmss13-devs/cmss13#7244]
### Testmerges

#6334: 'Xenomorph Endgame' by Git-Nivrak at commit 22dcde564c #6071: '[V] Sorokyne Strata: Expanded Small corridors, removed 3000 unused tiles, Xenos can now weed everything except LZ's and surrounding of LZ's, allow LAZ for CAS inside structures with light blue Areas on Tacmap (glass ceiling hallways)' by Venuska1117 at commit 300a41768f #6808: 'Attachments resprite' by Blundir at commit cc4fe40905 #6938: 'SHARP Rifle Revived' by Nomoresolvalou at commit db04ccde7e #7231: 'temp revert for cmss13-devs/cmss13#7201' by harryob at commit ad026a34c5 #7165: 'Fax Responders & Paperwork Prefabs hybrid TM' by realforest2001 at commit 359452315f

### Description of the bug

Basically, if someone cryos on the Royce, or the Marshal station, or anywhere off the Alaymer with hypersleep pods, their gear will be put into the ALAYMER'S cryogenic storage console.

Meaning if you exfil as PMCs or WY Chemical Team, then cryo, a NOSEY XO can just walk down to the console, steal himself a headset, and walk off with WY comms for free.

### What's the difference with what should have happened?

The console shouldn't store gear from off-ship cryopods. It A) Doesn't make sense and B) is bad.

### How do we reproduce this bug?

1. Spawn on the USS Royce
2. Cryo
3. Check the cryo console in req

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by kiVts** [comment]
#6709, duplicate

**Comment by thevandie** [comment]
well fix it already, it's being abused
