### ISSUE TITLE
i can't compile 

### ISSUE THREAD

**Issue by asskek** [cmss13-devs/cmss13#7250]
### Testmerges

no clue baby

### Round ID

HIV

### Description of the bug

i downloaded the code on the 28th; every time i run server.cmd it kicks out the following:
`Using vendored Node v20.12.0
:: Juke Build version 0.8.1
=> Starting 'yarn'
=> Starting 'dm'
:: Using defines: CBT
DM compiler version 515.1643
loading colonialmarines.dme
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 300ms
➤ YN0000: ┌ Fetch step
loading interface/skin.dmf
code\datums\mutable_appearance.dm:8:warning (no_parent): ..: ..() has no parent proc to call
code\datums\mutable_appearance.dm:7:error: New: undefined proc
`

i'm on the latest version of BYOND and i compared mutable_appearance.dm to the one that's on github and yeah they're identical. 

tried a clean compile and everything. do i have to downgrade my byond version maybe? 

### What's the difference with what should have happened?

i want to compile so i can start developing 

### How do we reproduce this bug?

maybe update to latest version of byond? also i don't use visual studio code

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
use the correct version of byond to compile. that's the version specified in https://github.com/cmss13-devs/cmss13/blob/master/dependencies.sh#L8

**Comment by harryob** [comment]
> thanks bro kind of sucks as i require byond 1635 to play CM kekekekek. but i'll just have two separate installs. appreciate the info

you can use any version of cm between 1635 and 1642. it's just the most recent version that is bugged
