### ISSUE TITLE
Random Grab dropping as Warrior

### ISSUE THREAD

**Issue by BKryth** [cmss13-devs/cmss13#729]
## Description

As warrior, start to randomly cancel grab, happens even during lunges, happened twice in different rounds already

Had ghosted the first time it happened and the player that took over the warrior had gotten the same issue, reconnecting doesn't fix it

## Difference between expected and actual behavior

Grab something, it drops the grab, it shouldnt drop grab without manually clicking the drop button

## Steps to reproduce

Don't know how, it just happens, not a keyboard issue since im not randomly pressing Q

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
apparently still a bug...
![image](https://user-images.githubusercontent.com/117036822/236617035-2d318bcf-0f97-4636-a0f8-6be6edafebcf.png)
