### ISSUE TITLE
incorect omnisentry prices with print queue

### ISSUE THREAD

**Issue by cuberound** [cmss13-devs/cmss13#7295]
### Testmerges

#none (itelevant)

### Description of the bug

when you place several omnisentryguns into print queue they are all printed for the price of first one ( only tested with two)

### What's the difference with what should have happened?

price should increment after each print as before queue this can be used for infinite money

### How do we reproduce this bug?

1.queue two omnisentryguns
2.ket them print
3.did not loose correct amount of money
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Should be resolved via #7282
