### ISSUE TITLE
Autolathes printing blowtorch with fuel

### ISSUE THREAD

**Issue by Ansekishokuu** [cmss13-devs/cmss13#7310]
### Testmerges

#6808: 'Attachments resprite' by Blundir at commit cc4fe40905 #6938: 'SHARP Rifle Revived' by Nomoresolvalou at commit 744d618abd #7242: 'WIP Yautja Clan TGUI Menu' by realforest2001 at commit cd3b853b09 #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 1afe9c9046 #7280: 'Fix unintended reagent refilling via vendors' by Drulikar at commit c4023e1df5 #7282: 'stops pilots breaking the bank' by harryob at commit 5d6f909bac #7165: 'Fax Responders & Paperwork Prefabs hybrid TM' by realforest2001 at commit decbc8dcfd #7106: 'Flexible Job Icons' by realforest2001 at commit a490c79b43 #7302: 'Hostile ERT clarity messages' by realforest2001 at commit 417a76ff50 #5925: 'Biosuit Updates' by realforest2001 at commit 875b8f703e #7307: 'TestMerge: Weedable area changes' by Nanu308 at commit 2e91bd298d

### Description of the bug

Autolathes print blowtorches with fuel inside them.
Putting your empty blowtorch inside the autolathe and printing a new one gives you a full one with no extra material cost.

### What's the difference with what should have happened?

Autolathes should print empty blowtorches.

### How do we reproduce this bug?

1- Print a blowtorch

Optionally:
1- Put your empty blowtorch inside the autolathe
2- Print a new one

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ansekishokuu** [comment]
To your knowledge!
Fix PR is ready but i can't send a PR right now, will send later.

**Comment by LC4492** [comment]
Fixed by #7407
