### ISSUE TITLE
Smartgun action icons don't disable automatically

### ISSUE THREAD

**Issue by NexusStorm1** [cmss13-devs/cmss13#736]
## Description
I keep forgetting to reactivate my motion detector so I'm making this report. Smartgun action icons do not turn off when the corresponding setting is turned off by the game automatically (e.g. motion detector upon dying, auto-fire upon unwielding).

## Difference between expected and actual behavior
The icons should turn off (not have the green outline) if the setting is off.

## Steps to reproduce
A. Turn on motion detector, die, motion detector icon remains green upon revival (but it's actually off and you have to click again to reactivate)
OR
B. Turn on auto-fire after wielding, un-wield sg, auto-fire icon remains green (but it's actually off and you have to click again after re-wielding to reactivate)

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
my mistake, will fix.

**Comment by Ticker175** [comment]
Another similar issue with the new smartgun buttons:
When you attach a **rail flashlight** to the smartgun, all of the button icons (at the top of the screen) are set to default pictures of a smartgun. This makes it very hard to quickly change certain settings on the smartgun as they all have the same image

**Comment by stanalbatross** [comment]
> Another similar issue with the new smartgun buttons: When you attach a **rail flashlight** to the smartgun, all of the button icons (at the top of the screen) are set to default pictures of a smartgun. This makes it very hard to quickly change certain settings on the smartgun as they all have the same image

I could not replicate this in the way you are describing, did you do anything else before this?

**Comment by Ticker175** [comment]
> > Another similar issue with the new smartgun buttons: When you attach a **rail flashlight** to the smartgun, all of the button icons (at the top of the screen) are set to default pictures of a smartgun. This makes it very hard to quickly change certain settings on the smartgun as they all have the same image
> 
> I could not replicate this in the way you are describing, did you do anything else before this?

Sorry I have just tested it and it appears fixed please disregard my reply.
Thanks to whoever fixed it recently

**Comment by stanalbatross** [comment]
> > > Another similar issue with the new smartgun buttons: When you attach a **rail flashlight** to the smartgun, all of the button icons (at the top of the screen) are set to default pictures of a smartgun. This makes it very hard to quickly change certain settings on the smartgun as they all have the same image
> > 
> > 
> > I could not replicate this in the way you are describing, did you do anything else before this?
> 
> Sorry I have just tested it and it appears fixed please disregard my reply. Thanks to whoever fixed it recently

turns out it's still happening.... but with orders causing it. FML. time to fix that too

**Comment by stanalbatross** [comment]
> > > > Another similar issue with the new smartgun buttons: When you attach a **rail flashlight** to the smartgun, all of the button icons (at the top of the screen) are set to default pictures of a smartgun. This makes it very hard to quickly change certain settings on the smartgun as they all have the same image
> > > 
> > > 
> > > I could not replicate this in the way you are describing, did you do anything else before this?
> > 
> > 
> > Sorry I have just tested it and it appears fixed please disregard my reply. Thanks to whoever fixed it recently
> 
> turns out it's still happening.... but with orders causing it. FML. time to fix that too

fixed in pr
