### ISSUE TITLE
Headlights in colony van do not work

### ISSUE THREAD

**Issue by vdog218** [cmss13-devs/cmss13#7411]
### Testmerges

N/A

### Description of the bug

When using the colony van the headlights for the van do not function, causing the surrounding area to be pitch black when driving the van.

### What's the difference with what should have happened?

When driving the colony van, headlights should illuminate the area surrounding you.

### How do we reproduce this bug?

Drive the  colony van.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by cuberound** [comment]
already fixed in  #7404, hopefuly if it can not be replicated now then it is fixed
