### ISSUE TITLE
Deploying M56D on elevated surfaces

### ISSUE THREAD

**Issue by StankylegPlaya** [cmss13-devs/cmss13#743]
## Description
Deploying an M56D onto an elevated surface (window frame, table, rack, etc..) makes it impossible to finish installing, which also makes it impossible to retrieve (unless you remove the surface under it) as you cannot fold an unfinished M56D back up by dragging it onto your sprite (might be a bug since the message claims the M56D must be unscrewed first even though it hasn't been screwed in in the first place).
The same issue is present for naked M56D mounts, but you can drag/fold those up.

## Difference between expected and actual behaviour 
You are allowed to deploy an M56D onto elevated surfaces (window frames, tables, racks, etc..), but you aren't allowed to finish installing it as "there is something in the way".
If you can't fully install it onto elevated surfaces, then you shouldn't be able to deploy it there in the first place. (alternatively you should be able to fully install them there)

## Steps to reproduce
STEP ONE: Climb onto an elevated surface
STEP TWO: Deploy M56D

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
`you cannot fold an unfinished M56D back up by dragging it onto your sprite`

this is the main part of the bug

`If you can't fully install it onto elevated surfaces, then you shouldn't be able to deploy it there in the first place.`

fair

will fix these in my pr

**Comment by nuklearcellphoneg** [comment]
Yes let us finish it inside windows plox
