### ISSUE TITLE
ARC visual glitch

### ISSUE THREAD

**Issue by Shibouze** [cmss13-devs/cmss13#7435]
### Testmerges

#7242, #6334, #7330, #7217, #7363, #7368, #7419, #7413, #7396, #7165

### Round ID

24576

### Description of the bug

Ride on a FOB sentry with ARC as SO role, the sentry blew up and that weird visual glitch happened. 
It keep working fine after that.

Image : https://i.imgur.com/VDysRtt.png

### What's the difference with what should have happened?

Nothing should have happened here.. 

### How do we reproduce this bug?

Ride on a FOB sentry with ARC as SO role, the sentry blew up under the ARC and that weird visual glitch happened. 

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by cuberound** [comment]
similar stuff happend to me with tank, can confirm that riding on fob sentry fuck vehicles up, the entry point gets rotated too but that can not be seen visualy (at least it happend with the tank)

**Comment by vero5123** [comment]
@Zonespace27
