### ISSUE TITLE
Autocompressor doesn't work as intended, if patient is heartbroken

### ISSUE THREAD

**Issue by QuickLode** [cmss13-devs/cmss13#7452]
### Testmerges

The following pull requests are currently test merged: #7242: 'WIP Yautja Clan TGUI Menu' by realforest2001 at commit fed028f46b #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 689c3509ad #7330: 'new chem master' by harryob at commit 32e9564954 #7217: 'Rebalances OT casings' by GoldenDarkness55 at commit 3aae674165 #7368: 'add cobalt tools media provider, refactor providers to be more OOP' by harryob at commit 02f2ff128f #7413: 'Fixes nostore cryopods still storing stuff' by realforest2001 at commit 19a253a680 #7396: 'temp revert for #6588' by harryob at commit 9ad22269b3 #7110: 'Refactors launching into a subsystem' by boskoramen at commit a9d9cf59c9 #7164: 'Fax Responders' by realforest2001 at commit cc5f5410fe #7451: 'Fix hivecore restriction' by Drulikar at commit 567ae79f76 #7438: 'Tacmap Polish' by Drulikar at commit 8a15bfd54f #7188: 'Nerfs queen screech and re-adds bombard to ovi state' by GoldenDarkness55 at commit 262d16b8a1

### Round ID

24596

### Description of the bug

Autocompressor believes patient is not capable of continued resuscitation when their heart is broken

### What's the difference with what should have happened?

- Autocompressor should continue compressions even patient is heartbroken

### How do we reproduce this bug?

- Heart broken patient
- Apply autocompressor
- Will make 2 compressions then fall off believing that the patient is not able to be resuscitated

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Ansekishokuu** [comment]
Doing CPR during heartbreak doesnt do anything and if the autocompressor didn't fall off all it would do was cause the autocompressor to drain its battery for nothing so i dont think this is a bug.

**Comment by ItsVyzo** [comment]
> Doing CPR during heartbreak doesnt do anything and if the autocompressor didn't fall off all it would do was cause the autocompressor to drain its battery for nothing so i dont think this is a bug.

see above / you cannot defib heartbroken people
