### ISSUE TITLE
No access to bell in Medbay

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#7457]
### Testmerges

Not TM related

### Description of the bug

![image](https://github.com/user-attachments/assets/45aa8600-8498-42fe-ab71-6bf8df1d950e)

Normal people can't open this window to ring for medical personnel 

### What's the difference with what should have happened?

Should be all access in the windoor

### How do we reproduce this bug?

Try to open the windoor as non medical personnel. 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by LC4492** [comment]
This issue is quite common, given that people usually forget to give separated "req_access" lists to both windoors.

**Comment by ItsVyzo** [comment]
not a bug, but intended (all windoors in medbay function this way). though you're welcome to make a PR to change that.

**Comment by ItsVyzo** [comment]
> Whoever added the bell didn't intend for it to work that way and likely assumed the outer door could be opened; after all what's the point of the bell if the public at large can't access it.
> 
> > not a bug, but intended (all windoors in medbay function this way). though you're welcome to make a PR to change that.

I have no idea how i misread the original issue post, though yes that is definitely an issue. My mistake qq
