### ISSUE TITLE
Nailgun n PDA Mutually Exclusive

### ISSUE THREAD

**Issue by thevandie** [cmss13-devs/cmss13#7465]
### Testmerges

#7242: 'WIP Yautja Clan TGUI Menu' by realforest2001 at commit fed028f46b #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 689c3509ad #7164: 'Fax Responders' by realforest2001 at commit cc5f5410fe #7438: 'Tacmap Polish' by Drulikar at commit 8a15bfd54f #6924: 'Satchel Charges' by LynxSolstice at commit bbb9225399 #7023: 'Research Rework Part Two: The Contract System.' by kiVts at commit 03259a8d28 #7197: 'Sentinel buffs' by GoldenDarkness55 at commit 2a5934a75d #7376: 'Remote building nerfs' by GoldenDarkness55 at commit f18adc6ccf #7389: 'Raise Corpsespawner Limit' by BOBAMAx at commit 457358053a #7453: 'fix squadless marines' by blackcrystall at commit 74f066ea8c

### Round ID

24618

### Description of the bug

The Nailgun and PDA are mutually exclusive in the CE vendor. If you grab one, it locks you out of the other.
I specifically grabbed the nailgun and PDA was locked, I didn't test if when you grabbed the PDA it locked the nailgun, but I'm assuming.

### What's the difference with what should have happened?

You should be able to grab both the nailgun and the PDA.

### How do we reproduce this bug?

1. Spawn as CE
2. Click either nailgun or PDA
3. Ones locked
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by wgtjunior743** [comment]
i can confirm that if you pick the nailgun you also get locked of the PDA
