### ISSUE TITLE
fancy chat won't load

### ISSUE THREAD

**Issue by kindadread2** [cmss13-devs/cmss13#7558]
### Testmerges

#7242 , #7164 , #6334 , #7521 , #7535 , #7556 , #7554

### Description of the bug

Previsto ')'
   at http://cdn.cm-ss13.com/live/d0/asset.d0f120f93d52541a1a09986a6dc9c634.js:267:1316
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

just doing as the funny W-Y writing told me.

### What's the difference with what should have happened?

fancy chat usually works, no idea why it's not working, only happening today.

### How do we reproduce this bug?

1.load in
2.fancy chat couldn't load click here to fix
3.funny W-Y RPFriendly message with the stuff I had to copy paste
4.see bug description

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
This is an issue unique to you, but also doesn't look to include all the information. Try https://forum.cm-ss13.com/t/how-to-clear-your-cache/2909
