### ISSUE TITLE
ChemMaster can not store liquids at all

### ISSUE THREAD

**Issue by deathrobotpunch** [cmss13-devs/cmss13#7594]
### Testmerges

not related

### Description of the bug

when you remove a beaker from a ChemMaster with reagents in the buffer, all the reagents will get disposed

### What's the difference with what should have happened?

To not remove my hard work because I took a beaker out.

### How do we reproduce this bug?

1. put water in beaker
2.put beaker in ChemMaster
3.Deposit water into ChemMaster buffer
4.Take out beaker
5.Cry as the water disappears 

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Weuyn** [comment]
skill issue

**Comment by private-tristan** [comment]
Intended, ChemMaster clears buffer when beaker is removed, although i'm not sure if the new TGUI update tells you this.

If someone wants they can probably PR it, it would probably get merged.

**Comment by kiVts** [comment]
Intended. Read above. yes the chemmaster tells you that it will clear buffer.

**Comment by harryob** [comment]
> Intended, ChemMaster clears buffer when beaker is removed, although i'm not sure if the new TGUI update tells you this.
> 
> If someone wants they can probably PR it, it would probably get merged.

it does already

https://github.com/cmss13-devs/cmss13/blob/32af3cb732cfb4496b7d4069245dec31382c7762/tgui/packages/tgui/interfaces/ChemMaster.tsx#L102
