### ISSUE TITLE
Empty alien nests staying around

### ISSUE THREAD

**Issue by zzzmike** [cmss13-devs/cmss13#7603]
### Testmerges

#7242: 'WIP Yautja Clan TGUI Menu' by realforest2001 at commit 0f24fabd69 #6334: 'Xenomorph Endgame' by Git-Nivrak at commit 6ab61a7c45 #7521: 'Human Resprites & Tweaks - Marines looking awesome' by Nanu308 at commit 3d25ec63f8 #7511: 'Weyland-Yutani Intranet Terminal' by realforest2001 at commit df2219bffb #7486: 'The Hunting Grounds (Needs Testing) NOW WITH A MAP THAT WORKS HOPEFULLY' by Joelampost at commit 5d7b70caac #7165: 'Fax Responders TestMerge Collection' by realforest2001 at commit 7728f59e28

### Round ID

24849

### Description of the bug

![Screenshot 2024-11-16 230325](https://github.com/user-attachments/assets/f5526698-19c9-48c6-8f75-8268d6fe5e9b)

(One person, two nests on that tile) Alien nests that appear empty seem to be sticking around a lot, preventing xenos from nesting a new person onto that specific wall facing. I'm guessing this has to do with the 'weeds eat perma bodies after awhile' mechanic.

### What's the difference with what should have happened?

I think intended behavior should be for nests to cease to exist when there is no visible body attached to it - otherwise it's confusing for new players who have no idea about the 'weeds slowly eat perma bodies' thing or how they need to clear the hardly-visible nest in order to nest someone new there, etc.

### How do we reproduce this bug?

Unknown, but I'm guessing you just leave a bursted body in a nest for awhile and then it slowly disappears (or weeds eat it) but the nest stays.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Git-Nivrak** [comment]
I think they are not empty it's just the person in them becoming weed food

**Comment by zzzmike** [comment]
> I think they are not empty it's just the person in them becoming weed food

Yup, I did mention this. I still don't think it should be the intended behavior per my explanation above.

**Comment by Drulikar** [comment]
Weed food is just that weeds cover up the bodies. They'll never get destroyed. It is intentional that the bodies get hidden. Nest needs to still exist so you can unnest.
