### ISSUE TITLE
trijent shuttles broken

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#764]
## Description

they don work

the doors are invis

errormessage : Transport terminal unlinked. Manual activation required.

they also do not appear in the shuttle manipulator

tldr they need to be recoded like tgshuttles 

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Unknownity** [comment]
bit update on this
the doors are using incorrect icon states for the sprite
the errormessage : "Transport terminal unlinked. Manual activation required." seems to be a gameplay issue as you need to click the terminal at the other destination to link both shuttle stations, forgot how it worked before.

**Comment by Mark9013100** [comment]
@Unknownity The last time I used the Trijent tram terminals(roughly two months ago), it didn't work. If you link the trams and then call the tram, they end up in limbo, and anything inside the area when the ghost tram arrives gets gibbed/crushed.

**Comment by Huffie56** [comment]
I don't know if it's consider like an elevator i remember being just one button to press...

**Comment by Huffie56** [comment]
same issue reported here https://github.com/cmss13-devs/cmss13/issues/466

**Comment by Huffie56** [comment]
@ItsVyzo trijent shuttle as been fixed with this PR
https://github.com/cmss13-devs/cmss13/pull/2964

**Comment by ItsVyzo** [comment]
thanks @Huffie56 
fixed
