### ISSUE TITLE
A fatal exception has occurred at 002B:C562F1B7 in TGUI

### ISSUE THREAD

**Issue by g5769** [cmss13-devs/cmss13#7673]
### Testmerges

#1

### Description of the bug

       
 

  \+++++\@@@@@@@@@@/++++\@@@@@@@@@@/+++++/
  \+++++\@``````@/++*+*+\@``````@/+++++/
   \+++++\@````@/++++++++\@````@/+++++/
    \+++++\@``@/++++++++++\@``@/+++++/
     \+++++\@@/+++++/\+++++\@@/+++++/
      \+++*+\/+*+++/@@\+++++\/+++++/
       \++++++++++/@``@\++++++++++/
        \++++++*+/@````@\++++++++/
         \++++++/@@@@@@@@\++++++/
 
 
A fatal exception has occurred at 002B:C562F1B7 in TGUI.The current application will be terminated.Send the copy of the following stack trace to an authorizedWeyland-Yutani incident handler at https://github.com/cmss13-devs/cmss13/issues.Thank you for your cooperation. 
 Error: Access is denied.

   at isStyleSheetLoaded (http://127.0.0.1:10849/tgui-window-1.html:247:7)
   at node.onload (http://127.0.0.1:10849/tgui-window-1.html:325:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"originalkiwininja","interface":"VendingSorted","window":{"key":"[0x2007467]-main","size":null,"fancy":1,"locked":0}}

Weyland-Yutani (c) 2100-2182 Building better user interfaces. 
  

Recoil Compensator

A muzzle attachment that reduces recoil by diverting expelled gasses upwards. Increases accuracy and reduces recoil, at the cost of a small amount of weapon damage.

### What's the difference with what should have happened?

The Weyland Utani corporation has caused an error on my access of my vendors

### How do we reproduce this bug?

1. Be OriginalKiwiNinja on BYOND
2. Access vendors
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
See #3846 #4865 #6454
