### ISSUE TITLE
The xeno marker acts like a solid xeno structure, blocking building

### ISSUE THREAD

**Issue by Vicacrov** [cmss13-devs/cmss13#7763]
### Testmerges

irrelevant

### Round ID

Every round

### Description of the bug

The leader marker xenos can put blocks xeno structures from building, including resin walls or bigger buildings like clusters that need a 3x3 area. If there is a marker on the tile, it cannot be built on.

### What's the difference with what should have happened?

They should not block building and they should be able to be placed on solid (xeno?) structures.

### How do we reproduce this bug?

1. Place a xeno leader marker
2. Try to build on top of / around it

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Intentional that you cannot build on top of it. You can build next to it (it has a block range of 0)
![image](https://github.com/user-attachments/assets/95043698-1010-4b9d-add6-7b84929ebac9)
