### ISSUE TITLE
BUG: Smartfridges not working as they should

### ISSUE THREAD

**Issue by Ticker175** [cmss13-devs/cmss13#777]
BUG REPORT

## Description
 - The “smart chemical storage” (all 3 of them on the ship) require identification even when the ID Wire has been cut
 - the industrial grinder (in OT lab) doesn’t have a connect to smart fridge button

## Difference between expected and actual behavior
 - smartfridge should be fully usable with the ID wire cut
 - There should be a button like there is for the normal grinder

## Steps to reproduce
Unscrew panel on any of the smart fridges and cut ID Wire then attempt to access to do anything

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
The fridge wiring was messed up waaaay back when hacking was swapped to easy mode with all wire effects being identified to the player. The ID wire for sure used to be useful before that but the change to new hacking also predates a lot of the smart fridge updates. When the hacking was dumbed down, many other objects suffered a similar fate like fire alarms, numerous vendors, shipside comm units, etc.

**Comment by Ticker175** [comment]
Still not fixed on master or any of the recent or current test merges
