### ISSUE TITLE
Queen Honks While healing

### ISSUE THREAD

**Issue by ClairionCM** [cmss13-devs/cmss13#7780]
### Testmerges

#7536: 'Adds crosshairs to all ranged weapons' by VileBeggar at commit d8bd7437c4 #7766: 'lobby screen update' by harryob at commit f7fe4cde8a #7754: 'Adds Watchtowers' by Git-Nivrak at commit 770a00ff31

### Round ID

25328

### Description of the bug

When the queen uses her healing ability instead of playing the healing animation the game will show a honk sprite instead.
The heal still works the sprite is just broken.
![image](https://github.com/user-attachments/assets/6bde661a-cd47-4acf-b89c-71ebe850c5f6)

### What's the difference with what should have happened?

It shouldnt be honking. It should be healing.

### How do we reproduce this bug?

1. Get damaged as a xeno
2. Beg for the queen to heal you
3. HONK

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ClairionCM** [comment]
Seems to be more sprites that are broken also. This is a trash bag that someone is wearing and I also saw a green HONK on a xeno earlier. Unsure what that green honk was though.
![image](https://github.com/user-attachments/assets/98f75de9-658f-4ad0-8fcd-bc2dad9fae91)
![image](https://github.com/user-attachments/assets/2ac1d3fe-f9b2-43d4-ab7d-b61425debfa8)

**Comment by Blundir** [comment]
Fixed queen honk and trash bags, not sure what gren honk was, probably wardern's healing, if it's that then it's fixed

**Comment by ClairionCM** [comment]
Found another one @Blundir
![image](https://github.com/user-attachments/assets/44c73cbf-8b99-48d2-b999-f9856dd23c2d)
![image](https://github.com/user-attachments/assets/4538c33d-75ec-4e04-98ee-842860569736)
This person is holding Black Athletic Shorts and its making it look like they are wearing some kind of untextured dress.
Maybe related is that they are also wearing Blue athletic shorts. But when they drop the black shorts that they are holding the error texture goes away.

**Comment by ClairionCM** [comment]
Actually the Optical Material Scanner on Fiora can also be added to the list.

![image](https://github.com/user-attachments/assets/1658c3c4-27a5-48a9-b89e-7a721e0a77e2)
![image](https://github.com/user-attachments/assets/c51dcddc-11f9-49ef-9e69-40fd39658f34)

**Comment by Blundir** [comment]
@ClairionCM fixed both

**Comment by ClairionCM** [comment]
@Blundir I bring you another error.
Synthesis of X and Analysis of X type papers will give an error sprite if you wear them on your head like a paper hat.
Regular paper hats work fine, these ones dont.
![image](https://github.com/user-attachments/assets/89ba2329-8b54-4812-97b0-5dea67c4f98c)

**Comment by Blundir** [comment]
fixed it a while ago, just not tmed yet
