### ISSUE TITLE
Wearing a Tan booniehat not working correctly, hat is in the middle of the chest

### ISSUE THREAD

**Issue by SirLambini** [cmss13-devs/cmss13#7784]
### Testmerges

#7536 #7766 #7754

### Round ID

25335

### Description of the bug

Tan boonie hat from loadout when equipped, instead of being in the head, it's located in the torso area, and with the same sprite of when you keep it in your inventory, not the wearable one.
Tried with an helmet and standard marine cap. Both were working correctly. Saw another marine with a boonie but it was working correctly. Did not try if this is a problem with the olive boonie hat.

### What's the difference with what should have happened?

Boonie hat should stay in the head, not in the torso area

### How do we reproduce this bug?

1. Add a Tan Boonie hat in your loadout, add orange balistic googles, add sunglasses
2. Spawn in
3.
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
Confirmed, but also confirmed to be fixed with linked PR
