### ISSUE TITLE
Headbands broken again

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#7859]
### Testmerges

#7536: 'Adds crosshairs to all ranged weapons' by VileBeggar at commit d8bd7437c4 #7766: 'lobby screen update' by harryob at commit 61b278ed88 #7754: 'Adds Watchtowers' by Git-Nivrak at commit 61479579ab #7802: 'Removes non combat click delay' by Git-Nivrak at commit 2cb21f8fe6 #7827: 'Overwatch can hear speech and see emotes' by ihatethisengine at commit a8b1dd98a6 #7607: 'Warden Praetorian rework (tm)' by Red-byte3D at commit 45bdf9761b #7600: 'SG Frontline Mode & Friends - Yay!!!' by BasilHerb at commit cfdd191899 #7774: 'req console tgui' by harryob at commit 566ef0b36a #7743: 'Ship Operations Synthetic' by QuickLode at commit 11fbc7a943 #7165: 'Fax Responders TestMerge Collection' by realforest2001 at commit ba8f3c52f4

### Round ID

25468

### Description of the bug

![image](https://github.com/user-attachments/assets/9987449f-fe46-49e6-beba-64307478bad3)

That's a red headband. It should be red. They were red a few days ago. Before that they were messed up as well.

### What's the difference with what should have happened?

Should be red. Thicker headband too.

### How do we reproduce this bug?

1. Spawn in with a red headband
2. Or grab the red headband in maint SW of Medbay, E of Autolathe

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
#7782 I think this borked headbands.

**Comment by nuklearcellphoneg** [comment]
Also important to note: If you place the headband inside a helmet and wear it, the headband shows up fine.

**Comment by nuklearcellphoneg** [comment]
And now they work again.

**Comment by nuklearcellphoneg** [comment]
![image](https://github.com/user-attachments/assets/37b21dad-a781-4143-89c5-981f631f16cf)
 @Drulikar Broken again. Dunno if maybe it's map related. Map is Solaris.

**Comment by nuklearcellphoneg** [comment]
Works fine on LV

**Comment by nuklearcellphoneg** [comment]
Works fine on LV 522

**Comment by Drulikar** [comment]
Some maps intentionally have different colors for camo. The main issue I'm concerned with is whether the color the item has matches what color the mob sprite has and as far as I can tell it does on Solaris.

But at least on Solaris being alpha and using squad headband will result in red so I guess up to @Blundir if they want to tweak how squad color headbands work, or if they'd rather just headbands not really get camo conforming colors.

**Comment by nuklearcellphoneg** [comment]
I understand that but these aren't camo headbands, they're listed as red so they shouldn't be changing to other colors. 
![image](https://github.com/user-attachments/assets/106875d6-8060-4c54-a2de-2314f675b18d)
