### ISSUE TITLE
evolution as a xeno

### ISSUE THREAD

**Issue by dantedesante** [cmss13-devs/cmss13#7934]
### Testmerges

7764,7909,7913

### Description of the bug

able to evolve as a xenomorph larva on the ground trough watching a xenomorph that is in hijack 

### What's the difference with what should have happened?

not evovle

### How do we reproduce this bug?

1.watch a xenomorph shipside
 2.while watching the xenomorph select the evolution ability
3.able to select a xenomorph to evolve into this way

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Git-Nivrak** [comment]
Not a bug?

**Comment by Drulikar** [comment]
I don't really understand the issue. You aren't evolving them, you're evolving yourself.
