### ISSUE TITLE
Dark mode broken

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#7951]
### Testmerges

#7764: '[TM only] Snowflake_SnowCap' by HIDgamer at commit 364f8cccd3 #7909: 'Fixes maintainer access to the profiler and clears profiler access whenever admins are loaded.' by Watermelon914 at commit f10699e7c0 #6951: 'New "in_hands" and "onmob" icon sprites for objects, book import from PVE (thanks Amory), small changes and fixes' by LC4492 at commit bdd6e7ad75 #7860: '516 compat' by harryob at commit 73162f2421

### Round ID

25678

### Description of the bug

![image](https://github.com/user-attachments/assets/e731eb43-10fc-4084-9850-08ca51d464d8)

### What's the difference with what should have happened?

Dark mode's enabled yet light mode is on.

### How do we reproduce this bug?

Not sure if it's reproducible. I have deleted my cache, am now going to try uninstalling.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nuklearcellphoneg** [comment]
Reinstalling did not fix it.

**Comment by nuklearcellphoneg** [comment]
Nevermind, it was a chat mode issue.

**Comment by Drulikar** [comment]
Chat mode issue?

**Comment by harryob** [comment]
misunderstanding of preferences

**Comment by nuklearcellphoneg** [comment]
@Drulikar All my preferences were saved across everything, but chat settings had been reset. Setting to dark mode there fixed it.

**Comment by harryob** [comment]
this is intended, clientside preferences are stored on the client. they were reset due to storage changes for 516 compatibility, and will be lost again when we mandate 516 clients
