### ISSUE TITLE
Hybrisia EMT Clothing Locked

### ISSUE THREAD

**Issue by troytroy400** [cmss13-devs/cmss13#7953]
### Testmerges

#7764, #7909, #6951, #7860

### Round ID

N/A, happens over multiple rounds.

### Description of the bug

Some EMT clothing (vests, hats, etc are fine, this just happens with shirt slot items) on Hybrisia seem to be job locked for some reason. This doesn't seem intentional, I was unable to use them as a medical survivor in the pictured image.

![Screenshot 2024-12-30 185647](https://github.com/user-attachments/assets/48d89454-7523-4ce3-8101-64770d795e4d)

### What's the difference with what should have happened?

I would assume its meant to be equipable by all, especially considering its just standard clothing.

### How do we reproduce this bug?

1. Attempt to put on EMT clothing from the Hybrisia PR Merge.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Blundir** [comment]
These are a suit slot item, not an uniform slot item
![dreamseeker_xXPcaK51Cd](https://github.com/user-attachments/assets/472748b2-35eb-47b6-b5f5-d1514aec19f6)
