### ISSUE TITLE
Resin Nodes blocking Resin Hole placement after patching broken weeds.

### ISSUE THREAD

**Issue by SarahJohnson489** [cmss13-devs/cmss13#829]
## Description

Burrower can't replace destroyed weeds and replace resin holes. It has to choose one or the other.

## Difference between expected and actual behavior

Thanks to the untested, unreviewed, non-atomic, speedmerged PR https://github.com/cmss13-devs/cmss13/pull/810 for https://github.com/cmss13-devs/cmss13/issues/805 

Marine or grenade splash breaks weed.
Place resin node to replace the weed.
"You can't place a resin hole on a resin node!"

Now your extremely placement dependent caste ability is removed from you. You can't repair the destroyed weed with a resin node to place a resin hole. Most notable for 1x1's near doorways and corners. You can't leave it unweeded because you need weeds to place the resin hole. You can't slash weeds so a new node can spread from nearby tiles. You can't slash the node to remove it blocking resin holes forever. Hive building for all castes was removed so you can't build a wall then destroy it to remove the node. That tile for resin hole placement is just fricken dead to you.

Grenades, CAS, wildin marine knives, c4, flames, a massive amount of sources cause non-orthagonal weed breakage while now results in denying burrowers tiles to place resin holes because of the change. Which is actually really kinda important given the extremely positional nature of Resin Hole placement. Needs a revert quickly.

Resin Hole layering was already moved above the resin node so it was visible there was no problem. There was no cause to remove a castes ability to function.

## Steps to reproduce

Weed a room
Place a resin hole by the door
Destroy the hole and the weed tile under it leaving a 1x1 hole
Place a resin node to replace the weed
Attempt to place a resin hole

"You can't place a resin hole on a resin node!"  "You can't place a resin hole on a resin node!"
"You can't place a resin hole on a resin node!"  "You can't place a resin hole on a resin node!"
"You can't place a resin hole on a resin node!"  "You can't place a resin hole on a resin node!"
"You can't place a resin hole on a resin node!"  "You can't place a resin hole on a resin node!"

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
if you read the changelog on the PR this was intended

**Comment by SarahJohnson489** [comment]
It's breaking basic functionality of a caste's main ability. The burrower can't break other weeds so it can place a node orthagonally. It can't break the node. It's blocked out of placing resin holes by other xenos placing resin nodes. Diagonal breaks from flames, and explosion splash pockmarking the existing weed mat blocking out hole placement. Again, for the purposes of placing resin holes the tile is denied to the burrower because of an OOC mechanical issue that makes no sense. 

I don't know how to further simplify a 1x1 tile of broken weeds can no longer be hole'd. Nodes haven't covered holes for a long time it wasn't a problem and certainly didn't warrant mutilating an entire caste over. I can't make it any simpler. Literally weed a room, put a hole by the door, destroy the hole and the weed, then figure out how to place a hole back on that tile cause it can't be done.

**Comment by stanalbatross** [comment]
>Literally weed a room, put a hole by the door, destroy the hole and the weed, then figure out how to place a hole back on that tile cause it can't be done.

place weeds on a tile next to the door and wait for them to spread?

**Comment by SarahJohnson489** [comment]
That's the problem with 1x1 broken weeds and diagonally broken weeds. They're isolated and the weed wont spread to them.
