### ISSUE TITLE
Papers can be generated with code in them before the paperwork systems are intializied

### ISSUE THREAD

**Issue by blackdragonTOW** [cmss13-devs/cmss13#838]
## Description
Certain items are spawned trying to format the paper on map start via item creation, before the paperwork systems that handle code for it is started.

## Difference between expected and actual behavior

The following should look like this:

**First EFTPOS setup:**
1. Memorise your EFTPOS command code (provided with all EFTPOS devices).
2. Connect the EFTPOS to the account in which you want to receive the funds.

**When starting a new transaction:**
1. Enter the amount of money you want to charge and a purpose message for the new transaction.
2. Lock the new transaction. If you want to modify or cancel the transaction, you simply have to reset your EFTPOS device.
4. Give the EFTPOS device to your customer, he/she must finish the transaction by swiping their ID card or a charge card with enough funds.
5. If everything is done correctly, the money will be transferred. To unlock the device you will have to reset the EFTPOS device.

Instead the paper will look like this:
`
<b>First EFTPOS setup:</b><br> 1. Memorise your EFTPOS command code (provided with all EFTPOS devices).<br>
2. Connect the EFTPOS to the account in which you want to receive the funds.<br><br> <b>When starting a new transaction:</b><br> 1. Enter the amount of money you want to charge and a purpose message for the new transaction.<br> 2. Lock the new transaction. If you want to modify or cancel the transaction, you simply have to reset your EFTPOS device.<br> 3. Give the EFTPOS device to your customer, he/she must finish the transaction by swiping their ID card or a charge card with enough funds.<br> 4. If everything is done correctly, the money will be transferred. To unlock the device you will have to reset the EFTPOS device.<br>
`

## Steps to reproduce
1. Start CM13 on any map
2. Begin the round as the Corporate Liaison
3. Move to the Liaisons Office -> Office Room
4. Open the Cabinet next to the desk/copy machine
5. Pick up and read the "Steps to success: Correct EFTPOS Usage" paper
7. --->The page has code that was simply output as a string, rather than run

## Notes:
Other papers that are generated by items after the systems have initialized, such as the ATM receipts, will have the above formatting style correctly generate formatted papers.  Leading me to believe this is an issue with items that are spawned on map start before other systems are up and running. 

## Issue bingo (not required to be all checked)
- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

![Capture](https://user-images.githubusercontent.com/31581761/184104486-1723c557-08c2-4cdb-aa6f-f2aa364dc8c3.PNG)

**Comment by stanalbatross** [comment]
this is because the paper is generated by the EFTPOS scanner on /New() not /Initialize(). Ez fix.
