### ISSUE TITLE
stui runtimes broken

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#858]
## Description

stui doesn't show runtimes

## Difference between expected and actual behavior

it should

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by morrowwolf** [comment]
Fixed by https://github.com/cmss13-devs/cmss13/pull/1030
