### ISSUE TITLE
No consequence for welding w/o eye protection(goggles, mask et al)

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#859]
## Description
Welding without eye protection no longer causes eye damage.

## Difference between expected and actual behavior
It should cause eye damage.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
I can confirm this. 3 days ago I welded 140 brute damage on a synth with no eye protection as a medic and had no side effects.

**Comment by kiVts** [comment]
#339
