### ISSUE TITLE
Logout messages show up to non-admins

### ISSUE THREAD

**Issue by Megarop** [cmss13-devs/cmss13#883]
## Description
I got a message during a round that said "[11:36:13]ACCESS: Logout: Roadmansteve".
![image](https://user-images.githubusercontent.com/91641474/185111153-ac3213fd-6ed9-4735-902c-6229e51fcc50.png)

## Difference between expected and actual behavior
I'm pretty sure i'm not supposed to see that.

## Steps to reproduce
No clue.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Shad0vvs** [comment]
#100
