### ISSUE TITLE
"Ghost pills" occasionally spawning after feeding a real pill to someone.

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#897]
## Testmerges:

A single PR is gona be difficult to associate with this bug. I have known of it for a year or more but can not intentionally cause the bug to occur.

## Description

Sometimes, seemingly more often at high pop when the lag is at its highest, just after administering a pill to a marine, a "ghost pill" is created on the ground where you were standing. This pill has 0u worth of chems and cannot be interacted with in any way via a person's hands. You cannot drag it nor pick it up though the pill does appear in the right click and alt + click menus. I have observed this 'ghost pill' from all types of chems so long as they are stored in pill form: custom such as IA or KD and basic such as kelotane or tramadol. 

## Difference between expected and actual behavior

Feeding someone a pill should delete said pill instead of leaving a useless object to clutter the ground. Attached are 3 separate examples of this 'ghost pill' in a single round on 8/18/2022 but if you keep an eye out, you will likely notice these 'ghost pills' in almost all rounds:

![Ghost Pill 1](https://user-images.githubusercontent.com/105765670/185552265-5e2263df-266c-48bf-b494-4bdaa1bce5ba.png)
-------------------
![Ghost Pill 2](https://user-images.githubusercontent.com/105765670/185552293-c5b13ca8-eb43-4724-8f5f-14040544c4a9.png)
-------------------
![Ghost Pill 3](https://user-images.githubusercontent.com/105765670/185552321-645b6ea1-5ff1-4afe-9b54-9f9c63f5b2e1.png)

## Steps to reproduce

I have tried in vain to replicate this bug over quite some time. The ghost pills SEEM to occur most frequently when the target of the pill walks out of the tile you are feeding just as you finish feeding the pill but the ghost pill does not always spawn from this. Combine that with exceptional lag spikes and that is my best guess as to the origin of these ghost pills. 

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
This is on my list. I have a guess as to what the cause might be, still need to actually test it.

**Comment by Superwelder** [comment]
If you discover the real cause I would be very interested in knowing. Such a strange little bug. I am almost fond of it after all this time.
