### ISSUE TITLE
Cybernetic hands/feet don't come off when removing the limb it is attached to

### ISSUE THREAD

**Issue by TropicalFlak** [cmss13-devs/cmss13#901]
## Description
Cybernetic hands/feet don't come off when removing the limb it is attached to. This was observed to occur during surgery on a dead body. Not sure what happens on delimbs coming from attacks, but likely also the same thing happens.

## Difference between expected and actual behavior

Expected:
It comes off along with the limb it was attached to.

Actual:
It does not, and simply disappears. 

## Steps to reproduce
Perform limb surgery on a body or person with a cybernetic limb
Upon completing the steps to remove a limb you should see "the limbs fly off in an arc"
The cybernetic limb is nowhere to be seen but the organic limb is

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by stanalbatross** [comment]
could not replicate

**Comment by TropicalFlak** [comment]
Alright hold on, uploading a video about it.

**Comment by TropicalFlak** [comment]
https://user-images.githubusercontent.com/108848001/186549630-db577bfd-84bf-4634-b183-f284c7bd32ff.mp4
