### ISSUE TITLE
BUG: Smart Fridges Wiring

### ISSUE THREAD

**Issue by ghost** [cmss13-devs/cmss13#906]
This post is to continue this post (https://github.com/cmss13-devs/cmss13/issues/777#issue-1322834926) as it is still not fixed but has been closed

## Description
None of the wiring for the Smartfridges in research or medical work

## Difference between expected and actual behavior
When the ID wire is pulsed it should remove ID restrictions, or if it’s cut it should not require an ID

So when restrictions are removed you should be able to vend anything and change the vending mode with out an ID/without permissions

## Steps to reproduce
None of the wiring works for the smartfridge. It just still needs an authorised ID no matter what

So cut the ID wire for example and try and vend something or change the vending mode

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by NewyearnewmeUwu** [comment]
This is no longer the case. Also, cutting the ID wire just locks up the vendor.

**Comment by ItsVyzo** [comment]
Still a bug, functionality does not exist.

**Comment by ItsVyzo** [comment]
#3034
