### ISSUE TITLE
BUG: Infinite M56D ammo

### ISSUE THREAD

**Issue by ZandraEmmie** [cmss13-devs/cmss13#907]
## Description
M56D having infinite ammo when putting another drum magazine in

## Steps to reproduce
(always be manning the M56D)
1. Set up M56D
2. load drum mag
3. fire a few rounds
4. load new drum magazine into gun while it still has the drum mag with decreased ammo
5. Grab the drum mag which has decreased ammo from the floor
6. load that drum magazine back inside the M56D while it still has the new drum magazine loaded
7. You now have a full M56D while still retaining the ammo inside the new drum mag

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by nauticall** [comment]
Reproduced and confirmed. For reproduction, you need to re-insert the expended magazine into the M56D to "refill" it, triggering the bug. Neither of the drums need to be full for this to happen either.
