### ISSUE TITLE
Claymores are extremely inconsistent 

### ISSUE THREAD

**Issue by Survivor23** [cmss13-devs/cmss13#914]
## Description
Claymores don't stun enemies if they are detonated on the actual mine itself, only the direction it is facing. In addition, claymores can be walked through often, and pounced over negating any of the stun.

## Difference between expected and actual behavior
Claymores are supposed to stun hostiles if they detonate them. The point of claymores is for someone to properly capitalize on the stun, as the damage is not intended to kill xenomorphs. The problem is that the main function of the claymore is extremely inconsistent due to several explosion changes over the years. While the pounce behavior is debatable, claymores are meant to be barriers, and should not be able to be instantly crossed with no repercussions. 

If I were able to fix it, my intended solution would be to have it so the hostile triggering the claymore via the detection radius (slashing it would not have this effect) would receive a 1.5 to 2 second stun, as well as stopping any momentum from movement such as pounces. In addition, it may be wise to make the claymore only detonate from the angle it is facing, instead of both the tile it is on and the faced tile. 

This won't really massively change how claymores function as a whole, as for them to be effective there has to be someone watching them at all times, meaning that for this to have any serious effect, someone would need to dedicate their round to it. Still, claymores should have proper functions regardless of how they are used. They are extremely limited in number for the small stunts that they are capable of, where as the xenomorph equivalent is simply based on how quick you can regain plasma to place burrower traps.

## Steps to reproduce
Place a claymore, walk over it a few times from different angles as a xenomorph. You will get various results depending on how fast you were going, what direction you triggered it from, and if you were using an ability.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wintermote** [comment]
Claymores need 2 changes/fixes imo:

1. Slashing them from the side should deal damage to and stun the xeno that slashes them. In what universe do you trigger an explosive directly, with your hand/claw, and it doesn't do anything to you?? 
2. Claymores need to set a flag on the xeno triggering them to apply stun/damage reliably, regardless of lag. If you trigger a claymore you get flagged for damage and stun. It solves the issue with claymores failing to do anything to a xeno that runs past it fast enough

**Comment by PhantomEpicness** [comment]
Fixing this issue in my upcoming marine mine update + SEBB PR

**Comment by Huffie56** [comment]
main issue is them only triggering if your on them or just in front.
second issue is being able to not be stun if you use pounce for example...

**Comment by Huffie56** [comment]
the only real inconsistency is when we pounce over them you don't get stun...

**Comment by Huffie56** [comment]
Hello @ItsVyzo and @usnpeepoo could you close this one?
someone open new one and  it's way more specific on the description of the bug...
this one is with to much talk about improving the mine witch is totally out of the scope of an issue report....

**Comment by Huffie56** [comment]
i am closing this issue as someone as open an issue that center on the real bug that is being able to pounce above clay-more without being stun.
