### ISSUE TITLE
Can still resist the grab of a warrior

### ISSUE THREAD

**Issue by 1845292047** [cmss13-devs/cmss13#930]
As the title Suggests, somehow i was able to resist the grab of warrior after it grabbed me 10 minutes ago, causing be not be able to resist anything else, not sure what causes the bug, I think its just random. I was on m2c when the warrior grabbed me, i broke free and even after evaccing to the almayer it would still say i was resisting to the grab of a warrior.

**Comment by morrowwolf** [comment]
This needs to be resubmitted with the proper outline.
