### ISSUE TITLE
Fluorosurfactant foam doesn't apply the on_touch effects

### ISSUE THREAD

**Issue by Dueu** [cmss13-devs/cmss13#932]
## Description
When you create a research chemical and try to use the on_touch effects of the properties through fluorosurfactant foam it does not apply them like the chem smoke does.

## Difference between expected and actual behavior

When testing the Toxic property through chem smoke grenades it could damage xeno weeds. But when used in foam it didnt cause the expected damage to human mobs.

## Steps to reproduce

1. Create a research chemical with a property with on_touch effect or relate a property to a research chemical (Some easy properties to test it are: Toxic from fluorine, Corrosive from polytrinic acid, Neurotoxic from mercury)
2. Mix the created chemical in a container with flourosurfactant and water
3. Stand on the foam and check health, no damage received as it does not apply the on_touch effects

## Possible code problem
I'm not an expert or got any experience at all in programming on byond but I think there is something wrong with this line of code:

**Fluorosurfactant foam (doesnt work properly):**
https://github.com/cmss13-devs/cmss13/blob/b75594fe0d063049fa9c1ba418a5452f4ac1592c/code/modules/reagents/chemistry_reactions/other.dm#L360

**Chemsmoke (does apply the effects correctly):**
https://github.com/cmss13-devs/cmss13/blob/b75594fe0d063049fa9c1ba418a5452f4ac1592c/code/modules/reagents/chemistry_reactions/other.dm#L251

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Unknownity** [comment]
intended, see my reply in my PR

**Comment by Dueu** [comment]
> intended, see my reply in my PR

Alright seems fair enough. I will close it.
