### ISSUE TITLE
Inability to fire the weapon while in melee range

### ISSUE THREAD

**Issue by Don2137** [cmss13-devs/cmss13#933]
## Testmerges:

Unrelated

## Description

Sometimes, when fighting in 1-2 tile range, a weapon will refuse to fire while sprite clicking. This can repeat over multiple clicks, leading to long periods of not firing.

I believe this has to do with PB code. I _think_ it specifically happens when the target moves out of PB range. The game checks for PB distance, decides it's too far, then applies a long fire delay.
## Difference between expected and actual behavior

If a PB fails, the gun should fire as normal. Instead of doing that, it stops firing at all.

## Steps to reproduce

One marine with an M41, one xeno running within 1-2 tile range around them

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by DylonBR** [comment]
this happens to me all the damn time. it is incredibly annoying

**Comment by Wintermote** [comment]
It happens because someone added a click delay if you happen to click on the tile right next to you. It's dumb as hell. I think the same update also added a click delay to taking tools out of your pouches which is also DUMB AS HELL.

I have absolutely HATED both of these click delays since they were added. They are pure cancer and we've been forced to just live with it.

**Comment by Huffie56** [comment]
this is old and need testing.

**Comment by Huffie56** [comment]
i tested in multiple configuration for at-least 5 min but never manage to trigger this bug...
for example i tried this:
 be in PB range move out and try to fire or fire coming close to a xeno everything worked....
 @ItsVyzo i am pretty sure this issue as been fixed and can be closed. thanks

**Comment by usnpeepoo** [comment]
This is a mix of server/client lag, and click delays on missed clicks. Don't believe this needs to stay up as a bug.
