### ISSUE TITLE
Synth light not turning off on death

### ISSUE THREAD

**Issue by Don2137** [cmss13-devs/cmss13#947]
## Testmerges:

Irrelevant

## Description

Synths have that one pseudo bulletproof vest of theirs that comes with the shoulder light. It should turn off when they die but it doesn't. I know they don't really die but it should still be consistent for the sake of gameplay.

## Difference between expected and actual behavior

See above

## Steps to reproduce

See above

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ThePiachu** [comment]
I see no special code for the synthvest. My guess it is an issue with synths dying if anything. Or maybe one time xenos didn't slash a synth enough and they were almost dead.

I tested it locally a little and couldn't reproduce.

**Comment by ItsVyzo** [comment]
Can't reproduce
