### ISSUE TITLE
Painkillers not working for a couple seconds when an unconscious patient wakes up during surgery

### ISSUE THREAD

**Issue by Sernoh** [cmss13-devs/cmss13#983]
## Description

Painkillers need a couple seconds to work again if starting a surgery from crit and the patient wakes up midway.

## Difference between expected and actual behavior

Doing surgery with painkillers (oxy/tram) shouldn't fail the step. However if the patient wakes up mid-surgery then you need to wait a couple seconds for the painkillers to 'work' again.

## Steps to reproduce

Most common occurrence:
- Defib a patient at 200~ damage, slam pills down their throat (bic, oxy, quikclot)
- Start doing surgery
- Surgery works while they're unconscious
- Pills are metabolizing, patient heals damage and wakes from unconscious state
- Suddenly surgery steps will fail when the patient wakes up, regardless of painkillers in their system
- Wait a couple seconds and surgery steps will work again

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
this is old and need testing...

**Comment by Huffie56** [comment]
@Sernoh did it happen again?

**Comment by Huffie56** [comment]
@ItsVyzo i think you can tag this with need reproducing. thanks
 it's old and nobody reproduce it since...

**Comment by Huffie56** [comment]
no update and impossible to test this(as most common occurrence state that it can't be reproduce 100% time)...
