### ISSUE TITLE
M2C Duplication

### ISSUE THREAD

**Issue by VagabondZero79** [cmss13-devs/cmss13#990]
Charger Crusher can duplicate M2C's if they charge into a deployed M2C with someone currently using it.

Same thing can be done for M56.

**Comment by PhantomEpicness** [comment]
Being included in charger crusher rebalance/fixes PR #1. Trying to reproduce

**Comment by PhantomEpicness** [comment]
Reproduced

Issue found

**Comment by PhantomEpicness** [comment]
Issue fixed
